### PR TITLE
Update gdas_gsibec_ver to 20240416

### LINKED ISSUE #2493: update gdas/gsibec qoption
### Target fix directory

gdas/gsibec

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

[GDASApp PR #1015](https://github.com/NOAA-EMC/GDASApp/pull/1015) updated the GSIBEC tag used by GDASApp.  A change to `qoption` associated with this change to GSIBEC is mentioned in [fv3-jedi PR #1173](https://github.com/JCSDA-internal/fv3-jedi/pull/1173).

### Pickup location

/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/jediinc2fv3/fix/gdas/gsibec

### Size

no change in size of `gfs_gsi_global.nml`

### LINKED ISSUE #2496: Update gdas_gsibec_ver to 20240416
### What new functionality do you need?

Update variable `gdas_gsibec_ver` in `versions/fix.ver` to `gdas_gsibec_ver=20240416`. 

### What are the requirements for the new functionality?

This change is required to restore `fv3jedi_var.x` functionality using the GSI static-B.   The 20240416 version allows GSIBEC to default to `qoption=1`.  The previous version, 20221031, used `qoption=2`.

### Acceptance Criteria

Install `gdas/gsibec/20240416` on g-w supported machines.

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
This PR updates `gdas_gsibec_ver` to use the default `qoption=1` when running `fv3jedi_var.x`.   This is the recommended configuration when using the statiic GSI-B in `fv3jedi_var.x`.

Resolves #2496 
Completes #2493

# Type of change
- Maintenance - gsibec update

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Check `gdas_gsibec_ver=20240416` on Hera to confirm that correct GSIBEC namelist is used.

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Approve pending any CI testing being successful.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Do you want us to run CI tests for this update? I believe this only impacts JEDI runs via global-workflow.

We had CI tests on hold last week so I'm getting back to this PR now.

**Comment by RussTreadon-NOAA** [comment]
@KateFriedman-NOAA - you are correct.  This PR only impacts JEDI ATM.   

JEDI ATM `ci/cases/pr/C96C48_ufs_hybatmDA` successfully runs on Hera and Orion as documented in g-w PRs #2420 and #2357.  I think we should include JEDI ATM CI as part of routine g-w CI.  We are actively submitting JEDI ATM g-w PRs  (e.g., #2420, #2477, & #2497 (this PR)).

Given your question I am stepping through the following on Orion:
- [x] clone `RussTreadon-NOAA:feature/gsibec` 
- [x] build g-w apps via `sorc/build_all.sh -u`
- [x] `sorc/link_workflow.sh`
- [x] remove the `-orion` entry in `ci/cases/pr/C96C48_ufs_hybatmDA`
- [x] run JEDI ATM CI

**Comment by RussTreadon-NOAA** [comment]
JEDI ATM CI run on Orion.  Cycling complete through GFS and GDAS atmanlrun.  These are the JEDI ATM jobs which use gsibec.  Both jobs ran to completion.   JEDI ATM CI passed.

This test could have been automatically run if JEDI ATM CI was turned on in `ci/cases/pr/C96C48_ufs_hybatmDA.yaml`.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA Thank you for running that JEDI CI test on Orion and reporting its success.

I will speak with the other CMs about potentially turning that JEDI CI test on automatically for the platforms where JEDI currently works.

**Pull request merged**
