### PR TITLE
Replace `CDATE` with `PDYcyc` combo

### LINKED ISSUE #198: Convert $CDATE to $PDY$cyc
NCO uses $PDY and $cyc to define the cycle date, whereas EMC mainly uses $CDATE and then $PDY and $cyc are cut from $CDATE for use in the system ($CDATE=$PDY$cyc). Consider replacing "$CDATE" with "$PDY$cyc" to be more consistent with NCO paradigm.

This came out of an email with NCO during the GFSv16 install process.

### LINKED ISSUE #1560: Replace `${CDATE}` with ${PDY}${cyc} in config.nsst (and possibly other configs)
https://github.com/NOAA-EMC/global-workflow/blob/608ff650fbc902114203a8d03893e3d26fa05d70/parm/config/config.nsst#L15

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**
This PR:
- replaces `${CDATE}` with `${PDY}${cyc}` in all `config.*` files.
- fixes permissions on some of the config files that were turned to be executable in some of the JEDI PRs.

Fixes #1560 
Partially fixes #198 

**Type of change**

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Cycled test on Orion
- [ ] Forecast-only test on Hera
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks good.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Failed to create experiment}:  *FAIL* C96_atm3DVar
Experiment setup: failed at Tue May  2 14:55:47 CDT 2023 for experiment C96_atm3DVar
Failed to create experiment}:  *FAIL* C96C48_hybatmDA
Experiment setup: failed at Tue May  2 14:55:49 CDT 2023 for experiment C96C48_hybatmDA

**Comment by aerorahul** [comment]
Not sure why the creating of experiment failed.  I just tried this from the command-line:
```bash
./workflow/setup_expt.py cycled --app ATM --pslot atmcyc --start cold --idate 2021122018 --edate 2021122112 --gfs_cyc 1 --resdet 96 --resens 48 --nens 4 --expdir /work2/noaa/stmp/rmahajan/gwWork/EXPDIR --comrot /work2/noaa/stmp/rmahajan/gwWork/ROTDIR --icsdir /work/noaa/global/glopara/data/ICSDIR/C96C48
```
and it created the experiment just fine in `/work2/noaa/stmp/rmahajan/gwWork/EXPDIR/atmcyc`

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Orion
Start: Tue May  2 14:58:57 CDT 2023 on Orion-login-1.HPC.MsState.Edu
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue May  2 15:00:48 CDT 2023
Build:                         *SUCCESS*
Build: Completed at Tue May  2 16:22:28 CDT 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue May  2 16:22:43 CDT 2023 for experiment C96_atm3DVar

**Comment by aerorahul** [comment]
> Automated global-workflow Testing Results:
> 
> ```
> Machine: Orion
> Start: Tue May  2 14:58:57 CDT 2023 on Orion-login-1.HPC.MsState.Edu
> ---------------------------------------------------
> Checkout:                      *SUCCESS*
> Checkout: Completed at Tue May  2 15:00:48 CDT 2023
> Build:                         *SUCCESS*
> Build: Completed at Tue May  2 16:22:28 CDT 2023
> Created experiment:            *SUCCESS*
> Case setup: Completed at Tue May  2 16:22:43 CDT 2023 for experiment C96_atm3DVar
> ```

It took 1 hour and 22 mins to build? wow!

**Comment by TerrenceMcGuinness-NOAA** [comment]
Yea it usually takes 30 minutes to build, we are doing full GSI and GDSApp build.
`+ clone-build_ci.sh[82]./checkout.sh -c -g -u`

**Comment by TerrenceMcGuinness-NOAA** [comment]
The fail on creating an experiment earlier was because I was using today's updated scripts, and there were a few small debug fixes, there in real time.  I had to use these newer scripts because we had to use the updates so that we ran with the **nems** accounts only. It's running fine now from a full end-to-end scripted run.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Orion
Start: Tue May  2 14:58:57 CDT 2023 on Orion-login-1.HPC.MsState.Edu
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue May  2 15:00:48 CDT 2023
Build:                         *SUCCESS*
Build: Completed at Tue May  2 16:22:28 CDT 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue May  2 16:22:43 CDT 2023 for experiment C96_atm3DVar
Experiment C96_atm3DVar completed: *SUCCESS*
Experiment C96_atm3DVar Completed at Tue May  2 19:07:05 CDT 2023
with 73 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Orion
Start: Tue May  2 14:58:57 CDT 2023 on Orion-login-1.HPC.MsState.Edu
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue May  2 15:00:48 CDT 2023
Build:                         *SUCCESS*
Build: Completed at Tue May  2 16:22:28 CDT 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue May  2 16:22:43 CDT 2023 for experiment C96_atm3DVar
Experiment C96_atm3DVar completed: *SUCCESS*
Experiment C96_atm3DVar Completed at Tue May  2 19:07:05 CDT 2023
with 73 successfully completed jobs

**Comment by aerorahul** [comment]
Awesome.  Looks like the 2 tests have passed.

**Review by TerrenceMcGuinness-NOAA — APPROVED** [review]
CI test runs end-to-end hands free.  Need to check why the one **C96_atm3DVar** is reported back to GitHub twice.

**Pull request merged**
