### PR TITLE
Update ufs-weather-model and remove upp hack

### LINKED ISSUE #1942: changes required for switching instances of "nems"  to "ufs"
### What new functionality do you need?

In PR ufs-community/ufs-weather-model/pull/1948, the ``coupling_mode`` options have been renamed and the ``nems.configure`` file is replaced with ``ufs.configure``. 

In the RTs, the ``coupling_mode`` is determined with the CPLMODE variable. The names have changed as follows

```
nems_orig --> ufs.nfrac
nems_orig_data --> ufs.nfrac.aoflux
nems_frac --> ufs.frac
nems_frac_aoflux and nems_frac_aoflux_sbs --> ufs.frac.aoflux
```

### What are the requirements for the new functionality?

NA

### Acceptance Criteria

The GW will need to recognize and use the new coupling mode definitions and configure file.

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Description
Updates the model to the most recent commit of ufs-weather-model.  This should allow for the removal of the UPP hack that was added in PR #2042  

This required changing nems.configure -> ufs.configure and 
Resolves #1942 

This also included the settings updates from @lisa-bengtsson  which added convection tuning parameters to namelist

# Type of change
- ufs-weather-model update & associated changes 

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- ran C48 S2SW test forecast only on orion 

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Looks good to me.
Just a note on possible conflicts arising if/when PR #2030 goes in before or after this PR.
PR #2030 is still in testing, I think.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul agreed, it looks like there will be some conflicts with #2030.  I think it should be fairly straightforward find/replace nems->ufs in addition to just resolving the conflicts. Since it's likely that #2030 will be merged first, I will make a new branch and merge in that PR there to proactively resolve conflicts, unless you think that's unnecessary?

**Comment by aerorahul** [comment]
> @aerorahul agreed, it looks like there will be some conflicts with #2030. I think it should be fairly straightforward find/replace nems->ufs in addition to just resolving the conflicts. Since it's likely that #2030 will be merged first, I will make a new branch and merge in that PR there to proactively resolve conflicts, unless you think that's unnecessary?

Actually, I don't think #2030 will be merged before this.  I also don't think this should wait for #2030 as this seems fairly compact.
If you can confirm this can be tested, we can churn the CI to test this PR.  You may still want to do an independent forecast-only test at the non-CI resolution.

**Comment by JessicaMeixner-NOAA** [comment]
I'd be happy to run a non-CI resolution test.  Any preference on machine/resolution?    Otherwise, I think this PR is ready for CI testing, but we can also wait until the non-CI resolution test is finished too.

**Comment by JessicaMeixner-NOAA** [comment]
I've looked at the error and I'm not sure what's going on.  This is a S2SA gefs and I ran S2SW gfs, so I'll try an S2SA C48 test, in the meantime I have a C768 S2SW test on hera in the queue.  All of these are free-forecast.

**Comment by JessicaMeixner-NOAA** [comment]
So I tried to run an S2SA C48 test case with: 

`./setup_expt.py gfs forecast-only --app S2SA --pslot gfsS2SAt02 --configdir /work2/noaa/marine/jmeixner/HR3/updatemodel/global-workflow/parm/config/gfs --idate 2021032312 --edate 2021032312 --res 48 --gfs_cyc 1 --comrot /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/COMROOT --expdir /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR`

I then changed the CPU account, RUNDIR and HOMEDIR. 

I then ran 
`./setup_xml.py /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02
`
And then tried the rocotorun command and got the following error: 

```
/apps/contrib/rocoto/1.3.3/bin/rocotorun -d /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.db -w /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml
11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Extra element dependency in interleave.
11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element task failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:126.
11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Extra element task in interleave.
11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element workflow failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:17.
11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element workflow failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:17.
```

I also tried this with a clone of the develop branch of the global-workflow on WCOSS2 and got the same error.  Is there something wrong with what I'm trying to do that I'm just not seeing.  I thought this would help me debug the failed gefs case.

**Comment by WalterKolczynski-NOAA** [comment]
> So I tried to run an S2SA C48 test case with:
> 
> `./setup_expt.py gfs forecast-only --app S2SA --pslot gfsS2SAt02 --configdir /work2/noaa/marine/jmeixner/HR3/updatemodel/global-workflow/parm/config/gfs --idate 2021032312 --edate 2021032312 --res 48 --gfs_cyc 1 --comrot /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/COMROOT --expdir /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR`
> 
> I then changed the CPU account, RUNDIR and HOMEDIR.
> 
> I then ran `./setup_xml.py /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02 ` And then tried the rocotorun command and got the following error:
> 
> ```
> /apps/contrib/rocoto/1.3.3/bin/rocotorun -d /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.db -w /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml
> 11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Extra element dependency in interleave.
> 11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element task failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:126.
> 11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Extra element task in interleave.
> 11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element workflow failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:17.
> 11/16/23 10:54:10 CST :: gfsS2SAt02.xml :: Error: Element workflow failed to validate content at /work2/noaa/marine/jmeixner/HR3/updatemodel/gfsS2SAt02/EXPDIR/gfsS2SAt02/gfsS2SAt02.xml:17.
> ```
> 
> I also tried this with a clone of the develop branch of the global-workflow on WCOSS2 and got the same error. Is there something wrong with what I'm trying to do that I'm just not seeing. I thought this would help me debug the failed gefs case.

I just found this myself, I'm testing a fix. In the meantime, you can manually edit the gfsfcst dependency. Change
```<not><cycleexistdep cycle_offset="-1 day, 0:00:00"/></not>```
to
```<not><cycleexistdep cycle_offset="-24:00:00"/></not>```

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @WalterKolczynski-NOAA !

**Comment by JessicaMeixner-NOAA** [comment]
I think I found the issue for the GEFS test where I missed an update in the parm/gefs.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
