### PR TITLE
Update component versions

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
Updates the version of components except UFS and verify to the current tip of their respective develop branches.
    
Verify is not yet updated because we are currently on a branch that hasn't been merged to develop yet in order to use the module/py environment fix.
    
GSI will still need to be updated further before use after the resolution of NOAA-EMC/GSI/issues/348

Also updated the GSI and UPP build scripts to take in debug (`-d`), operations (`-o`), and verbose (`-v`) options and apply them as appropriate to the component build scripts. The ops flag for GSI still needs work, as I encountered issues using the [build_4nco_global.sh](https://github.com/NOAA-EMC/GSI/blob/develop/ush/build_4nco_global.sh) or [prune_4nco_global.sh](https://github.com/NOAA-EMC/GSI/blob/develop/ush/prune_4nco_global.sh) scripts.

Also fixes a typo in the `parm/post` file list.

Updates are in preparation for the [COM reorg](https://github.com/NOAA-EMC/global-workflow/issues/761)

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
- [x] Clone and Build tests on Hera
- [x] Clone and Build tests on Orion
- [x] Clone and Build tests on Dell
- [x] Forecast-only test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Looks like I'll need to add a new checkout and build script for [GSI-Monitor](https://github.com/NOAA-EMC/GSI-Monitor). Backing this off to draft.

**Comment by WalterKolczynski-NOAA** [comment]
Still have this one `radmon_ck_stdout.sh` that doesn't seem to exist anymore. A recursive grep doesn't yield any hits except the link script; maybe we should just stop linking it?

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good, thanks @WalterKolczynski-NOAA !

**Review by aerorahul — APPROVED** [review]
looks good.

**Pull request merged**
