### PR TITLE
[DO NOT MERGE] Weekly CI Tests Friday Nov 03, 2023

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Nov 03, 2023

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Hera still stalls on **`gfsstage_ic`**  for **C384_S2SWA** with:
 
`/scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/GEFSwave20210528v2_refactored/2016070100/wave/20160701.000000.restart.glo_025 does not exist`
 
 @WalterKolczynski-NOAA is aware of this issue and CI code is being developed this week to automate the detections of such stalls of this type.

**Comment by TerrenceMcGuinness-NOAA** [comment]
There is no known cause for the creation failure of C384_atm3DVar on Orion (see below)
Weekly Tests for Orion is being restarted.


```
(gfs_workflow) mterry (Orion-login-3) pr (weekly_ci_20231103) $ /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/global-workflow/workflow/create_experiment.py --yaml C384_atm3DVar.yaml 
2023-11-06 08:25:25,368 - INFO     - root        : BEGIN: __main__.input_args
2023-11-06 08:25:25,368 - DEBUG    - root        : (  )
2023-11-06 08:25:25,369 - INFO     - root        :   END: __main__.input_args
2023-11-06 08:25:25,369 - DEBUG    - root        :  returning: Namespace(yaml=PosixPath('C384_atm3DVar.yaml'))
2023-11-06 08:25:25,379 - INFO     - root        : Call: setup_expt.main()
2023-11-06 08:25:25,379 - DEBUG    - root        : setup_expt.py gfs cycled --pslot C384_atm3DVar_c2ef73a3 --app ATM --resdet 384 --resens 192 --comrot /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/COMROT --expdir /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR --icsdir /work/noaa/global/glopara/data/ICSDIR/C384C192 --idate 2023040118 --edate 2023040200 --nens 0 --gfs_cyc 1 --start cold --yaml /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/global-workflow/ci/platforms/gfs_defaults_ci.yaml
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.base as per user input.
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.atmanl as per user input.
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.atmensanl as per user input.
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.aeroanl as per user input.
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.landanl as per user input.
EDITED:  /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3/config.ocnanal as per user input.
2023-11-06 08:25:25,542 - INFO     - root        : Call: setup_xml.main()
2023-11-06 08:25:25,542 - DEBUG    - root        : setup_xml.py /work2/noaa/stmp/GFS_CI_ROOT/PR/2032/RUNTESTS/EXPDIR/C384_atm3DVar_c2ef73a3
Finalizing initialize
sourcing config.prep
sourcing config.anal
sourcing config.analdiag
sourcing config.sfcanl
sourcing config.analcalc
sourcing config.fcst
sourcing config.post
sourcing config.vrfy
sourcing config.fit2obs
sourcing config.arch
sourcing config.cleanup
sourcing config.verfozn
sourcing config.verfrad
sourcing config.vminmon
sourcing config.metp
(gfs_workflow) mterry (Orion-login-3) pr (weekly_ci_20231103) $ 
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
Team working diligently on this issue: [#1996](https://github.com/NOAA-EMC/global-workflow/issues/1996)

**Comment by WalterKolczynski-NOAA** [comment]
A newer weekly test has taken the mantle.

**Pull request closed without merging**
