### PR TITLE
one-step cold start implementation.

### PR DESCRIPTION
**Pull request by jkuang-exploro**
This run style can be turned on using option in "settings" called "onestep"
	True if you want on-step cold start;
	False if traditional two-step;

### CODE REVIEW

**Comment by jiandewang** [comment]
works on orion, will test on HERA

**Comment by JessicaMeixner-NOAA** [comment]
My tests with waves worked on orion for both 1step and 2step and without waves 1 step also worked.  If @jiandewang Hera test worked I say this is good to go.  Thanks @JianKuang-NOAA and sorry for the delay in testing.

**Comment by jiandewang** [comment]
works fine on HERA, too

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA Please approve this PR.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks @JianKuang-NOAA

**Pull request merged**
