### PR TITLE
Consolidate `npe_node_max`

### LINKED ISSUE #2133: Consolidate HPC npe_node_max settings
### What new functionality do you need?

Consolidation of where the `npe_node_max` values for each supported platform are set. The values are currently set in multiple places, example for Orion:

1. https://github.com/NOAA-EMC/global-workflow/blob/develop/env/ORION.env#L17
2. https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.resources#L45
3. https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gefs/config.ufs#L76
4. https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.resources#L57
5. https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.ufs#L76

### What are the requirements for the new functionality?

The value of `npe_node_max` for each supported platform should be set just once, instead of in multiple configs.

### Acceptance Criteria

Duplicate `npe_node_max` settings are removed and the value is sourced from the single consolidated location.

### Suggest a solution (optional)

Remove `npe_node_max` if/case blocks from env files and both  `config.ufs`. Leave existing blocks in both `config.resources`.

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
# Description
This PR addresses issue #2133. The following is accomplished:

- The environment variable `npe_node_max` is removed from all files beneath `global-workflow/env`;
- The environment variable `npe_node_max` is removed from `parm/config/gefs/config.ufs` and `parm/config/gfs/config.ufs`;
- The environment variable `npe_node_max` is maintained only within `parm/config/gefs/config.resources` and `parm/config/gfs/config.resources`.

  Resolves #2133 

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Tested for RDHPCS Hera C48 ATM configuration. The Rocoto status is as follows:

```
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202103231200             gfsstage_ic                    55350726           SUCCEEDED                   0         1          10.0
202103231200                 gfsfcst                    55350743           SUCCEEDED                   0         1         290.0
202103231200    gfsatmprod_f000-f012         druby://hfe06:41305          SUBMITTING                   -         0           0.0
202103231200                 gfsarch                           -                   -                   -         -             -
202103231200              gfscleanup                           -                   -                   -         -             -
```

The above indicates that the correct number of PEs for the respective platform (RDHPCS Hera) is determined from `parm/config/gfs/config.resources` and the global-workflow is able to carry out the specified tasks.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
LGTM.
Perhaps combine this with the other PR so we can run one test.

**Comment by HenryRWinterbottom** [comment]
@aerorahul Thank you for the quick review. Yes, leave it open for now (or how the CMs want to proceed) and I will add other small issues to it not requiring rebase.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good! Thanks @HenryWinterbottom-NOAA !

Approve pending successful completion of CI testing.

**Pull request merged**
