### PR TITLE
Converts obsproc to obsprep in prepoceanobs config file

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
# Description

Converts obsproc to obsprep in prepoceanobs config file as a compliment to mutually depended GDASApp PR https://github.com/NOAA-EMC/GDASApp/pull/858 
The motivations are explained in refs https://github.com/NOAA-EMC/GDASApp/issues/857
 
# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Tested with SOCA ctests on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Review by aerorahul — APPROVED** [review]

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
I think the GDASapp PR needs to be merged first, otherwise this will require a second PR with the hash update.

**Comment by AndrewEichmann-NOAA** [comment]
@WalterKolczynski-NOAA I've updated it

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
Any chance this could be merged @WalterKolczynski-NOAA or @aerorahul ?

**Pull request merged**
