### PR TITLE
Add two ucx modules to solve C768 S2SW hanging

### PR DESCRIPTION
**Pull request by jiandewang**
# Description
It happened frequently that fcst job hang in wcoss2 for S2SW C768. Adding two ucx modules solve the issue.
Resolves #https://github.com/NOAA-EMC/global-workflow/issues/1845

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build on WCOSS

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Happy to add it temporarily, but seems like this should really be a PR into UFS.

**Comment by jiandewang** [comment]
@WalterKolczynski-NOAA the hanging issue only happened to C768 and C1152 while in UFS the max resolution is C384

**Comment by WalterKolczynski-NOAA** [comment]
I would argue this is a UFS problem even if they don't have any regression tests for those resolutions.

@junwang-noaa, what do you think?

**Comment by aerorahul** [comment]
> I would argue this is a UFS problem even if they don't have any regression tests for those resolutions.
> 
> @junwang-noaa, what do you think?

We might need to include it in the global-workflow while the UCX, Slingshot issues are being worked on.
My q. is, clearly this has an impact based on high resolutions.  Will this create issues when the model is run at lower resolutions; C384 for e.g.?

**Comment by junwang-noaa** [comment]
The impact to low resolutions is minimal, slightly faster for C384 runs, unnoticeable for lower resolutions.

**Review by aerorahul — APPROVED** [review]

**Pull request merged**
