### PR TITLE
Update JEDI ATM to use .nc for obs and generalize x,y layout

### LINKED ISSUE #2335: Replace .nc4 with .nc for JEDI ATM observation related files
### What new functionality do you need?

JEDI ATM currently uses a mix of `.nc` and `.nc4` suffixes for files related to observations (dump files, bias correction files).  The same suffix should be used.  

The NetCDF 4.92. [FAQ](https://docs.unidata.ucar.edu/netcdf-c/current/faq.html) recommends `.nc`

> What convention should be used for the names of netCDF files?
> NetCDF files should have the file name extension ".nc". The recommended extension for netCDF files was changed from ".cdf" to ".nc" in 1994 in order to avoid a clash with the NASA CDF file extension, and now it also avoids confusion with "Channel Definition Format" files.

JEDI ATM python scripts need to be updated to use `.nc` for observation related files.

Full implementation of this change requires completion of GDASApp PR [#933](https://github.com/NOAA-EMC/GDASApp/pull/933)

### What are the requirements for the new functionality?

Replace `.nc4` with `.nc` for observation related files in JEDI ATM python scripts.

### Acceptance Criteria

When these changes are complete we should be able to run a JEDI ATM cycle with the `.nc` suffix for observation related files. 

### Suggest a solution (optional)

The following needs to be done to resolve this issue
1. Merge GDASApp PR [#933](https://github.com/NOAA-EMC/GDASApp/pull/933) into GDASApp `develop`
2. Update GDASApp hash in the forked feature branch created for this g-w issue
3. Update JEDI ATM python scripts to use `.nc` for observation related files
4. Open g-w PR to merge the forked feature branch into g-w `develop`

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
The changes in this PR are twofold
1. replace `.nc4` suffix for JEDI ATM observation related files with `.nc`
2. use templated variables to specify `{layout_x, layout_y}` for JEDI ATM variational and local ensemble apps

The first change conforms with the Unidata recommendation that netCDF files end with the suffix `.nc`.  The second change replaces hardwired JEDI ATM var and ens `{layout_x, layout_y}` in `config.resources` with a more flexible approach.

Resolves #2335 

**NOTE**  This PR depends on  GDASApp PR[ #933](https://github.com/NOAA-EMC/GDASApp/pull/933).  Once GDASApp PR #933 is merged into GDASApp `develop`, the `gdas.cd` submodule pointer in `feature/jediatm_nc` needs to be updated to point at the new GDASApp hash.  Without an updated `gdas.cd` submodule the changes in this PR will not be fully functional.

# Type of change
- Maintenance (clean-up)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? **NO**
- Does this change require a documentation update? **NO**

# How has this been tested?
- Clone, build, and cycle in JEDI ATM mode on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good.
since these changes are not covered under the CI, they will be merged when the gdasapp pointer is updated as described in the PR.

**Comment by RussTreadon-NOAA** [comment]
Thank you @aerorahul for quickly looking at these changes.  The changes in this PR require a GDASApp hash coincident with or after GDASApp PR [#933](https://github.com/NOAA-EMC/GDASApp/pull/933) enters GDASApp `develop`.

**Comment by aerorahul** [comment]
> Thank you @aerorahul for quickly looking at these changes. The changes in this PR require a GDASApp hash coincident with or after GDASApp PR [#933](https://github.com/NOAA-EMC/GDASApp/pull/933) enters GDASApp `develop`.

Sounds good.
I'll keep an eye on this PR for that update and confirm with you before merging.

**Comment by WalterKolczynski-NOAA** [comment]
Converting to draft until it is ready to merge.

**Comment by RussTreadon-NOAA** [comment]
`RussTreadon-NOAA:feature/jediatm_nc` at [`d763546`](https://github.com/RussTreadon-NOAA/global-workflow/commit/d763546446db226606c026918c73b618855a1073) points submodule `gdas.cd` at a GDASApp hash containing the `.nc` changes required by this g-w PR.

**Comment by RussTreadon-NOAA** [comment]
Mark this PR as ready for review now that the `gdas.cd` submodule has been updated.

**Comment by RussTreadon-NOAA** [comment]
That was fast, @aerorahul .  Thank you!

**Pull request merged**
