### PR TITLE
Dummy PR to trigger CI

### PR DESCRIPTION
**Pull request by AnilKumar-NOAA**
# Description

### New CI testing for Gaea system via Jenkins 
# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO
- Does this change require an update to any of the following submodules? YES/NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global
  - [ ] GDAS
  - [ ] GFS-utils
  - [ ] GSI
  - [ ] GSI-monitor
  - [ ] GSI-utils
  - [ ] UFS-utils
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by AnilKumar-NOAA** [comment]
> Checkout **Failed** on Gaea in Build# 1: Could not perform submodule update
Yes, I am checking and looking into it.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA The module load for `git-lsf` is in fact in the [module_gwsetup.gaea.lua](https://github.com/NOAA-EMC/global-workflow/blob/2602eac32fe9b538310ae25f154d219d8400fa0b/modulefiles/module_gwsetup.gaea.lua#L18) file.  But since `git-lsf` is being used the the Jenkins SCM plugin via a shell to C5 the module load has to be ran in the shell that launched the Java agent as demonstrated in [launch_java_agent.sh](https://github.com/NOAA-EMC/global-workflow/blob/2602eac32fe9b538310ae25f154d219d8400fa0b/ci/scripts/utils/launch_java_agent.sh#L89)

**Comment by AnilKumar-NOAA** [comment]
> @AnilKumar-NOAA The module load for `git-lsf` is in fact in the [module_gwsetup.gaea.lua](https://github.com/NOAA-EMC/global-workflow/blob/2602eac32fe9b538310ae25f154d219d8400fa0b/modulefiles/module_gwsetup.gaea.lua#L18) file. But since `git-lsf` is being used the the Jenkins SCM plugin via a shell to C5 the module load has to be ran in the shell that launched the Java agent as demonstrated in [launch_java_agent.sh](https://github.com/NOAA-EMC/global-workflow/blob/2602eac32fe9b538310ae25f154d219d8400fa0b/ci/scripts/utils/launch_java_agent.sh#L89)

Yes, I see git-lfs command not found.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA yes, we ran into this before with you.  Do you understand the solution?

**Comment by AnilKumar-NOAA** [comment]
> @AnilKumar-NOAA yes, we ran into this before with you. Do you understand the solution?

Just trying to gather our discussion and try to recall. It has been few weeks now since then. The machine configuration is done in launch_java_agent.sh. Still not getting

**Comment by AnilKumar-NOAA** [comment]
> > @AnilKumar-NOAA yes, we ran into this before with you. Do you understand the solution?
> 
> Just trying to gather our discussion and try to recall. It has been few weeks now since then. The machine configuration is done in launch_java_agent.sh. Still not getting

I sent you a message on Slack with the link to our discussion about git-lfs.

**Comment by AnilKumar-NOAA** [comment]
We have configured Jenkin node with MODULE_GWSETUP_PATH now, please rerun this PR. Thanks

**Comment by AnilKumar-NOAA** [comment]
Let me look why git is failing this time. ERROR: Checkout failed

hudson.plugins.git.GitException: Command "git submodule update --init --recursive sorc/gdas.cd" returned status code 1:
stdout: 
stderr: error: The following untracked working tree files would be overwritten by checkout:

Is this indicate there were unsaved changes?

**Pull request closed without merging**
