### PR TITLE
Add the capability to use slurm reservation nodes

### LINKED ISSUE #2626: add the capability to use slurm "reservation” nodes
### What new functionality do you need?

add the capability to use slurm "reservation” nodes

### What are the requirements for the new functionality?

SLURM provides “reservations” of compute nodes. We would like to use reservation nodes on Jet.

Also, hpss access jobs can only run in the service partition (i.e. outside reservations), so a new variable "ACCOUNT_SERVICE" is needed.

### Acceptance Criteria

The global workflow can run in SLURM reservation nodes.

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by guoqing-noaa**
# Description
Add the capability to use slurm reservation nodes
Add "ACCOUNT_SERVICE" for jobs to run in PARTITION_SERVICE

  Resolves #2626 

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build on Jet
- Cycled test on Jet
- Forecast-only on Jet

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks reasonable to me.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Review by DavidHuber-NOAA — APPROVED** [review]
Looks good to me.

On a side note, perhaps the method here for `reservation` could probably be expanded to `cluster` as needed for Gaea (FYI @AnilKumar-NOAA @DavidBurrows-NCO).

**Comment by WalterKolczynski-NOAA** [comment]
logfile looks like it was cut off mid-execution. Not even a SIGTERM. The part we have looks fine. May just retry Hercules.

**Comment by WalterKolczynski-NOAA** [comment]
Log on disk is complete. Ends like this:
```
End interp_atmos_sflux.sh at 19:42:42 with error code 0 (time elapsed: 00:00:01)
+ exglobal_atmos_products.sh[190]: export err=0
+ exglobal_atmos_products.sh[190]: err=0
+ exglobal_atmos_products.sh[190]: err_chk
 completed cleanly
+ exglobal_atmos_products.sh[193]: IFS=:
+ exglobal_atmos_products.sh[193]: read -ra grids
+ exglobal_atmos_products.sh[194]: for grid in "${grids[@]}"
+ exglobal_atmos_products.sh[195]: prod_dir=COM_ATMOS_GRIB_1p00
+ exglobal_atmos_products.sh[196]: /bin/cp -p sflux_f015_1p00 /work2/noaa/stmp/CI/HERCULES/2627/RUNTESTS/COMROOT/C48_ATM_2aad9b3e/gfs.20210323/12//products/atmos/grib2/1p00/gfs.t12z.flux.1p00.f015
+ exglobal_atmos_products.sh[197]: wgrib2 -s sflux_f015_1p00
+ exglobal_atmos_products.sh[202]: [[ YES == \Y\E\S ]]
+ exglobal_atmos_products.sh[203]: grp=
+ exglobal_atmos_products.sh[204]: ((  FORECAST_HOUR > 0 & FORECAST_HOUR <= FHMAX_WGNE  ))
+ exglobal_atmos_products.sh[206]: wgrib2 /work2/noaa/stmp/CI/HERCULES/2627/RUNTESTS/COMROOT/C48_ATM_2aad9b3e/gfs.20210323/12//products/atmos/grib2/0p25/gfs.t12z.pgrb2.0p25.f015 -d 597 -grib /work2/noaa/stmp/CI/HERCULES/2627/RUNTESTS/COMROOT/C48_ATM_2aad9b3e/gfs.20210323/12//products/atmos/grib2/0p25/gfs.t12z.wgne.f015

*** FATAL ERROR: record 597 not found ***

+ exglobal_atmos_products.sh[1]: postamble exglobal_atmos_products.sh 1717011684 8
+ preamble.sh[70]: set +x
End exglobal_atmos_products.sh at 19:42:42 with error code 8 (time elapsed: 00:01:18)
+ JGLOBAL_ATMOS_PRODUCTS[1]: postamble JGLOBAL_ATMOS_PRODUCTS 1717011674 8
+ preamble.sh[70]: set +x
End JGLOBAL_ATMOS_PRODUCTS at 19:42:42 with error code 8 (time elapsed: 00:01:28)
+ atmos_products.sh[1]: postamble atmos_products.sh 1717011391 8
+ preamble.sh[70]: set +x
End atmos_products.sh at 19:42:43 with error code 8 (time elapsed: 00:06:12)
```

Doesn't look like anything that would be related to this PR.

**Comment by WalterKolczynski-NOAA** [comment]
I'm separately getting errors from cron, so I think hercules is just having some issues right now.

**Comment by guoqing-noaa** [comment]
Thanks, @WalterKolczynski-NOAA @aerorahul @DavidHuber-NOAA

**Pull request merged**
