### PR TITLE
Add support for waves at low resolution 

### LINKED ISSUE #1333: Provide lower resolution wave model grid & IC set-ups
**Description**
For efficient testing and development, a low resolution wave model set-up is needed within the workflow.   In addition to grids, ICs are needed to be staged (Please let me know if there's already a specific date being used for other testing).  

**Requirements**
Able to run waves within low resolution testing. 

**Acceptance Criteria (Definition of Done)**
Merged in the develop branch and can run low-res fully coupled tests for whatever configurations are currently being tested.  

**Dependencies**
The biggest blocking issue here is my time.

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
**Description**

This adds an option for 2 or 5 deg global wave models, which will provide a light weight version to assist in engineering development.    
-- This PR requires PR #1648 to be merged as this builds on it as well as issue #1652 which adds the fix files needed for this PR to be addressed first. 

The resources were chosen to stay under  1 or 2 node and be faster than the atm component.  

- Fixes #1333 

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Two tests on hera have been completed: 
- [x] C96 5 deg Ocean/Ice 2 deg wave S2SW forecast only: /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/wavelowres/c96o500w200t2
- [x] C48 5 deg Ocean/Ice 5 deg wave S2SW forecast only:  /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/wavelowres/c48o500w500t2

Note for these tests, you must change the wave grid in config.base to glo_200 or glo_500.  ICs are staged on hera for 2021032312  (For the C96 test, you also have to change the ocean resolution to 500).  
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA Are 5° wave ICs available yet? Last I knew we were still waiting on them.

@TerrenceMcGuinness-NOAA would you please add a new CI test for forecast-only S2SWA at C48/5° marine once we have the wave ICs? Work with Jessica if necessary.

**Comment by JessicaMeixner-NOAA** [comment]
> @JessicaMeixner-NOAA Are 5° wave ICs available yet? Last I knew we were still waiting on them.
> 
> @TerrenceMcGuinness-NOAA would you please add a new CI test for forecast-only S2SWA at C48/5° marine once we have the wave ICs? Work with Jessica if necessary.

@WalterKolczynski-NOAA as indicated in the text of the PR, ICs are available for 2021032312, but note you must change the OCNRES for C96 to 5 deg as we do not have 1 deg ocean ICs.

**Comment by WalterKolczynski-NOAA** [comment]
> > @JessicaMeixner-NOAA Are 5° wave ICs available yet? Last I knew we were still waiting on them.
> > @TerrenceMcGuinness-NOAA would you please add a new CI test for forecast-only S2SWA at C48/5° marine once we have the wave ICs? Work with Jessica if necessary.
> 
> @WalterKolczynski-NOAA as indicated in the text of the PR, ICs are available for 2021032312, but note you must change the OCNRES for C96 to 5 deg as we do not have 1 deg ocean ICs.

Oh, are they staged with the rest? Okay, I'll work on synchronizing then.

**Comment by JessicaMeixner-NOAA** [comment]
The ICs are on hera here: 

```
/scratch1/NCEPDEV/climate/role.ufscpara/IC/workflowtest 
.
└── 2021032312
    ├── gfs
    │   ├── C48
    │   │   └── INPUT
    │   │       ├── gfs_ctrl.nc
    │   │       ├── gfs_data.tile1.nc
    │   │       ├── gfs_data.tile2.nc
    │   │       ├── gfs_data.tile3.nc
    │   │       ├── gfs_data.tile4.nc
    │   │       ├── gfs_data.tile5.nc
    │   │       ├── gfs_data.tile6.nc
    │   │       ├── sfc_data.tile1.nc
    │   │       ├── sfc_data.tile2.nc
    │   │       ├── sfc_data.tile3.nc
    │   │       ├── sfc_data.tile4.nc
    │   │       ├── sfc_data.tile5.nc
    │   │       └── sfc_data.tile6.nc
    │   └── C96
    │       └── INPUT
    │           ├── gfs_ctrl.nc
    │           ├── gfs_data.tile1.nc
    │           ├── gfs_data.tile2.nc
    │           ├── gfs_data.tile3.nc
    │           ├── gfs_data.tile4.nc
    │           ├── gfs_data.tile5.nc
    │           ├── gfs_data.tile6.nc
    │           ├── sfc_data.tile1.nc
    │           ├── sfc_data.tile2.nc
    │           ├── sfc_data.tile3.nc
    │           ├── sfc_data.tile4.nc
    │           ├── sfc_data.tile5.nc
    │           └── sfc_data.tile6.nc
    ├── ice
    │   └── 500
    │       ├── 20210323.120000.cice_model.res.nc
    │       └── cice5_model_5.00.res_2021032312.nc -> 20210323.120000.cice_model.res.nc
    ├── ocn
    │   └── 500
    │       └── MOM.res.nc
    └── wav
        ├── glo_200
        │   └── 20210323.120000.restart.glo_200
        └── glo_500
            └── 20210323.120000.restart.glo_500
```

**Comment by JessicaMeixner-NOAA** [comment]
This PR has been marked as ready to review as PR https://github.com/NOAA-EMC/global-workflow/pull/1648 was merged and issue https://github.com/NOAA-EMC/global-workflow/issues/1652 has been at least partially addressed.  Please let me know if anything else is needed from me.

**Comment by WalterKolczynski-NOAA** [comment]
ICs are sync'd to Orion.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA I updated the `config.base` files with waveGRD pairings for each ATM resolution to mirror those done for the ocean resolution. Would you please check them and adjust as necessary? Once that is done, I will send it through CI and then merge if it passes. @TerrenceMcGuinness-NOAA is working on a new CI test for the new resolution, but we will handle that in a separate PR.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA In the future I'd highly appreciate that you coordinate with me before pushing changes to my PR.  The chosen grids for waves are not correct, I will be making changes shortly.  

Does this CI require access for maintainers?  That is why I allowed for maintainers to have access to my PR, I will disable this for future PRs unless this is explicitly required for CI.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA the config.base options have been updated.  Note, the C384 option only has an IC for the one date 2013010100 but that is the gefs grid moving forward.   I'm not sure all the details of this have been thought through sufficiently, particularly in terms of cycling if waves ever end up in the enkf, but these are at least more correct options.  Again, please coordinate with me before pushing any additional changes to this branch.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending CI results

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA I didn't get an answer to my question about CI testing - does this need the box for maintainers to have access? @TerrenceMcGuinness-NOAA might also be able to answer this.  It doesn't look like it but it'd be great to have confirmation.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA I'm going to stop by this afternoon to discuss this with you

**Pull request merged**
