### PR TITLE
Add more ocean variables for post-processing in GEFS

### LINKED ISSUE #2993: Add more ocean variables for ocean post-processing in GEFS
### What new functionality do you need?

Additional ocean variables need to be post-processed in the ocean_prod task for GEFS. 

### What are the requirements for the new functionality?

1.  The requested variables need to be added to `sorc/gfs_utils.fd/parm/ocnicepost/ocean.csv`. A gfs_utils hash update will be needed so that these changes are included in global-workflow. A [PR](https://github.com/NOAA-EMC/gfs-utils/pull/85) has already been submitted in gfs_utils. 
2. `parm/post/oceanice_products_gefs.yaml` needs to be modified so that the needed ocean variables are post-processed. 

### Acceptance Criteria

The ocean grib2/netcdf gridded products included the requested additional variables. 

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
# Description

This PR adds an ocean variable `tob` (Sea Water Potential Temperature at Sea Floor) for post-processing in GEFS, which is a variable that has been requested for GEFSv13 and the reforecast. 

Also, this PR moves the atmos variable `PEVPR` from the "b" group to the "a" group of pgrb products in GEFS. This was requested by a reforecast stakeholder.  

Resolves #2993 

# Type of change
- [ ] Bug fix (fixes something broken)
- [x] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [x] GFS-utils NOAA-EMC/gfs-utils#85
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?

These changes have been tested on WCOSS2. This PR will be left as a draft until the necessary gfs-utils PR is merged. 

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] This change is covered by an existing CI test or a new one has been added
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Comment by EricSinsky-NOAA** [comment]
After testing this branch with the latest gfs_utils hash, the new ocean variable `tob` is successfully being post-processed in the ocean_prod task. Also, `PEVPR` is being successfully written to the "a" atmos pgrb file group. Marking this PR as ready for review.

**Review by WalterKolczynski-NOAA — DISMISSED** [review]

**Comment by EricSinsky-NOAA** [comment]
A change needed to be made to the name of one of the extractvars dependencies due to the changes made in PR #2981. This change has been committed in d7a10a9354c30401647dbacaa2dd61c1237950c7.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@WalterKolczynski-NOAA Build fail with gfs_utils, seems to cause a Jenkins failure, not sure how the two are related:

[guild_gfs_utils.log](https://gist.github.com/emcbot/df12e53e08c71cfdc20f8993ece9b174)

**Comment by WalterKolczynski-NOAA** [comment]
@TerrenceMcGuinness-NOAA Did the build cause a Jenkins failure, or vice versa? The build log looks successful.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
