### PR TITLE
Link ensemble analysis increment files to COMROOT for warm_start

### LINKED ISSUE #2552: Link ensemble ratminc files for warm_start CI
### What is wrong?

`workflow/setup_expt.py` does not link ensemble increments to COMROOT when `warm_start=.true.`

### What should have happened?

When `warm_start=.true.` and ensemble members are specified, `setup_expt.py` should link the required ensemble ratminc files to the appropriate COMROOT directory.

### What machines are impacted?

All or N/A

### Steps to reproduce

1. enable C96C48_ufs_hybatmDA
2. run `setup_expt.py` to create EXPDIR and COMROOT
3. `cd $COMROOT/$pslot/enkfgdas.20240223`.  Directory `18/` containing mem001 and mem002 ratminc.nc files is not present.

### Additional information

The 2024022318 enkfgdasfcst can not be warm_started without the required ratminc files.

### Do you have a proposed solution?

Add logic to `setup_expt.py` to link ensemble increment files when `warm_start=.true.` and ensemble members are included in the experiment setup.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
Scripting is added to `setup_expt.py` to link ensemble analysis increment files to COMROOT for warm_start experiments.

Resolves #2552

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build on Orion
- Run C96C48_ufs_hybatmDA on Orion

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Will mark PR for ready once Orion testing is complete.

**Comment by RussTreadon-NOAA** [comment]
**Orion test**
C96C48_ufs_hybatmDA (JEDI ATM CI)  successfully ran the first half cycle using warm start initial conditions.   C96C48_hybatmDA (GSI ATM CI), a cold start test, has also been launched on Orion.  The first half cycle completed successfully.  The revised `setup_expt.py` works for warm start and does not alter cold start behavior. 

Additionally the JEDI ATM CI 2024022400 gfsfcst ran to completion.   The GSI ATM CI test has not yet run the 2021122100 gfsfcst.
 
**Hera test**
C96C48_ufs_hybatmDA (JEDI ATM CI) and C96C48_hybatmDA (GSI ATM CI) successfully ran the first half cycle.  Additionally, both the JEDI and GSI based parallels successfully ran the gfsfcst in the first full cycle.  

The successful gfsfcst is contrary to what issue #2551 reports.  This issue was using an older snapshot of g-w.  Perhaps recent commits resolved whatever caused the gfsfcst failures reported in #2551.  Another possibility is that the errors reported in #2551 were due to system errors, not g-w problems.

**Comment by RussTreadon-NOAA** [comment]
Orion GSI ATM CI also successfully ran 2021122100 gfsfcst.   So on both Orion and Hera the 00Z gfsfcst now successfully runs.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Pull request merged**
