### PR TITLE
Fix field table missing newline at EOF

### LINKED ISSUE #1764: Missing \n in two field tables
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**

field tables should have \n at the end of file.
**Current behavior**

field tables "field_table_thompson_noaero_tke_progsigma" and "field_table_zhaocarr_satmedmf_progsigma" missing \n
**Machines affected**

Hera and WCOSS2, but should be same for all the machines
**To Reproduce**

Run HR1 aerosol, the rebuilt field table will be missing one line for "prognotsitc sigmab tracer". 
**Context**

**Detailed Description**

**Additional Information**

**Possible Implementation**

### PR DESCRIPTION
**Pull request by bingfu-NOAA**
**Description**
Two field tables has \n missing. This can lead to one of the lines is missing when the field table is rebuilt for aerosol applications. And one of the impacts is large bias of sea salt concentration for aerosol applications. 
This PR is to fix two field table files that missing \n

Resolves #1764 

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [x] Forecast-only test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good to me.

**Comment by aerorahul** [comment]
Just getting a confirmation from @JessicaMeixner-NOAA

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
> Just getting a confirmation from @JessicaMeixner-NOAA

I think @NeilBarton-NOAA would be a better person to confirm this particular update.

**Comment by aerorahul** [comment]
> > Just getting a confirmation from @JessicaMeixner-NOAA
> 
> I think @NeilBarton-NOAA would be a better person to confirm this particular update.

Ok.  I just requested you since you added these files in https://github.com/NOAA-EMC/global-workflow/pull/1197

**Pull request merged**
