### PR TITLE
Rename the land DA jobs to snow DA to better reflect what they are doing

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
# Description
This PR renames all of the land DA jobs to snow DA to better reflect that this is a JEDI-based snow analysis capability and not a more generic land surface analysis. 

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? YES (if it is previously documented)

# How has this been tested?
- Cycled test on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by jiaruidong2017 — APPROVED** [review]
Approve pending on success of CI test.

**Review by aerorahul — COMMENTED** [review]
@CoryMartin-NOAA 
Changes look fine here.  Thanks for making the change to identify this is snow DA.

If you could please update the branch and resolve the conflicts, that would be great.

Additionally, please remove `hera` from `ci/cases/pr/C96_atmsnowDA.yaml` so we can run this PR with the snowDA test.

**Comment by CoryMartin-NOAA** [comment]
@aerorahul done

**Review by aerorahul — APPROVED** [review]
Looks good.
Thanks!

**Pull request merged**
