### PR TITLE
Update gsi analysis script and fix files with gfs v16.3.9 changes.

### LINKED ISSUE #1856: Update gsi fix files for gfs.v16.3.9
### Target fix directory

gsi

### Type of change

- [X] Update existing files

### Any workflow changes needed?

Fix version only

### Related issues

NOAA-EMC/GSI-fix issue [#9](https://github.com/NOAA-EMC/GSI-fix/issues/9)
 - global_convinfo.txt - assimilate PlanetIQ gpsro
 - global_ozinfo.txt - assimilate NOAA-20 OMPS, adjust OMP observation errors (all satellite platforms)
 
NOAA-EMC/global-workflow issue #1813

### Pickup location

Hera /scratch2/NCEPDEV/stmp1/Russ.Treadon/fix/gsi/20230911

### Size

0.043 Mb smaller.  20230601 at 2333.973 Mb vs 20230911 at 2333.930 Mb

*** To Do

- [x] Pull new GSI fix folder into primary fix location (@KateFriedman-NOAA @WalterKolczynski-NOAA )
- [ ] Update `gsi_ver` in `versions/fix.ver`
- [x] Update timestamp for gsi subfolder in fix spreadsheet

### LINKED ISSUE #1857: Update exglobal_atmos_analysis.sh with gfs.v16.3.9 changes
### What new functionality do you need?

This issue is not requesting a new functionality.  It is opened instead to update `exglobal_atmos_analysis.sh` with changes from gfs.v16.3.9.   

One of the changes in gfs.v16.3.9 was to turn off ingest of NOAA-21 radiances in the GSI.  This was achieved by removing the following lines 
```
    atmsbufr       atms        n21         atms_n21            0.0     1     1
    crisfsbufr     cris-fsr    n21         cris-fsr_n21        0.0     1     0
```
from the `OBS_INPUT` section of the GSI namelist in `exglobal_atmos_analysis.sh`

While operational GSI still maintains `exglobal_atmos_analysis.sh` in the GSI repository, this is not true for the development GSI.   g-w maintains `exglobal_atmos_analysis.sh` for the development GSI.   As such, this issue is opened to get the above two line change into g-w `exglobal_atmos_analysis.sh`.

### What are the requirements for the new functionality?

The updated `exglobal_atmos_analysis.sh` script will not process NOAA-21 radiances.

### Acceptance Criteria

The updated `exglobal_atmos_analysis.sh` script does not process NOAA-21 radiances.

### Suggest a solution (optional)

As with GFS v16.3.9, remove the two NOAA-21 lines noted above from the `OBS_INPUT` namelist in `exglobal_atmos_analysis.sh`.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**

GFS v16.3.9 was implemented 20230911 12Z.  The following changes were implemented into operations:
- turns off ingest of NOAA-21 radiances into the GSI,
-  PlanetIQ GPSRO and NOAA-20 OMPS (Ozone Mapping and Profiler Suite) Ozone retrievals will be actively assimilated,
-  OMPS observation errors will be adjusted.

g-w PR #1852 brought these changes into g-w branch [`dev/gfs.v16`](https://github.com/NOAA-EMC/global-workflow/tree/dev/gfs.v16).  This PR brings the same changes into g-w `develop`.

Fixes #1856
Fixes #1857

Related to, but not dependent on, GSI [#621](https://github.com/NOAA-EMC/GSI/pull/621)

# Type of change
- Maintenance - update `develop` with changes from GFS v16.3.9 implementation

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO.  Functionally is not changed but analysis results will change if impacted observations are assimilated.
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build on WCOSS
- Cycled test on WCOSS

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]

**Review by WalterKolczynski-NOAA — COMMENTED** [review]
Won't this cause retrospective experiments to now be missing the NOAA-21 data? Seems like this needs to be date-gated somehow.

**Comment by RussTreadon-NOAA** [comment]
We are not yet assimilating NOAA-21 radiances from ATMS or CrIS.  `CRTM_FIX` for `crtm/2.4.0` does not contain CRTM coefficients for NOAA-21 sensors.  GFS v16.3.10 is being proposed as the implementation in which we assimilate NOAA-21.   

GFS v16.3.9 removed NOAA-21 ATMS and CrIS from the GSI namelist because this data is or soon will be dumped.   If it's dumped and listed in the GSI namelist, the GSI will attempt to read the data and fail.  We didn't want this to happen in operations.

**Comment by WalterKolczynski-NOAA** [comment]
Okay, got it.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending CI testing results

**Pull request merged**
