### PR TITLE
Fix Index Error from WDQMS Python Script in release/gfs.v16.3.16

### PR DESCRIPTION
**Pull request by emilyhcliu**
# Description
This PR fixes the Python `IndexError` reported by NCO's test for the implementation of adding WDQMS processing into global-workflow
 
Note:
1. I am having trouble opening issue to report this bug (the submit button disabled).  I will try again to open an issue related to this PR.
2. Please add @kevindougherty-noaa as reviewer

Case study for 2024040212:
1. Reproduced IndexError for MARINE processing but not for TEMP
3. Function `genqsat` failed when temperature, moisture, and  pressure do not have consistent dimensions and thus caused index error
4. The Python numpy in1d function does not work as expected.  The in1d does not match elements in the selected columns strictly row by row.  

Proposed fixes: 
1. Drop duplicates from df_total
2. Replace in1d with merge, and drop duplicates for selected columns

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Stand-alone (outside of global-workflow) test from 2024010100 - 2024041018 (404 stand-alone cycles tested)
- Cycled test on WCOSS-2 from 2024033118 to 2024040618 and 2023123118 to ? (to be determined)

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu I just merged the other PR so please sync your branch for this PR with the updates in the release branch. Thanks!

**Comment by emilyhcliu** [comment]
@kevindougherty-noaa and I have come up with the final version of the bug fix for the Index Error from Python when processing MARINE data. 

We are doing the following test for the bug fix:

1. The stand-alone WDQMS processing for three month.  (2024 January, February, March, and up to April 04 18Z)
2. GFS parallel experiment with deterministic GDAS (no ensembles) starting from 2023123118.

**Comment by aerorahul** [comment]
> @kevindougherty-noaa and I have come up with the final version of the bug fix for the Index Error from Python when processing MARINE data.
> 
> We are doing the following test for the bug fix:
> 
> 1. The stand-alone WDQMS processing for three month.  (2024 January, February, March, and up to April 04 18Z)
> 2. GFS parallel experiment with deterministic GDAS (no ensembles) starting from 2023123118.

Thanks @emilyhcliu 
If this is ready, we can merge and you can continue the testing.  If an update is required, just open a new PR.

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu If ready, please bring this PR out of draft mode. Thanks!

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA I am running the parallel for a few cycles to make sure the output file names are correct (following our guideline), and check if the index errors are gone.

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu Okie dokie. When you're ready, please move this out of draft and we can review and merge. Thanks for the update!

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA @aerorahul 
We have tested the proposed fix in both cycled experiment (global-workflow) and stand-alone test (wdqms processing only):
- global-workflow cycled experiments (2023123118-2024010200 and 2024033118- 2024040518)
- stand-alone test (404 cases from 2024010100 to 2024041018)

Two checks:
- [x] The proposed bug fix resolves the Index Error from Python 
- [x] The WDQMS product follows the naming convention of NCEP guidline (Referece: [PR #2470](https://github.com/NOAA-EMC/global-workflow/pull/2470))

This is PR is ready to be merged back to release/gfs.v16.3.16.

**Comment by emilyhcliu** [comment]
@KateFriedman-NOAA  @aerorahul 
One question:
I am updating the PNS related to this implementation and will share it with you later.
How about SCN, do we have an SCN for WDQMS already?  If not, I will create one.  Please let me know.

**Comment by KateFriedman-NOAA** [comment]
> How about SCN, do we have an SCN for WDQMS already? If not, I will create one. Please let me know.

Not that I know of, please create one. Thanks!

**Comment by emilyhcliu** [comment]
> > How about SCN, do we have an SCN for WDQMS already? If not, I will create one. Please let me know.
> 
> Not that I know of, please create one. Thanks!

OK, I will create one today.

**Review by aerorahul — APPROVED** [review]
Looks good.
@kevindougherty-noaa 
If you can approve, we can merge this.

**Review by kevindougherty-noaa — APPROVED** [review]
We tested a few different approaches and this was the best result. Thank you @emilyhcliu for taking this on when I was on leave!

**Pull request merged**
