### PR TITLE
Add new data sources used in GFS v16.3.12

### PR DESCRIPTION
**Pull request by ADCollard**
Changes to `scripts/exglobal_atmos_analysis.sh` to include new data that are being operationally assimilated in GFS v16.3.12.

**Note that this requires CRTM v2.4.0.1 **

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Since hirs dump files are not included in the list of bufr dump files to link, we don't need to comment out `B1HRS2`, `B1HRS3`, and `B1HRS4`.   Even if the dump files exist, they are not copied or linked to the run directory.   The same comment applies to `ESHRS3` and `HRS3DB`.

Given this, should we simply remove the variables pointing at hirs dump files instead of commenting out the line?   Either approach is OK.  Just asking.

The other change in `exglobal_atmos_analysis.sh` is to add abi_g18, atms_n21, and cris-fsr_n21 are added `OBS_INPUT`.  This is correct.

**Comment by ADCollard** [comment]
@RussTreadon-NOAA I am hoping that the removal of HIRS is a temporary measure (as I think there is still a need in reanalysis) and it can be re-instated once a revised version of CRTM  is installed.  So I was leaving it here as a reminder.

But I'd also be happy to remove it completely.

**Review by RussTreadon-NOAA — APPROVED** [review]
I'm fine with what you have.

Approve.

**Review by HaixiaLiu-NOAA — APPROVED** [review]
changes look good to me. Approving now.

**Review by emilyhcliu — APPROVED** [review]

**Review by KateFriedman-NOAA — COMMENTED** [review]
This PR looks to cover half of the checklist items in issue #1918. Will the following remaining checklist items be added to this PR when it comes out of draft mode?
* Update GSI hash to one that uses new CRTM version
* Update ufs-weather-model hash to one that uses new CRTM version
* Update UPP hash to one that uses new CRTM version
* Uncomment GMI line scripts/exglobal_atmos_analysis.sh (commented out in https://github.com/NOAA-EMC/global-workflow/pull/1404).

**Comment by ADCollard** [comment]
@KateFriedman-NOAA 

I am working on the first three.   The GMI change will not go in until the obsproc v1.2 upgrade that will fix erroneous GMI dumps.

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Great! I will open a separate g-w issue to update to `obsproc.v1.2` and make the GMI change in the future.

**Comment by ADCollard** [comment]
After merging `develop` into this fork, I ran a c96 test case on Hera for a full cycle without incident.

ufs appears to compile with `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8/install/intel/2021.5.0/crtm-2.4.0-alizlgl` but runs with ` crtm-fix/2.4.0.1_emc` loaded.  Apparently without incident.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
