### PR TITLE
Update to add 1-deg global wave grid

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Description
This PR adds options to use a global 1 deg grid, intended for testing with the SFS applicaiton.   

Requires new fix file chnages https://github.com/NOAA-EMC/global-workflow/issues/2618 

# Type of change
- New feature  - new wave grid option 

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO

# How has this been tested?

- Forecast-only on Hera, GEFS with 1 enemble member: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/SFS/testwave02/sfs06/sfs06/
Note this was tested with @NeilBarton-NOAA branch + some updates that shouldn't be used in develop, but this did test that the grid and mesh file were as expected. 

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Marking as draft until the prerequisite fix files have been staged.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA Please merge in develop to get the CI fixes, then I think we are ready for CI testing.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA done! Thanks!

**Pull request merged**
