### PR TITLE
PR Low resolution ecflow and JET changes into global-workflow develop

### PR DESCRIPTION
**Pull request by lgannoaa**
Merge global-workflow develop with JET update to enable developer run rocoto workflow forecast only.

### CODE REVIEW

**Comment by lgannoaa** [comment]
Combined merge global-workflow develop with low resolution ecflow enhancement to enable developer using cycled ecflow parallel C192C96L127 on WCOSS,

**Comment by aerorahul** [comment]
Can we please break this PR into smaller PR's?
Also, please provide as detailed description as possible in the PR on what is being changed/added/removed in each PR.

Reviewing changes in 451 files is impossible to do so in a timely or thorough manner.

**Comment by lgannoaa** [comment]
> Can we please break this PR into smaller PR's?
> Also, please provide as detailed description as possible in the PR on what is being changed/added/removed in each PR.
> 
> Reviewing changes in 451 files is impossible to do so in a timely or thorough manner.

Thank you Rahul for your comment, let me try to describe it:
1. I have two on-line documents
    ecflow: https://docs.google.com/presentation/d/1HyIx3rHTKnj8pKVuW1SEb52gt2J6Zi0UsKau0eSjpZA/edit?usp=sharing
    rocoto jet: https://docs.google.com/presentation/d/16PJ6FMdrfl2BpKlO3QvwO5paz13o8CoPM4u7YRQZcWQ/edit?usp=sharing
2. The major part of these 451 files changes are associated with ecflow scripts. There are needed and can not be separated.
3. The HOMEgfs/ecflow directory is replaced with the low resolution ecflow solution (this is requested by Arun)
4. The Jet changes are clear in file diff.

I suggest we can have a google meet to talk about your question.
Thank you.

**Comment by aerorahul** [comment]
The Jet changes can clearly be separated into another PR.

**Comment by lgannoaa** [comment]
> The Jet changes can clearly be separated into another PR.

Should I delete this PR and create two PRs instead? It will save time not to. Because the Jet change is already been used by the physics group for a few months. I put this into PR now to complete the merge requested by Arun.

Let me know how you want it to be done.
Thanks

**Comment by arunchawla-NOAA** [comment]
Lin please separate Jet related changes from the low res ecflow related changes -- The low res ecflow options need to be a separate PR. Is there a way to reduce the number of file changes for ecflow to run low vs high resolution?

**Comment by lgannoaa** [comment]
> Lin please separate Jet related changes from the low res ecflow related changes -- The low res ecflow options need to be a separate PR. Is there a way to reduce the number of file changes for ecflow to run low vs high resolution?

Hi Arun,
Ok. I will delete this PR and create two separated PR. One for JET and the other for ECFLOW.
The number of changes for running ecflow in high and low resolution are small, However, many files need to be updated to include these small changes. That is how ecflow works.
Thank you for your question.

**Comment by aerorahul** [comment]
@arunchawla-NOAA @lgannoaa 
Having a PR so big is a recipe for disaster.
Having inadequate description in the PR is a red flag.
Not to mention the repetition of the scripts that should be templated and generated when setting up the experiment.
Then there are scripts creating scripts within.

**Comment by lgannoaa** [comment]
Close this PR as requested by Arun.

**Pull request closed without merging**
