### PR TITLE
Add Gaea C5 to CI

### PR DESCRIPTION
**Pull request by AnilKumar-NOAA**
# Description
Adds gaea as a recognized machine in the CI system.

# Type of change

- New CI test for Gaea C5 system 

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO
- Does this change require an update to any of the following submodules? YES/NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global
  - [ ] GDAS
  - [ ] GFS-utils
  - [ ] GSI
  - [ ] GSI-monitor
  - [ ] GSI-utils
  - [ ] UFS-utils
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by TerrenceMcGuinness-NOAA — APPROVED** [review]
Looks good!

**Comment by AnilKumar-NOAA** [comment]
@WalterKolczynski-NOAA - Please check this PR for merge. Terry is the one reviewer and need your approval for final merge. Thanks

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
Title and description both say Jenkinsfile, but I see no Jenkinsfile changes.

**Comment by AnilKumar-NOAA** [comment]
Initially, we made changes to the Jenkinsfile, adding Gaea in several places. However, Terry later updated the Jenkinsfile himself, incorporating the Gaea additions (nodename and custom_workspace) and pushed those changes to my repo, which is why they're not reflected in this PR.

**Comment by WalterKolczynski-NOAA** [comment]
@AnilKumar-NOAA I've updated them this time. Next time, please update them yourself to be consistent with what the PR is actually doing.

**Pull request merged**
