### PR TITLE
Support for the GDASApp testing in containers

### PR DESCRIPTION
**Pull request by guillaumevernieres**
**Description**

Features proposed to be added:
-  Support for running part of the global-workflow in a container (only works with the GDASApp for now).
~- Moves a few default values from `config.ocnanal` to the new `defaults.yaml` recently added by @aerorahul~

`CONTAINER.env` is quite minimalist at this point, it could also certainly be cleaned up, but since this is just a draft PR ...

Issues fixed:
- Fixes #1234

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**
In containers, running the 3 ctests related to the g-w
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by aerorahul** [comment]
This looks great!
Just please remove changes to `config.ocnanal` and `defaults.yaml` from this PR as they appear to be subject of a different PR.

And please fix the linter comments.

**Comment by guillaumevernieres** [comment]
> This looks great! Just please remove changes to `config.ocnanal` and `defaults.yaml` from this PR as they appear to be subject of a different PR.
> 
> And please fix the linter comments.

Thanks for the review @aerorahul . I removed the files that are not related to this PR.

**Review by aerorahul — APPROVED** [review]
Looks good to me.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
I imagine other parts of the system will need to be expanded (like gfs_utils) to support all but simple tests in containers?

**Comment by guillaumevernieres** [comment]
> I imagine other parts of the system will need to be expanded (like gfs_utils) to support all but simple tests in containers?

I would like to cover the cycling at somepoint, but that will require a container can be used to build both the ufs and jedi.
Could this be merged now by any-chance @WalterKolczynski-NOAA ?

**Comment by aerorahul** [comment]
> > I imagine other parts of the system will need to be expanded (like gfs_utils) to support all but simple tests in containers?
> 
> I would like to cover the cycling at somepoint, but that will require a container can be used to build both the ufs and jedi. Could this be merged now by any-chance @WalterKolczynski-NOAA ?

Yes, @WalterKolczynski-NOAA will merge this today as is.  I don't think he means to hold this up till the other components are enabled (whenever that will be).

**Comment by WalterKolczynski-NOAA** [comment]
Yeah, I was just looking for more info. Thanks!

**Pull request merged**
