### PR TITLE
Update ufs model hash to 20240625

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Description
Updates UFS weather model hash to hash from  2024-06-24 which has orion porting updates + a few namelist updates. 

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)?  NO
- Does this change require a documentation update?  NO

# How has this been tested?
Tested with other chnages on hera (only a half test as things failed), currently have a C48mx500 S2SW forecast running on wcoss2.  Needs full CI testing. 

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — DISMISSED** [review]
looks good.

**Comment by JessicaMeixner-NOAA** [comment]
Not sure why this PR would break a gdas build as there was no chnage.

**Comment by RussTreadon-NOAA** [comment]
The `gdas.cd` hash associated with g-w `develop` is obsolete.  GDASApp PR [#1202](https://github.com/NOAA-EMC/GDASApp/pull/1202) changed `model_data` to `model` as per NCO requirements (see g-w issue #2686).   We used this opportunity to clean up the directory structure for GDASApp CI.   

The GDASApp build in this PR failed because it is looking for `gdasapp-fix-bda76f.tgz` using a path which no longer exists.

**Comment by RussTreadon-NOAA** [comment]
As a temporary fix I added links on Dogwood to mimic the old directory structure shown below
```
setenv("CRTM_FIX","/lfs/h2/emc/da/noscrub/emc.da/GDASApp/fix/crtm/2.4.0")
setenv("GDASAPP_TESTDATA","/lfs/h2/emc/da/noscrub/emc.da/GDASApp/data")
setenv("GDASAPP_UNIT_TEST_DATA_PATH", "/lfs/h2/emc/da/noscrub/emc.da/GDASApp/data/test")
```

**Comment by RussTreadon-NOAA** [comment]
The Hera failure is strange.  Directory `/scratch1/NCEPDEV/global/CI/2729/gfs/sorc/gdas.cd/sorc/vader` only contains `.git`. 

[`JessicaMeixner-NOAA:updateufs20240625`](https://github.com/JessicaMeixner-NOAA/global-workflow/tree/updateufs20240625) points at [`gdas.cd @ 368c9c5`](https://github.com/NOAA-EMC/GDASApp/tree/368c9c5db9b5ea62e72937b6d1b0f753adb9be40).   This GDASApp has points at [`vader @ 8210ecc`](https://github.com/jcsda/vader/tree/8210eccf77b80f51cce470ecdd5dd4cc2ec646bc).  This snapshot of vader contains more than just `.git`

**Comment by aerorahul** [comment]
> The Hera failure is strange. Directory `/scratch1/NCEPDEV/global/CI/2729/gfs/sorc/gdas.cd/sorc/vader` only contains `.git`.
> 
> [`JessicaMeixner-NOAA:updateufs20240625`](https://github.com/JessicaMeixner-NOAA/global-workflow/tree/updateufs20240625) points at [`gdas.cd @ 368c9c5`](https://github.com/NOAA-EMC/GDASApp/tree/368c9c5db9b5ea62e72937b6d1b0f753adb9be40). This GDASApp hash points at [`vader @ 8210ecc`](https://github.com/jcsda/vader/tree/8210eccf77b80f51cce470ecdd5dd4cc2ec646bc). This snapshot of vader contains more than just `.git`

sounds like a full disk and git failed

**Comment by JessicaMeixner-NOAA** [comment]
Global disk space seems okay: 	

Project: global 
		Directory: /scratch1/NCEPDEV/global DiskInUse=328906 GB, Quota=387000 GB, Files=42804324, FileQUota=77400000

**Comment by RussTreadon-NOAA** [comment]
Does automated CI have logs which can confirm that the `/scratch1/NCEPDEV/global` fileset is full?   

I ask because I am currently in `/scratch1/NCEPDEV/global/Russ.Treadon/git/global-workflow/develop`.  My `git clone` of g-w `develop` failed not due to a disk quota issue.  Instead I see
```
/scratch1/NCEPDEV/global/Russ.Treadon/git/global-workflow/develop$ git clone --recursive https://github.com/NOAA-EMC/global-workflow.git .
Cloning into '.'...
remote: Enumerating objects: 61037, done.
remote: Counting objects: 100% (726/726), done.
remote: Compressing objects: 100% (440/440), done.
^Cfetch-pack: unexpected disconnect while reading sideband packet

Hera(hfe06):/scratch1/NCEPDEV/global/Russ.Treadon/git/global-workflow/develop$
```

**Comment by WalterKolczynski-NOAA** [comment]
```
nid001072.dogwood.wcoss2.ncep.noaa.gov 0: Configuration input file is: /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/gfs.t00z.aerovar.yaml
Full configuration is:YAMLConfiguration[path=/lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/gfs.t00z.aerovar.yaml, root={cost function => {cost type => 3D-FGAT , time window => {begin => 2021-12-20T21:00:00Z , length => PT6H} , analysis variables => (mass_fraction_of_sulfate_in_air,mass_fraction_of_hydrophobic_black_carbon_in_air,mass_fraction_of_hydrophilic_black_carbon_in_air,mass_fraction_of_hydrophobic_organic_carbon_in_air,mass_fraction_of_hydrophilic_organic_carbon_in_air,mass_fraction_of_dust001_in_air,mass_fraction_of_dust002_in_air,mass_fraction_of_dust003_in_air,mass_fraction_of_dust004_in_air,mass_fraction_of_dust005_in_air,mass_fraction_of_sea_salt001_in_air,mass_fraction_of_sea_salt002_in_air,mass_fraction_of_sea_salt003_in_air,mass_fraction_of_sea_salt004_in_air) , geometry => {fms initialization => {namelist filename => ./fv3jedi/fmsmpp.nml , field table filename => ./fv3jedi/field_table} , akbk => ./fv3jedi/akbk.nc4 , layout => (8,8) , npx => 97 , npy => 97 , npz => 127 , field metadata override => ./fv3jedi/fv3jedi_fieldmetadata_restart.yaml} , model => {name => PSEUDO , datapath => ./bkg , filetype => fms restart , filename is datetime templated => true , tstep => PT3H , filename_core => %yyyy%mm%dd.%hh%MM%ss.fv_core.res.nc , filename_trcr => %yyyy%mm%dd.%hh%MM%ss.fv_tracer.res.nc , filename_cplr => %yyyy%mm%dd.%hh%MM%ss.coupler.res} , background => {datapath => ./bkg , filetype => fms restart , datetime => 2021-12-20T21:00:00Z , filename_core => 20211220.210000.fv_core.res.nc , filename_trcr => 20211220.210000.fv_tracer.res.nc , filename_cplr => 20211220.210000.coupler.res , state variables => (t,delp,sphum,so4,bc1,bc2,oc1,oc2,dust1,dust2,dust3,dust4,dust5,seas1,seas2,seas3,seas4)} , background error => {covariance model => FV3JEDI-ID , date => 2021-12-20T21:00:00Z} , observations => {observers => ({obs space => {name => viirsnid001072.dogwood.wcoss2.ncep.noaa.gov 0: _n20_aod , obsdatain => {engine => {type => H5File , obsfile => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/obs/gfs.t00z.viirs_n20.2021122100.nc4}} , obsdataout => {engine => {type => H5File , obsfile => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/diags/diag_viirs_n20_2021122100.nc4}} , io pool => {max pool size => 1} , simulated variables => (aerosolOpticalDepth) , channels => 4} , get values => {interpolation method => barycentric , time interpolation => linear} , obs operator => {name => AodCRTM , Absorbers => (H2O,O3) , obs options => {Sensor_ID => v.viirs-m_j1 , EndianType => little_endian , CoefficientPath => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/crtm/ , AerosolOption => aerosols_gocart_default}} , obs error => {covariance model => diagonal} , obs filters => ({filter => PreQC , maxvalue => 1},{filter => Domain Check , where => ({variable => {name => latitude@MetaData} , minvalue => -60 , maxvalue => 60})},{filter => Bounds Check , filter variables => ({name => aerosolOpticalDepth , channels => 4}) , minvalue => 0 , maxvalue => 4.9 , action => {name => reject}},{filter => Background Check , channels => 4 , threshold => 3 , action => {name => inflate error , inflation factor => 3}})},{obs space => {name => viirs_npp_aod , obsdatain => {engine => {type => H5File , obsfile => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/obs/gfs.t00z.viirs_npp.2021122100.nc4}} , obsdataout => {engine => {type => H5File , obsfile => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/diags/diag_viirs_npp_2021122100.nc4}} , io pool => {max pool size => 1} , simulated variables => (aerosolOpticalDepth) , channels => 4} , get values => {interpolation method => barycentric , time interpolation => linear} , obs operator => {name => AodCRTM , Absorbers => (H2O,O3) , obs options => {Sensor_ID => v.viirs-m_npp , EndianType => little_endian , Coeffinid001072.dogwood.wcoss2.ncep.noaa.gov 0: cientPath => /lfs/h2/emc/stmp/terry.mcguinness/RUNDIRS/C96_atmaerosnowDA_68dc5c74/gfsaeroanl_00/crtm/ , AerosolOption => aerosols_gocart_default}} , obs error => {covariance model => diagonal} , obs filters => ({filter => PreQC , maxvalue => 1},{filter => Domain Check , where => ({variable => {name => latitude@MetaData} , minvalue => -60 , maxvalue => 60})},{filter => Bounds Check , filter variables => ({name => aerosolOpticalDepth , channels => 4}) , minvalue => 0 , maxvalue => 4.9 , action => {name => reject}},{filter => Background Check , channels => 4 , threshold => 3 , action => {name => inflate error , inflation factor => 3}})})}} , variational => {minimizer => {algorithm => DRPCG} , iterations => ({ninner => 35 , gradient norm reduction => 1e-10 , test => true , geometry => {fms initialization => {namelist filename => ./fv3jedi/fmsmpp.nml , field table filename => ./fv3jedi/field_table} , akbk => ./fv3jedi/akbk.nc4 , layout => (8,8) , npx => 97 , npy => 97 , npz => 127 , field metadata override => ./fv3jedi/fv3jedi_fieldmetadata_restart.yaml} , diagnostics => {departures => bkgmob}},{ninner => 35 , gradient norm reduction => 1e-10 , test => true , geometry => {fms initialization => {namelist filename => ./fv3jedi/fmsmpp.nml , field table filename => ./fv3jedi/field_table} , akbk => ./fv3jedi/akbk.nc4 , layout => (8,8) , npx => 97 , npy => 97 , npz => 127 , field metadata override => ./fv3jedi/fv3jedi_fieldmetadata_restart.yaml} , diagnostics => {departures => bkgmob1}})} , final => {diagnostics => {departures => anlmob} , increment => {geometry => {fms initialization => {namelist filename => ./fv3jedi/fmsmpp.nml , field table filename => ./fv3jedi/field_table} , akbk => ./fv3jedi/akbk.nc4 , layout => (8,8) , npx => 97 , npy => 97 , npz => 127 , field metadata override => ./fv3jedi/fv3jedi_fieldmetadata_restart.yaml} , output => {state component => {datapath => ./anl , prefix => aeroinc , filetype => fms restart , filename_core => 20211221.000000.fv_core.res.nc , filename_trcr => 20211221.000000.fv_tracer.nid001072.dogwood.wcoss2.ncep.noaa.gov 0: res.nc , filename_cplr => 20211221.000000.coupler.res , state variables => (t,delp,sphum,so4,bc1,bc2,oc1,oc2,dust1,dust2,dust3,dust4,dust5,seas1,seas2,seas3,seas4)}}}}}]
nid001072.dogwood.wcoss2.ncep.noaa.gov 0: OOPS_STATS ObjectCountHelper started.
nid001072.dogwood.wcoss2.ncep.noaa.gov 0: OOPS_STATS Run start                                - Runtime:      5.11 sec,  Memory: total:    76.27 Gb, per task: min =   115.64 Mb, max =   243.01 Mb
Run: Starting oops::Variational<FV3JEDI, UFO and IODA observations>
nid001072.dogwood.wcoss2.ncep.noaa.gov 0: OOPS_STATS Variational start                        - Runtime:     5.11 sec,  Local Memory:   126.60 Mb
nid001072.dogwood.wcoss2.ncep.noaa.gov 0: 
FATAL from PE     0: get_ascii_file_num_lines: File ./fv3jedi/fmsmpp.nml does not exist.

nid001072.dogwood.wcoss2.ncep.noaa.gov 0: 
FATAL from PE     0: get_ascii_file_num_lines: File ./fv3jedi/fmsmpp.nml does not exist.
```

**Comment by JessicaMeixner-NOAA** [comment]
Looks like this is a failure for missing model variable.  I will look into this more here in about an hour.

**Comment by JessicaMeixner-NOAA** [comment]
There was one variable undefined that's just in the 1 ufs.configure template.  I added it in the same way rt.sh uses it.  This will effect any test using S2S_esmf ufs.configure template.

**Review by aerorahul — APPROVED** [review]

**Pull request merged**
