### PR TITLE
Increase wallclock for analysis job

### LINKED ISSUE #1996: GSI-based analysis jobs dying after hitting wallclock limit on Orion
### What is wrong?

The GSI-based analysis jobs are running out of walltime before completing on Orion.

### What should have happened?

Analysis jobs should complete

### What machines are impacted?

Orion

### Steps to reproduce

1. Set up a cycled experiment on Orion
2. Observe workflow failure for analysis jobs

### Additional information

Unsure what conditions changed on Orion to cause this issue.

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
Increases the wallclock limit of the analysis job so the job completes on Orion.

Resolves #1996

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Letting CI handle it

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
The issue seems to be something other than just the wall time.

**Comment by WalterKolczynski-NOAA** [comment]
Going to resurrect this and just increase wallclock to something that seems to be working until a better solution is found.

**Comment by RussTreadon-NOAA** [comment]
> Going to resurrect this and just increase wallclock to something that seems to be working until a better solution is found.

Agreed.  Waiting for change to `/work/noaa/nems/arichert/spack-stack-1.4.1-gw/envs/gw/install/modulefiles/Core` permissions.  I do not belong to the `nems` group.  Thus, I cannot access `/work/noaa/nems/arichert/spack-stack-1.4.1-gw`.

**Comment by WalterKolczynski-NOAA** [comment]
Gonna close this again since it looks like the real fix has been found.

**Pull request closed without merging**
