### PR TITLE
HR4 GWD update

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
# Description

This PR replaces/builds on https://github.com/NOAA-EMC/global-workflow/pull/2670 Authored by @Qingfu-Liu  

The following description is copied from that PR: 

This PR#2670 depends on ufs-weather-model PR[#2290](https://github.com/ufs-community/ufs-weather-model/pull/2290) (waiting to merge), fv3atm [PR#836](https://github.com/NOAA-EMC/fv3atm/pull/836) and ccpp-physics [PR#207](https://github.com/ufs-community/ccpp-physics/pull/207).

This update is a combination of the gravity wave drag (GWD) versions from the NOAA/GSL and NOAA/PSL

The test results with this update can be seen in:
a) summer: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/hr3e50s
b) winter: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/hr3d11w
HR4GWD: same as HR3 but with the updated GWD

Compared to the HR2 and HR3, the HR4GWD shows a significant improvement especially in 500mb height AC and CONUS precipitation forecast skills. The HR4GWD reduces the cold and dry biases in the lower troposphere compared to the HR3. It also reduces the negative wind speed biases in the troposphere compared to the HR2.

This PR #2670 includes changes for four scripts, and new orographic data.
The new orographic data temporarily stored at:
/scratch1/NCEPDEV/global/Qingfu.Liu/git/GWD_SHong/APR2023_SSO
and this new data should replace the old data: /scratch1/NCEPDEV/global/glopara/fix/ugwd/20231027

This is relevant to issue: https://github.com/NOAA-EMC/global-workflow/issues/2716 

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Testing is ongoing. Experiment results are shared above. 

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Recent test is in wavepostpnt for forecast only: /scratch1/NCEPDEV/climate/Jessica.Meixner/GWDupdate/update01/test01 

I believe this is now ready for review and CI testing.

**Review by aerorahul — DISMISSED** [review]
looks good to me.

**Comment by aerorahul** [comment]
@NeilBarton-NOAA @bingfu-NOAA 
GEFS defaults are altered in this PR.
Please verify and approve the changes.

**Review by NeilBarton-NOAA — APPROVED** [review]

**Review by bingfu-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
This looks to be a model failure on WCOSS2.  It appears to crash in the ice model which is odd since 1. this test passed on hera in my testing and 2. it does not seem related to the bug report in UFS model.   I'll see if I can recreate the problem and/or if the new ufs helps even though I don't think it should?

**Comment by JessicaMeixner-NOAA** [comment]
@JongilHan66 I have run with the updated ufs-wetaher-model with the recent bug fix on wcoss2 and I'm still getting a failure: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWDprtest/update02/t01/COMROOT/t01/logs/2021032312/gfsfcst.log 

Curious if you or others on the physics team might have insight to this.  The runs were okay on hera.

**Comment by JongilHan66** [comment]
> @JongilHan66 I have run with the updated ufs-wetaher-model with the recent bug fix on wcoss2 and I'm still getting a failure: /lfs/h2/emc/couple/noscrub/jessica.meixner/GWDprtest/update02/t01/COMROOT/t01/logs/2021032312/gfsfcst.log
> 
> Curious if you or others on the physics team might have insight to this. The runs were okay on hera.

@JessicaMeixner-NOAA  I will try to test it with your workflow on wcoss2 to find a possible cause.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @JongilHan66 !

**Comment by JongilHan66** [comment]
> Thanks @JongilHan66 !

@JessicaMeixner-NOAA With DELTIM=1200 for C48, it crashes at 96 hrs. When I reduce it to DELTIM=900, the run does not crash with FHMAX=120. We may need to reduce the time step for C48.

**Comment by JessicaMeixner-NOAA** [comment]
@JongilHan66 thank you for your investigative work!   Did we just get lucky on hera that this worked?

**Comment by JongilHan66** [comment]
> @JongilHan66 thank you for your investigative work! Did we just get lucky on hera that this worked?

@JessicaMeixner-NOAA A critical time step could be machine dependent.

**Comment by CatherineThomas-NOAA** [comment]
@JongilHan66:  I'm not used to the timestep being machine dependent, though I understand that the instabilities can be very sensitive.  The timesteps for all resolutions were previously provided in [this document](https://docs.google.com/document/d/1LOJ0Mip2ZXOHKQxIA_Pkv6GlTXUnOHQbFQl2Psuf2TQ/edit?usp=sharing).  Are they being set properly on WCOSS compared to Hera?  Do you think that these need to be reevaluated?  

Any additional insights @KevinViner-NOAA?

**Review by WalterKolczynski-NOAA — DISMISSED** [review]
Conditionally approved, pending whatever timestep adjustments need to be made.

**Comment by JongilHan66** [comment]
> @JongilHan66: I'm not used to the timestep being machine dependent, though I understand that the instabilities can be very sensitive. The timesteps for all resolutions were previously provided in [this document](https://docs.google.com/document/d/1LOJ0Mip2ZXOHKQxIA_Pkv6GlTXUnOHQbFQl2Psuf2TQ/edit?usp=sharing). Are they being set properly on WCOSS compared to Hera? Do you think that these need to be reevaluated?
> 
> Any additional insights @KevinViner-NOAA?

@CatherineThomas-NOAA I've always had occasional crashes in my previous HR1-HR3 tests on wcoss2 although they are usually numerically stable. So I think the current time step settings are still ok.

**Comment by JessicaMeixner-NOAA** [comment]
Some updates on some experiments: 

A longer 1200 hour run on hera runs without failure of the C48_S2SW case that is failing on wcoss2.  
A comparison of atm-only runs between hera/wcoss2 by @RuiyuSun showed similar results/warnings between the two platforms. 

I did notice this difference: https://github.com/NOAA-EMC/global-workflow/blob/develop/jobs/rocoto/fcst.sh#L9-L13 that we load modules differently but I don't think that's the issue, just wanted to note it here.

**Comment by JessicaMeixner-NOAA** [comment]
This PR has been updated to use the latest ufs-weather-model hash which has other HR4 updates.  It also changes tau for  the C48 test based on recommendations from the physics team (@yangfanglin has confirmed) and @RuiyuSun did tests (including on wcoss2) which confirm that things should be working.   

@aerorahul i believe this is now ready for re-review and CI testing

**Review by aerorahul — APPROVED** [review]

**Comment by RuiyuSun** [comment]
A test run with the latest model updates and the change in TAU (from 10 to 8.) for C48 was performed on CACTUS. The run successfully completed.

**Comment by RuiyuSun** [comment]
> A test run with the latest model updates and the change in TAU (from 10 to 8.) for C48 was performed on CACTUS. The run successfully completed.

The workflow dir: /lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270722
The experiment dir: /lfs/h2/emc/physics/noscrub/ruiyu.sun/para_gfs/s2swnew
The log file dir: /lfs/h2/emc/stmp/ruiyu.sun/ROTDIRS/s2swnew/logs/2021032312 
                     and  /lfs/h2/emc/physics/noscrub/ruiyu.sun/para_gfs/s2swnew/logfiles

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul please let us know if you'd like to see any other testing on our end.  Otherwise, I believe this is ready to be re-tested with CI.

**Comment by DavidHuber-NOAA** [comment]
The error encountered occurs on rare occasions and is a bug with the version of METplus used (i.e. nothing we can fix).  This is in lines 2812-2813 of `/apps/ops/para/libs/intel/19.1.3.304/metplus/3.1.1/metplus/util/met_util.py`:

```python
    if not os.path.exists(outdir):
        os.makedirs(outdir, mode=0o0775)
```
When running 4 instances at once (which the metp jobs do), it is possible to attempt to create a directory that has already been created.

However, during testing of #2749 on WCOSS2, I found another issue with a file check inside of `copy_stat_files.py`.  I propose that the WCOSS2 tests continue for both PRs, ignoring metp errors, while I work out the issues in another PR.  I will add the CI tests to my cron and report when they are complete.

**Comment by DavidHuber-NOAA** [comment]
All CI tests passed on WCOSS2 with the exception of the `metpg2g1` and `metpg2o1` jobs, as already discussed.

**Comment by DavidHuber-NOAA** [comment]
Does this PR need tests run on other platforms?  I can launch them manually.

**Comment by RuiyuSun** [comment]
> Does this PR need tests run on other platforms? I can launch them manu
Yes, please do so. Is it right, Cathy @CatherineThomas-NOAA?

**Comment by CatherineThomas-NOAA** [comment]
@DavidHuber-NOAA Can you run on Hera as well?

**Comment by DavidHuber-NOAA** [comment]
I think Hera's automated CI has come back online, so I will give it a try, then run manually if needed.

**Comment by DavidHuber-NOAA** [comment]
The metpg2o jobs will fail for all tests.  Once the tests progress to this point, I will take over and finish the tests manually.

**Comment by DavidHuber-NOAA** [comment]
All tests passed on Hera with the exception of the expected `metp` jobs.

**Comment by DavidHuber-NOAA** [comment]
Hera passed all tests, manually setting label.

**Pull request merged**
