### PR TITLE
updates to use CMEPS for coupled-crow

### PR DESCRIPTION
**Pull request by jiandewang**
* Updates to build and input files for using CMEPS 
* Changes mediator pet counts to only have fv3 computational cores (not the write groups) 
* updates to module files for ocean post (which now runs) 
* update to CICE5 input.nml in prep to be consistent with CICE6

### CODE REVIEW

**Comment by jiandewang** [comment]
@JianKuang-NOAA  and @JessicaMeixner-NOAA 
  Can you review this PR?
 
Thanks
Jiande

PS: Somehow I can't assign you two as reviewers by click the icon of reviewer, there is simply no icon for me to click, normally there is a round shaped icon to the right of "reviewers", don't understand why at this moment.

**Comment by jkuang-exploro** [comment]
OK. I will test it.

**Comment by jkuang-exploro** [comment]
@jiandewang It seems like this PR needs to first merge with feature/coupled-crow.

**Comment by jkuang-exploro** [comment]
@jiandewang @JessicaMeixner-NOAA @binli2337 Also, I suggest we make every PR directly into feature/coupled-crow instead of another PR. Our PR into the trunk are supposed to be independent from each other

**Comment by JessicaMeixner-NOAA** [comment]
@JianKuang-NOAA I think feature/coupled-crow has already been merged in and the branch is up to date.  At least that's what it tells me when trying to merge it in. 

The PRs to and from these branches/PRs are because we are working in our own forks together towards the same goal.  While this could probably be broken down into a few PRs, all the work is connected. I'll try to keep my work in smaller chunks in the future.

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA OK. Let me check again.

**Comment by jiandewang** [comment]
switch to request to merge be merged to feature/coupled-crow

**Comment by jkuang-exploro** [comment]
@jiandewang Apologize for the confusion. Now I found that all we need is to point the destination of this PR to feature/coupled-crow instead of bugfix/coupled-crow :)

**Comment by jiandewang** [comment]
@JianKuang-NOAA now we are on the same page. My branch is based on Jessica's original branch which is based on feature/coupled-crow, so there shall be no conflict.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by jiandewang** [comment]
@JianKuang-NOAA the merging needs to be done by you as what I see is:
**This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests.**

I guess this is why I couldn't assign reviewers in the formal way last night

**Pull request merged**
