### PR TITLE
update GFS drivers, Jobs and scripts

### PR DESCRIPTION
**Pull request by BoiVuong-NOAA**
1. Update drivers to use run.ver
2. Update Jobs to add an option -l in mpiexec
   -JGDAS_ATMOS_GEMPAK
   -JGFS_ATMOS_GEMPAK
3. Update script to add an option -l in mpiexec
  -exgfs_atmos_gempak_meta.sh

### CODE REVIEW

**Comment by BoiVuong-NOAA** [comment]
Hi Kate, 
I just create a PR #504 in the branch feature/ops-wcoss2

    1.Update drivers to use run.ver
    2.Update Jobs to add an option -l in mpiexec
    -JGDAS_ATMOS_GEMPAK
    -JGFS_ATMOS_GEMPAK
    3.Update script to add an option -l in mpiexec
    -exgfs_atmos_gempak_meta.sh

**Comment by KateFriedman-NOAA** [comment]
@BoiVuong-NOAA Please sync your fork branch now that I have submitted PR #490. Let us know when you're incorporated the updates and resolved any conflicts. I'll do the review when you're ready, thanks!

**Comment by BoiVuong-NOAA** [comment]
Hi Kate, 
How Do I sync my fork branch that I have submitted PR #490 ? Thanks, Boi

**Comment by KateFriedman-NOAA** [comment]
> Hi Kate, How Do I sync my fork branch that I have submitted PR #490 ? Thanks, Boi

@BoiVuong-NOAA See the answer I gave @GuangPingLou-NOAA in his PR, he's doing the same sync merge right now: https://github.com/NOAA-EMC/global-workflow/pull/502#issuecomment-970562180

**Comment by BoiVuong-NOAA** [comment]
Hi Kate,
I  sync my fork branch that I have submitted PR #490 by using method #2. It is done. Thanks,
Boi

**Comment by KateFriedman-NOAA** [comment]
> Hi Kate, I sync my fork branch that I have submitted PR #490 by using method #2. It is done. Thanks, Boi

Boi, your fork copy of feature/ops-wcoss2 is still behind the auth copy. If you look at your branch in your fork in GitHub it says this:

"This branch is 1 commit ahead, 14 commits behind NOAA-EMC:feature/ops-wcoss2."

The PR changes also don't show some of the updates I pushed to the auth branch in my PR yesterday. Did you push your merge up to your fork branch?

Also, see the bottom of this PR and note that it still says there are conflicts, that's another indication that your fork branch isn't synced. Let me know if you need help checking it's synced.

**Review by KateFriedman-NOAA — APPROVED** [review]
After sync merge this looks good, thanks @BoiVuong-NOAA !

**Pull request merged**
