### PR TITLE
Consolidate post scripts to eliminate coupled mode of link script

### LINKED ISSUE #679: Reconcile differences between coupled and standard post scripts
**Description**
The linker script currently takes in an additional argument to link "coupled". Differences in the fix files have already been removed, leaving just two post scripts that point to scripts in the post repo in standard mode but to g-w controlled scripts for coupled.

[exgfs_atmos_nceppost_cpl.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exgfs_nceppost_cpl.sh) is almost identical to its post counterpart, with only a small additional block.

[fv3gfs_downstream_nems_cpl.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/ush/fv3gfs_downstream_nems_cpl.sh) has a few more differences to be worked out, partially because it has fallen behind the version in post.

Non-coupled already runs to completion with the coupled version of the scripts, but the differences should be worked out before this is a permanent solution (like the change to land interpolation).

These could be updated in post, but there is a desire to move these scripts (and others) out of post anyway.

**Requirements**
Remove the temporary "coupled" argument for [link_workflow.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/sorc/link_workflow.sh).

**Acceptance Criteria (Definition of Done)**
Post scripts that produce the desired output for both modes without the need to link to different very similar scripts.

**Dependencies**
None

### LINKED ISSUE #746: Consolidate link script modes
**Description**
The ([link script](https://github.com/NOAA-EMC/global-workflow/blob/develop/sorc/link_workflow.sh)) currently has different uncoupled and coupled modes. Both modes link most of the same files, but there are two remaining files where different versions are linked depending on the mode:

- exgfs_atmos_nceppost.sh points to either exgfs_atmos_nceppost.sh in post or exgfs_nceppost_cpl.sh in global-workflow
- fv3gfs_downstream_nems.sh points to eitherfv3gfs_downstream_nems.sh in post or fv3gfs_downstream_nems_cpl.sh in global-workflow

As part of this consolidation, the scripts may be moved from post into global-workflow.

**Requirements**
Removal of the coupled option as a separate mode.

**Acceptance Criteria (Definition of Done)**
A link script without a coupled option that links updated files applicable for all global-workflow applications.

**Dependencies**
None if scripts are moved to global-workflow; otherwise an update to UPP to update the relevant scripts.

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
The two scripts that had modified versions for the coupled model have been joined with changes to the original scripts, eliminating the need for a special coupled mode for the link script. As part of this, those two scripts are no longer copied from UPP and are now part of the global-workflow repository.

Fixes: #679
Fixes: #746
Refs: #270

**Type of change**
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**
- [x] Forecast-only on Hera
- [x] Coupled on Hera
- [x] Forecast-only on Orion
- [x] Coupled on Orion
- [x] Forecast-only on Dell
- [x] Coupled on Dell
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
@WenMeng-NOAA @JessicaMeixner-NOAA
I've done my best to reconcile the differences between the two fv3gfs_downstream_nems scripts. The main differences seemed to be:
- Addition of bilinear interpolation and modification of sea ice cover that had been added to the UPP version since the cpl version diverged
- Elimination of some special code by machine in the cpl version (which I've taken a bit further, even)
- Deactivation of ½° files in cpl version (I've kept these pending a discussion on whether to eliminate, restore, or make these an option flag)
- Replacement of backticks with $( ) for subshells (a change I have previously made to all g-w scripts)

The exgfs_atmos_nceppost.sh versions really weren't different at all outside of the small block that executes an additional script when flux files are generated from coupled.

**Comment by WalterKolczynski-NOAA** [comment]
In draft mode pending testing on all tier-1 platforms

**Comment by WalterKolczynski-NOAA** [comment]
Here are the output locations, if someone wants to check the files:
Atm-only: `/scratch2/NCEPDEV/ensemble/noscrub/Walter.Kolczynski/global-workflow/link_atm`
Coupled: `/scratch2/NCEPDEV/ensemble/noscrub/Walter.Kolczynski/global-workflow/link_cpl`

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA requested the 1/2 degree files, which are needed for evaluation of the prototypes.  Can this removal either be delayed until after p8 or some sort of option be added?

**Comment by LydiaStefanova-NOAA** [comment]
A slight correction: the 1/2 degree evaluations may have been used for evaluations in the initial prototypes, but I am not using them now, and am not aware of anyone who does (but would be good to ask at the Wednesday tag up to make sure nobody is blindsided if they are removed). What I am using and would like to keep at least until P8 is over is the 1-deg flux files (flux.1p00)

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good and if I'm understanding them correctly we are absorbing UPP scripts into global-workflow (`scripts/exgfs_atmos_nceppost.sh` and `ush/fv3gfs_downstream_nems.sh`). One comment, not necessarily just for Walter, can `ush/fv3gfs_downstream_nems.sh` get renamed at some point? It feels outdated.

Thanks for this consolidation @WalterKolczynski-NOAA !

**Comment by WenMeng-NOAA** [comment]
> Addition of bilinear interpolation and modification of sea ice cover that had been added to the UPP version since the cpl version diverged

@WalterKolczynski-NOAA These special interpolation options  are for generating initial/boundary condictiones of some GFS downstream applications, such as HWRF.

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA It is okay for me to absorb some UPP scripts into the global-workflow as a workaround.  Would you submit an UPP PR for syncing your updates in corresponding UPP scripts in UPP repository?

**Comment by WenMeng-NOAA** [comment]
@aerorahul , @KateFriedman-NOAA @WalterKolczynski-NOAA Several months ago, we had a discussion for moving all GFS related post processing scripts from UPP repository into global-workflow. I wonder if it is time to start this transition?

**Comment by KateFriedman-NOAA** [comment]
>  Several months ago, we had a discussion for moving all GFS related post processing scripts from UPP repository into global-workflow. I wonder if it is time to start this transition?

I'm good with this but in a separate PR with an associated discussion. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
> @LydiaStefanova-NOAA requested the 1/2 degree files, which are needed for evaluation of the prototypes. Can this removal either be delayed until after p8 or some sort of option be added?

The coupled script is what removed them in the first place (the version in UPP still produces them). The lines are just commented out, so it is easy to turn them back on if desired. But it sounds like Lydia doesn't need them.

**Comment by WalterKolczynski-NOAA** [comment]
> Changes look good and if I'm understanding them correctly we are absorbing UPP scripts into global-workflow (`scripts/exgfs_atmos_nceppost.sh` and `ush/fv3gfs_downstream_nems.sh`). One comment, not necessarily just for Walter, can `ush/fv3gfs_downstream_nems.sh` get renamed at some point? It feels outdated.
> 
> Thanks for this consolidation @WalterKolczynski-NOAA !

This is correct, and once they are under our control, we should be able to rename them however we'd like.

**Comment by WalterKolczynski-NOAA** [comment]
> @aerorahul , @KateFriedman-NOAA @WalterKolczynski-NOAA Several months ago, we had a discussion for moving all GFS related post processing scripts from UPP repository into global-workflow. I wonder if it is time to start this transition?

I see this as the first step of that, yes. I was debating whether to just bring them all over as part of this PR. The two I moved were the only ones that had been modified for coupled, so it would just be a straight copy. But probably better to do that in a new PR where I also stop checking out and building UPP entirely and use the copy in UFS instead.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA It is okay for me to absorb some UPP scripts into the global-workflow as a workaround. Would you submit an UPP PR for syncing your updates in corresponding UPP scripts in UPP repository?

Given we are going to absorb all these scripts, do you still want a PR, or should I not bother assuming you will be deleting them once we have brought them all over?

**Comment by WenMeng-NOAA** [comment]
> > @aerorahul , @KateFriedman-NOAA @WalterKolczynski-NOAA Several months ago, we had a discussion for moving all GFS related post processing scripts from UPP repository into global-workflow. I wonder if it is time to start this transition?
> 
> I see this as the first step of that, yes. I was debating whether to just bring them all over as part of this PR. The two I moved were the only ones that had been modified for coupled, so it would just be a straight copy. But probably better to do that in a new PR where I also stop checking out and building UPP entirely and use the copy in UFS instead.

We might discuss how to transition gfs post processing scripts from UPP repository into global-workflow repository later.

**Comment by WenMeng-NOAA** [comment]
> > @WalterKolczynski-NOAA It is okay for me to absorb some UPP scripts into the global-workflow as a workaround. Would you submit an UPP PR for syncing your updates in corresponding UPP scripts in UPP repository?
> 
> Given we are going to absorb all these scripts, do you still want a PR, or should I not bother assuming you will be deleting them once we have brought them all over?

Before the gfs post processing scripts transition, I will keep on these scripts in UPP repository. Also they are used in the UPP RT test for gfs. Please submit a PR to the UPP repository. Thanks!

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA I did the line by line comparison the file  exgfs_atmos_nceppost.sh, fv3gfs_downstream_nems.sh between global-workflow and UPP. It seems to me a lot of key parts for generating operational GFS products are not adapted or commented out in the related scripts in your branch. The examples like:
```

 #         if [ $SENDDBN = YES ]; then
 #            $DBNROOT/bin/dbn_alert MODEL GFS_WAFS_GB2 $job $COMOUT/${PREFIX}wafs.0p25.anl
 #            $DBNROOT/bin/dbn_alert MODEL GFS_WAFS_GB2__WIDX $job $COMOUT/${PREFIX}wafs.0p25.anl.idx
 #         fi

```
Missing in fv3gfs_downstream_nems.sh for MPMD:
```
 if [ $machine = WCOSS -o $machine = WCOSS_C -o $machine = WCOSS_DELL_P3 -o $machine = HERA -o $machine = ORION -o $machine = JET -o $machine = S4 -o $machine = WCOSS2 ]; then
```

**Comment by WenMeng-NOAA** [comment]
I wonder if the changes in post processing scripts for coupled GFS only can be made in UPP repository first and you transition all gfs post processing scripts in the global-workflow later.

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA 
https://github.com/WalterKolczynski-NOAA/global-workflow/blob/4a9c26735ff8a0c1cd10e5a8810d7a38c468e991/ush/fv3gfs_downstream_nems.sh#L101
The if statement is needed for generating pgrb2 and pgrb2b datasets on platforms with MPMD, and pgrb2 only on platforms
without MPMD.

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA You commented out all pgrb2 and pgrb2b in 0.5 degree dataset generation. These are the official GFS products. Any official product removal needs the approval from Jason and SCN.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA You commented out all pgrb2 and pgrb2b in 0.5 degree dataset generation. These are the official GFS products. Any official product removal needs the approval from Jason and SCN.

I already mentioned this above.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA https://github.com/WalterKolczynski-NOAA/global-workflow/blob/4a9c26735ff8a0c1cd10e5a8810d7a38c468e991/ush/fv3gfs_downstream_nems.sh#L101 The if statement is needed for generating pgrb2 and pgrb2b datasets on platforms with MPMD, and pgrb2 only on platforms without MPMD.

As near as I can tell, all tier-1 and tier-2 supported machines for g-w are on that list. Maybe Cheyenne? But I find it hard to believe Cheyenne doesn't also support MPMD. It's a lot of extra code to carry around if it is never used.

**Review by KateFriedman-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I did the line by line comparison the file exgfs_atmos_nceppost.sh, fv3gfs_downstream_nems.sh between global-workflow and UPP. It seems to me a lot of key parts for generating operational GFS products are not adapted or commented out in the related scripts in your branch. The examples like:
> 
> ```
> 
>  #         if [ $SENDDBN = YES ]; then
>  #            $DBNROOT/bin/dbn_alert MODEL GFS_WAFS_GB2 $job $COMOUT/${PREFIX}wafs.0p25.anl
>  #            $DBNROOT/bin/dbn_alert MODEL GFS_WAFS_GB2__WIDX $job $COMOUT/${PREFIX}wafs.0p25.anl.idx
>  #         fi
> ```
> 

This was not a change I made. These lines are commented out in [UPP develop](https://github.com/NOAA-EMC/UPP/blob/develop/scripts/exgfs_atmos_nceppost.sh#L229).

**Comment by WalterKolczynski-NOAA** [comment]
Going to move forward with these post PRs in global workflow as a sort of transition period. I'll replicate any changes made to these scripts in UPP until the 'official' transition is made.

**Review by KateFriedman-NOAA — APPROVED** [review]

**Comment by WenMeng-NOAA** [comment]
@WalterKolczynski-NOAA With this PR committed, I would expect the global-workflow managers will start to take care of the user support of GFS V17 post processing. Tagging-up @HuiyaChuang-NOAA.

**Review by WenMeng-NOAA — APPROVED** [review]

**Pull request merged**
