### PR TITLE
Add 3 and 9 hr increment files to IC staging

### LINKED ISSUE #2874: The new IC staging task appears to neglect atmi003 and atmi009 files
### What is wrong?

When running an experiment with `DOIAU=YES`, task `gdasfcst_seg0` fails on the half-cycle with the complaint

`FATAL ERROR: missing increment file '/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/doublectest/global-workflow/sorc/gdas.cd/build/gdas/test/gw-ci/../../test/gw-ci/WCDA-3DVAR-C48mx500ens/COMROOT/WCDA-3DVAR-C48mx500ens/gdas.20210324/12//analysis/atmos/gdas.t12z.atmi003.nc', ABORT!`

Examination of the directory shows that there is no file `gdas.t12z.atmi009.nc `either, and the `003` and `009` increment files are missing from the respective ensemble member directories as well, resulting in the failure of the `enkfgdasfcst_mem00?` tasks as well

### What should have happened?

The full increment files should be included with the ICs where appropriate

### What machines are impacted?

Hera

### Steps to reproduce

The experiment can be set up with the yaml `/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/doublectest/global-workflow/ci/cases/pr/C48mx500_3DVarAOWCDAens.yaml ` 

### Additional information

The `COMROOT` and `EXPDIR` are under /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/doublectest/global-workflow/sorc/gdas.cd/build/gdas/test/gw-ci/WCDA-3DVAR-C48mx500ens

### Do you have a proposed solution?

I presume the yamls under `global-workflow/parm/stage/` need to be modified

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
# Description

Adds files `atmi009.nc`, `atmi003.nc`,  `ratmi009.nc`,  and `ratmi003.nc` to list of files to be staged for ICs, if available. These are necessary for starting an IAU run, and are currently missing.

Resolves https://github.com/NOAA-EMC/global-workflow/issues/2874

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

GDASApp WCDA ctests and cycled experiment on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good, thanks for adding those files @AndrewEichmann-NOAA !

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Review by guillaumevernieres — APPROVED** [review]
thanks @AndrewEichmann-NOAA

**Comment by WalterKolczynski-NOAA** [comment]
Is this going to cause issues for 3D-var when these may not be available?

**Comment by KateFriedman-NOAA** [comment]
> Is this going to cause issues for 3D-var when these may not be available?

Every file in the analysis yaml only gets added to the filehandler list if it exists. See the `path_exists` check in the yaml. I added that since there are varied combinations of which of these files are needed. The only issue may be if the user needs/expects one of those files but since it doesn't exist it's not picked up and an error isn't thrown.

**Comment by WalterKolczynski-NOAA** [comment]
> > Is this going to cause issues for 3D-var when these may not be available?
> 
> Every file in the analysis yaml only gets added to the filehandler list if it exists. See the `path_exists` check in the yaml. I added that since there are varied combinations of which of these files are needed. The only issue may be if the user needs/expects one of those files but since it doesn't exist it's not picked up and an error isn't thrown.

Okay, Good for the PR, not so good overall.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
