### PR TITLE
revert changes that introducing gfs v16 physics

### PR DESCRIPTION
**Pull request by jkuang-exploro**
Fix the wrong update happened on an earlier commit. Revert changes for gfs v16 physics in workflow/config/fcst.yaml
IAU settings in workflow/config/base.yaml are also removed.

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]
@JianKuang-NOAA  This helped reduce the differences significantly.  Thank you!

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA So is there still inconsistency against your benchmark?

**Comment by JessicaMeixner-NOAA** [comment]
Yes there are still inconsistencies, but significantly fewer. Differences in input.nml include: 

```
18,19c18,19
<   fhmaxhf = 0
<   fhouthf = -1
---
>   fhmaxhf = 0     ! CROW configured
>   fhouthf = 1     ! CROW configured
93,96c93,96
<   hord_mt = 5
<   hord_vt = 5
<   hord_tm = 5
<   hord_dp = -5
---
>   hord_mt = 6
>   hord_vt = 6
>   hord_tm = 6
>   hord_dp = -6
```

With the first two being something that can be changed in the workflow/cases/coupled_free_forecast.yaml 

I'm hoping the same for the hord_* values although this does seem to be a change introduced by this commit that was not there before this commit, so maybe the lines in workflow/defaults/fv3_gdas.yaml should not have been deleted and not changed in  workflow/schema/fv3.yaml.

Differences in model_configure include the addition of: 
```
 > output_history:          .true.
> write_dopost:            .false.
```
which I do not think hurt anything.  

There were also some changes in this commit with the field_table but I didn't save off that file for checking so, I'm not sure if these changes are wanted or not, but this gets us much closer and I can make updates for the rest if you push these changes now.

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA OK. I will fix these.

**Comment by jkuang-exploro** [comment]
@JessicaMeixner-NOAA Would you please let me know which set of value is the "right" one (control)?
And what's the path of your log file?

**Comment by JessicaMeixner-NOAA** [comment]
input.nml is now the same as benchmark 3.1! 

Thank you @JianKuang-NOAA

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Pull request merged**
