### PR TITLE
Migrate `jobs/`, `scripts/` and `ush/` from GSI to global-workflow

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**
This PR moves the `jobs/`, `scripts/` and `ush/` from NOAA-EMC/GSI into the global-workflow.
History is preserved.

Corresponding GSI PR https://github.com/NOAA-EMC/GSI/pull/436

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

- [ ] Clone and Build tests on WCOSS Dell P3
- [ ] Cycled test on Orion
- [ ] Forecast-only test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks good. Confirmed all the scripts that were formerly linked have been added to the repo.

**Comment by RussTreadon-NOAA** [comment]
Please add @AndrewEichmann-NOAA as a reviewer since these changes include EFSOI.

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks ok

**Comment by AndrewEichmann-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA I take it this means that cycling is working on Orion?

**Comment by aerorahul** [comment]
> @aerorahul @WalterKolczynski-NOAA I take it this means that cycling is working on Orion?

Yes @AndrewEichmann-NOAA 
The cycling capability has been restored (with caveats noted in https://github.com/NOAA-EMC/global-workflow/pull/895).
Thank you for your review.

**Pull request merged**
