### PR TITLE
Update script names to match ecflow convention

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
General updates to rename both JJOB and ex-scripts to meet NCO ecflow naming convention.

- new tags: GLDAS, EMC_post, EMC_verif-global, EMC_gfs_wafs
- JJOB scripts renamed
- ex-scripts renamed
- config.base.nco.static updated with config.base.emc.dyn changes

Test reproduced v16rt2 with v16rt2 setup/inputs and feature/gfsv16b_jobname branch.

### CODE REVIEW

**Review by RussTreadon-NOAA — APPROVED** [review]
Due to size of this PR and other pressing v16 tasks, I am unable to look at each of the 124 changed files.   The changes in this PR were tested in a global parallel run on Venus.  The parallel reproduced the v16rt2 control.  Based on this confirmation, approve changes for merger into feature/gfsv16b.

**Comment by yangfanglin** [comment]
I will approve without actually checking the scripts.  Since cycling works then  everything should be fine. Thanks everyone for making this update.

**Review by BoiVuong-NOAA — APPROVED** [review]

**Review by yangfanglin — APPROVED** [review]
approved

**Comment by KateFriedman-NOAA** [comment]
Thanks all! PR Submitted.

**Pull request merged**
