### PR TITLE
Update dev/gdasapp with develop

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
This PR updates `dev/gdasapp` with `develop`

# Type of change
- Maintenance - keep `dev/gdasapp` in sync with `develop`

# Change characteristics
- Is this a breaking change (a change in existing functionality)? **NO**
- Does this change require a documentation update? **NO**

# How has this been tested?
- Clone and build on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Assign @CoryMartin-NOAA and @guillaumevernieres as reviewers to see if their reviews & approvals are sufficient for one of us to merge this PR into `dev/gdasapp`.

**Review by guillaumevernieres — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres .  Your approval unlocked the merge button!  Let me go ahead and update `dev/gdasapp`.

**Comment by RussTreadon-NOAA** [comment]
Question for @aerorahul , @WalterKolczynski-NOAA , @CoryMartin-NOAA , and @guillaumevernieres .   

We have two merge options for this PR, #2714:
1. squash and merge
2. rebase and merge

Which one should I select?

I'm thinking ahead to when `dev/gdasapp` contains GDASApp changes to merge into `develop`.  Which of the above merge options for this PR, #2714, will cause the least trouble when we get to this future scenario?

**Comment by guillaumevernieres** [comment]
Rebase and merge @RussTreadon-NOAA we don't want to squash the commits coming from develop. But happy to hear from others.

**Comment by RussTreadon-NOAA** [comment]
The rebase & merge is complete but I don't what I see for [`dev/gdasapp`](https://github.com/NOAA-EMC/global-workflow/tree/dev/gdasapp).   github says the branch is 19 commits ahead and behind of `develop`.

**Comment by guillaumevernieres** [comment]
> The rebase & merge is complete but I don't what I see for [`dev/gdasapp`](https://github.com/NOAA-EMC/global-workflow/tree/dev/gdasapp). github says the branch is 19 commits ahead and behind of `develop`.

The log history is the same but the commit # don't match, oops ... Let me try to do a reset to develop and submit that as a pr.

**Pull request merged**
