### PR TITLE
feature/coupled-crow updating to use latest ups-weather

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
This PR has updates to use ufs-weather-model from 12/7/2020  commit 0cf031edc217707f3b5c912e0844e2c2b885ff82 

This will close issue #172 

Updates include: 
- MOM_input updates to correspond with https://github.com/ufs-community/ufs-weather-model/pull/290 (FYI @jiandewang ) 
- ice_in updates to correspond with https://github.com/ufs-community/ufs-weather-model/pull/270 (FYI @DeniseWorthen ) 
- input.nml updates for iovrsw and iovrlw being replaced by a single iovr  
- updates for nems.configure to match ufs-weather-model/tests/parm directory 
- adds variables  cplmode (nems_orig or nems_frac) and FRAC_GRID (true/.false.) in prep for fractional grid

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Output from a test can be found on orion at: /work/noaa/marine/jmeixner/p6consitency/test01 and for hera at: /scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/test_nonfrac/COMROOT/test02

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA can you give me the code and script dir on HERA ?

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang the local copy of the workflow is here: /scratch2/NCEPDEV/climate/Jessica.Meixner/p6workflow/fracgrid but I have made local changes building on this to test the fractional grid (just in the workflow/cases directory) so FYI it's not a perfect match anymore.  Sorry about that.  It's not been changed on orion which is here: /work/noaa/marine/jmeixner/p6consitency/global-workflow

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA file changes look fine, let me check the results. Your run is frac_grid=F, right ?

**Comment by JessicaMeixner-NOAA** [comment]
@jiandewang correct, there are now flags for fractional grid now but they are all set to false for now

**Comment by DeniseWorthen** [comment]
Is there a reason both nems.configure files are retained? nems.configure.med_atm_ocn_ice.IN should be identical to  nems.configure.cpld.IN  (same for nems.configure.cpld_wave.IN)

**Comment by JessicaMeixner-NOAA** [comment]
No. I'll delete the extra. Thanks for catching that!  

> Is there a reason both nems.configure files are retained? nems.configure.med_atm_ocn_ice.IN should be identical to nems.configure.cpld.IN (same for nems.configure.cpld_wave.IN)

**Comment by jiandewang** [comment]
@JessicaMeixner-NOAA I checked your run results, they look good. Since you have run them already I am not going to repeat that, is this fine ?

**Comment by JessicaMeixner-NOAA** [comment]
It worked on multiple platforms for me so I think that sufficiently tested some sort of user environment issue hopefully. So it's okay with me.  Thanks for checking everything @jiandewang

**Review by jiandewang — APPROVED** [review]

**Review by jkuang-exploro — APPROVED** [review]

**Pull request merged**
