### PR TITLE
Develop Bash CI self test [do not merge]

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
CI Bash Self test on Orion

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
```
24:        Type 8 : Restart files second request
24:       -----------------------------------------
24:             From     : 2021/03/23 12:00:00 UTC
24:             To       : 2021/03/28 12:00:00 UTC
24:             Interval :            12:00:00
24:
24:        Wave model ...
 0:  zeroing coupling accumulated fields at kdt=            1
 0:  zeroing coupling accumulated fields at kdt=            1
25: [Orion-04-53:72055:0:72055] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
27: [Orion-04-53:72057:0:72057] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
28: [Orion-04-53:72058:0:72058] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
29: [Orion-04-53:72059:0:72059] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
31: [Orion-04-53:72061:0:72061] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
33: [Orion-04-53:72063:0:72063] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
35: [Orion-04-53:72065:0:72065] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
30: [Orion-04-53:72060:0:72060] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
34: [Orion-04-53:72064:0:72064] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
24: [Orion-04-53:72054:0:72054] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
26: [Orion-04-53:72056:0:72056] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
32: [Orion-04-53:72062:0:72062] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x4)
29: ==== backtrace (tid:  72059) ====
29:  0 0x0000000001dfe97e pdlib_field_vec_mp_unst_pdlib_read_from_file_()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/WW3/model/src/pdlib_field_vec.F90:501
29:  1 0x0000000001c887ad w3iorsmd_mp_w3iors_()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/WW3/model/src/w3iorsmd.F90:801
29:  2 0x0000000001bd147b w3initmd_mp_w3init_()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/WW3/model/src/w3initmd.F90:961
29:  3 0x0000000001aef5c1 waveinit_ufs()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/WW3/model/src/wav_comp_nuopc.F90:1659
29:  4 0x0000000001aef5c1 initializerealize()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/WW3/model/src/wav_comp_nuopc.F90:696
29:  5 0x0000000000a77134 ESMCI::FTable::callVFuncPtr()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:2167
29:  6 0x0000000000a7b1ff ESMCI_FTableCallEntryPointVMHop()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:824
29:  7 0x0000000000bd9337 ESMCI::VMK::enter()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Infrastructure/VM/src/ESMCI_VMKernel.C:1125
29:  8 0x00000000008e9232 ESMCI::VM::enter()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Infrastructure/VM/src/ESMCI_VM.C:1216
29:  9 0x0000000000a7857a c_esmc_ftablecallentrypointvm_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:981
29: 10 0x000000000097aaa0 esmf_compmod_mp_esmf_compexecute_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMF_Comp.F90:1223
29: 11 0x0000000000d56301 esmf_gridcompmod_mp_esmf_gridcompinitialize_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMF_GridComp.F90:1412
29: 12 0x000000000091d5a0 nuopc_driver_mp_loopmodelcompss_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/addon/NUOPC/src/NUOPC_Driver.F90:2886
29: 13 0x000000000093a36f nuopc_driver_mp_initializeipdv02p3_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/addon/NUOPC/src/NUOPC_Driver.F90:1979
29: 14 0x000000000094f7f0 nuopc_driver_mp_initializegeneric_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/addon/NUOPC/src/NUOPC_Driver.F90:484
29: 15 0x0000000000a77134 ESMCI::FTable::callVFuncPtr()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:2167
29: 16 0x0000000000a7b1ff ESMCI_FTableCallEntryPointVMHop()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:824
29: 17 0x0000000000bd912a ESMCI::VMK::enter()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Infrastructure/VM/src/ESMCI_VMKernel.C:2321
29: 18 0x00000000008e9232 ESMCI::VM::enter()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Infrastructure/VM/src/ESMCI_VM.C:1216
29: 19 0x0000000000a7857a c_esmc_ftablecallentrypointvm_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMCI_FTable.C:981
29: 20 0x000000000097aaa0 esmf_compmod_mp_esmf_compexecute_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMF_Comp.F90:1223
29: 21 0x0000000000d56301 esmf_gridcompmod_mp_esmf_gridcompinitialize_()  /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/cache/build_stage/spack-stage-esmf-8.5.0-7t7fsxpkw36g4ht6c6qbu4bvviztvaim/spack-src/src/Superstructure/Component/src/ESMF_GridComp.F90:1412
29: 22 0x0000000000437502 MAIN__()  /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2365/global-workflow/sorc/ufs_model.fd/driver/UFS.F90:381
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
Since CI BASH is not "gefs" ready in that all cases are built agains `build_all.sh -guw` so wasn't this out come expected?

**Comment by WalterKolczynski-NOAA** [comment]
The GEFS test needs to be off if you aren't doing a dual build.

**Comment by WalterKolczynski-NOAA** [comment]
Simultaneous comments. We both got to the same place.

**Comment by TerrenceMcGuinness-NOAA** [comment]
So let's simply add skip host for now for the gefs test and proceed.

**Comment by WalterKolczynski-NOAA** [comment]
Do it just for this fake PR so we can confirm existing tests still work, because after that I'd like to rapidly move to Jenkins.

**Pull request closed without merging**
