### PR TITLE
nwtest module library and tag updates

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
Changes to move components to updated nwtest module libraries:

- update FV3 tag
- update GSI from release branch to tag
- update GLDAS tag
- update UPP tag
- update link_fv3gfs.sh for adjusted UFS_UTILS tag execs
- remove unneeded modulefile loads from downstream wave jobs
- update workflow modulefiles to nwtest module libraries
- bufr sounding updates from issue #145 and #147
- pull in updates from real-time parallel test configs

@lgannoaa FYI for incoming changes to feature/gfsv16b. These changes will be promoted to the real-time v16rt2 parallel today.

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Changes were tested in v16rt2b.  Jobs ran to completion.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA To update v16rt2 please do the following:

**1. update $HOMEgfs**

Either git pull and full recheckout/rebuild of current $HOMEgfs or fresh clone/build or swap with v16rt2b $HOMEgfs:

/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/global-workflow/feature-gfsv16b_updates

Either way $HOMEgfs should get a full refresh. A full reclone/rebuild is safest.

**2. update v16rt2 $EXPDIR**

Can use /gpfs/dell2/emc/modeling/noscrub/emc.glopara/para_fv3gfs/v16rt2b configs for comparison with v16rt2 as needed.

- Update obsproc pointers in config.base:

```
export HOMEobsproc_network="$BASE_GIT/obsproc/gfsv16b/obsproc_global_RB-3.4.0"
```
Note, my test used this copy for HOMEobsproc_prep:
```
export HOMEobsproc_prep="$BASE_GIT/obsproc/gfsv16b/obsproc_prep.iss70457.netcdfhistory.HEAD"
```

We can now update the obsproc_prep.iss70457.netcdfhistory copy to match that HEAD version. Once updated you can keep using the copy set in v16rt2's config.base.

- Update config.fcst to pull in nsponge and d2_bg_k1/d2_bg_k2 settings:

```
cd $EXPDIR
cp $HOMEgfs/parm/config/config.fcst config.fcst
```

All other configs in v16rt2 can remain as is.

**3. Update v16rt2 xml to pull in prep job resource updates:**

```
cd $HOMEgfs/ush/rocoto
./setup_workflow.py --expdir /gpfs/dell2/emc/modeling/noscrub/emc.glopara/para_fv3gfs/v16rt2/
```

...or manually update xml:
```
<!ENTITY RESOURCES_PREP_GDAS "<nodes>2:ppn=2</nodes>">
<!ENTITY RESOURCES_PREP_GFS "<nodes>2:ppn=2</nodes>">
```

May use /gpfs/dell2/emc/modeling/noscrub/emc.glopara/para_fv3gfs/v16rt2b/v16rt2b.xml for reference.

------

That should be it, let me know if you have any questions or issues. Also let me know if I can assist with any of the above. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa FYI, feature/gfsv16b has been updated.

**Comment by RussTreadon-NOAA** [comment]
We should use ObsProc RB for both obsproc_global and obsproc_prep.   Let's
ask Shelley if she has an obsproc_prep RB.

**Pull request merged**
