### PR TITLE
Add coupled files to archive and streamline

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
The following tar files for ocean and ice output are added to the
archive job to be stored on HPSS:
- ocn_2D
- ocn_3D
- ocn_xsect
- ocn_daily
- ocn_ice_grib2_0p25
- ocn_ice_grib2_0p5
- wavocn
- ice
- gfs_flux_1p00

Handling of the archival of gaussian grid NetCDF files is changed. The former, unused, and now misnamed setting of SAVEFCSTNEMSIO has been changed to ARCH_GAUSSIAN and is now also used consistently between arch.sh and hpssarch_gen.sh. The setting was previously broken,  so the default has been changed to "NO" to avoid an unexpected increase in tape usage (but coupled overrides this to "YES").  gfs_pgrb2b remains controlled by this setting as well, though it is not a gaussian grid. The half-degree pgrb2b files inside the gfs_pgrb2b tarball have been replaced with one-degree pgrb2b files (the quarter-degree files remain). Additionally, there are new settings, ARCH_GAUSSIAN_FHMAX and ARCH_GAUSSIAN_FHINC, to control which atm and sfc files are saved. The default values are 36 and 6, maintaining the previous hardcoded values.

The archive job is also streamlined by replacing a bunch of repeating code. Instead of creating tar files in small loops, a list of all the tarfiles to archive is created, then a single loop executes the archival and error checking. Only the MOS tarfile remains separate (for now).

The forecast input.nml has been added to the gfsa tarball. The WW3 grid definitions (ww3_multi*) have been added to the gfswave tarball.

For those used to the coupled-crow archiving, there are some changes to be consistent and remove some redundancy:
- Stuff formerly in log
  - atmos/${head}logf*.txt - removed (only contains one line saying the forecast hour completed)
  - gfs*.log - already in gfsa
  - input.nml - added to gfsa
  - ww3_multi* - added to gfswave
  - ice_in - added to ice
  - MOM_input - added to ocn_2d (I had to pick one of the ocean tars, this seemed the best one)
- gfs_pgrb2b_0p25 and gfs_pgrb2b_1p00 are now in gfs_pgrb2b
- gfs_atm_netcdfb and gfs_sfc_netcdfb are now in gfs_netcdfb

Refs: #416

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Draft until I or someone else tests it

**Comment by WalterKolczynski-NOAA** [comment]
Here's a first-pass tar inventory for a 48-hr coupled test: https://gist.github.com/WalterKolczynski-NOAA/38854172592c515bb04d650d8cd0ecc2

A couple issue I've already spotted:
- input.nml isn't added to gfsa.tar because it is never copied to COM
- gfs_netcdfb.tar only goes to 36 hours because I forgot to update the variable name for the overrides in config.defaults.s2sw as I iterated

Also, I looked back at my recent cycled tests: the SAVEFCSTNEMSIO section doesn't currently work at all because backticks were used instead of quotes. So this will fix that as well.

**Comment by WalterKolczynski-NOAA** [comment]
A couple more I found and fixed:
- None of the ocean tars were created because I used the wrong ocean control variable
- I was looking for ww3_multi in the wrong place (had an extra level of wave/)

Will do a redo after I fix the last one (copying input.nml).

**Comment by WalterKolczynski-NOAA** [comment]
Copying input.nml wasn't the problem, it was in COM but I did the same thing as with ww3_multi and added a second atmos/ level in the path.

**Comment by WalterKolczynski-NOAA** [comment]
Completed a second pass. gist above has been updated with the new inventories.

**Comment by JessicaMeixner-NOAA** [comment]
Which tar file should I expect the ocean files to be in?  

I ran a test over the weekend after merging this branch to my PR#500 test branch, and only have: 
/NCEPDEV/emc-climate/1year/Jessica.Meixner/HERA/scratch/octtest02/2013100100:
gfs_flux.tar           gfs_pgrb2b.tar         gfs_restarta.tar.idx   gfsb.tar               gfswave.tar.idx        
gfs_flux.tar.idx       gfs_pgrb2b.tar.idx     gfsa.tar               gfsb.tar.idx           ice.tar                
gfs_netcdfb.tar        gfs_restarta.tar       gfsa.tar.idx           gfswave.tar            ice.tar.idx            
gfs_netcdfb.tar.idx

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA I had an error in my log file /scratch2/NCEPDEV/climate/Jessica.Meixner/workflowPR500/octtest02/COMROOT/octtest02/logs/2013100100/gfsarch.log : 
```
+ htar -T 4 -P -cvf /NCEPDEV/emc-climate/1year/Jessica.Meixner/HERA/scratch/octtest02/2013100100/ocn_2D.tar ./gfs.20131001/00/ocn/MOM_input './gfs.20131001/00/ocn/ocn_2D*'
[connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gfs.20131001/00/ocn/MOM_input"
*** Warning: No matching names located for './gfs.20131001/00/ocn/MOM_input'
ERROR: matchdir:  opendir error 2 opening directory ./gfs.20131001/00/ocn/
*** Warning: No matching names located for './gfs.20131001/00/ocn/ocn_2D*'
INFO: refusing to create empty archive
HTAR: HTAR SUCCESSFUL
```

I did check that the xml seems to have the correct dependency.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I had an error in my log file /scratch2/NCEPDEV/climate/Jessica.Meixner/workflowPR500/octtest02/COMROOT/octtest02/logs/2013100100/gfsarch.log :
> 
> ```
> + htar -T 4 -P -cvf /NCEPDEV/emc-climate/1year/Jessica.Meixner/HERA/scratch/octtest02/2013100100/ocn_2D.tar ./gfs.20131001/00/ocn/MOM_input './gfs.20131001/00/ocn/ocn_2D*'
> [connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
> ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gfs.20131001/00/ocn/MOM_input"
> *** Warning: No matching names located for './gfs.20131001/00/ocn/MOM_input'
> ERROR: matchdir:  opendir error 2 opening directory ./gfs.20131001/00/ocn/
> *** Warning: No matching names located for './gfs.20131001/00/ocn/ocn_2D*'
> INFO: refusing to create empty archive
> HTAR: HTAR SUCCESSFUL
> ```
> 
> I did check that the xml seems to have the correct dependency.

Sorry, I had one change that never got pushed fixing the ocean path. Please try again.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @WalterKolczynski-NOAA I will try again as soon as HPSS & a machine w/HPSS is available.

**Comment by JessicaMeixner-NOAA** [comment]
I just compared the feature/coupled-crow archived output with that in this branch and I'm missing: 
gfs.t00z.pgrb2b.1p00.f* files and gfs.t00z.flux.1p00.f* files in this branch.  

See: 
un-tarred crow output is here: /scratch2/NCEPDEV/climate/Jessica.Meixner/workflowPR500/HPSS/crow and from this branch is here: /scratch2/NCEPDEV/climate/Jessica.Meixner/workflowPR500/HPSS/develop

**Review by JessicaMeixner-NOAA — APPROVED** [review]
All files previously archived in feature/coupled-crow are now archived here.  THANK YOU @WalterKolczynski-NOAA

**Pull request merged**
