### PR TITLE
Remove RUNDIRS before running CI cases to cover re-run events

### LINKED ISSUE #2954: Remove on disk archive files in CI pipeline after running a test
### What new functionality do you need?

As a CI user I need to have the on disk archive files removed after a CI test case passes.

### What are the requirements for the new functionality?

Need to remove the directory $HOMEDIR/archive/$PSLOT after each CI case completes successfully

### Acceptance Criteria

 We see the folder is gone after the tests runs

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
# Description

This Pr removes **pslot** dir (with hash) from local archive folder on CI case completion and also adds `cleanup_experiment` function in the BASH utilities to clean up after a CI case runs. This change consolidates cleanup actions and adds functionality to clean the local archive folders.

Key changes:

- Fixes bug for cleaning up the `RUNDIRS` directory before new experiments are run in the case the pipeline is being ran for a second time
- Updated `$HOMEgfs/ci/scripts/check_ci.sh` to use the new `cleanup_experiment` function under the BASH CI system.
- Added `cleanup_experiment `function in `$HOMEgfs/ci/scripts/utils/ci_utils.sh` to handle various cleanups including: 
  - COMROOT/EXPDIR per case
  - ARCDIR and ATADIR directories for archive
  - STMP/RUNDIRS/${PSLOT}
- Added get config var from EXPDIR utility  [get_config_var.py](https://github.com/NOAA-EMC/global-workflow/pull/2961/files#diff-b780733ae1d45917730364e09a6c510e79d4cc8cffad6d9020c7961c53b987bc) for getting config values in BASH

Resolves #2954, #3066 

# Type of change
- [ ] Bug fix (fixes something broken)
- [x] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?
This PR still needs to be tested with the CI system which would effectively be a self-test.
image# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Checkout failed for **gfs** but not for **gefs** on a basic git command on Hera.  Simply restarting CI in attempts to repeat the error.
Error was not repeatable for the gfs checkout and proceeded normally.  **scm** also did the checkout in normal `git `fashion with updates only on previously **gefs** side as well.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@DavidHuber-NOAA Is it possible that the post jobs are still running after the experiment is deemed completed by Rocoto?
```
*************************************************** 
 FATAL ERROR : NO MOD_DEF FILE mod_def.uglo_100km 
*************************************************** 
 
+ exgfs_wave_post_pnt.sh[145]: err=2
+ exgfs_wave_post_pnt.sh[145]: export err
+ exgfs_wave_post_pnt.sh[145]: err_chk

-------------------------------------------------------------
-- FATAL ERROR: Job wavepostpnt.2182353 failed RETURN CODE 2
-- ABNORMAL EXIT at Fri Nov  8 15:11:13 CST 2024 on hercules-01-14
-------------------------------------------------------------
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
Hercules disk full?  It just ran this morning.
```
FAIL tasks failed and 1 dead at Fri Nov  8 18:57:38 CST 2024
Experiment C96C48_hybatmDA_d9d63af5 Terminated: *FAIL*
tee: 'standard output': Disk quota exceeded
tee: write error: Input/output error
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
Massive failure of **scm** checkout of global-workflow on Orion.
Looking into a lead with this part of the error log.
```
fatal: write error: Disk quota exceeded
fatal: fetch-pack: invalid index-pack output
```

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
PR description needs to be updated before merging.

**Pull request merged**
