### PR TITLE
Add preipicating hydrometeors for zeroing out increments and tapering increments in the stratosphere

### LINKED ISSUE #869: Control the use of increments from precipitating hydrometeors
Add control to the use of increments for precipitating hydrometeors
 The following two variables in the config.base will be changes from:

```
# Analysis increments to zero in CALCINCEXEC
export INCREMENTS_TO_ZERO="'liq_wat_inc','icmr_inc'"

# Stratospheric increments to zero
export INCVARS_ZERO_STRAT="'sphum_inc','liq_wat_inc','icmr_inc'"

```

to

```
# Analysis increments to zero in CALCINCEXEC
export INCREMENTS_TO_ZERO="'liq_wat_inc','icmr_inc','rwmr_inc','snmr_inc','grle_inc'"

# Stratospheric increments to zero
export INCVARS_ZERO_STRAT="'sphum_inc','liq_wat_inc','icmr_inc','rwmr_inc','snmr_inc','grle_inc'"

```

### PR DESCRIPTION
**Pull request by emilyhcliu**
**Description**

This PR contains changes for /parm/config.base.nco.static and config.base.emc.dyn:
Added precipitating hydrometeors in the list to zero out the increments for IAU
Added precipitating hydrometeors in the list to taper out increments in the startosphere.

Fixes #869

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
FYI @lgannoaa

**Review by aerorahul — APPROVED** [review]
My approval does not carry any weight in terms of science, but still I approve.

**Comment by RussTreadon-NOAA** [comment]
I need to defer to those working on GFS v16.3.   The changes are correct in terms of syntax.   I assume they are what we want for GFS v16.3 DA.  

One question for @emilyhcliu .  Should we move these settings into DA ex scripts?  That is, the default behavior in the script is to zero the indicated increments.   This keeps DA settings inside the DA repo.   Users still have the ability to override this setting via the config file.

I'm not arguing for either approach.  Just wondering.   

What's your take @aerorahul?

**Comment by emilyhcliu** [comment]
> I need to defer to those working on GFS v16.3. The changes are correct in terms of syntax. I assume they are what we want for GFS v16.3 DA.
> 
> One question for @emilyhcliu . Should we move these settings into DA ex scripts? That is, the default behavior in the script is to zero the indicated increments. This keeps DA settings inside the DA repo. Users still have the ability to override this setting via the config file.
> 
> I'm not arguing for either approach. Just wondering.
> 
> What's your take @aerorahul?

The low-resolution parallels had been testing with these two variables (INCREMENTS_TO_ZERO and INVARS_ZERO_STRAT) in the config.base.  There two variables are here since v16 implementation.  My suggestion is to keep where we specify them (in config.base).  We will move these two variables into GSI for v17 implementation.

**Comment by aerorahul** [comment]
> > I need to defer to those working on GFS v16.3. The changes are correct in terms of syntax. I assume they are what we want for GFS v16.3 DA.
> > One question for @emilyhcliu . Should we move these settings into DA ex scripts? That is, the default behavior in the script is to zero the indicated increments. This keeps DA settings inside the DA repo. Users still have the ability to override this setting via the config file.
> > I'm not arguing for either approach. Just wondering.
> > What's your take @aerorahul?
> 
> The low-resolution parallels had been testing with these two variables (INCREMENTS_TO_ZERO and INVARS_ZERO_STRAT) in the config.base. There two variables are here since v16 implementation. My suggestion is to keep where we specify them (in config.base). We will move these two variables into GSI for v17 implementation.

`INCVARS_ZERO_STRAT` is used in `exglobal_atmos_analysis.sh` while `INCREMENTS_TO_ZERO` is used in multiple scripts.
Moving them to the DA repo may result in duplicate definitions.  We can re-evaluate in the future on configuring data assimilation component options.

**Comment by RussTreadon-NOAA** [comment]
> > > I need to defer to those working on GFS v16.3. The changes are correct in terms of syntax. I assume they are what we want for GFS v16.3 DA.
> > > One question for @emilyhcliu . Should we move these settings into DA ex scripts? That is, the default behavior in the script is to zero the indicated increments. This keeps DA settings inside the DA repo. Users still have the ability to override this setting via the config file.
> > > I'm not arguing for either approach. Just wondering.
> > > What's your take @aerorahul?
> > 
> > 
> > The low-resolution parallels had been testing with these two variables (INCREMENTS_TO_ZERO and INVARS_ZERO_STRAT) in the config.base. There two variables are here since v16 implementation. My suggestion is to keep where we specify them (in config.base). We will move these two variables into GSI for v17 implementation.
> 
> `INCVARS_ZERO_STRAT` is used in `exglobal_atmos_analysis.sh` while `INCREMENTS_TO_ZERO` is used in multiple scripts. Moving them to the DA repo may result in duplicate definitions. We can re-evaluate in the future on configuring data assimilation component options.

Excellent point @aerorahul!  I totally forgot.  It's best to keep this setting in one location.  Sprinkling it into multiple locations and expecting it to be set the same way everywhere is asking for trouble.

**Review by RussTreadon-NOAA — APPROVED** [review]
My approval means nothing other than checking a box.  I was not involved in the planning, preparation, or testing of GFS v16.3.  DA team members who were part of the decision for these settings should review this set of changes.  @emilyhcliu , who do you recommend?

I'll approve but again it's not a real review.  It's a rubber stamp.

**Comment by emilyhcliu** [comment]
> My approval means nothing other than checking a box. I was not involved in the planning, preparation, or testing of GFS v16.3. DA team members who were part of the decision for these settings should review this set of changes. @emilyhcliu , who do you recommend?
> 
> I'll approve but again it's not a real review. It's a rubber stamp.

Please add @ADCollard

**Comment by KateFriedman-NOAA** [comment]
Given approval to merge this PR.

**Pull request merged**
