### PR TITLE
[DO NOT MERGE] Weekly CI Tests Friday Feb 09, 2024

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Feb 09, 2024

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
> ```
> Experiment C384_atm3DVar_941f419a  *** FAILED *** on Orion
> Experiment C384_atm3DVar_941f419a  with 3 tasks failed at 02/09/24 06:20:18 PM
> Error logs:
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040118/gdasanal.log
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040118/gdasfcst.log
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040118/gfsanal.log
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040200/gdasanal.log
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040200/gdasfcst.log
> /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2305/RUNTESTS/COMROOT/C384_atm3DVar_941f419a/logs/2023040200/gfsanal.log
> ```

No idea what happened here. Some of these logs are gone. The fcst job hit the wallclock. Modules hanging again?

**Comment by DavidHuber-NOAA** [comment]
Looks like the `gdasfcst` timed while attempting to write the 9-hour surface forecast file.  No errors reported.  The timestamp of the `gdas.t18z.sfcf009.nc` file is the same as the timeout timestamp, so I don't think it stalled.  Moreover, the `gdas.t18z.atmf009.nc` file timestamp is also the same, further suggesting that it wasn't taking an inordinate amount of time to write the surface file.  The forecast steps were all reasonable as well (mostly less than 2s, with only 1 longer than 10s).  So I think there was a delay in setting up the forecast.

Should this be rebooted or should we wait until next weekend?

**Comment by TerrenceMcGuinness-NOAA** [comment]
@DavidHuber-NOAA I'll rewind that job and update the CI state database and reset the Label

**Comment by TerrenceMcGuinness-NOAA** [comment]
```
mterry (Orion-login-1) C384C192_hybatmda_941f419a $ rocotorewind -v 10 -d C384C192_hybatmda_941f419a.db -w C384C192_hybatmda_941f419a.xml -c 202304020000 -t gdasanal
02/12/24 11:44:32 CST :: C384C192_hybatmda_941f419a.xml :: Cycle 202304020000, Task gdasanal, jobid=16548531, in state DEAD (FAILED), ran for 88.0 seconds, exit status=9, try=2 (of 2)
02/12/24 11:44:32 CST :: C384C192_hybatmda_941f419a.xml :: Cycle 202304020000, Task gfsanal, jobid=16548532, in state DEAD (FAILED), ran for 29.0 seconds, exit status=9, try=2 (of 2)
202304020000: Rewind tasks for 202304020000 in state "activated" since 2024-02-10 09:30:12
202304020000: gdasanal: rewinding dead job.
202304020000: gdasanal: deleting all records of this job.
mterry (Orion-login-1) C384C192_hybatmda_941f419a $ 
```

**Pull request closed without merging**
