### PR TITLE
Enable traditional threading as an option

### LINKED ISSUE #3122: Traditional threading as option for forecast model
### What new functionality do you need?

Due to an issue with the model hanging on orion/hercules at high resolutions (C768/C1152) being most likely associated with the esmf managed threading (see https://github.com/ufs-community/ufs-weather-model/issues/2486 for more details), to support GFSv17 development we'd like to get traditional threading as an option in the g-w.  This comment from  @aerorahul https://github.com/ufs-community/ufs-weather-model/issues/2486#issuecomment-2465658188 says that a different set of ufs_configure files are needed.  I think these are now available in ufs-weather-model though.  I believe those are the options without the _esmf 

Hercules and orion are being explored as potential options for retrospective runs as WCOSS2 is busy with multiple large implementations coming up. 

### What are the requirements for the new functionality?

Allow for an option to run with traditional threading since ESMF managed threading appears to be an issue currently on hercules/orion. 

### Acceptance Criteria

- [] Forecast completes with traditional threading 
- [] forecast still completes with esmf managed threading (where it's possible) 

### Suggest a solution (optional)

I believe that the calculation of resources also needs to be updated.

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
In a previous PR, stubs were added to enable traditional threading in the UFS.
This PR takes the next step to execute the model with traditional threading.
Specifically;
1. Do not use the `_esmf` `ufs_configure` file for traditional threading.  This sets the `globalResourceControl` to `false` (traditional threading) ... this was done in the previous PR
2. when calculating components pet bounds do not multiply with number of threads also in `ufs_configure` ... this PR
3. `export OMP_NUM_THREADS=$UFS_THREADS` ... this was done in the previous PR

The default behaviour to use ESMF-managed threading is retained.  Traditional threading can be achieved by toggling `USE_ESMF_THREADING` flag in `config.fcst`

Closes #3122 - as in allows the model to be configured to run w/ traditional threading.  Testing on C768 S2SW was successful on Hercules (This was previously reported to be failing)

The use of traditional threading will be inefficient for model components that are not thread-enabled and supported e.g. MOM6 and CICE6, but since they require smaller number of tasks compared to ATM or WAV, the CPU 'waste' is not huge.

# Type of change
- [ ] Bug fix (fixes something broken)
- [X] New feature (adds functionality)
- [X] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?
Testing on Hercules for a C768 S2SW case was run with traditional threading (4 threads)
Some particulars of the run are as follows:
Run directory: `/work/noaa/stmp/rmahajan/HERCULES/RUNDIRS/c768s2swtt/gfs.2019120300/gfsfcst.2019120300/fcst.2077795/`
Run log: `/work2/noaa/stmp/rmahajan/RUNTESTS//COMROOT/c768s2swtt/logs/2019120300/gfs_fcst_seg0.log`

# Checklist
- [X] Any dependent changes have been merged and published
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have documented my code, including function, input, and output descriptions
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [X] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [X] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

**Comment by aerorahul** [comment]
After some waiting for WW3 points, it seems the model progressed in the test on Hercules.  The run will time out at 30 mins, because I was testing it.  Still worth taking a look at the log.

**Comment by aerorahul** [comment]
A run of the test [C768_S2SW](https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/hires/C768_S2SW.yaml) succeeded on Hercules with traditional threading.
This test was previously reported to be failing on Hercules and Orion.
I have not tested this for C1152 or Orion.

**Review by RuiyuSun — APPROVED** [review]

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA is there an expectation the model reproduces results based on who is managing threading?

**Comment by JessicaMeixner-NOAA** [comment]
I would think that we should get the same answers regardless of if it's ESMF managed threading or not, or how many threads.  I don't know if ufs-weather-model currently tests, but assume that was probably an early test if not a current one.

**Comment by WalterKolczynski-NOAA** [comment]
CI Tests set up to run in /lfs/h2/emc/ptmp/walter.kolczynski/PR/PR_3149/RUNTESTS on WCOSS

**Pull request merged**
