### PR TITLE
Add `POSTAMBLE_CMD` into preamble postamble

### LINKED ISSUE #1145: Add POSTAMBLE_CMD into preamble
**Description**

Add a variable `POSTAMBLE_CMD` to the postamble function in the preamble. The value of `POSTAMBLE_CMD` can be set in the `env` files (defaults for each machine) or elsewhere as users need.

Initial functionality will run `report-mem` on SLURM R&Ds to provide a report of job memory usage at the end of each job. Related to issue #1144.

**Requirements**

Job memory usage is reported within jobs on specified platforms.

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR adds the ability to run a command at the end of jobs via the preamble's postamble function. A new command can be set via `POSTAMBLE_CMD` and will be invoked at the end of jobs. Users can add the command to the top of an env file to have every job run it or it can be placed within a job if-block in the env file to run for just that job.

Resolves #1145

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Low-res atmos-only cycled test on Hera with `'report-mem'` command in `POSTAMBLE_CMD`.

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
Sample `POSTAMBLE_CMD` output from an eobs job using `'report-mem'` on Hera below. Have already discussed module error messages in `'report-mem'` with Hera sysadmins and can't do anything about it at the moment. Memory report command works otherwise.
```
+ exglobal_atmos_analysis.sh[943]: echo Tue Jan 16 20:08:12 UTC 2024 END tar obs_input
Tue Jan 16 20:08:12 UTC 2024 END tar obs_input
+ exglobal_atmos_analysis.sh[948]: '[' NO = YES ']'
+ exglobal_atmos_analysis.sh[956]: cd /scratch1/NCEPDEV/stmp2/Kate.Friedman/RUNDIRS/testpostamble/eobs.238059
+ exglobal_atmos_analysis.sh[957]: [[ NO = \Y\E\S ]]
+ exglobal_atmos_analysis.sh[964]: '[' NO = YES -a enkfgdas '!=' enkf ']'
++ exglobal_atmos_analysis.sh[967]: date
+ exglobal_atmos_analysis.sh[967]: echo 'gdas 2021122100 atminc done at Tue Jan 16 20:08:12 UTC 2024'
+ exglobal_atmos_analysis.sh[971]: exit 0
+ exglobal_atmos_analysis.sh[1]: postamble exglobal_atmos_analysis.sh 1705435237 0
+ preamble.sh[70]: set +x
h35m21: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 42: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 42: module: command not found
Peak memory usage summary:
  min =   27083568  KB
  ave =   29502052  KB
  max =   31920536  KB

All nodes sorted by peak memory as percentage of limit: (in KB)
          % of      user        user          user         total       total
Node      limit     max         limit        current      current      phys
h35m22    33.9    31920536     94208000      4038552     10119844    394753940 
h35m21    28.7    27083568     94208000      4163496     10400592    394753948 
End exglobal_atmos_analysis.sh at 20:08:13 with error code 0 (time elapsed: 00:07:36)
+ exgdas_enkf_select_obs.sh[105]: export err=0
+ exgdas_enkf_select_obs.sh[105]: err=0
+ exgdas_enkf_select_obs.sh[105]: err_chk
+ exgdas_enkf_select_obs.sh[109]: cd /scratch1/NCEPDEV/stmp2/Kate.Friedman/RUNDIRS/testpostamble/eobs.238059
+ exgdas_enkf_select_obs.sh[110]: [[ NO = \Y\E\S ]]
+ exgdas_enkf_select_obs.sh[113]: exit 0
+ exgdas_enkf_select_obs.sh[1]: postamble exgdas_enkf_select_obs.sh 1705435237 0
+ preamble.sh[70]: set +x
h35m21: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 42: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 42: module: command not found
Peak memory usage summary:
  min =   27083568  KB
  ave =   29502052  KB
  max =   31920536  KB

All nodes sorted by peak memory as percentage of limit: (in KB)
          % of      user        user          user         total       total
Node      limit     max         limit        current      current      phys
h35m22    33.9    31920536     94208000      4038048     10121124    394753940 
h35m21    28.7    27083568     94208000      4161792     10401488    394753948 
End exgdas_enkf_select_obs.sh at 20:08:14 with error code 0 (time elapsed: 00:07:37)
+ JGDAS_ENKF_SELECT_OBS[119]: status=0
+ JGDAS_ENKF_SELECT_OBS[120]: [[ 0 -ne 0 ]]
+ JGDAS_ENKF_SELECT_OBS[126]: [[ NO = YES ]]
+ JGDAS_ENKF_SELECT_OBS[138]: [[ -e OUTPUT.238646 ]]
+ JGDAS_ENKF_SELECT_OBS[139]: cat OUTPUT.238646
/scratch1/NCEPDEV/global/Kate.Friedman/git/feature-postamble-cmd/exec/gsi.x
+ JGDAS_ENKF_SELECT_OBS[145]: cd /scratch1/NCEPDEV/stmp2/Kate.Friedman/RUNDIRS/testpostamble
+ JGDAS_ENKF_SELECT_OBS[146]: [[ NO = \N\O ]]
+ JGDAS_ENKF_SELECT_OBS[146]: rm -rf /scratch1/NCEPDEV/stmp2/Kate.Friedman/RUNDIRS/testpostamble/eobs.238059
+ JGDAS_ENKF_SELECT_OBS[149]: exit 0
+ JGDAS_ENKF_SELECT_OBS[1]: postamble JGDAS_ENKF_SELECT_OBS 1705435230 0
+ preamble.sh[70]: set +x
h35m22: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 29: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 30: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 31: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 32: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 33: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 34: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 35: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 36: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 38: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 39: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 41: module: command not found
h35m21: /home/Kate.Friedman/.bashrc: line 42: module: command not found
h35m22: /home/Kate.Friedman/.bashrc: line 42: module: command not found
Peak memory usage summary:
  min =   27083568  KB
  ave =   29502052  KB
  max =   31920536  KB

All nodes sorted by peak memory as percentage of limit: (in KB)
          % of      user        user          user         total       total
Node      limit     max         limit        current      current      phys
h35m22    33.9    31920536     94208000      3945000     10126136    394753940 
h35m21    28.7    27083568     94208000      3702568     10340756    394753948 
End JGDAS_ENKF_SELECT_OBS at 20:08:15 with error code 0 (time elapsed: 00:07:45)
+ eobs.sh[17]: status=0
+ eobs.sh[20]: exit 0
+ eobs.sh[1]: postamble eobs.sh 1705435227 0
+ preamble.sh[70]: set +x
End eobs.sh at 20:08:15 with error code 0 (time elapsed: 00:07:48)
_______________________________________________________________
Start Epilog on node h35m21 for job 54325432 :: Tue Jan 16 20:08:16 UTC 2024
Job 54325432 finished for user Kate.Friedman in partition hera with exit code 0:0
_______________________________________________________________
End Epilogue Tue Jan 16 20:08:16 UTC 2024
```

**Review by DavidHuber-NOAA — APPROVED** [review]
That's a very useful tool!  Thanks!

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks good. Especially like the documentation.

Conditionally approved pending successful completion of CI tests.

**Comment by KateFriedman-NOAA** [comment]
> Looks good. Especially like the documentation.

IIRC you helped write the documentation for this @WalterKolczynski-NOAA . Thank you and kudos to you for it! :)

**Pull request merged**
