### PR TITLE
Add fix for metplus jobs when gfs_cyc=2 or 4

### LINKED ISSUE #2790: METplus jobs fail for gfs_cyc=2 or 4
### What is wrong?

When running the `C96_atm3DVar_extended` test, the `gfsmetpg2g1` and `gfsmetpg2o1` jobs fail to locate all data.  For this test, `gfs_cyc=4` and the `metp` jobs only run on the 00z cycle, so it should be looking for GRIB2 data from the 00Z cycle and the previous 3 cycles.  Instead, it is looking for the 00Z cycle and the _next_ 3 cycles.  These data are not available until later cycles, so the `.stat` files are not generated for cycles 06-18.

### What should have happened?

The METplus scripts should look backwards instead of forwards and skip over cycles that should not exist.

### What machines are impacted?

All or N/A

### Steps to reproduce

Run a GFS cycle in either forecast-only or cycled mode with `gfs_cyc=4`.

### Additional information

Found while testing #2749 and #2732.
Sample log file can be found here: `/lfs/h2/emc/nems/noscrub/david.huber/GFS_CI_ROOT/PR/2749/RUNTESTS/COMROOT/C96_atm3DVar_extended_5a7dd316/logs/2021122100/gfsmetpg2g1.log`

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
Changes how METplus jobs run so that they run on the last GFS cycle for a given `PDY`.

This is a departure from operations where the METplus jobs run on the 00Z cycle for the previous 3 cycles and 00Z (i.e. `${PDYm1}06` through `${PDY}00`).  With this PR, for gfs_cyc=4, METplus jobs will run on `${PDY}18` for cycles 00-18.  See https://github.com/NOAA-EMC/EMC_verif-global/pull/131 for more details.

`ecf` scripts may need to be modified.

Depends on https://github.com/NOAA-EMC/EMC_verif-global/pull/131
Resolves #2790 

# Type of change
- Bug fix (fixes something broken)
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES (departure from operations)
- Does this change require a documentation update? NO

# How has this been tested?
Will test a full suite on WCOSS2

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
@malloryprow These fixes are working well for the `g2g1` and `g2o1` jobs, but the `pcp1` job is producing a 0-sized `.stat` file for the boundary case when `EDATE_GFS` ends on cycle `06` with `gfs_cyc=4` for the `00` cycle.  I am not sure what the issue is.  Would you mind taking a look at my log?

`/lfs/h2/emc/nems/noscrub/david.huber/para/COMROOT/fix_metp/logs/2021122206/gfsmetppcp1.log`

**Comment by malloryprow** [comment]
I can try to look at it here this afternoon.

**Comment by malloryprow** [comment]
In /lfs/h2/emc/stmp/david.huber/RUNDIRS/fix_metp/metppcp1.103932/precip_step1/metplus_output/logs/fix_metp/master_metplus_precip_step1_ccpa_accum24hr_gatherbyVSDB_for20211222_runon20240726144059.log, I see

> DEBUG 2: Processing Job 1: -job filter -model fix_metp -fcst_valid_beg 20211222_120000 -fcst_valid_end 20211222_120000 -fcst_valid_hour 120000 **-fcst_init_hour 000000** -dump_row /lfs/h2/emc/stmp/david.huber/RUNDIRS/fix_metp/metppcp1.103932/precip_step1/metplus_output/gather_by_VSDB/stat_analysis/ccpa_accum24hr/fix_metp/fix_metp_2021122212_2021122212_00.stat

But it looks like you only have data for the 06Z cycle? (ls /lfs/h2/emc/stmp/david.huber/RUNDIRS/fix_metp/metppcp1.103932/precip_step1/data/fix_metp)

Is that what is suppose to be happening in this experiment?

**Comment by DavidHuber-NOAA** [comment]
@malloryprow There should also be data for both the 00Z and 06Z cycle as the GFS was run on all cycles.

The archive shows GFS forecast data for all cycles from 2021122100 to 2021122206 in `/lfs/h2/emc/nems/noscrub/david.huber/archive/fix_metp`.

**Comment by malloryprow** [comment]
Ah, okay. I think I'm understanding now. Did the grid2grid and grid2obs pick up the 00Z and 06Z files in their stats? I know you said they worked, but want to make sure they worked like they are suppose to.

**Comment by malloryprow** [comment]
Okay upon looking at the log again, I think the problem is coming from https://github.com/NOAA-EMC/EMC_verif-global/blob/develop/ush/set_init_valid_fhr_info.py.

exprecip_step1.sh[45]: python /lfs/h2/emc/nems/noscrub/david.huber/GW/gw_fix_metp/sorc/verifglobal.fd/ush/set_init_valid_fhr_info.py
> BEGIN: set_init_valid_fhr_info.py
> END: set_init_valid_fhr_info.py
> exprecip_step1.sh[46]: status=0
>exprecip_step1.sh[47]: [[ 0 -ne 0 ]]
> exprecip_step1.sh[48]: [[ 0 -eq 0 ]]
> exprecip_step1.sh[48]: echo 'Succesfully ran set_init_valid_fhr_info.py'
> Succesfully ran set_init_valid_fhr_info.py
> exprecip_step1.sh[49]: echo
>
> exprecip_step1.sh[50]: . /lfs/h2/emc/stmp/david.huber/RUNDIRS/fix_metp/metppcp1.103932/precip_step1/python_gen_env_vars.sh
> python_gen_env_vars.sh[2]: echo BEGIN: python_gen_env_vars.sh
> BEGIN: python_gen_env_vars.sh
> python_gen_env_vars.sh[3]: export 'precip1_ccpa_accum24hr_fcyc_list=00 06'
> python_gen_env_vars.sh[3]: precip1_ccpa_accum24hr_fcyc_list='00 06'
> python_gen_env_vars.sh[4]: export 'precip1_ccpa_accum24hr_init_hr_list=00, 06'
> python_gen_env_vars.sh[4]: precip1_ccpa_accum24hr_init_hr_list='00, 06'++ python_gen_env_vars.sh[5]: export precip1_ccpa_accum24hr_init_hr_beg=00
> python_gen_env_vars.sh[5]: precip1_ccpa_accum24hr_init_hr_beg=00++ python_gen_env_vars.sh[6]: export precip1_ccpa_accum24hr_init_hr_end=06
> python_gen_env_vars.sh[6]: precip1_ccpa_accum24hr_init_hr_end=06++ python_gen_env_vars.sh[7]: export precip1_ccpa_accum24hr_init_hr_inc=21600
> python_gen_env_vars.sh[7]: precip1_ccpa_accum24hr_init_hr_inc=21600++ python_gen_env_vars.sh[8]: export precip1_ccpa_accum24hr_vhr_list=12
> python_gen_env_vars.sh[8]: precip1_ccpa_accum24hr_vhr_list=12
> python_gen_env_vars.sh[9]: export precip1_ccpa_accum24hr_valid_hr_list=12
> python_gen_env_vars.sh[9]: precip1_ccpa_accum24hr_valid_hr_list=12
> python_gen_env_vars.sh[10]: export precip1_ccpa_accum24hr_valid_hr_beg=12
> python_gen_env_vars.sh[10]: precip1_ccpa_accum24hr_valid_hr_beg=12
> python_gen_env_vars.sh[11]: export precip1_ccpa_accum24hr_valid_hr_end=12
> python_gen_env_vars.sh[11]: precip1_ccpa_accum24hr_valid_hr_end=12
> python_gen_env_vars.sh[12]: export precip1_ccpa_accum24hr_valid_hr_inc=86400
> python_gen_env_vars.sh[12]: precip1_ccpa_accum24hr_valid_hr_inc=86400
> python_gen_env_vars.sh[13]: export precip1_ccpa_accum24hr_obs_daily_file=True
> python_gen_env_vars.sh[13]: precip1_ccpa_accum24hr_obs_daily_file=True
**> python_gen_env_vars.sh[14]: export precip1_ccpa_accum24hr_fhr_list=30
> python_gen_env_vars.sh[14]: precip1_ccpa_accum24hr_fhr_list=30
> python_gen_env_vars.sh[15]: export precip1_ccpa_accum24hr_fhr_beg=30
> python_gen_env_vars.sh[15]: precip1_ccpa_accum24hr_fhr_beg=30**

**Comment by DavidHuber-NOAA** [comment]
Yes, I think I'm understanding a little better now, too.  The grid2grid and grid2obs pulled the data they were supposed to.  Based on messages from get_data_files.py, the following grib2 data files were pulled:
grid2grid:
```
pgbf[00,24].gfs.2021122200.grib2
pgbf[00,24].gfs.2021122206.grib2
pgbanl.gfs.2021122200.grib2
pgbanl.gfs.2021122206.grib2
```
grid2obs:
```
pgbf[00-45].gfs.2021122200.grib2
pgbf[00-39].gfs.2021122106.grib2
```
precip:
```
pgbf[12-30].gfs.2021122106.grib2
```

**Comment by DavidHuber-NOAA** [comment]
So should `export precip1_ccpa_accum24hr_fhr_list` have two members, `[36, 30]`?

**Comment by malloryprow** [comment]
Great about the grid2grid and grid2obs, but in addition to pgbf[12-30].gfs.2021122106.grib2 precip also should have pulled pgbf[06-36].gfs.2021122100.grib2. Yes, should have been `export precip1_ccpa_accum24hr_fhr_list=36,30`.

**Comment by DavidHuber-NOAA** [comment]
Alright, I'll see if I can figure out what happened there.

**Comment by DavidHuber-NOAA** [comment]
This PR is ready for review, but not yet ready to merge.  The dependent PR https://github.com/NOAA-EMC/EMC_verif-global/pull/131 needs to be reviewed and merged first.

Tests were performed on WCOSS2 for gfs_cyc=1, 2, and 4 for the following edge cases:
```
gfs_cyc=2, SDATE_GFS=2021122100, EDATE_GFS=2021122200
gfs_cyc=4, SDATE_GFS=2021122100, EDATE_GFS=2021122206
```

The logs for these cases can be found in the following respective directories
```
/lfs/h2/emc/nems/noscrub/david.huber/para/COMROOT/fix_metp_gfs2/logs/2021122200
/lfs/h2/emc/nems/noscrub/david.huber/para/COMROOT/fix_metp/logs/2021122206
```
The grid2grid, grid2obs, and precip step 1 jobs were all successful and generated expected data in `/lfs/h2/emc/nems/noscrub/david.huber/archive/metplus_data/by_VSDB/<job_name>/<sub_job_name>/<cycle>Z/[fix_metp_gfs2,fix_metp]`.

**Comment by malloryprow** [comment]
https://github.com/NOAA-EMC/EMC_verif-global/pull/131 has been merged! https://github.com/NOAA-EMC/EMC_verif-global/commit/92904d2c431969345968f74e676717057ec0042a

**Comment by DavidHuber-NOAA** [comment]
Thanks @malloryprow!

**Comment by DavidHuber-NOAA** [comment]
Tests are running manually on WCOSS2 after updating the `HOMEDIR` in each config.base.

**Comment by DavidHuber-NOAA** [comment]
All tests were successful on WCOSS2, though I will note that I encountered a bug within METplus when running the gfsmetpg2o1 job for the C48_S2SW case.  This bug is located here in lines 2812-2813 of `/apps/ops/para/libs/intel/19.1.3.304/metplus/3.1.1/metplus/util/met_util.py`:

```python
    if not os.path.exists(outdir):
        os.makedirs(outdir, mode=0o0775)
```

When running the Grid2Obs job (and very rarely the Grid2Grid job) in parallel as we do in the global workflow, it is possible for two instances to attempt to create the same directory at the same time.  Knowing that this is a production script and a no-longer-maintained version of DTC-controlled software, I know it is highly unlikely to be able to change these lines, but it would be nice to change them to

```python
    if not os.path.exists(outdir):
        os.makedirs(outdir, mode=0o0775, exist_ok=True)
```

This would prevent crashes if a directory already exists.

**Comment by malloryprow** [comment]
Ah yeah, probably not something that can be changed.

**Review by malloryprow — APPROVED** [review]

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
