### PR TITLE
CI Updates to support Hercules

### LINKED ISSUE #2154: Add CI for Free Forecast only Hercules
### What new functionality do you need?

We need to run CI with FF until #1588 is complete

### What are the requirements for the new functionality?

CI runs on Hercules on only the FF CI cases 

### Acceptance Criteria

Cron CI works on Hercules 

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
# Description

If merged, this PR will update the CI scripts so they will run on Hercules for Free Forecast only
NOTE: This is a stop gap to issue #2131 until its block on #1588 is removed.

Resolves #2154 

# Type of change

- New feature (adds functionality)
Updates CI to run on Hercules

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
This will be tested in place when the label **CI-Hercules-Ready** is applied to this PR.
- Forecast-only on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good.

**Review by DavidHuber-NOAA — COMMENTED** [review]
The NCL module is not loaded on Hercules, so I don't think that the ocnpost jobs can run in the S2SW* jobs.  Should these also be disabled until we can load that module OR NCL is removed from the scripts?

**Comment by aerorahul** [comment]
> The NCL module is not loaded on Hercules, so I don't think that the ocnpost jobs can run in the S2SW* jobs. Should these also be disabled until we can load that module OR NCL is removed from the scripts?

good point.  Can we tackle it in a subsequent PR?  `ocnpost` jobs have been disabled on wcoss2 as well, so we know there is a mechanism in place.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul I'm good with that being tackled later.

**Review by DavidHuber-NOAA — APPROVED** [review]
Approved assuming `ocnpost` jobs will be handled later.

**Comment by JessicaMeixner-NOAA** [comment]
> > The NCL module is not loaded on Hercules, so I don't think that the ocnpost jobs can run in the S2SW* jobs. Should these also be disabled until we can load that module OR NCL is removed from the scripts?
> 
> good point. Can we tackle it in a subsequent PR? `ocnpost` jobs have been disabled on wcoss2 as well, so we know there is a mechanism in place.

Just need to add a statement here for Hercules: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.ocnpost#L20-L24

**Comment by aerorahul** [comment]
> > > The NCL module is not loaded on Hercules, so I don't think that the ocnpost jobs can run in the S2SW* jobs. Should these also be disabled until we can load that module OR NCL is removed from the scripts?
> > 
> > 
> > good point. Can we tackle it in a subsequent PR? `ocnpost` jobs have been disabled on wcoss2 as well, so we know there is a mechanism in place.
> 
> Just need to add a statement here for Hercules: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.ocnpost#L20-L24

Thanks for the pointer @JessicaMeixner-NOAA 
@TerryMcGuinness-NOAA
Can we extend the conditional in the file @JessicaMeixner-NOAA pointed to, to include hercules in this PR itself.
Thanks.

**Review by aerorahul — CHANGES_REQUESTED** [review]
Please update `config.ocnpost` to disable this job processing on Hercules.  See comments in this PR.

**Comment by TerrenceMcGuinness-NOAA** [comment]
> Please update config.ocnpost to disable this job processing on Hercules

@aerorahul got it, ok on it.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks good. Nice simple update.

**Review by aerorahul — APPROVED** [review]
thanks. looks great.

**Pull request merged**
