### PR TITLE
CI Self Test of develop branch [Do Not Merge]

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
This is a CI Self Test on Develop: Seeing failures on Orion during development of CI.  Also need to baseline Hera.

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
> ```
> Experiment C96_atm3DVar_2d389c8a Terminated: *** FAILED *** on Orion
> Experiment C96_atm3DVar_2d389c8a Terminated with 1 tasks failed at Tue Nov 21 10:10:33 CST 2023
> Error logs:
> /work2/noaa/stmp/GFS_CI_ROOT/PR/2085/RUNTESTS/COMROT/C96_atm3DVar_2d389c8a/logs/2021122106/gdasanal.log
> ```
> 
> **srun: warning: can't honor --ntasks-per-node set to 8 which doesn't match the requested tasks 84 with the number of requested nodes 11. Ignoring --ntasks-per-node.**
> 
> ```
> + exglobal_atmos_analysis.sh[918]: /bin/cp -p /work2/noaa/stmp/GFS_CI_ROOT/PR/2085/global-workflow/exec/gsi.x /work/noaa/stmp/mterry/RUNDIRS/C96_atm3DVar_2d389c8a/anal.303567
> ++ exglobal_atmos_analysis.sh[919]: basename /work2/noaa/stmp/GFS_CI_ROOT/PR/2085/global-workflow/exec/gsi.x
> + exglobal_atmos_analysis.sh[919]: srun -l --export=ALL -n 84 --cpus-per-task=5 /work/noaa/stmp/mterry/RUNDIRS/C96_atm3DVar_2d389c8a/anal.303567/gsi.x
> srun: warning: can't honor --ntasks-per-node set to 8 which doesn't match the requested tasks 84 with the number of requested nodes 11. Ignoring --ntasks-per-node.
> 16: [Orion-25-42:342733:0:342733]     address.c:1052 Assertion `*addr_version == UCP_OBJECT_VERSION_V2' failed: addr version 14
> ```

CI misidentified the real problem, which begins on the last line shown here. May be insufficient memory, but I think we need an expert to look at it. @DavidHuber-NOAA can you take a look and determine whether this is a settings problem, machine problem, or a GSI problem?

Tests were passing until this started late Friday. Maybe some combination of the PRs that were merged, even though they individually passed?

**Comment by DavidHuber-NOAA** [comment]
@WalterKolczynski-NOAA I am not sure exactly what to make of this error.  It's obviously an MPI error, but beyond that I am not sure.  I would be happy to test some things out on Orion, though.  Is there a way to run this test on Orion directly?

**Comment by WalterKolczynski-NOAA** [comment]
@DavidHuber-NOAA This might actually be a different thing than the other issue. This one seems ephemeral (I can't reproduce it), the other (higher-res) seems consistent.

**Comment by DavidHuber-NOAA** [comment]
@WalterKolczynski-NOAA Apologies, I am looking through my emails and I don't see the the other issue you are referring to.  Can you point me to it again?  Glad to see that Orion is running again, though.

**Pull request closed without merging**
