### PR TITLE
Update the gfs_utils repository hash

### LINKED ISSUE #2669: gdasatmanlprod fails in C48mx500_3DVarAOWCDA CI on Hera
### What is wrong?

The  20210324 18Z gdasatmanlprod fails when running C48mx500_3DVarAOWCDA CI on Hera.  Investigation of the failure (see PR #2641) points to nonphysical values in the precipitation field.

### What should have happened?

gdasatmanlprod  should run to completion without error

### What machines are impacted?

Hera

### Steps to reproduce

1. install `develop` at 9caa51de
2. set up and run C48mx500_3DVarAOWCDA CI
4. 20210324 18 Z gdasatmanlprod fails

### Additional information

The specific log file in the run directory containing the error is `mpmd.${jobid}.21.out`
```
21: + interp_atmos_master.sh[44](tmpfile_anl_22): wgrib2 tmpfile_anl_22 -set_grib_type same -set_bitmap 1 -set_grib_max_bits 16 -new_grid_\
winds earth -new_grid_interpolation bilinear -if ':(CSNOW|CRAIN|CFRZR|CICEP|ICSEV):' -new_grid_interpolation neighbor -fi -if ':(APCP|ACPC\
P|PRATE|CPRAT|DZDT):' -new_grid_interpolation budget -fi -if ':(APCP|ACPCP|PRATE|CPRAT):' -set_grib_max_bits 25 -fi -new_grid latlon 0:144\
0:0.25 90:721:-0.25 pgb2file_anl_22_0p25 -new_grid latlon 0:720:0.5 90:361:-0.5 pgb2file_anl_22_0p50 -new_grid latlon 0:360:1.0 90:181:-1.\
0 pgb2file_anl_22_1p00
21:
21: *** FATAL ERROR: add_many_bitstream: n_bits = (26) ***
21:
21: 1:0:d=2021032418:MSLET:mean sea level:anl:
21: 2:27834:d=2021032418:HGT:1000 mb:anl:
21: 3:54708:d=2021032418:PRES:surface:anl:
21: 4:81277:d=2021032418:HGT:surface:anl:
21: + interp_atmos_master.sh[1](tmpfile_anl_22): postamble interp_atmos_master.sh 1717869240 8
```
The failure occurs while processing the record 5, PRATE.  Below is a `wgrib2 -V` listing for PRATE.
```
5:97347:vt=2021032418:surface:anl:PRATE Precipitation Rate [kg/m^2/s]:
    ndata=18432:undef=4148:mean=4.25403e+16:min=-6.08487e+19:max=5.02802e+20
    grid_template=40:winds(N/S):
        Gaussian grid: (192 x 96) units 1e-06 input WE:NS output WE:SN
        number of latitudes between pole-equator=48 #points=18432
        lat 88.572166 to -88.572166
        lon 0.000000 to 358.125000 by 1.875000
```
The PRATE values are non-physical.

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
# Description
Point to the latest hash of the gfs-utils repository, which contains the bug fix to gaussian_sfcanl.

Resolves #2669.
Refs: https://github.com/NOAA-EMC/gfs-utils/pull/73

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Clone and build gfs_utils on Hercules.
- @CatherineThomas-NOAA - can you list your tests?

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes  (Not sure what tests are required.)
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by CatherineThomas-NOAA** [comment]
Thanks for opening this PR @GeorgeGayno-NOAA.

For [gfs-utils PR#73](https://github.com/NOAA-EMC/gfs-utils/pull/73), I ran S2S 3DVar cycling tests on Hera for C48 and C384.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved

**Comment by WalterKolczynski-NOAA** [comment]
WCOSS is failing for reasons unrelated to this PR

**Comment by DavidHuber-NOAA** [comment]
Picking up the WCOSS2 tests manually.

**Comment by DavidHuber-NOAA** [comment]
Some of the C96_atm3DVar_extended gempak jobs failed.  This was also seen in #2753 and has been fixed in that PR and has nothing to do with gfs_utils.

All other jobs were successful.  Setting the CI-Wcoss2-Passed label.

**Pull request merged**
