### PR TITLE
Remove firstcyc job

### LINKED ISSUE #415: Rework firstcyc job
Cycled mode currently has a `firstcyc` job in the first half cycle. It's dependency is currently on the existence of the rocoto log 4 cycles later. This dependency often holds up the forward progress of the 4th cycle when the cycle throttle of 3 is met because firstcyc isn't done yet and therefore the first half cycle can't complete and become Inactive (freeing up a cycle in cyclethrottle).

Easy workaround is to increase cycle throttle to 4 in live experiments but better yet, a review of the need/use of `firstcyc` job should happen. Review how the `firstcyc` job is used and, if needed, update what its dependency should be. Remove if not truly required.

### PR DESCRIPTION
**Pull request by jkuang-exploro**
This PR removes the redundant firstcyc job.

Addressing issue #415

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
@JianKuang-UMD Changes look good. Before I approve and submit this PR...in your cycled test did the first half cycle become inactive after it was completed? Can you share the output from this command?

`rocotostat -d DB_FILE -w XML_FILE -s`

The `-s` will give you the state of each cycle (active or not). I want to make sure the first half cycle becomes inactive eventually, depending on your cycle throttle of course. Let me know what your cycle throttle was too, thanks!

**Comment by jkuang-exploro** [comment]
@KateFriedman-NOAA Forgot to respond. The completed cycles are deactivated as anticipated.

**Comment by KateFriedman-NOAA** [comment]
> The completed cycles are deactivated as anticipated.

@JianKuang-UMD Excellent, thanks for confirming! I'll wrap up this PR now.

**Review by KateFriedman-NOAA — APPROVED** [review]
@JianKuang-UMD confirmed that the first half cycle deactivates properly after the removal of the firstcyc job

**Comment by KateFriedman-NOAA** [comment]
@JianKuang-UMD I initially deleted the `feature/earc_dependency` branch after submitting the PR but I just restored it to check with you...do you need this branch still or may I now remove it? Thanks!

**Comment by KateFriedman-NOAA** [comment]
Close #415

**Comment by jkuang-exploro** [comment]
@KateFriedman-NOAA No. I don't need this branch anymore. Thanks for checking with me.

**Pull request merged**
