### PR TITLE
Update LandDA related job post COM refactor plus other minor fixes.

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**

This is a partial pull of files from PR 1541.
All modified files have been pulled here.
The ones not added are the land_analysis.py related scripts.

Specifically, this PR:
- updates the j-jobs to accommodate post COM refactor upgrades.
- minor updates to `config.resources` for land DA tasks
- add task dependencies in the rocoto workflow
- when doing LandDA, use `sfc_data.tile{{ t }}.nc` created by Land DA is used as input  of `global_cycle` for the deterministic and case w/ `DOIAU=NO`.

The updates needed in `land_analysis.py` will be the subject of a follow-up PR along with adding of the `landanlprep` job.

This is the work of @jiaruidong2017 and is being done here at his request in PR #1541 

By and large, the updates to the COM reorg are captured in here along with a few other items.

**Type of change**

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
@jiaruidong2017 is best suited to answer this question.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Script changes look fine. PR title and description should be updated before merging to say what is actually being accomplished in this PR beyond it was extracted from the other PR (the list of caveats is a good inclusion though).

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by jiaruidong2017 — CHANGES_REQUESTED** [review]
@aerorahul Would you please pull the file `parm/config/config.landanlprep` so that we can setup both the experiment and workflow.

**Comment by jiaruidong2017** [comment]
> 2. `scripts/exglobal_atmos_sfcanl.sh` creates `sfcanl_data.tile{{t}}.nc` in `model_data/atmos/restart` while the land DA executables are creating similar named file in `analysis/land`.  Which of these is used by the forecast model during initialization?  Is the `global_cycle` which creates the former still needed when doing Land DA?  Or is the Land DA updating a subset of the fields?

Originally, the `sfcanl_data.tile{{t}}.nc` is copied from the model restart file in the previous cycle and updated in the `global_cycle`, which is used by the forecast model during initialization. 
When the land DA is available, the land DA executables create the land analysis files, which are copied to the `sfcanl_data.tile{{t}}.nc` in the `model_data/atmos/restart` and updated in the `global_cycle`, and then is used by the forecast model during initialization.

> 3. Does `landanlprep` truly depend on `landanlinit`?  If not, we would like to collect all the `prep` related jobs upfront at the beginning of the cycle.
> 
Yes, the `landanlprep` depends on the `landanlinit`, because `landanlinit` stages the background restart files and these restart files were required by the `landanlprep` in the IMS processing. 

> 
> **How Has This Been Tested?** @jiaruidong2017 is best suited to answer this question.
> 
After pull the file `parm/config/config.landanlprep`, we can setup both experiment and workflow with land DA implementation.

**Comment by aerorahul** [comment]
> @aerorahul Would you please pull the file `parm/config/config.landanlprep` so that we can setup both the experiment and workflow.

Done.

**Comment by aerorahul** [comment]
> > 2. `scripts/exglobal_atmos_sfcanl.sh` creates `sfcanl_data.tile{{t}}.nc` in `model_data/atmos/restart` while the land DA executables are creating similar named file in `analysis/land`.  Which of these is used by the forecast model during initialization?  Is the `global_cycle` which creates the former still needed when doing Land DA?  Or is the Land DA updating a subset of the fields?
> 
> Originally, the `sfcanl_data.tile{{t}}.nc` is copied from the model restart file in the previous cycle and updated in the `global_cycle`, which is used by the forecast model during initialization. When the land DA is available, the land DA executables create the land analysis files, which are copied to the `sfcanl_data.tile{{t}}.nc` in the `model_data/atmos/restart` and updated in the `global_cycle`, and then is used by the forecast model during initialization.
> 
> > 3. Does `landanlprep` truly depend on `landanlinit`?  If not, we would like to collect all the `prep` related jobs upfront at the beginning of the cycle.
> 
> Yes, the `landanlprep` depends on the `landanlinit`, because `landanlinit` stages the background restart files and these restart files were required by the `landanlprep` in the IMS processing.
> 
> > **How Has This Been Tested?** @jiaruidong2017 is best suited to answer this question.
> 
> After pull the file `parm/config/config.landanlprep`, we can setup both experiment and workflow with land DA implementation.

@jiaruidong2017 
I don't think what you said is completely accurate re. 2.
`scripts/exglobal_atmos_sfcanl.sh` creates `sfcanl_data.tile{{t}}.nc` in `model_data/atmos/restart` in the `current_cycle`.  This file is used as `sfc_data.tile{{t}}.nc` during the initialization of the forecast model.
Are you saying that when `LandDA` is on, the execution of `scripts/exglobal_atmos_sfcanl.sh` is no longer necessary?

Thank you for clarifying the dependency of `landanlprep` on `landanlinit`.   In keeping w/ the `prep` step nature, would the team be willing to make `landanlprep` independent of `landanlinit`?  @CoryMartin-NOAA thoughts?

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017
> I don't think what you said is completely accurate re. 2.
> `scripts/exglobal_atmos_sfcanl.sh` creates `sfcanl_data.tile{{t}}.nc` in `model_data/atmos/restart` in the `current_cycle`. This file is used as `sfc_data.tile{{t}}.nc` during the initialization of the forecast model.
> Are you saying that when `LandDA` is on, the execution of `scripts/exglobal_atmos_sfcanl.sh` is no longer necessary?

@aerorahul I am not quite familiar with `scripts/exglobal_atmos_sfcanl.sh`. What I mean is when `landDA` is on, the analysis files from the `landDA` feed the `scripts/exglobal_atmos_sfcanl.sh` (`sfcanl_data.tile{{t}}.nc`) and the `scripts/exglobal_atmos_sfcanl.sh` is executed to update `sfcanl_data.tile{{t}}.nc` (replacing `sfc_data.tile{{t}}.nc`) for the forecast initialization.

**Review by jiaruidong2017 — APPROVED** [review]

**Comment by jiaruidong2017** [comment]
> > @aerorahul Would you please pull the file `parm/config/config.landanlprep` so that we can setup both the experiment and workflow.
> 
> Done.

Thanks @aerorahul for your great efforts.

**Review by jiaruidong2017 — APPROVED** [review]

**Comment by aerorahul** [comment]
@WalterKolczynski-NOAA 
I have updated the description of the PR. 

@jiaruidong2017 @CoryMartin-NOAA Is the description accurate?

**Comment by jiaruidong2017** [comment]
Complete the Issue #1520

**Pull request merged**
