### PR TITLE
Cleanup of stale RUNDIRS from an experiment

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
This PR:
- removes stale temporary scratch run directories from `$DATAROOT/` every 3 days.
- should help to scrub failed attempts.
- removes an unused variable `RUNDIR` defined in `config.base`

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- The segment of the change was tested in an offline shell script on some older RUNDIRs from previous experiments.

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved

**Review by DavidHuber-NOAA — APPROVED** [review]
LGTM

**Comment by CoryMartin-NOAA** [comment]
FYI I'm not sure this works properly. A brand new experiment today is failing in the `enkfgdascleanup` job. My hypothesis is that files are being deleted by other jobs running concurrently and causing the cleanup job to fail. I fear that the `find` command finds all the files first, then it goes through them to check the dates, and if the file is subsequently deleted (by a successful job), the cleanup will crash. But this is purely a hypothesis.

**Comment by aerorahul** [comment]
> FYI I'm not sure this works properly. A brand new experiment today is failing in the `enkfgdascleanup` job. My hypothesis is that files are being deleted by other jobs running concurrently and causing the cleanup job to fail. I fear that the `find` command finds all the files first, then it goes through them to check the dates, and if the file is subsequently deleted (by a successful job), the cleanup will crash. But this is purely a hypothesis.

hmm .. race conditions are the best.

**Comment by CoryMartin-NOAA** [comment]
With no other jobs running, a rocotoboot causes it to run to completion. So yeah I am 95% sure this is the root cause of the issue. The cleanup cannot run while any other job is working in the RUNDIRS

**Comment by aerorahul** [comment]
@CoryMartin-NOAA 
I will open a PR to revert this.

@RussTreadon-NOAA 
Would you be willing to comment out the 2 find and remove lines in `scripts/exglobal_cleanup.sh` in your PR #2700 and we can kick off the testing in it again?  Thanks!

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , An updated `exglobal_cleanup.sh` has been committed to `feature/rename_atm`.  Done at c1ef4b30.

**Comment by aerorahul** [comment]
The CI has been kicked off in #2700 on Hera.

**Pull request merged**
