### PR TITLE
Removes files module loading file no longer used by the GW

### LINKED ISSUE #2130: Eliminate module-setup.inc files
### What new functionality do you need?

The `*.inc` files in the modulefiles directory are redundant (and also not module files). We only support bash, so the `module-setup.csh.inc` one can just be discarded, while the functionality of `module-setup.sh.inc` should be added to `ush/module-setup.sh`.

### What are the requirements for the new functionality?

No more module-setup.*.inc files in `modulefiles/`

### Acceptance Criteria

- [ ] No more module-setup.*.inc files in `modulefiles/`
- [ ] Results unchanged

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by HenryRWinterbottom**
# Description
This PR addresses issue #2130. The following is accomplished:

- The following files are removed beneath `modulesfiles/`: `module-setup.csh.inc` and `module-setup.sh.inc`;
- The module `ush/module-setup.sh` is updated such that it now sources `ush/detect_machine.sh` to determine which supported platform the global-workflow is being execute on.

Resolves #2130

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
CI/CD will test changes.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by KateFriedman-NOAA — CHANGES_REQUESTED** [review]
Removals look fine, although their usage needs to be removed from scripts that use them still:
```
-bash-4.2$ grep module-setup * -r | grep inc
ush/load_fv3gfs_modules.sh:source "${HOMEgfs}/modulefiles/module-setup.sh.inc"
ush/load_ufsda_modules.sh:source "${HOMEgfs}/modulefiles/module-setup.sh.inc"
```
Pre-PR testing (either build, setup, or full runs) should generally be done on at least one platform. A full test would have run into failures pretty quick because of those scripts using the files that were just removed.

**Comment by aerorahul** [comment]
If there are no more uses of `module-setup.csh.inc` and `module-setup.sh.inc` in the global-workflow and they have been replaced with `module-setup.sh`, then this looks good to me.

**Review by aerorahul — APPROVED** [review]

**Comment by HenryRWinterbottom** [comment]
@aerorahul I am still trying to test this. I am waiting on https://github.com/NOAA-EMC/global-workflow/pull/2252 to be merged.

**Comment by HenryRWinterbottom** [comment]
@KateFriedman-NOAA @aerorahul Somehow the `detect_machine.sh` update never made it into GW. I updated this in order to get the scope of this PR to work correctly. As shown below, the cycles are completing now as expected.
```
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202103231200             gfsstage_ic                    55311814           SUCCEEDED                   0         1          11.0
202103231200                 gfsfcst                    55312032           SUCCEEDED                   0         1         290.0
202103231200    gfsatmprod_f000-f012                    55312118           SUCCEEDED                   0         1         188.0
202103231200                 gfsarch         druby://hfe06:36112          SUBMITTING                   -         0           0.0
202103231200              gfscleanup                           -                   -                   -         -             -
```

I am assuming that the CI/CD will handle the remainder of the platforms?

**Comment by WalterKolczynski-NOAA** [comment]
Please merge or rebase from current develop.

**Comment by HenryRWinterbottom** [comment]
@WalterKolczynski-NOAA Done.

**Comment by WalterKolczynski-NOAA** [comment]
Hera test will just sit until it returns from downtime.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Review by KateFriedman-NOAA — APPROVED** [review]
Approve pending successful completion of CI tests. Thanks @HenryWinterbottom-NOAA !

**Pull request merged**
