### PR TITLE
Fix eupd after GSI PR 602

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
# Description
https://github.com/NOAA-EMC/GSI/pull/602 was merged in without the subsequent script changes needed in the workflow. This PR fixes that.

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Build, cycled on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Kernel failed with exit 1, no core dump.

**Orion:**

`/work2/noaa/stmp/GFS_CI_ROOT/PR/1835/global-workflow/sorc/gsi_enkf.fd/install/bin/enkf.x`

**Comment by CoryMartin-NOAA** [comment]
@azadeh-gh are you having the same issue? I don't know why it looks like ozone diagnostic files are now missing `Observation_Operator_Jacobian_stind`...

**Comment by CoryMartin-NOAA** [comment]
@TerrenceMcGuinness-NOAA could you retry the test with this new commit? It uses a slightly older version of GSI. We think there might be an issue in the n-1 hash, but need to dig deeper to know for sure.

**Comment by azadeh-gh** [comment]
> @azadeh-gh are you having the same issue? I don't know why it looks like ozone diagnostic files are now missing `Observation_Operator_Jacobian_stind`...

@CoryMartin-NOAA I haven't seen this issue, but the task "enkfgdaseupd" failed in my experiment, since the "use_qsatensmean" is removed in GSI (accb07e), but still exists in "scripts/exgdas_enkf_update.sh".

**Comment by TerrenceMcGuinness-NOAA** [comment]
@CoryMartin-NOAA,  You can re-run the CI tests by simply making the necessary changes in the repo to the PR and/or to the files on the targeted platform and just remove all the labels and set them back to **"MACHINE"-Ready** and the CI framework will automaticlly rerun the tests in `$HOMEgfs/ci/cases` that are in your PR repo.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending CI tests

**Pull request merged**
