### PR TITLE
Stage atmospheric backgrounds and UFS cubed-sphere history files

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
# Description

This PR changes the G-W so that backgrounds for the atmospheric analyses are staged as UFS cubed-sphere history files rather than FMS restarts. The motivation being that FMS restarts include many data we don't need for the analyses and thus take up too much disk space/bandwidth.

This is a companion PR to GDASApp [#1236](https://github.com/NOAA-EMC/GDASApp/pull/1236) and JCB-GDAS [#19](https://github.com/NOAA-EMC/jcb-gdas/pull/19).

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES
- Does this change require a documentation update? NO

# How has this been tested?
- Build on Hera
- Cycling experiment on Hera
- GDASApp jjob tests 

# Checklist
- [ ] Any dependent changes have been merged and published
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
Install `DavidNew-NOAA:feature/cubed_sphere_bkg` at 018f24b9 on Hera.  Run JEDI based CI with the following results

**C96C48_ufs_hybatmDA**
All jobs successfully ran to completion
```
Hera(hfe01):/scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/prufsda$ rocotostat -d prufsda.db -w prufsda.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202402231800        Done    Jul 26 2024 09:56:20    Jul 26 2024 10:13:16
202402240000        Done    Jul 26 2024 09:56:20    Jul 26 2024 12:35:15
```

**C96_atmaerosnowDA**
All jobs successfully ran to completion
```
Hera(hfe01):/scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/praero$ rocotostat -d praero.db -w praero.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202112201200        Done    Jul 26 2024 10:45:08    Jul 26 2024 11:05:17
202112201800        Done    Jul 26 2024 10:45:08    Jul 26 2024 12:25:15
202112210000        Done    Jul 26 2024 10:45:08    Jul 26 2024 15:00:19
```

**C48mx500_3DVarAOWCDA**
All jobs run to completion except 20210324 18Z gdasatmanlprod, gdasarch, and gdascleanup.  Job gdasatmanlprod failed for the reason reported in issue #2669.  Job gdasarch did not run because it depends upon completion of gdasatmanlprod.  Likewise, gdascleanup did not run because it depends upon completion of gdasarch.  All JEDI based jobs successfully ran to completion.
```
Hera(hfe01):/scratch1/NCEPDEV/stmp2/Russ.Treadon/EXPDIR/prwcda$ rocotostat -d prwcda.db -w prwcda.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202103241200        Done    Jul 26 2024 10:44:37    Jul 26 2024 11:05:20
202103241800      Active    Jul 26 2024 10:44:37             -
```

**Review by RussTreadon-NOAA — DISMISSED** [review]
Looks good to me.  JEDI based CI passes.

Approve.

**Comment by DavidNew-NOAA** [comment]
Thanks, @RussTreadon-NOAA

**Review by WalterKolczynski-NOAA — DISMISSED** [review]
Conditionally approved.

**Comment by WalterKolczynski-NOAA** [comment]
Marking as draft until the dependencies are merged.

**Comment by DavidNew-NOAA** [comment]
Thanks @WalterKolczynski-NOAA . Just merged recent changes

**Comment by WalterKolczynski-NOAA** [comment]
> Thanks @WalterKolczynski-NOAA . Just merged recent changes

But the other two PRs are still waiting to be merged.

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA Ah, got it. Will try to get those moved along

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA Dependencies merged

**Comment by DavidNew-NOAA** [comment]
Are these ocean CI tests that are failing on Hera?

**Comment by WalterKolczynski-NOAA** [comment]
> Are these ocean CI tests that are failing on Hera?

Well, it isn't just an ocean test, but yes. There is a field missing from the background file:
```
unable to find mandatory variable aice_h in restart file ./ice.bkgerr_stddev.nc
```

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA OK, so I'm assuming this isn't a problem with this PR, since it doesn't have anything to do with sea ice?

**Comment by WalterKolczynski-NOAA** [comment]
I'll try running it again. Guillaume's PR just passed, so it should be working if you didn't change anything.

**Comment by WalterKolczynski-NOAA** [comment]
Now it's failing due to lack of space, I think.

**Comment by WalterKolczynski-NOAA** [comment]
> Now it's failing due to lack of space, I think.

Actually, a sysadmin killed all the CI running on Hera because we had three PRs building at once and it hammered the node. Going to relaunch a bit at a time.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by DavidNew-NOAA** [comment]
Thank you @WalterKolczynski-NOAA

**Pull request merged**
