### PR TITLE
Update to obsproc/v1.2.0 and prepobs/v1.1.0

### LINKED ISSUE #2291: GFSv16.3.15 - Update to obsproc.v1.2
### What new functionality do you need?

Update to `obsproc.v1.2` when it is introduced in operations. Also make related GSI change to turn GMI back on.

### What are the requirements for the new functionality?

- [x] Update `obsproc_ver` in version files in `dev/gfs.v16`
- [ ] Update `obsproc_ver` in version files in `develop`
- [x] Install `obsproc.v1.2` on R&D machines
- [ ] Uncomment GMI line `scripts/exglobal_atmos_analysis.sh` (commented out in https://github.com/NOAA-EMC/global-workflow/pull/1404).
- [x] Update ops version in RTD

### Acceptance Criteria

New version works everywhere.

### Suggest a solution (optional)

_No response_

### LINKED ISSUE #2840: Update to prepobs/v1.1.0
### What new functionality do you need?

Need `develop` to run with the new prepobs/1.1.0 version that was implemented into operations this past May.

Will need to update prepobs in conjunction with new obsproc version (issue #2291).

Operations issue #2837 will be taken care of first due to urgency.

### What are the requirements for the new functionality?

That the prepbufr file is produced without error.

### Acceptance Criteria

Invoking the prepobs/1.1.0 module works and the prepbufr file is generated successfully while also using the newer obsproc/v1.2.

### Suggest a solution (optional)

_No response_

### LINKED ISSUE #2844: Use a single spack.ver file
### What new functionality do you need?

Currently, there are `build.spack.ver` and `run.spack.ver` version files.  However, since the versions are not different when building or running, this should be reduced to a single `spack.ver` file and then allow the `{machine}.build.ver` and `{machine}.run.ver` files to source and use the needed versions from `spack.ver`.

### What are the requirements for the new functionality?

That `build.spack.ver` and `run.spack.ver` are combined into `spack.ver`.

### Acceptance Criteria

All module loads are identical and no downstream changes.

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR updates the `develop` branch to use the newer operational `obsproc/v1.2.0` and `prepobs/v1.1.0`. The obsproc/prepobs installs in glopara space on supported platforms use tags cut from the `dev/gfsv17` branches in the respective repos. The installation of `prepobs/v1.1.0` on WCOSS2 is called "gfsv17_v1.1.0" to help avoid GFSv16 users using it instead of the operational module.

Also, the `HOMEobsproc` path is updated to set an empty default for `obsproc_run_ver`. This both removes the need to set a default (and constantly update it, which is duplication) and avoid the unset variable error when the fcst jobs use their own load module script that does not know `obsproc_run_ver`:
```
export HOMEobsproc="${BASE_GIT:-}/obsproc/v${obsproc_run_ver:-}"
```

This PR also reverts the prepobs and fit2obs installs on MSU back to the glopara space from the temporary `/work/noaa/global/kfriedma/glopara` space installs.

Lastly, this PR also includes updates to complete issue #2844 (merge `build.spack.ver` and `run.spack.ver`).

Resolves #2291
Resolves #2840
Resolves #2844

# Type of change

Regular updates to upstream components

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)

# How has this been tested?

Cycled tests on WCOSS2 and Hera.

### CODE REVIEW

**Review by aerorahul — DISMISSED** [review]
looks ok

**Review by DavidHuber-NOAA — DISMISSED** [review]
Looks good.  I see that Jet is still using /lfs4 for Fit2Obs, but I think this is being covered in #2878, correct?

**Comment by KateFriedman-NOAA** [comment]
Awaiting install of `prepobs/v1.1.0` on MSU before CI tests should start.

**Comment by aerorahul** [comment]
Before tests are run, do you see an issue in perhaps combining `build.spack.ver` and `run.spack.ver` into a single `spack.ver` and updating the host specific build and run version files?
A little busy work, but small enough and relevant to the changes in this PR.
Thoughts?

**Comment by KateFriedman-NOAA** [comment]
> Looks good. I see that Jet is still using /lfs4 for Fit2Obs, but I think this is being covered in #2878, correct?

Yes, I believe @InnocentSouopgui-NOAA will be updating that path for Fit2Obs on Jet. They are likely also updating the prepobs path too but this PR will do that before their PR.

**Comment by KateFriedman-NOAA** [comment]
> Before tests are run, do you see an issue in perhaps combining `build.spack.ver` and `run.spack.ver` into a single `spack.ver` and updating the host specific build and run version files? A little busy work, but small enough and relevant to the changes in this PR. Thoughts?

Sure, I can do that in this PR. Stay tuned...

**Comment by KateFriedman-NOAA** [comment]
Will now combine changes for issue #2844 into this PR.

**Review by DavidHuber-NOAA — DISMISSED** [review]
*.spack.ver merge looks good!

**Review by aerorahul — DISMISSED** [review]
lgtm

**Comment by TerrenceMcGuinness-NOAA** [comment]
Looks like `git-lfs` failed when checking out MOM6 in gdas git submodule on Hera.
If it's not reproducible we can simply try again and reset the Ready-Hera label.

```
Submodule 'mom6/MOM6' (https://github.com/NOAA-EMC/MOM6) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6'
Cloning into '/scratch1/NCEPDEV/global/CI/2903/gefs/sorc/gdas.cd/sorc/soca/mom6/MOM6'...
Submodule 'pkg/CVMix-src' (https://github.com/mom-ocean/CVMix-src.git) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/CVMix-src'
Submodule 'pkg/GSW-Fortran' (https://github.com/mom-ocean/GSW-Fortran.git) registered for path 'sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/GSW-Fortran'
Cloning into '/scratch1/NCEPDEV/global/CI/2903/gefs/sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/CVMix-src'...
Cloning into '/scratch1/NCEPDEV/global/CI/2903/gefs/sorc/gdas.cd/sorc/soca/mom6/MOM6/pkg/GSW-Fortran'...
fatal: the remote end hung up unexpectedly
error: git-lfs filter-process died of signal 15
fatal: Unable to checkout 'cd66505007b1559d79cb158bd6dc018a3943c1e7' in submodule path 'sorc/gdas.cd/sorc/ufo'
fatal: Failed to recurse into submodule path 'sorc/gdas.cd'
```

**Comment by WalterKolczynski-NOAA** [comment]
```
Lmod has detected the following error: The following module(s) are unknown:
"fit2obs/1.1.2" "prepobs/1.1.0"
```

**Comment by KateFriedman-NOAA** [comment]
> ```
> Lmod has detected the following error: The following module(s) are unknown:
> "fit2obs/1.1.2" "prepobs/1.1.0"
> ```

Looking into it...

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
