### PR TITLE
Bug fix to enkf_chgres_recenter_nc.fd

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
**Description**

The vertical interpolation routine of `enkf_chgres_recenter_nc.fd` was rewritten to speed up processing on WCOSS2, and to eliminate variable run times. 

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

Tested using one canned case on WCOSS2. The test converts a (3072 x 1536) gaussian history file to (1536 x 768). The output file from the test was bit-identical to output file from the head of the `dev_v16` branch. My test directory is on Dogwood - /lfs/h2/emc/global/noscrub/George.Gayno/global_workflow.git/enkf_test

Part of #713.

### CODE REVIEW

**Comment by GeorgeGayno-NOAA** [comment]
Note - the fix was provided by Peter Johnsen of GDIT.

**Comment by aerorahul** [comment]
we should atleast try and run a similar test on Orion and Hera.
Is the dogwood test case portable (assuming the fix files etc are present locally)?

**Comment by GeorgeGayno-NOAA** [comment]
> we should atleast try and run a similar test on Orion and Hera. Is the dogwood test case portable (assuming the fix files etc are present locally)?

Yes, the test is portable. I can test on Orion and Hera this afternoon. Will someone do a cycled test?

**Comment by aerorahul** [comment]
I don't think a cycled test is really necessary to test the utility.

**Review by aerorahul — APPROVED** [review]
I have no objections or questions.

**Comment by aerorahul** [comment]
FYI @RussTreadon-NOAA

**Comment by GeorgeGayno-NOAA** [comment]
> > we should atleast try and run a similar test on Orion and Hera. Is the dogwood test case portable (assuming the fix files etc are present locally)?
> 
> Yes, the test is portable. I can test on Orion and Hera this afternoon. Will someone do a cycled test?

I repeated my test on Hera. As on WCOSS2, the code updates did not change results. The test ran in 196 seconds and the control ran in 228 seconds. So, there is some speed up, but not as much as on WCOSS2. My test directory is here - /scratch1/NCEPDEV/da/George.Gayno/global-workflow.git/enkf_test

**Comment by GeorgeGayno-NOAA** [comment]
I was willing to test on Orion as well. However, they are having disk problems.

**Comment by aerorahul** [comment]
> I was willing to test on Orion as well. However, they are having disk problems.

I think Hera is just fine.
Thanks for the test.  I will copy the test directory and try and create a smaller resolution case.

**Comment by GeorgeGayno-NOAA** [comment]
@aerorahul - for a stand-alone test case, use what is on Hera - /scratch1/NCEPDEV/da/George.Gayno/global-workflow.git/enkf_test

**Pull request merged**
