### PR TITLE
Update rocoto_viewer with python3 version from CROW

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
There was work on the CROW version of rocoto_viewer to update it to python3, remove the prod_utils dependency, and make some other updates.  This commit brings those changes to global-workflow.

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
I tried it out on Orion and it appears to work but I notice that metatasks don't collapse:

image

**Comment by WalterKolczynski-NOAA** [comment]
Weird, metatask folding _does_ work on WCOSS, but apparently not on Hera and Orion. I will look into it.

**Comment by WalterKolczynski-NOAA** [comment]
Metatask folding should work now.

**Review by KateFriedman-NOAA — APPROVED** [review]
Works on WCOSS-Dell, Hera, and Orion...including metatasks. Thanks @WalterKolczynski-NOAA !

**Pull request merged**
