### PR TITLE
Added ff coupled wave case  C48_S2SW for testing

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
**Description**

Adding a yaml file **C48_S2SW**, **C384_S2S** to the case CI directory for testing.
Added **C384_S2SW.pending** for latter.

This will be part of the PR and weekly split of cases with weekly cases ran automatically once a week.

**How Has This Been Tested?**

- [ ] Clone and Build tests on WCOSS Dell P3
- [ ] Cycled test on Orion
- [x] Forecast-only test on Hera and Orion with CI framework

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @TerrenceMcGuinness-NOAA  It's great to get waves included in the CI testing!

**Comment by TerrenceMcGuinness-NOAA** [comment]
Sure thing @JessicaMeixner-NOAA, Raul gave me the arguments for the run but I noticed that **idate** was wrong (**idate=2021032312**).  Is there a SDATE you would prefer?   I noticed on Orion `/work/noaa/global/glopara/data/ICSDIR/prototype_ICs/GEFS-NoahMP-aerosols-p8c` has a latest **SDATE** of `2018031500`.

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA I set up low resolution wave ICs for IDATE of 2021032312 
On hera they can be found here: 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/workflowtest/2021032312/wav/glo_500 
On orion they can be found here: 
 /work/noaa/global/glopara/data/ICSDIR/prototype_ICs//workflowtest/2021032312/wav/glo_500 

This is for S2SW the wave grid is glo_500 (5 deg global grid). 

There are corresponding C48 or C96 atm and 5 deg ocean/ice ICs. Please let me know if you have any other questions.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Ok, Looks like we have the ICs in place for C48 resolution (I simply changed **resdent** to 48 from 384 to make it valid -- see below)

```
(gfs_workflow) mterry (Orion-login-2) C48_S2SW $ rocotocheck -c 202103231200 -t gfscoupled_ic  -w C48_S2SW.xml -d C48_S2SW.db

Task: gfscoupled_ic
  account: nems
  command: /work2/noaa/global/mterry/global-workflow_forked/jobs/rocoto/coupled_ic.sh
  cores: 1
  cycledefs: gfs
  final: false
  jobname: C48_S2SW_gfscoupled_ic_12
  join: /work2/noaa/global/mterry/RUNTESTS/COMROT/C48_S2SW/logs/2021032312/gfscoupled_ic.log
  maxtries: 2
  name: gfscoupled_ic
  nodes: 1:ppn=1:tpp=1
  partition: orion
  queue: batch
  throttle: 9999999
  walltime: 00:15:00
  environment
    CDATE ==> 2021032312
    CDUMP ==> gfs
    COMROOT ==> /work/noaa/global/glopara/com
    DATAROOT ==> /work/noaa/stmp/mterry/RUNDIRS/C48_S2SW
    EXPDIR ==> /work2/noaa/global/mterry/RUNTESTS/EXPDIR/C48_S2SW
    HOMEgfs ==> /work2/noaa/global/mterry/global-workflow_forked
    NET ==> gfs
    PDY ==> 20210323
    RUN ==> gfs
    RUN_ENVIR ==> emc
    cyc ==> 12
  dependencies
    AND is satisfied
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_ctrl.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile1.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile2.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile3.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile4.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile5.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/gfs_data.tile6.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile1.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile2.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile3.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile4.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile5.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/gfs/C48/INPUT/sfc_data.tile6.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/ocn/500/MOM.res.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/ice/500/cice5_model_5.00.res_2021032312.nc is available
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest/2021032312/wav/glo_500/20210323.120000.restart.glo_500 is available

Cycle: 202103231200
  Valid for this task: YES
  State: active
  Activated: 2023-08-28 13:43:51 UTC
  Completed: -
  Expired: -

Job: 14804368
  State:  QUEUED (queued)
  Exit Status:  -
  Tries:  0
  Unknown count:  0
  Duration:  0.0
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
@JessicaMeixner-NOAA  Rahul was actually trying to setup a C384 case for S2SW.  Do we have a good SDATE in  `/work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflowtest` that works for C384?

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA Apologies I thought @aerorahul had asked me for low resolution ICs for CI testing, which is what I had provided before.    C384 is the atm resolution, what resolution of the wave model do you want for this test?    My recommendation is since atm is C384 that you use the GEFS configuration.  In which case, I'd recommend moving to EP* ICs versus using previous P8 ICs.    If you let me know the date and wave model resolution I can provide inputs.  If you want all components ICs, we'd likely need to stick to something that's already exiting for the other components.

**Comment by aerorahul** [comment]
@JessicaMeixner-NOAA 
Would using `2016070100` from the P8 IC's be ok for us to get started on setting up a weekly C384, 1/4 degree ocean+ice and P8 wave configuration? 
When the modeling team is ready to provide with a different test case that they wish to maintain as part of the global-workflow weekly test, we can make a swap easily.  
If you would rather have us wait till you are comfortable with providing a C384 equivalent test, we understand.

The dates are not really that critical at the moment, but I recognize your effort in providing tests ICs for the various resolutions at the same date of `2021032312`.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul If date doesn't matter, I'd recommend us grabbing some already created EP4a ICs instead of going back to P8 ICs and creating a wave IC for the GEFS grid.    @NeilBarton-NOAA It looks like 2021032400 is an IC date for EP4, I can put those in the workflowtest area on hera for the workflow team to create a test based on this.   Also since C384 is the GEFS resolution, if you have a preferred date or different source of ICs for this that you'd prefer let me know.

**Comment by aerorahul** [comment]
> @aerorahul If date doesn't matter, I'd recommend us grabbing some already created EP4a ICs instead of going back to P8 ICs and creating a wave IC for the GEFS grid. @NeilBarton-NOAA It looks like 2021032400 is an IC date for EP4, I can put those in the workflowtest area on hera for the workflow team to create a test based on this. Also since C384 is the GEFS resolution, if you have a preferred date or different source of ICs for this that you'd prefer let me know.

That sounds great.  I assume this test will run out of the box in the workflow; i.e. there is no need for any manual edits in the configs after `setup_expt.py`.

**Comment by JessicaMeixner-NOAA** [comment]
> > @aerorahul If date doesn't matter, I'd recommend us grabbing some already created EP4a ICs instead of going back to P8 ICs and creating a wave IC for the GEFS grid. @NeilBarton-NOAA It looks like 2021032400 is an IC date for EP4, I can put those in the workflowtest area on hera for the workflow team to create a test based on this. Also since C384 is the GEFS resolution, if you have a preferred date or different source of ICs for this that you'd prefer let me know.
> 
> That sounds great. I assume this test will run out of the box in the workflow; i.e. there is no need for any manual edits in the configs after `setup_expt.py`.

We'd have to modify the coupled_ic input if you'd like for that to be the case.  Do you want the P8 ICs then?  Are the C48 wave ICs and set-up not going to be used for any workflow tests?

**Comment by aerorahul** [comment]
> > > @aerorahul If date doesn't matter, I'd recommend us grabbing some already created EP4a ICs instead of going back to P8 ICs and creating a wave IC for the GEFS grid. @NeilBarton-NOAA It looks like 2021032400 is an IC date for EP4, I can put those in the workflowtest area on hera for the workflow team to create a test based on this. Also since C384 is the GEFS resolution, if you have a preferred date or different source of ICs for this that you'd prefer let me know.
> > 
> > 
> > That sounds great. I assume this test will run out of the box in the workflow; i.e. there is no need for any manual edits in the configs after `setup_expt.py`.
> 
> We'd have to modify the coupled_ic input if you'd like for that to be the case. Do you want the P8 ICs then? Are the C48 wave ICs and set-up not going to be used for any workflow tests?

The C48 IC's will be used for testing with every PR.
The C384 IC's will be used for weekly testing to ensure that that configuration is also tested and is in working order (on a weekly basis).  Testing at C384 on a per-PR basis is not possible.

The C48 and C384 configurations ideally should be identical with the exception of resolution (obviously) to ensure we are testing the same thing.

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul That is awesome.  Two quick questions: 
Is this a gefs or gfs free forecast test? 
Will both C48 and C384 tests with waves be added in this PR?

**Comment by aerorahul** [comment]
> 

GFS is the focus of this PR.
GEFS will be coming shortly (and ideally would be similar to GFS free-forecast configuration, but we understand those two would be different as development progresses)

If ICs at those resolutions include waves for free-forecast, then waves will be added in as well in the test suite.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks Rahul - I was confused by the C384 as it's GEFS's targeted resolution.  Since this is GFS targeted test, I'll proceed with getting ICs ready for something that will run out of the box.  In the meantime, there's an expectation that the C48 tests do run out of the box, so if there's any issue there please let me know.  I'll try to have the C384 gfs ff configuration to you and Terry mid week.

**Comment by NeilBarton-NOAA** [comment]
@aerorahul @JessicaMeixner-NOAA I put some EP4a ICs are on hpss at

/NCEPDEV/emc-marine/1year/Neil.Barton/ICs_2021032400.tar

Note, these are not the typical ocean restarts because EP4 initializes the ocean from ORAS5.

**Comment by aerorahul** [comment]
Thanks  @NeilBarton-NOAA 
This draft PR was just a quick way to find out if we can include C384-resolution type testing at a weekly cadence.
@TerrenceMcGuinness-NOAA will work on weekly testing in the next sprint and we will reach out to you all for ICs and configurations that you wish to be tested at a weekly basis.  We hope the same configurations can be tested at a lower resolution on a per PR basis.

An issue on weekly testing is forthcoming.

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA @aerorahul  until you upgrade to @NeilBarton-NOAA ICs, here's two cases that will run out of the box on hera.  For orion you will have to move the IC created for the C384 case to the staged location.  This file is: 
/scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFSwave20210528v2/2016070100/wav/glo_025/20160701.000000.restart.glo_025

I believe this becomes a yaml file /ci/cases/C48_S2SW.yaml as 
```
experiment:
  type: gfs
  mode: forecast-only

arguments:
  pslot: ${pslot}
  app: S2SW
  resdet: 48
  comrot: ${RUNTESTS}/COMROT
  expdir: ${RUNTESTS}/EXPDIR
  idate: 2021032312
  edate: 2021032312
  yaml: ${HOMEgfs_PR}/ci/platforms/gfs_defaults_ci-updates.yaml
```

and a file /ci/cases/C384_S2SWA.yaml as 
```
experiment:
  type: gfs
  mode: forecast-only

arguments:
  pslot: ${pslot}
  app: S2SWA
  resdet: 384
  comrot: ${RUNTESTS}/COMROT
  expdir: ${RUNTESTS}/EXPDIR
  idate: 2016070100
  edate: 2016070100
  yaml: ${HOMEgfs_PR}/ci/platforms/gfs_defaults_ci-updates.yaml
```

although I'm not sure about the yaml line. 

Tests were completed on hera (not via ci) and output can be seen here: 

**G-w clone:**(of develop): /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow
**C48 output:** /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/s2swc48t02
**C48 helper script which contains exp setup info**:  /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow/workflow/coupled_48.sh
**C384 output**: /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/s2swaC384
**C384 helper script which contains exp setup info**: /scratch1/NCEPDEV/climate/Jessica.Meixner/gwtests/global-workflow/workflow/coupled_384.sh

Please let me know if you need any additional information from me.

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA just wanted to check in to see if you needed further information from me or if things were working for you for both the C48 and C384 tests?

**Comment by JessicaMeixner-NOAA** [comment]
@TerrenceMcGuinness-NOAA Will another PR with this capability be opened?

**Pull request closed without merging**
