### PR TITLE
Feature/gfsv16b

### PR DESCRIPTION
**Pull request by GuangPingLou-NOAA**
Add 6 bufr stations to the bufr sounding output per requests from Thailand Meteorological Department. This corresponds to Issue #142.
Change module paths from dev to prod for bufr sounding package and this relates to issue #145.

### CODE REVIEW

**Review by yangfanglin — APPROVED** [review]
looks good for me

**Review by RussTreadon-NOAA — COMMENTED** [review]
Kate requested this PR be deleted and a new PR be opened to merge these changes into feature/gfsv16b_updates.

**Comment by yangfanglin** [comment]
There is a conflict  now.  You need to resolve it.

**Comment by GuangPingLou-NOAA** [comment]
Will do that after two meetings this morning.

**Comment by GuangPingLou-NOAA** [comment]
Kate, in the current PR, it says there is a conflict need to be resolved. If I open another PR to feature/gfsv16b_updates, do I have resolve this conflict first? Or just open a PR and use my current Fork.

**Comment by KateFriedman-NOAA** [comment]
@GuangPingLou-NOAA Please sync your fork's branch with feature/gfsv16b_updates, resolve any conflicts in your sync merge on your end and then submit the PR to feature/gfsv16b_updates. Thanks!

See guidance on syncing your branch if needed here:
https://github.com/NOAA-EMC/global-workflow/wiki/Development-of-global-workflow#how-to-sync-fork-with-the-authoritative-repository

**Pull request closed without merging**
