### PR TITLE
Do Not Merge: Test ufs-utils from PR 815

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**

This is a draft PR to test https://github.com/ufs-community/UFS_UTILS/pull/815

Addresses global-workflow issue: #1775 

**DO NOT MERGE**

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs
Experiment C48_ATM_2974811c completed: *SUCCESS*
Experiment C48_ATM_2974811c Completed at Tue Aug 22 20:27:08 UTC 2023
with 48 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs
Experiment C48_ATM_2974811c completed: *SUCCESS*
Experiment C48_ATM_2974811c Completed at Tue Aug 22 20:27:08 UTC 2023
with 48 successfully completed jobs
Experiment C48_S2S_2974811c completed: *SUCCESS*
Experiment C48_S2S_2974811c Completed at Tue Aug 22 20:36:14 UTC 2023
with 18 successfully completed jobs

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA @GeorgeGayno-NOAA 
Running with PR 815 from ufs-utils resulted in a failure in the GSI analysis jobs on Orion for both the GDAS and GFS cycles.
I don't see an obvious error message and am suspecting a glitch on Orion.
I will let the tests on Hera continue to see if they complete successfully.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA @GeorgeGayno-NOAA 
I checked the tests on Hera and they do seem to be progressing without errors with the UFS-utils from PR 815.  I am sure now the failures on Orion in the GSI analysis jobs were a result of something with the system.  Looking at the timestamps on those failed logs, they appear to be at the same time, likely confirming my suspicion.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs
Experiment C48_ATM_2974811c completed: *SUCCESS*
Experiment C48_ATM_2974811c Completed at Tue Aug 22 20:27:08 UTC 2023
with 48 successfully completed jobs
Experiment C48_S2S_2974811c completed: *SUCCESS*
Experiment C48_S2S_2974811c Completed at Tue Aug 22 20:36:14 UTC 2023
with 18 successfully completed jobs
Experiment C96C48_hybatmDA_2974811c completed: *SUCCESS*
Experiment C96C48_hybatmDA_2974811c Completed at Tue Aug 22 22:51:10 UTC 2023
with 151 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Yes, I can see those jobs were CANCELED by Slurm.  Not sure what the root cause it yet.  Could have been done by the admins for up-and-coming maintenance or for account allocations or limits.  I'll keep you guys posted if I can find out.

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs
Experiment C48_ATM_2974811c completed: *SUCCESS*
Experiment C48_ATM_2974811c Completed at Tue Aug 22 20:27:08 UTC 2023
with 48 successfully completed jobs
Experiment C48_S2S_2974811c completed: *SUCCESS*
Experiment C48_S2S_2974811c Completed at Tue Aug 22 20:36:14 UTC 2023
with 18 successfully completed jobs
Experiment C96C48_hybatmDA_2974811c completed: *SUCCESS*
Experiment C96C48_hybatmDA_2974811c Completed at Tue Aug 22 22:51:10 UTC 2023
with 151 successfully completed jobs
Experiment C96_atm3DVar_2974811c completed: *SUCCESS*
Experiment C96_atm3DVar_2974811c Completed at Tue Aug 22 23:03:11 UTC 2023
with 89 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Tue Aug 22 18:44:23 UTC 2023 on hfe05
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Tue Aug 22 18:48:27 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Tue Aug 22 19:12:30 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:33 UTC 2023 for experiment C48_ATM_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:36 UTC 2023 for experiment C48_S2S_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:39 UTC 2023 for experiment C48_S2SA_gefs_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:45 UTC 2023 for experiment C96C48_hybatmDA_2974811c
Created experiment:            *SUCCESS*
Case setup: Completed at Tue Aug 22 19:12:48 UTC 2023 for experiment C96_atm3DVar_2974811c
Experiment C48_S2SA_gefs_2974811c completed: *SUCCESS*
Experiment C48_S2SA_gefs_2974811c Completed at Tue Aug 22 19:51:14 UTC 2023
with 3 successfully completed jobs
Experiment C48_ATM_2974811c completed: *SUCCESS*
Experiment C48_ATM_2974811c Completed at Tue Aug 22 20:27:08 UTC 2023
with 48 successfully completed jobs
Experiment C48_S2S_2974811c completed: *SUCCESS*
Experiment C48_S2S_2974811c Completed at Tue Aug 22 20:36:14 UTC 2023
with 18 successfully completed jobs
Experiment C96C48_hybatmDA_2974811c completed: *SUCCESS*
Experiment C96C48_hybatmDA_2974811c Completed at Tue Aug 22 22:51:10 UTC 2023
with 151 successfully completed jobs
Experiment C96_atm3DVar_2974811c completed: *SUCCESS*
Experiment C96_atm3DVar_2974811c Completed at Tue Aug 22 23:03:11 UTC 2023
with 89 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Is this expected ...

>mterry (Orion-login-1) 2021122100 $ grep FAILURE gdasanal.log | wc
 571178 5140602 38268926
mterry (Orion-login-1) 2021122100 $ grep WARNING gdasanal.log | wc
     97     684    7870
mterry (Orion-login-1) 2021122100 $ awk 'NR >= 575595 && NR <= 575600' gdasanal.log
73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
75:  READ_PREPBUFR:  ***WARNING*** invalid pressure pob=  0.000000000000000E+000 
75:   at k=           1  for obstype=t          kx=         180  c_station_id=
75:  0022958  reset pob=   1000000000.00000     
mterry (Orion-login-1) 2021122100 $

**Comment by aerorahul** [comment]
> Is this expected ...
> 
> > mterry (Orion-login-1) 2021122100 $ grep FAILURE gdasanal.log | wc
> > 571178 5140602 38268926
> > mterry (Orion-login-1) 2021122100 $ grep WARNING gdasanal.log | wc
> > 97     684    7870
> > mterry (Orion-login-1) 2021122100 $ awk 'NR >= 575595 && NR <= 575600' gdasanal.log
> > 73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
> > 73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
> > 73:  Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data
> > 75:  READ_PREPBUFR:  _**WARNING**_ invalid pressure pob=  0.000000000000000E+000
> > 75:   at k=           1  for obstype=t          kx=         180  c_station_id=
> > 75:  0022958  reset pob=   1000000000.00000
> > mterry (Orion-login-1) 2021122100 $

I am not sure @TerrenceMcGuinness-NOAA 
This is for the science team to verify if this output is expected.  Either way, the runs on Hera completed without an error, so I am confident the Orion failures were machine related and these may not be relevant to the failure.

**Comment by CatherineThomas-NOAA** [comment]
Thanks for setting up these tests @aerorahul.  Can you or @TerrenceMcGuinness-NOAA point me to the full log for the Orion failure?  I don't think it's related to this PR but I'd like to check out the antenna correction error.

**Comment by aerorahul** [comment]
> 

Failed logs on Orion at:
/work2/noaa/stmp/GFS_CI_ROOT/PR/1818/RUNTESTS/COMROT/C96_atm3DVar_2974811c/logs/2021122100/gdasanal.log
/work2/noaa/stmp/GFS_CI_ROOT/PR/1818/RUNTESTS/COMROT/C96_atm3DVar_2974811c/logs/2021122100/gfsanal.log

**Comment by TerrenceMcGuinness-NOAA** [comment]
Let's set off the Orion CI tests again since it's been a full day after the maintenance updates.

**Comment by aerorahul** [comment]
Closing this PR as testing has concluded.

**Comment by CatherineThomas-NOAA** [comment]
> 73: Apply_AntCorr(FAILURE) : Input iFOV inconsistent with AC data

These errors in the Orion log are from a problem with the CRTM installation.  As pointed out by @emilyhcliu, the MHS MetOp-C coefficient file is incorrect.  It only contains header information:
```
Orion-login-4[4] cthomas$ pwd
/apps/contrib/NCEP/libs/hpc-stack/intel-2018.4/crtm/2.4.0/fix
Orion-login-4[5] cthomas$ ls -l mhs*
-rw-r----- 1 8536 noaa-hpc 11396 Feb  4  2022 mhs_metop-a.SpcCoeff.bin
-rw-r----- 1 8536 noaa-hpc 49212 Feb  4  2022 mhs_metop-a.TauCoeff.bin
-rw-r----- 1 8536 noaa-hpc 11396 Feb  4  2022 mhs_metop-b.SpcCoeff.bin
-rw-r----- 1 8536 noaa-hpc 49212 Feb  4  2022 mhs_metop-b.TauCoeff.bin
-rw-r----- 1 8536 noaa-hpc   492 Feb  4  2022 mhs_metop-c.SpcCoeff.bin
-rw-r----- 1 8536 noaa-hpc 49212 Feb  4  2022 mhs_metop-c.TauCoeff.bin
```
Which repo should I open an issue under to get this fixed?

**Comment by aerorahul** [comment]
seems like an installation issue with CRTM.
hpc-stack seems relevant.

**Pull request closed without merging**
