### PR TITLE
Make wxflow links static instead of from link_workflow

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
Commits symlinks to the repo for wxflow instead of relying on link_workflow to create them. This will allow testing in the ci or workflow directory without needing to run an otherwise unnecessary link_workflow first.

# Type of change
- [ ] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [x] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [x] This change is covered by an existing CI test or a new one has been added
- [x] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
lgtm

**Comment by WalterKolczynski-NOAA** [comment]
Failed because the fix for the gefs extractvars dependency is in #2928

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WalterKolczynski-NOAA !

**Comment by TerrenceMcGuinness-NOAA** [comment]
Jenkins controller was down yesterday.  Clearing the Running label.  Connection to the controller  has been re-established for Hera.  CI can restart for Hera now.

**Review by DavidHuber-NOAA — APPROVED** [review]

**Pull request merged**
