### PR TITLE
Adding WAFS jobs to GFSv16

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
- Update WAFS tag to gfs_wafs.v6.0.3 in Externals.cfg and checkout.sh.
- Add new gfs jobs (none for gdas) to setup scripts:
-- gfswafs
-- gfswafsgcip
-- gfswafsgrib2
-- gfswafsgrib20p25
-- gfswafsblending
-- gfswafsblending0p25
- Update to build_gfs_wafs.sh to remove machine-specific if-blocks.
- Added job/rocoto scripts for each job
- Added config for each job with needed workflow manager level variable settings
- Added new jobs to config.resources
- Added two new module loads to module_base.wcoss_dell_p3
- Added WAFSF to both config.base* configs for setup script parsing. Set it in config.base. Variable in config.post will pick up config.base value at runtime. Default is NO in emc config and YES in nco config.
- Added SENDDBN_NTC to both config.base* configs. Default is NO in emc config and YES in nco config.

Also:
- bug fix in hpssarch_gen.sh to remove extra "}"

Dependencies:
- gfswafs <-- gfspost metatask complete
- gfswafsgcip <-- gfspost metatask complete
- gfswafsgrib2 <-- gfspost metatask complete
-- gfswafsblending <-- gfswafsgrib2 complete
- gfswafsgrib20p25 <-- gfspost metatask complete
-- gfswafsblending0p25 <-- gfswafsgrib20p25 complete

Caveats/additional work to do:

1. WAFS only supported in global-workflow on WCOSS-Dell. WAFS package also supports Hera and Orion though.
2. No UK data available in production yet so blending0p25 job produces nothing. Will need to update/retest when data is available under /dcom.
3. From Yali today: "NCO dataflow group just notified us FAA is requesting more data than what we have. So grib2 WAFS package needs to be updated on script level when we get confirmation from FAA."

Testing: Ran tests on WCOSS-Dell and used v16rt2 output as input for testing (via symlinks in comrot). Ran setup scripts to test EXPDIR/xml generation. Ran all six jobs (rocotoboot) and provided logs/output for Yali to inspect on Orion.

Notes for users:
1. Need GTG UPP for WAFS; run checkout.sh with "-o" flag to get GTG UPP checked out with regular UPP code.
2. Set HOURLY=YES when hourly post output is available. Currently set to NO in WAFS configs.
3. Set WAFSF=YES in config.base.

------

Thanks for all your help @YaliMao-NOAA and @WenMeng-NOAA !

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
If these changes work in your test and reproduce v16rt2, merge.   I can not comment further without testing myself.

**Review by YaliMao-NOAA — APPROVED** [review]
Since the log files and data outputs look good, this pull request is good to go.

**Review by yangfanglin — APPROVED** [review]
There are a lot of changes.  Great job.  Now we have a lot of small wafs jobs under rocoto/jobs.  It is not desirable but there is no other option if we need to mimic operation.

**Comment by KateFriedman-NOAA** [comment]
Thanks for the approvals! Submitting this PR.

**Pull request merged**
