### PR TITLE
update GDASApp hash to d34f616

### LINKED ISSUE #1505: Update GDASApp hash to fully exercise UFS-DA functionality
**Description**
The GDASApp hash needs to be updated to exercise the UFS-DA functionality recently merged into g-w.

**Requirements**
g-w `develop` should clone the current head, [d34f616](https://github.com/NOAA-EMC/GDASApp/commit/d34f616f5f48b3db0b15dd34687d70d54a087614), of GDASApp.

**Acceptance Criteria (Definition of Done)**
Update the GDASApp hash in `Externals.cfg` and `checkout.sh` to [d34f616](https://github.com/NOAA-EMC/GDASApp/commit/d34f616f5f48b3db0b15dd34687d70d54a087614)

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
Recent g-w PRs have enhanced UFS-DA functionality.   To fully exercise this enhanced functionality the GDASApp hash in `Externals.cfg` and `sorc/checkout.sh` needs to be updated.   This PR updates the GDASApp hash in both files.

Fixes #1505

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
- [x] Clone and Build tests on Hera

`feature/update_gdasapp` has been cloned on Hera and `./checkout.sh -u` executed.   `git status` in `gdas.cd` confirms that hash [d34f616](https://github.com/NOAA-EMC/GDASApp/commit/d34f616f5f48b3db0b15dd34687d70d54a087614) was checked out.   This is correct.
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]

**Comment by aerorahul** [comment]
@RussTreadon-NOAA 
I assume we should merge this asap to go with the series of Atm UFS-DA PRs from last week.

**Comment by aerorahul** [comment]
> @RussTreadon-NOAA I assume we should merge this asap to go with the series of Atm UFS-DA PRs from last week.

doh. you said so in the PR description. merging now.

**Comment by RussTreadon-NOAA** [comment]
Yes, @aerorahul , a merge of this PR before #1421 would be much appreciated.   Doing so gives us a g-w `develop` hash which works for a wide variety of UFS-DA apps.    

We can work on updating GDASApp and g-w to the new directory structure after PR #1421 enters `develop`.

**Comment by RussTreadon-NOAA** [comment]
You are fast, @aerorahul !   Thank you!

**Comment by CoryMartin-NOAA** [comment]
FYI this checks out `develop` of JEDI repos. Apologies to @RussTreadon-NOAA as I think only @aerorahul and I have previously discussed this. I suggest we revert, and use this instead: https://github.com/NOAA-EMC/GDASApp/commit/aaf7caa2b3e8b2c28b1ae5207166d2b85031e38c

This uses the most recent stable-nightly hashes combined with Russ's recent changes in develop.

**Comment by RussTreadon-NOAA** [comment]
OK.  Thanks @CoryMartin-NOAA .   This explains why I couldn't find the previous hash in GDASApp `develop`.   I need to look in `feature/stable-nightly`.

**Comment by CoryMartin-NOAA** [comment]
well `feature/stable-nightly` is "bad" and I need to fix it... it deletes and creates a new branch each time, so it doesn't retain the history. I / we got burned by this a few weeks ago where the workflow was unable to checkout the hash that was listed. I need to find the most elegant solution to this problem but I don't have it yet. Ideally it will automatically update no problem, but if there are conflicts in the CMakeLists.txt file, then the automation crashes. After talking with Rahul, we thought the workflow gets updated infrequently enough that we should probably manually 'tag' when the workflow is updated.

**Pull request merged**
