### PR TITLE
Consolidate UFS build

### LINKED ISSUE #745: Consolidate UFS build
**Description**
The UFS build currently requires a user to determine whether to build for atmosphere-only (ATMW) or coupled (S2SW). This is no longer necessary, as the coupled executable can be used for atmosphere-only runs. The two options build with different CCPP suite lists, so these lists need to be combined

**Requirements**
Removal of special switches for build_ufs and build_all.

**Acceptance Criteria (Definition of Done)**
A UFS executable that is usable for all global-workflow applications.

**Dependencies**
None

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**
Consolidates UFS build into a single executable. UFS will now always build with coupled components (S2SW app) and aerosols. Previous -a and -c options to build with coupled have been removed (-a was already defunct). The previous CCPP suite lists have been combined so all previously available suites will be available in the executable. This list likely needs to be trimmed to remove no longer supported options.

Fixes #745

**Type of change**
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**
- [x] Build on Hera
 
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
While this is mostly a maintenance issue, it is also much more convenient when testing to not have to deal with two different executables. I've actually been doing this manually when testing for a while.

**Comment by JessicaMeixner-NOAA** [comment]
Two questions about this PR: 
1. What about the lack of being able to run with 32bit=Y for ATM only?  Isn't this a significant increase in resources for those running atm-only at this time? 
2. There is now the APP=S2SWA in ufs-weather-model.  Should we be using this in the build in the workflow now?

**Comment by WalterKolczynski-NOAA** [comment]
> Two questions about this PR:
> 
> 1. What about the lack of being able to run with 32bit=Y for ATM only?  Isn't this a significant increase in resources for those running atm-only at this time?

As near as I can tell, we've been compiling 64-bit no matter what anyway. Might as well just condense it until mixed-mode FMS is ready.

> 2. There is now the APP=S2SWA in ufs-weather-model.  Should we be using this in the build in the workflow now?

Once we update to a UFS hash that allows this, yes. Unless we already are? In which case I can update this PR.

Also: what happened to putting A and W in alphabetical order?

**Comment by junwang-noaa** [comment]
If you are using the Prototype-p8b tag, the APP S2SWA is the configuration
with all the components. The S2SWA is the app name, changing the order of W
and A won't work.

**Review by XianwuXue-NOAA — COMMENTED** [review]
I like this changes. If you can improve the link_workflow.sh to only link the building components in *.cfg, for example: the exes in gsi is not needed in coupled mode, however, the current link_workflow.sh still link them to the exec folder but with broken links.

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA the work required for : https://github.com/NOAA-EMC/global-workflow/issues/736 will mean that we need different builds for ATMW (which is currently not working in the workflow) and for S2SWA

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good, thanks @WalterKolczynski-NOAA !

**Review by XianwuXue-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
We're going to have to keep different builds to support ATMW (though that is currently broken) as well as some future configurations, so killing this PR.

**Pull request closed without merging**
