### PR TITLE
Feature/gfsv16b

### PR DESCRIPTION
**Pull request by lgannoaa**
ecflow merge PR. 

There are known condition and upcoming changes from the individual package developer after the ecflow test on 9/26:
- forecast job resource may need to be changed.
- wave package resource is not finalized.
- wave job jgfs_wave_prdgen_bulls need fix a bug with silent fail.
- Some module not installed in production.
- obsproc packages not installed in production.
- post implementation tag is not finalized.
- wafs implementation tag is not finalized.

Jobs were tested with PDY 20200925, code managers from post, gempak, wave, and post process certified the test run result.

This merge included an update from high watermark testing result for the following jobs:
jgfs_atmos_analysis.ecf
jgfs_forecast.ecf
jgdas_atmos_analysis.ecf
jgdas_enkf_update.ecf
jgdas_enkf_ecen.ecf

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks like a lot of work to overhaul the ecflow scripts for GFSv16. Thanks Lin!

**Review by yangfanglin — COMMENTED** [review]
sorry I have a few other urgent tasks to deal with. I cannot review.  If needed, please add another reviewer. If it is working, it should be fine.

**Review by RussTreadon-NOAA — COMMENTED** [review]
Kate approved these changes.   She's the workflow code manager.   Her approval matters.   I assume these changes allow an ecflow driven parallel to reproduce the rocoto driven v16rt2,   Operations runs some parts of our rocoto workflow differently.   Operations also runs jobs not in our rocoto workflow.  I assume these have all been tested and verified as correct.   Job configurations should be consistent with the parts tested in the June rocoto HWM test.  As noted, minor adjustments to some job configurations may be needed.   ecflow job cards load modules.  I assume these module loads are correct.

**Comment by lgannoaa** [comment]
- I had a google meeting with Fanglin on 9/29 (yesterday). I show him the email sent by each of the code manager that certified my ecflow test results over the weekend of 9/25-9/27. Fanglin said it looks good.
- The analysis and forecast was tested in early stage of ecflow development using recommended utility compare_ncfile,py. On August 18, Russ and I tested it and find diff=0.0000000000 on compare_ncfile,py output.

**Comment by KateFriedman-NOAA** [comment]
Based on Lin's test results and since these files only impact the ecflow side of things this is approved. Submitting now. Thanks @lgannoaa !

**Pull request merged**
