### PR TITLE
Update readme 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
This updates the readme adding information about ICs and specific version of the workflow.  Adds a note about what is currently not working and copies information from the main wiki about crons and Rocoto

### CODE REVIEW

**Review by jiandewang — APPROVED** [review]
look nice, more information being added which is very helpful

**Review by KateFriedman-NOAA — COMMENTED** [review]
Unable time-wise to give an in-depth review but I'm glad to see this!

**Comment by JessicaMeixner-NOAA** [comment]
There was no testing for this as it's just an update to the README.

**Review by aerorahul — COMMENTED** [review]
👍

**Review by aerorahul — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @aerorahul and @jiandewang for the reviews!

**Pull request merged**
