### PR TITLE
Fix two bugs in release/gefs_v12 for GEFSv12.2.0

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
1) To make sure that the out_grd file has finished writing for ush
2) When rerun forecast job, it will link the wrong files

 On branch hotfix/gefs_v12.2.0
	modified:   scripts/exglobal_fcst_nemsfv3gfs.sh
	modified:   ush/wave_grid_interp_sbs.sh

Refs: #787

**Description**

**Type of change**

Please delete options that are not relevant.

- [ x ] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

  
**Checklist**

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA The changes are already implemented on WCOSS2 by NCO, and I want to update the repository to create a new tag.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA Could you merge it and create a new tag: gefs_v12.2.0-1 or update the existing tag: gefs_v12.2.0. thanks a lot in advance.

**Comment by WalterKolczynski-NOAA** [comment]
Tag gefs_v12.2.0-1 created.

**Comment by XianwuXue-NOAA** [comment]
Great. Thanks a lot.

**Pull request merged**
