### PR TITLE
GFSv16.0.7 changes from NCO

### LINKED ISSUE #238: Pull GFSv16.0.6[7] updates into release/gfsv16.0.0 and develop branches
Pull in updates from NCO for nwpara/gfsv16.0.6[7]:

Per request to speed up model output in soon-to-be GFS production updates are being made to parts of the system. Will document and pull in those updates to the release/gfsv16.0.0 branch.

Also pull in wave updates discussed in other thread.

- [x] ufs-weather-model tag update (GFS.v16.0.15)
- [x] EMC_gfs_wafs tag update (gfs_wafs.v6.0.19)
- [x] wave updates (config.wave)
- [x] wave updates (other)
- [x] resource updates

### LINKED ISSUE #279: Update EMC_verif-global tag to verif_global_v1.13.5
Update EMC_verif-global tag to verif_global_v1.13.5. 

Fixes bug in plotting of confidence interval bars in mean plots: https://github.com/NOAA-EMC/EMC_verif-global/issues/32

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
Updates from NCO post-hand-off for GFSv16.0.7:

- adjust forecast and post ecflow job resources to speed them up
- small fixes/adjustments to WAFS scripts (new WAFS tag: gfs_wafs.v6.0.19)
- fix to speed up gfs_bufr code in ops
- small fixes to wave scripts
- add nth_fv3_gfs to configs to differentiate thread values between gdas and gfs jobs
- remove KEEPDATA from config.base.nco.static per request from NCO (no config-level changes to KEEPDATA in ops)
- update EMC_verif-global tag to verif_global_v1.13.5 (Issue #279)

Ran quick cycled test on WCOSS-Dell to check changes didn't break anything.

Close #238 . Close #279 .

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
@RobertoPadilla-NOAA Can you double check the wave script changes from NCO? I'm merging them into global-workflow develop. Thanks!

**Review by RobertoPadilla-NOAA — COMMENTED** [review]
@KateFriedman-NOAA  Changes to the waves scripts look good to me.

**Comment by KateFriedman-NOAA** [comment]
Pulled further resource updates from forecast ecf scripts into release/gfsv16.0.0 from nwpara/gfsv16.0.7 and then into feature/issue238 branch. Added config.resources.nco.static to document ops resources for rocoto runs. Rerunning cycled test on WCOSS.

**Comment by KateFriedman-NOAA** [comment]
Reran 2.5 cycles on WCOSS-Venus with shorter forecast length for speed (120hrs). Uncovered two bugs related to FHMAX_GFS being less than the expected forecast length in both the bufr sounding (postsnd) and wavepostbndpnt jobs (both expected 180hrs). Added check of FHMAX_GFS in config.postsnd and config.wavepostbndpnt and reran jobs to get successful completion. Committed config updates to feature/issue238. Other jobs in test on WCOSS-Venus ran successfully.

**Pull request merged**
