### PR TITLE
Modify TRACKER job to use one JJOB JGLOBAL_ATMOS_CYCLONE_TRACKER

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**
A new JGLOBAL_ATMOS_CYCLONE_TRACKER is now created to handle both gdas/gfs verification TRACKER jobs.
Code manager certified the new job log and COM.

**How Has This Been Tested?**
Tested on retro parallel CDATE=2022011300. Code manager checked and certified.

  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

**Review by aerorahul — COMMENTED** [review]
Looks good to me.
@JiayiPeng-NOAA verified the output in the context of the parallel.
Q. is this expected in the v16.3.0 package since that is already w/ NCO.
Or should this be targeted for `develop` and the next implementation?

**Comment by JiayiPeng-NOAA** [comment]
Hi Rahul,
This update is not related to GFS operational TC track/genesis jobs, which
is under ens_tracker.v1.3.2.
But the calculation (The FORTRAN Code) is the same.
Thanks,
Jiayi

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by aerorahul** [comment]
@lgannoaa 
Can you explain why this is directed at `gfsv16.3.0`?

**Comment by lgannoaa** [comment]
> this expected in the v16.3.0 package since that is alread

It is my understanding this change will be on WCOSS2 and going forward. Maybe that is the wording used from @JiayiPeng-NOAA in try to say the same as I stated here.

**Comment by aerorahul** [comment]
Someone needs to explain clearly:
1. Is this particular J-Job called in ops from within the GFS.
2. If  the answer to 1 is No, then, why does this J-Job exist and who uses it and under what circumstances.
3. I understand it creates tracker files with storm location and intensity.  Where is the output of this job used in the parallel experimentation.

**Comment by lgannoaa** [comment]
> Someone needs to explain clearly:
> 
> 1. Is this particular J-Job called in ops from within the GFS.
> 2. If  the answer to 1 is No, then, why does this J-Job exist and who uses it and under what circumstances.
> 3. I understand it creates tracker files with storm location and intensity.  Where is the output of this job used in the parallel experimentation.

Although the JJob is part of the global workflow package, the only use is to run TRACKER. Therefore, I recommend the code manager @JiayiPeng-NOAA to help answer this question.

**Comment by JiayiPeng-NOAA** [comment]
Hi Rahul,
The answer to Question (1): NO. The TC track/genesis J-jobs in GFS workflow
will be run for GFSv17 retrospective runs, it's nothing to do
with GFS operational.
The answer to Question (2): see above.
The answer to Question (3): After the GFSv17 retrospective runs start, you
will see the output.
Thanks,
Jiayi

**Comment by aerorahul** [comment]
OK. Thanks @JiayiPeng-NOAA 
So this development is targeted for `develop` and not `release/gfs.v16.3.0`

**Comment by aerorahul** [comment]
@lgannoaa 
can we repoint these changes to `develop`?

**Comment by aerorahul** [comment]
release/gfs.v16.3.0 branch is frozen for new development.  
Please redirect to develop in preparation for v17 as time allows.
Closing.

**Pull request closed without merging**
