### PR TITLE
Update UFS-DA atmospheric prep script to be consistent with GDASApp update

### LINKED ISSUE #1262: import specific ufsda stage functions in ufsda atm prep script
**Description**
Specify the functions to import from ufsda.stage in UFS-DA atmospheric prep script.

**Requirements**
GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) removes stage from `ufsda/__init__.py`.   As a result, global-workflow `scripts/exgdas_global_atmos_analysis_prep.py` must specify the specific stage functions it uses.   GDASApp includes the option to run ctests with g-w.   Test `test_gdasapp_atm_jjob_var_prep` fails without updating `exgdas_global_atmos_analysis_prep.py`.

**Acceptance Criteria (Definition of Done)**
GDASApp g-w ctest `test_gdasapp_atm_jjob_var_prep` should pass.

**Dependencies**
Closure of this issue requires GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) to be merged into GDASApp `develop`.   Once this is done, the GDASApp has in g-w `sorc/checkout.sh` and `Externals.cfg` should be updated along with the change to `scripts/exgdas_global_atmos_analysis_prep.py`.

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) restores the ability of `run_jedi_exe.py` to execute UFS-DA applications, specifically `fv3jedi_var.x`.  Included in PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) is the removal of entry `ufsda.stage` from `ush/ufsda/__init__.py`.  Scripts which simply `import ufsda` must now specify the functions to from `ufsda.stage`.  

g-w issue #1262 documents the addition of the `ufsda.stage` line to `scripts/exgdas_global_atmos_analysis_prep.py`.  This change is required for g-w to successfully stage files used by the var and ensemble UFS-DA applications.

Fixes #1262

**NOTE:**  This PR depends upon the merger of GDASApp PR #278 into GDASApp `develop` followed by updating the GDASApp hash in g-w `Externals.cfg` and `sorc/checkout.sh`

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
- [x] Clone and Build g-w on Orion and Hera
- [x] Execute GDASApp ctests `test_gdasapp_atm_jjob_var` and `test_gdasapp_atm_jjob_ens`

**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
GDASApp built from GDASApp PR [278](https://github.com/NOAA-EMC/GDASApp/pull/278) within local clone of [RussTreadon-NOAA:feature/ufsda_stage](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_stage) on both Orion and Hera.    GDASApp ctests executed on both machines.  All ctests pass including `test_gdasapp_atm_jjob_var*` and `test_gdasapp_atm_jjob_ens*`.    

The g-w changes in this PR only impact atmospheric UFS DA.   GSI based DA is not altered by this PR.

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) has been opened for review.   g-w tests using [RussTreadon-NOAA:feature/ufsda_stage](https://github.com/RussTreadon-NOAA/global-workflow/tree/feature/ufsda_stage) confirm that the combination of GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) and g-w PR #1265 produce the desired behavior.

Once GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) is approved and merged into GDASApp [`develop`](https://github.com/NOAA-EMC/GDASApp/tree/develop), the GDASApp hash in `Externals.cfg` and `sorc/checkout.sh` will be updated in this PR.

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) was merged into GDASApp `develop` at [f7c23af](https://github.com/NOAA-EMC/GDASApp/commit/f7c23af6f7389c36817825ff9714be27d7068491).   Given this, the GDASApp hash in `Externals.cfg` and `sorc/checkout.sh` have been updated to the new head of GDASApp `develop`.   Done at [0744e22](https://github.com/NOAA-EMC/global-workflow/pull/1265/commits/0744e221ade1b0aa159aeec26fcb4e474baa7232).

This PR is now ready for review.

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA and @CoryMartin-NOAA , do you have time to review this PR?   Three files are changed:
1. `scripts/exgdas_global_atmos_analysis_prep.sh` - add line to import the ufsda functions used by the script.   This change is required due to the merger of GDASApp PR [#278](https://github.com/NOAA-EMC/GDASApp/pull/278) into GDASApp `develop` at [f7c23af](https://github.com/NOAA-EMC/GDASApp/commit/f7c23af6f7389c36817825ff9714be27d7068491).
2. `Externals.cfg` - update GDASApp hash to head of GDASApp `develop`, [f7c23af](https://github.com/NOAA-EMC/GDASApp/commit/f7c23af6f7389c36817825ff9714be27d7068491)
3. `sorc/checkout.sh` - same change as `Externals.cfg`

**Review by aerorahul — APPROVED** [review]
looks ok to me.

**Comment by RussTreadon-NOAA** [comment]
> looks ok to me.

Thank you @aerorahul!

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good, thanks @RussTreadon-NOAA

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
