### PR TITLE
Add 6 bufr stations to the bufr sounding output

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
Add 6 bufr stations to the bufr sounding output per requests from Thailand Meteorological Department. This corresponds to Issue #142. Change module paths from dev to prod for bufr sounding package and this relates to issue #145.

### CODE REVIEW

**Comment by GuangPingLou-NOAA** [comment]
Hi Kate,

The version is still the old one and my new commits on Friday were not in
there.
Thanks,
Guang Ping

**Comment by GuangPingLou-NOAA** [comment]
Oh, okay. they have not been merged to the upstream yet.

**Comment by KateFriedman-NOAA** [comment]
> Oh, okay. they have not been merged to the upstream yet.

@GuangPingLou-NOAA So the files in the "Files changed" tab of this PR are correct?

**Comment by GuangPingLou-NOAA** [comment]
Checking them out right now.

**Comment by GuangPingLou-NOAA** [comment]
Kate,
File "module_base.wcoss_dell_p3" was copied from Russ and there are lines
that may not have been intended for
my bufr sounding scripts, but they are used by Russ' components. See lines
39-46.

Russ, should I revert to the original or leave them as is?
Thanks!

**Comment by RussTreadon-NOAA** [comment]
Guang Ping,

I think Kate already has the necessary changes for module_base.wcoss_dell_p3
in her branch.  Please check.

Russ

**Comment by KateFriedman-NOAA** [comment]
@GuangPingLou-NOAA I have those module_base.wcoss_dell_p3 edits from Russ already so that's fine, that change can come in, I'll sort it out. Are all other changes good?

**Comment by GuangPingLou-NOAA** [comment]
That's fantastic! Everything else checked out fine.

Thanks, Kate and Russ!

**Review by GuangPingLou-NOAA — APPROVED** [review]
All changes look good, Thanks!

**Comment by KateFriedman-NOAA** [comment]
Thanks @GuangPingLou-NOAA ! Submitting this now.

**Pull request merged**
