### PR TITLE
Update ufs_utils hash that supports global_cycle with NoahMP.

### LINKED ISSUE #1275: Cold starts fail following enkf atmos/mem swap
**Expected behavior**

The workflow scripts should be able to take the gdasenkf cold start ICs from gdas_init and organize them in the expected memxxx/atmos structure.

**Current behavior**

When running setup_expt.py with --icsdir specified, the script fails with a message in the form
`FileNotFoundError: [Errno 2] No such file or directory: '<ICS_DIR>/enkfgdas.YYYYMMDD/CC/mem001/atmos/INPUT'`

**Machines affected**

Hera at least.

**To Reproduce**

Check out a fresh copy of ufs_utils and generate ICs to a directory `$ICSDIR`
Run setup_expt.py with `--icsdir $ICSDIR`

Alternatively, run setup_expt.py and setup_workflow.py without `--icsdir` and start the experiment.  The efcs jobs will fail.

**Context**

This seems to have started with PR #1201.

**Detailed Description**

**Additional Information**

**Possible Implementation**

Write a function to swap the location of memxxx and atmos when copying data from the `icsdir` to the `comrot` OR if the data has already been staged.  I accomplished this with the following line, performed in `$COMROT/enkfgdas.YYYYMMDD/CC/`:
```
set -eu
cwd=$(pwd)
cd atmos
for dir in mem*; do
   mkdir $dir/atmos
   mv $dir/{INPUT,*txt} $dir/atmos
   mv $dir $cwd/
done
cd $cwd
rm -rf atmos
```

This function would need to be intelligent enough to know it should only execute on the first cycle.

Alternatively, this could be addressed in gdas_init.

### LINKED ISSUE #1314: cycling with atmosphere DA fails with CCPP_SUITE for P8 due to lack of NoahMP support in global_cycle
**Expected behavior**
`cycled` mode should work for `CCPP_SUITE = FV3_GFS_v17_p8`.

**Current behavior**

This is the error when the model is initialized after the surface fields are updated.

```sh
     16: Stack trace terminated abnormally.
     22: forrtl: severe (174): SIGSEGV, segmentation fault occurred
     22: Image              PC                Routine            Line        Source            
     22: ufs_model.x        00000000063EB33A  Unknown               Unknown  Unknown
     22: libpthread-2.17.s  00002B47C7D455D0  Unknown               Unknown  Unknown
     22: ufs_model.x        0000000003B86550  module_sf_noahmpl        2566  module_sf_noahmplsm.f90
```

**Machines affected**
All

**To Reproduce**
Setup and run a cycled experiment with P8 CCPP suite and Thompson MP.
Cycled the atmosphere with the GSI and update the land surface with global_cycle.

global_cycle was built with the ufs-utils hash [8b990c06](https://github.com/ufs-community/UFS_UTILS/commit/8b990c060af2e13f0f5b2ea5b54aa2a7686333c1).

**Detailed Description**

Comparing the `sfc_data.tile1.nc` before the `global_cycle` update with the one after the update shows many differences via `ncdump -h`.
There are new or missing fields added or removed as part of `global_cycle`, is likely the reason for the model to fail.

There is an issue in ufs_utils https://github.com/ufs-community/UFS_UTILS/issues/549 that states that `global_cycle` does not work with `NoahMP`.

### PR DESCRIPTION
**Pull request by aerorahul**
**Description**
This PR:
- updates ufs_utils hash that contains upgrades to `global_cycle` that  updates only the greenness fraction.  This update expects a pre-existing surface restart file to be updated.
- corressponding updates to scripts that call `global_cycle` to stage the surface restart file to update.
- updates to `checkout.sh` and `Externals.cfg`.  Temporary pointers to [this](https://github.com/GeorgeGayno-NOAA/UFS_UTILS/tree/feature/cycle_noahmp) branch until `develop` in `ufs_utils` is updated.
- updates to `setup_expt.py` to force using the same `CCPP_SUITE` and `IMP_PHYSICS` for cycled and forecast-only modes and all apps.
- only builds utilities from ufs_utils that are used in the GFS application.

@GeorgeGayno-NOAA still needs to work with the land team to determine which fields (other than greenness fraction) need to be updated through `global_cycle`.

Depends on https://github.com/ufs-community/UFS_UTILS/pull/774
Fixes #1314 

Updating the UFS_utils hash will also resolve #1275 
Fixes #1275 

**Type of change**
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
- [X] Cycled test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
This will also fix #1275.

**Comment by GeorgeGayno-NOAA** [comment]
To clarify, this version of global_cycle is backwards compatible with runs that use the Noah LSM. So, you should see no differences when using the 'old' land model.  When using Noah-MP, only the greenness is currently updated.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by GeorgeGayno-NOAA — APPROVED** [review]

**Comment by CoryMartin-NOAA** [comment]
Did anyone notice issues with checksums not matching when running the fcst after `gdassfcanl` completes? (specifically `variable:slmsk`) Or is this likely some user error/config issue on my end?

**Comment by aerorahul** [comment]
I ran this branch for 4 1/2 cycles without an error.  So no, I did not notice it.  I don't see how this could come from a config error.

**Comment by CoryMartin-NOAA** [comment]
I'm perplexed, my old run has checksums in each variable for `sfc_data` but none for `sfcanl_data`. The new run has checksums for most variables in `sfcanl_data`.

**Comment by aerorahul** [comment]
in the "old" run, `sfc_data` is written by the model.  `sfcanl_data` is a very different file written by `global_cycle`.
In the "new" run, `sfcanl_data` is a copy of `sfc_data` and only fields are updated. 
I think what you are saying is that we need an update in `global_cycle`, that removes the `checksum` global attribute from it.

My confusion is, how is this failing for you now, when in the last 2 days, I have run several cycled runs and none of them failed.

**Comment by CoryMartin-NOAA** [comment]
@aerorahul I agree it is quite bizarre. Do you have a rotdir I can look at? My new one is on orion at: `/work2/noaa/da/cmartin/jkumm/rotdirs/jkumm_test2/gdas.20190621/06/atmos/RESTART`

**Comment by aerorahul** [comment]
On Hera:
last week `/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/ROTDIR/ufscyc`
today `/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/ROTDIR/ufss2s`

Both runs are with the branch in #1334

**Comment by GeorgeGayno-NOAA** [comment]
> in the "old" run, `sfc_data` is written by the model. `sfcanl_data` is a very different file written by `global_cycle`. In the "new" run, `sfcanl_data` is a copy of `sfc_data` and only fields are updated. I think what you are saying is that we need an update in `global_cycle`, that removes the `checksum` global attribute from it.
> 
> My confusion is, how is this failing for you now, when in the last 2 days, I have run several cycled runs and none of them failed.

The previous tag of `global_cycle` wrote an entirely new restart file (without the checksum attribute). The latest tag updates an existing restart file.

**Comment by CoryMartin-NOAA** [comment]
I think the issue could be the new physics/land model vs the old? I was using the previous configuration, and @aerorahul was using the new one

**Comment by aerorahul** [comment]
I created an issue in ufs-utils https://github.com/ufs-community/UFS_UTILS/issues/781

**Pull request merged**
