### PR TITLE
JJobs for cyclone tracker

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**

There are two CYCLONE_TRACKER jjobs to merge into GFS 16.3.

**How Has This Been Tested?**
Tested with tracker code manager.

  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes

### CODE REVIEW

**Comment by aerorahul** [comment]
@lgannoaa 
Can you explain why a `JGLOBAL_ATMOS_CYCLONE_TRACKER` won't work for GFS and GDAS cycles?

**Comment by lgannoaa** [comment]
Hi Rahul,
Jiayi who is the code manager. Requested the two jjobs.

Hi Jiayi,
Would you please help us understand?

Thanks,
Lin

**Comment by lgannoaa** [comment]
Hi Rahul and Lin,
The GFS and GDAS forecasts have different forecast dataset.
Each one will have its own tracker J-job for TC tracking, which will be
easier for the code management.
Thanks,
Jiayi

**Comment by aerorahul** [comment]
@JiayiPeng-NOAA 
Looking at  the j-jobs in this PR `JGDAS_ATMOS_CYCLONE_TRACKER` and `JGFS_ATMOS_CYCLONE_TRACKER`, the differences are:

Screen Shot 2022-07-21 at 4 58 42 PM

The core difference is 2 lines, which we can easily distinguish between the GFS and GDAS cycles without having to duplicate  160 lines in 2 files.  
I think you will agree that maintaining a single file with a single conditional is easier to maintain.

**Pull request closed without merging**
