### PR TITLE
Adds group size and nmem for GEFS

### LINKED ISSUE #1117: Introduce NMEM_EFCS for gfsefmn jobs
**Description**

Introduce NMEM_EFCS for gfsefmn jobs for ensemble workflow

**Requirements**

Introduce NMEM_EFCS to run 30 members gfsefmn jobs

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**
**Description**
Adds additional settings for ensemble forecast group size and number of members since gfs CDUMP (GEFS) will have different values than GDAS.

NMEM_EFCS sets the number of members for GEFS (default: 30)
NMEM_EFCSGRP_GFS sets the number of members per job for GEFS (default: 1)

Fixes #1117 

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
- [x] Tested on WCOSS2
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by XianwuXue-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA Please don't forget to reviewing my PR.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Separate PR, but now that many of these ex-scripts are being used for proto-GEFS, the script names should be updated from `exgdas_*` to `exglobal_*`.

**Comment by XianwuXue-NOAA** [comment]
> Separate PR, but now that many of these ex-scripts are being used for proto-GEFS, the script names should be updated from `exgdas_*` to `exglobal_*`.

OK. Thanks.

**Comment by XianwuXue-NOAA** [comment]
@aerorahul When you have time, could you review this PR? Thanks.

**Review by aerorahul — APPROVED** [review]
looks good.

**Comment by XianwuXue-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA Thanks a lot for your review.

**Comment by WalterKolczynski-NOAA** [comment]
Will merge later today.

**Pull request merged**
