### PR TITLE
Update JGDAS ENKF POST  job 

### PR DESCRIPTION
**Pull request by mingshichen-noaa**
# Description
 
NCO has requested that each COM variable specify whether it is an input or an output. This completes that process for the global jgdas enkf post job.

Refs https://github.com/NOAA-EMC/global-workflow/issues/2451

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
 
- Clone and build on RDHPCS
- Cycled tests on Hercules
- Forecast-only tests on Hercules
 
# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by DavidHuber-NOAA — CHANGES_REQUESTED** [review]
The J-Job needs to be here, too.

**Comment by WalterKolczynski-NOAA** [comment]
> The J-Job needs to be here, too.

This J-Job defines no COM variables

**Review by DavidHuber-NOAA — APPROVED** [review]
Ah, my bad.  Thanks @mingshichen-noaa @WalterKolczynski-NOAA.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @mingshichen-noaa !

**Pull request merged**
