### PR TITLE
Fix post parm links

### LINKED ISSUE #2259: parm/post incomplete after executing link_workflow.sh
### What is wrong?

`./link_workflow.sh` creates a `parm/post` directory with dead links and missing files.

### What should have happened?

`link_workflow.sh` should populate `parm/post` with all the files needed by g-w jobs.

### What machines are impacted?

Hera

### Steps to reproduce

1. clone g-w develop at ee6f536e
2. execute `build_all.sh -g`
3. execute `link_workfow.sh`

### Additional information

Below is a listing of a working copy of `parm/post` on Hera
```
Hera(hfe10):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/parm/post$ ls -lL
ls: cannot access optics_luts_WASO.dat: No such file or directory
ls: cannot access postxconfig-NT-GEFS-ANL.txt: No such file or directory
ls: cannot access postxconfig-NT-gefs-aerosol.txt: No such file or directory
ls: cannot access optics_luts_SUSO.dat: No such file or directory
ls: cannot access optics_luts_DUST.dat: No such file or directory
ls: cannot access optics_luts_SOOT.dat: No such file or directory
ls: cannot access optics_luts_SALT.dat: No such file or directory
ls: cannot access AEROSOL_LUTS.dat: No such file or directory
total 352
l????????? ? ?            ?      ?            ? AEROSOL_LUTS.dat
-rw-r--r-- 1 Russ.Treadon da   420 Jan 25 16:18 itag.jinja
-rwxr-xr-x 1 Russ.Treadon da 30200 Jan 25 13:56 nam_micro_lookup.dat
l????????? ? ?            ?      ?            ? optics_luts_DUST.dat
l????????? ? ?            ?      ?            ? optics_luts_SALT.dat
l????????? ? ?            ?      ?            ? optics_luts_SOOT.dat
l????????? ? ?            ?      ?            ? optics_luts_SUSO.dat
l????????? ? ?            ?      ?            ? optics_luts_WASO.dat
-rwxr-xr-x 1 Russ.Treadon da 32903 Jan 25 13:56 params_grib2_tbl_new
-rw-r--r-- 1 Russ.Treadon da   326 Jan 25 13:56 post_tag_gfs128
-rw-r--r-- 1 Russ.Treadon da   293 Jan 25 13:56 post_tag_gfs65
l????????? ? ?            ?      ?            ? postxconfig-NT-GEFS-ANL.txt
-rw-r--r-- 1 Russ.Treadon da 20725 Jan 25 13:56 postxconfig-NT-GEFS-F00.txt
-rw-r--r-- 1 Russ.Treadon da 26652 Jan 25 13:56 postxconfig-NT-GEFS.txt
-rw-r--r-- 1 Russ.Treadon da 18257 Jan 25 13:56 postxconfig-NT-GFS-ANL.txt
-rw-r--r-- 1 Russ.Treadon da 34026 Jan 25 13:56 postxconfig-NT-GFS-F00-TWO.txt
-rw-r--r-- 1 Russ.Treadon da 27823 Jan 25 13:56 postxconfig-NT-GFS-F00.txt
-rw-r--r-- 1 Russ.Treadon da  6205 Jan 25 13:56 postxconfig-NT-GFS-FLUX-F00.txt
-rw-r--r-- 1 Russ.Treadon da 15006 Jan 25 13:56 postxconfig-NT-GFS-FLUX.txt
-rw-r--r-- 1 Russ.Treadon da   677 Jan 25 13:56 postxconfig-NT-GFS-GOES.txt
-rw-r--r-- 1 Russ.Treadon da 50055 Jan 25 13:56 postxconfig-NT-GFS-TWO.txt
-rw-r--r-- 1 Russ.Treadon da 35051 Jan 25 13:56 postxconfig-NT-GFS.txt
l????????? ? ?            ?      ?            ? postxconfig-NT-gefs-aerosol.txt
-rw-r--r-- 1 Russ.Treadon da  8334 Jan 25 13:56 postxconfig-NT-gefs-chem.txt
-rw-r--r-- 1 Russ.Treadon da  5092 Jan 25 16:18 upp.yaml
```

Additionally, job gdasatmprod_f000-f002 fails to find the following file in `parm/post`
```
+ exglobal_atmos_products.sh[50]: wgrib2 -i -grib tmpfile_f000 /scratch2/NCEPDEV/stmp3/Russ.Treadon/TestExperiment/MonthSanityCheck/gdas.20230402/00//model_data/atmos/master/gdas.t00z.master.grb2f000
grep: /scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/develop/parm/post/global_1x1_paramlist_g2.f000: No such file or directory
```

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by WenMeng-NOAA**
# Description
Change symbolic links under parm/post with the latest version of develop branch from UPP repository and enable MERRA2 aerosol fields.

Resolves #2259 

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Setup script test on WCOSS2 and Hera with changes.

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
The git diff wasn't the most readable, so I copied the old and new lists for `parm/post` and did a comparison:

Out:
- postxconfig-NT-GEFS-aerosol.txt
- postxconfig-NT-GEFS-F00-aerosol.txt
- postxconfig-NT-GEFS-WAFS.txt

In:

- AEROSOL_LUTS.dat
- optics_luts_DUST.dat
- optics_luts_SALT.dat
- optics_luts_SOOT.dat
- optics_luts_SUSO.dat
- optics_luts_WASO.dat
- postxconfig-NT-gefs-aerosol.txt
- postxconfig-NT-GEFS-ANL.txt
- postxconfig-NT-gefs-chem.txt

Why is UPP inconsistent with capitalization?

**Comment by WalterKolczynski-NOAA** [comment]
Changing what files are in `parm/post` isn't going to do much unless the new files are then copied in the appropriate jobs.

**Comment by WenMeng-NOAA** [comment]
> postxconfig-NT-GEFS-ANL.txt
This file was removed for GEFS v13

> AEROSOL_LUTS.dat
optics_luts_DUST.dat
optics_luts_SALT.dat
optics_luts_SOOT.dat
optics_luts_SUSO.dat
optics_luts_WASO.dat

These legacy files will not be used for GFS v17 and GEFS v13.

The control files of aerosol and wafs in low case for GEFS v13 are not finalized. They are linked to the glowbal-workflow for developer's experiments via global-workflow.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
This fixes some of the broken symlinks in `parm/post`. This PR will not change any results, but the fixed links will be necessary later.

**Pull request merged**
