### PR TITLE
Add links to the ocean insitu obs processing tools

### LINKED ISSUE #1106: Add some of the insitu profiles as part of the cycling
This will require a few minor updates to the `g-w` and this repo. 

Leveraging the work that @AndrewEichmann-NOAA and Shastri did:

insitu-tmp

Blue is obs, red is analysis and green is the bkg ... Looks terrible but not a surprise.

**Current issue:**
- [x] #1131
- [x] #1132
- [ ] "over-fitting" Argo

### PR DESCRIPTION
**Pull request by guillaumevernieres**
# Description
Add links to the marine bufr to ioda converters for the marine insitu observations. 

- fixes https://github.com/NOAA-EMC/GDASApp/issues/1106
- waiting for https://github.com/NOAA-EMC/GDASApp/pull/1135 

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Tested on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
looks good to me.

**Comment by guillaumevernieres** [comment]
> looks good to me.

Thanks for the quick review @aerorahul , I'll un-draft and update the gdas.cd # once the companion gdasapp PR is merged .

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
@WalterKolczynski-NOAA , @aerorahul , I finished testing and just updated gdas.cd to the head of develop.

**Review by AndrewEichmann-NOAA — APPROVED** [review]
Looks good

**Comment by WalterKolczynski-NOAA** [comment]
Looks like WCOSS failed because stmp filled.

**Comment by WalterKolczynski-NOAA** [comment]
Restart files didn't get scrubbed properly from last attempt, so forecast started partway through. Will run through again once #2620 gets merged.

**Comment by WalterKolczynski-NOAA** [comment]
@guillaumevernieres please merge in develop with Russ's enabling of UFSDA on WCOSS and resolve the version conflict, then we'll rerun.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres please merge in develop with Russ's enabling of UFSDA on WCOSS and resolve the version conflict, then we'll rerun.



> @guillaumevernieres please merge in develop with Russ's enabling of UFSDA on WCOSS and resolve the version conflict, then we'll rerun.

Do we really need to rerun the ci @WalterKolczynski-NOAA ? The failure had nothing to do with the changes in this PR.

**Comment by WalterKolczynski-NOAA** [comment]
I was just going to rerun it on WCOSS

**Comment by WalterKolczynski-NOAA** [comment]
stmp still/again full on WCOSS2. This PR doesn't have any changes that should impact only WCOSS, so I'm just going to merge without the test passing.

**Comment by RussTreadon-NOAA** [comment]
FYI:  The files linked by this PR to `ush/` should be added to `.gitignore`.   

After executing `sorc/link_workflow.sh` the `bufr2ioda_insitu_profile_${platform}.py` files are flagged as _untracked files_ when we execute `git status`
```
Hera(hfe08):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/pr2641$ git status
On branch feature/update_gdasapp
Your branch is up to date with 'origin/feature/update_gdasapp'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ush/bufr2ioda_insitu_profile_argo.py
        ush/bufr2ioda_insitu_profile_bathy.py
        ush/bufr2ioda_insitu_profile_glider.py
        ush/bufr2ioda_insitu_profile_marinemammal.py
        ush/bufr2ioda_insitu_profile_tesac.py
        ush/bufr2ioda_insitu_profile_xbtctd.py
        ush/bufr2ioda_insitu_surface_altkob.py
        ush/bufr2ioda_insitu_surface_trkob.py

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by aerorahul** [comment]
Thanks @RussTreadon-NOAA for identifying the linked files that are untracked.

**Comment by RussTreadon-NOAA** [comment]
@aerorahul , I can add 
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ush/bufr2ioda_insitu_profile_argo.py
        ush/bufr2ioda_insitu_profile_bathy.py
        ush/bufr2ioda_insitu_profile_glider.py
        ush/bufr2ioda_insitu_profile_marinemammal.py
        ush/bufr2ioda_insitu_profile_tesac.py
        ush/bufr2ioda_insitu_profile_xbtctd.py
        ush/bufr2ioda_insitu_surface_altkob.py
        ush/bufr2ioda_insitu_surface_trkob.py
```
to `.gitignore` in PR #2641.  Is this acceptable or would you prefer a separate issue and PR?

**Pull request merged**
