### PR TITLE
Update snow obs processing job

### PR DESCRIPTION
**Pull request by jiaruidong2017**
# Description
This PR removes the `prepsnowobs` job, and add the IMS snow obs processing to the snow analysis job and it will only process the snow cover obs if the cycle is 00z. 

Resolves (https://github.com/NOAA-EMC/global-workflow/issues/2902)

# Type of change
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?
- Cycled test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Comment by jiaruidong2017** [comment]
FYI @CoryMartin-NOAA @TravisElless-NOAA

**Review by CoryMartin-NOAA — APPROVED** [review]
Thanks @jiaruidong2017 I think this makes things a lot tidier overall

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good. Approve pending successful completion of CI tests. Thanks @jiaruidong2017 !

**Review by DavidHuber-NOAA — APPROVED** [review]
Much simpler, thanks @jiaruidong2017!

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by jiaruidong2017** [comment]
@WalterKolczynski-NOAA It seems to me that the failure is unrelated to this PR. Any suggestions? Thank you.

**Pull request merged**
