### PR TITLE
Update gsi_utils.fd hash

### LINKED ISSUE #2597: update hash for gsi_utils.fd
### What new functionality do you need?

g-w PR #2592 identified unsafe coding in two [GSI-utils](https://github.com/NOAA-EMC/GSI-utils) files:
- `src/EnKF/gfs/src/getsigensmeanp_smooth.fd/getsigensmeanp_smooth_ncep.f90`
- `src/EnKF/gfs/src/recentersigp.fd/recentersigp.f90`

GSI-utils PR [#41](https://github.com/NOAA-EMC/GSI-utils/pull/41) added safeguards to the two files in question.  The `gsi_utils.fd` hash in g-w should be updated to GSI-utils `develop` at [0cdc3b4](https://github.com/NOAA-EMC/GSI-utils/commit/0cdc3b4f7ff8d4f0c54da3dab70ea2743bd68478)

### What are the requirements for the new functionality?

Clone and builid g-w with the updated `gsi_utils.fd` hash

### Acceptance Criteria

Update the `gsi_utils.fd` hash to [0cdc3b4](https://github.com/NOAA-EMC/GSI-utils/commit/0cdc3b4f7ff8d4f0c54da3dab70ea2743bd68478)

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
# Description
This PR updates the `gsi_utils.fd` hash to bring in updates which add safeguards to 
- `src/EnKF/gfs/src/getsigensmeanp_smooth.fd/getsigensmeanp_smooth_ncep.f90`
- `src/EnKF/gfs/src/recentersigp.fd/recentersigp.f90`

The safeguards are described in GSI-utils PR [#41](https://github.com/NOAA-EMC/GSI-utils/pull/41) and the associated issue.

Resolves #2597

# Type of change
- Maintenance - update submodule hash

# Change characteristics
- Is this a breaking change (a change in existing functionality)?  **NO**
- Does this change require a documentation update?  **NO**

# How has this been tested?
- [x] Clone, build, and cycle on Orion

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
C96C48_hybatmDA (GSI-based DA) and C96C48_ufs_hybatmDA (JEDI-based DA) CI initiated on Orion.  Initial half-cycle is complete.  DA jobs for the first full cycle are complete.  Only the gfs forecast remains running for the first full cycle.  The second full cycle for GSI-based DA has begun.  JEDI-based DA does not run a second full cycle.

Change this PR to _Ready for review_

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Comment by RussTreadon-NOAA** [comment]
Run second set of GSI and JEDI based CI tests using current head of g-w `develop`.  Compare atmf006.nc files from last cycle with those from GSI and JEDI CI tests using `feature/gsi_utils`.  Forecasts are identical.  As expected, the changes in this PR do not alter cycled results.

**Comment by TerrenceMcGuinness-NOAA** [comment]
All CI Cases passed on **Hercules**:

Not sure why Label and reporting failed.   The Controler removed the run record.
I'm going to increase the number retained runs on the project and update the label to PASSED by hand.

```
mterry (hercules-login-1) EXPDIR $ pwd
/work2/noaa/stmp/CI/HERCULES/2598/RUNTESTS/EXPDIR

mterry (hercules-login-1) EXPDIR $ ll
total 60K
drwxr-s--- 3 mterry stmp  12K May 14 18:11 C48_ATM_9e46637d
drwxr-s--- 4 mterry stmp 4.0K May 14 18:11 ..
drwxr-s--- 7 mterry stmp 4.0K May 14 18:12 .
drwxr-s--- 3 mterry stmp  12K May 14 19:54 C96C48_hybatmDA_9e46637d
drwxr-s--- 3 mterry stmp  12K May 14 20:22 C96_atm3DVar_9e46637d
drwxr-s--- 3 mterry stmp 4.0K May 14 21:59 C48_S2SWA_gefs_9e46637d
drwxr-s--- 3 mterry stmp  12K May 14 23:55 C48_S2SW_9e46637d

mterry (hercules-login-1) EXPDIR $ cat ../ci-run_check.log 
Experiment C48_ATM_9e46637d Completed 1 Cycles at Tue May 14 18:11:57 CDT 2024
with 20 successfully completed jobs
Experiment C48_ATM_9e46637d Completed: *SUCCESS*
Experiment C96C48_hybatmDA_9e46637d Completed 3 Cycles at Tue May 14 19:54:37 CDT 2024
with 120 successfully completed jobs
Experiment C96C48_hybatmDA_9e46637d Completed: *SUCCESS*
Experiment C96_atm3DVar_9e46637d Completed 3 Cycles at Tue May 14 20:22:43 CDT 2024
with 62 successfully completed jobs
Experiment C96_atm3DVar_9e46637d Completed: *SUCCESS*
Experiment C48_S2SWA_gefs_9e46637d Completed 1 Cycles at Tue May 14 21:59:43 CDT 2024
with 216 successfully completed jobs
Experiment C48_S2SWA_gefs_9e46637d Completed: *SUCCESS*
Experiment C48_S2SW_9e46637d Completed 1 Cycles at Tue May 14 23:55:49 CDT 2024
with 37 successfully completed jobs
Experiment C48_S2SW_9e46637d Completed: *SUCCESS*
```

**Pull request merged**
