### PR TITLE
Sync final GFSv16.1.6 updates into GFSv16.2.0 package

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
This PR syncs the final GFSv16.1.6 package updates (`release/gfs.v16.1.6`) into the GFSv16.2.0 package (`feature/ops-wcoss2`).

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA !

**Review by CatherineThomas-NOAA — COMMENTED** [review]
When we updated the release branch previously, @MichaelLueken-NOAA had us add the --init flag to the git submodule update for GSI (commit [87ed5d0](https://github.com/NOAA-EMC/global-workflow/commit/87ed5d0fafd724f8ec4811481f26c4967c50d372)).  Is this still needed?

**Comment by KateFriedman-NOAA** [comment]
> When we updated the release branch previously, @MichaelLueken-NOAA had us add the --init flag to the git submodule update for GSI (commit [87ed5d0](https://github.com/NOAA-EMC/global-workflow/commit/87ed5d0fafd724f8ec4811481f26c4967c50d372)). Is this still needed?

@CatherineThomas-NOAA Good catch! When I did the sync merge I failed to include that update when resolving the conflict. I just double-checked (cloned GSI with and without `--init`) and it's not needed for v16 since libsrc is still in that GSI version but for consistency we should retain that checkout flag. We will need it for develop for sure!

I have now put it in and committed it to my `feature/ops-wcoss2` fork branch for this PR @ fd3dc42d. I will make sure it's included when I do a similar sync merge of the `release/gfs.v16.1.7` branch into `feature/ops-wcoss2`. Thank you!

**Review by CatherineThomas-NOAA — APPROVED** [review]
Thanks @KateFriedman-NOAA, looks good now.

**Pull request merged**
