### PR TITLE
Update aerosol variable names and dust alpha

### LINKED ISSUE #887: Update GOCART configuration files for latest version and MAPL 2.22.0
With the latest version of MAPL and GOCART for p8.1 there is a needed update for the global-workflow configuration files in parm/chem.  This is related to https://github.com/ufs-community/ufs-weather-model/pull/1192 and https://github.com/ufs-community/ufs-weather-model/issues/1259

Files to be updated: 

`parm/chem/CAP.rc`

from: 
```bash 
    CAphobicCA.bc,CA.bc     bc1
    CAphilicCA.bc,CA.bc     bc2
    CAphobicCA.oc,CA.oc     oc1
    CAphilicCA.oc,CA.oc     oc2
```

to: 

```bash
   CA.bcphobic,CA.bc       bc1
   CA.bcphilic,CA.bc       bc2
   CA.ocphobic,CA.oc       oc1
   CA.ocphilic,CA.oc       oc2
```

and `parm/chem/AERO_HISTORY.rc`

from: 

```bash
  inst_aod.fields:     'CAEXTTAUCA.bc' , 'CA.bc'    , 'AOD_BC',
                       'CAEXTTAUCA.oc' , 'CA.oc'    , 'AOD_OC',
```

to: 
```bash
  inst_aod.fields:     'CA.bcEXTTAU'   , 'CA.bc'    , 'AOD_BC',
                       'CA.ocEXTTAU'   , 'CA.oc'    , 'AOD_OC',
```

### PR DESCRIPTION
**Pull request by bbakernoaa**
With https://github.com/ufs-community/ufs-weather-model/pull/1192 getting ready to be merged, an update needs to occur with the gocart configuration files for global-workflow.  This PR is in response to Issue #887 and should only be merged after #1192 is merged in the ufs-weather-model.

Fixes #887 
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by bbakernoaa** [comment]
There seems to be a problem with the libraries. We need to make sure that they are synced up with the ufs-weather-model 

trying some tests now

**Comment by bbakernoaa** [comment]
@WalterKolczynski-NOAA With the help of @JessicaMeixner-NOAA we found the issue that was causing the model to crash with aerosols in global-workflow

after generating the EXPDIR the config.aero file gets modified and has an invalid character.

inside the workflow directory the `parm/config/config.aero` has:
```
aero_conv_scav_factors='"*:0.3","so2:0.0","msa:0.0","dms:0.0","nh3:0.4","nh4:0.6","bc1:0.6","bc2:0.6","dust1:0.6","dust2:0.6","dust3:0.6","dust4:0.6","dust5:0.6","seas1:0.5","seas2:0.5","seas3:0.5","seas4:0.5","seas5:0.5"'
```

after generating the EXPDIR `config.aero` becomes:
```
aero_conv_scav_factors="'*:0.3','so2:0.0','msa:0.0','dms:0.0','nh3:0.4','nh4:0.6','bc1:0.6','bc2:0.6','dust1:0.6','dust2:0.6', 'dust3:0.6','dust4:0.6','dust5:0.6','seas1:0.5','seas2:0.5','seas3:0.5','seas4:0.5','seas5:0.5’"
```

specifically it is the last character: 

`"seas5:0.5"'` becomes `'seas5:0.5’"`

Still trying to track this down.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA With the help of @JessicaMeixner-NOAA we found the issue that was causing the model to crash with aerosols in global-workflow
> 
> after generating the EXPDIR the config.aero file gets modified and has an invalid character.
> 
> inside the workflow directory the `parm/config/config.aero` has:
> 
> ```
> aero_conv_scav_factors='"*:0.3","so2:0.0","msa:0.0","dms:0.0","nh3:0.4","nh4:0.6","bc1:0.6","bc2:0.6","dust1:0.6","dust2:0.6","dust3:0.6","dust4:0.6","dust5:0.6","seas1:0.5","seas2:0.5","seas3:0.5","seas4:0.5","seas5:0.5"'
> ```
> 
> after generating the EXPDIR `config.aero` becomes:
> 
> ```
> aero_conv_scav_factors="'*:0.3','so2:0.0','msa:0.0','dms:0.0','nh3:0.4','nh4:0.6','bc1:0.6','bc2:0.6','dust1:0.6','dust2:0.6', 'dust3:0.6','dust4:0.6','dust5:0.6','seas1:0.5','seas2:0.5','seas3:0.5','seas4:0.5','seas5:0.5’"
> ```
> 
> specifically it is the last character:
> 
> `"seas5:0.5"'` becomes `'seas5:0.5’"`
> 
> Still trying to track this down.

I think it's the same as the problem I just fixed: there is a smart-quote in there instead of a real quote. I fixed the double-quote, but it looks like the final single-quote is also a smart-quote. Common problem when copying from word/gdocs.

**Comment by bbakernoaa** [comment]
@WalterKolczynski-NOAA We also need to resync the dust inputs again.  Sorry.  We found an error that crops up at time near the poles with the new MAPL and the fix is updating the file.  No file name change just updated file that extends globally.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA We also need to resync the dust inputs again. Sorry. We found an error that crops up at time near the poles with the new MAPL and the fix is updating the file. No file name change just updated file that extends globally.

Is it ready now, or should we wait for your go-ahead?

**Comment by bbakernoaa** [comment]
From the Aerosols perspective it is ready to go 

@JessicaMeixner-NOAA Good on your end?

**Comment by WalterKolczynski-NOAA** [comment]
I meant the fix files. This PR doesn't seem to do anything about updating the model (though maybe Jessica's PR #897 that I just merged did that already).

**Comment by bbakernoaa** [comment]
I believe she does point to a newer hash there instead of the p8c tagged version.

@JessicaMeixner-NOAA can you confirm?

**Comment by bbakernoaa** [comment]
@WalterKolczynski-NOAA the checkout script does point to a newer hash that has the latest GOCART and MAPL 

`b97375c`

https://github.com/NOAA-EMC/global-workflow/pull/897/files

**Comment by JessicaMeixner-NOAA** [comment]
@WalterKolczynski-NOAA - PR #897 updated the hash of the ufs-weahter-model past  https://github.com/ufs-community/ufs-weather-model/pull/1192 so the model update has already been made.  This PR will update the configuration files.  As far as I"m aware, this PR is ready to be merged but we do need the fix files sync'd again, which I believe @bbakernoaa already gave the go ahead that those are ready.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
Fix files have been synchronized

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for the fix file updates @WalterKolczynski-NOAA !!

**Pull request merged**
