### PR TITLE
[DO NOT MERGE] Weekly High Resolution CI Tests Thursday Sep 21, 2023

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly High Resolution CI Tests Thursday Sep 21, 2023

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Orion needs the "dump" stuff too for these **C384C192** runs as is on Hera ...

```
Terry.McGuinness (hfe12) 1874 $ ls /scratch1/NCEPDEV/global/glopara/dump/gdas.20230402/
00  06	12  18

mterry (Orion-login-3) ~ $ ls /work/noaa/rstprod/dump/gdas.20230402/
ls: cannot access /work/noaa/rstprod/dump/gdas.20230402/: No such file or directory
```

**Comment by aerorahul** [comment]
@KateFriedman-NOAA @WalterKolczynski-NOAA Please take note:
```
❯❯❯ ls /work/noaa/rstprod/dump/gdas.20230401/
/bin/ls: cannot access /work/noaa/rstprod/dump/gdas.20230401/: No such file or directory
```
is the cause of the failure in `gdasprep` in `/work2/noaa/stmp/GFS_CI_ROOT/PR/1874/RUNTESTS/COMROT/C384_atm3DVar_2889c56c/logs/2023040200/gdasprep.log`

The starting observation dataset is from `gdas.20230402`.  I wonder how @CatherineThomas-NOAA is running an experiment on Orion with these ICs.

**Comment by CatherineThomas-NOAA** [comment]
@aerorahul I don't think we ever tried running with these ICs on Orion.  We mostly run our DA exps on Hera.

**Comment by WalterKolczynski-NOAA** [comment]
Necessary dump has been copied to Orion. Restarting test.

**Comment by WalterKolczynski-NOAA** [comment]
Is this back to the old collision problem, since the hash hasn't changed?

**Comment by TerrenceMcGuinness-NOAA** [comment]
So we just need to run the CI script again to get a new hash?

**Pull request closed without merging**
