### PR TITLE
HR4 GWD update

### PR DESCRIPTION
**Pull request by Qingfu-Liu**
# Description

This PR#2670 depends on ufs-weather-model PR#2290 (waiting to merge), fv3atm PR#836 and ccpp-physics PR#207.

This update is a combination of the gravity wave drag (GWD) versions from the NOAA/GSL and NOAA/PSL

The test results with this update can be seen in:
a) summer: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/hr3e50s
b) winter: https://www.emc.ncep.noaa.gov/gmb/jhan/vsdbw/hr3d11w
HR4GWD: same as HR3 but with the updated GWD

Compared to the HR2 and HR3, the HR4GWD shows a significant improvement especially in 500mb height AC and CONUS precipitation forecast skills. The HR4GWD reduces the cold and dry biases in the lower troposphere compared to the HR3. It also reduces the negative wind speed biases in the troposphere compared to the HR2.

This PR#2670 includes changes for four scripts, and new orographic data.
    The new orographic data temporarily stored at:
     /scratch1/NCEPDEV/global/Qingfu.Liu/git/GWD_SHong/APR2023_SSO
    and this new data should replace the old data: /scratch1/NCEPDEV/global/glopara/fix/ugwd/20231027

  Refs NOAA-EMC/fv3atm PR#836
  Refs ufs-community/ccpp-physics PR#207

# Type of change

- Physics upgrade for HR4 (waiting for merge PR#207 and PR#836)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published, "waiting for merges for PR#836 and PR#207" 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by aerorahul** [comment]
@Qingfu-Liu 
Please open an issue to update the fix files that are included in this issue description.
Also, please update the hash of the ufs-weather-model submodule when it is merged. 
We will begin testing then.

The changes in this PR look simple enough.  Tests will be required to pass before we can merge this PR as it involves an update to the hash of the ufs-weather-model.

**Comment by Qingfu-Liu** [comment]
@aerorahul Thank you very much. I am setting up a forecast only test. Once the test is complete, I will update this PR.

**Review by JongilHan66 — COMMENTED** [review]
do_gsl_drag_ss should be set to ".false" in config.fcst

**Review by JongilHan66 — COMMENTED** [review]
"psl_gwd_z0m_factor" should be renamed as "gwd_z0m_factor" in config.fcst and parsing_namelists_FV3*.sh, to be consistent with that change in NoahMP codes.

**Comment by Qingfu-Liu** [comment]
> "psl_gwd_z0m_factor" should be renamed as "gwd_z0m_factor" in config.fcst and parsing_namelists_FV3*.sh, to be consistent with that change in NoahMP codes.

@JongilHan66 Thank you very much. I saw this two days ago, but I am thinking to update it once the workflow test is successful.  I still have problem to run the workflow tests since the input.nml does not match the namelist reading

**Comment by Qingfu-Liu** [comment]
The changes of the NoahMP model (which are not used for HR4-GWD-update tests) have been retracted. All the regression tests are passed on Hera

**Comment by JessicaMeixner-NOAA** [comment]
New ugwd fix version will be: 20240624 @Qingfu-Liu

**Review by JongilHan66 — COMMENTED** [review]
I suggest to also add "export psl_gwd_dx_factor=6.0" after "export do_gwd_opt_psl=".true." line in config.fcst, so one can easily test the model with a different value of psl_gwd_dx_factor.

**Comment by JessicaMeixner-NOAA** [comment]
@JongilHan66 I think that means we're going to have to create a new PR building off this one (unless you have permissions on the branch to push updates). We'll need to update the model once the PR is merged and update the fix ver, so there will be other updates for that as well.

**Comment by JongilHan66** [comment]
> @JongilHan66 I think that means we're going to have to create a new PR building off this one (unless you have permissions on the branch to push updates). We'll need to update the model once the PR is merged and update the fix ver, so there will be other updates for that as well.

@JessicaMeixner-NOAA If necessary, please create a new PR.

**Comment by JongilHan66** [comment]
> > @JongilHan66 I think that means we're going to have to create a new PR building off this one (unless you have permissions on the branch to push updates). We'll need to update the model once the PR is merged and update the fix ver, so there will be other updates for that as well.
> 
> @JessicaMeixner-NOAA If necessary, please create a new PR.

@JessicaMeixner-NOAA If adding "export psl_gwd_dx_factor=6.0" in config.fcst requires a too much effort, I'd like to cancel my suggestion.

**Comment by JessicaMeixner-NOAA** [comment]
@JongilHan66 I don't think it's a huge effort to add your suggestion.  It would be great if someone from the physics team could take over this PR and make the suggestion you made as well as update the model and the fix ver.  If no one from the physics team is available to do this, please let me know.

**Comment by JongilHan66** [comment]
> @JongilHan66 I don't think it's a huge effort to add your suggestion. It would be great if someone from the physics team could take over this PR and make the suggestion you made as well as update the model and the fix ver. If no one from the physics team is available to do this, please let me know.

@JessicaMeixner-NOAA I don't think we have someone from the physics team to take over this PR.

**Comment by JessicaMeixner-NOAA** [comment]
@JongilHan66 I will take this over.

**Comment by JongilHan66** [comment]
> @JongilHan66 I will take this over.

@JessicaMeixner-NOAA Thanks very much, Jessica!!

**Comment by JessicaMeixner-NOAA** [comment]
This PR is being closed and continued in https://github.com/NOAA-EMC/global-workflow/pull/2732

**Pull request closed without merging**
