### PR TITLE
Add GEFS capability to setup_expt

### LINKED ISSUE #1576: Add initial GEFS support to experiment setup
**Description**
Update experiment setup to handle GEFS.

**Requirements**
Accept a new GEFS mode for forecast setup that uses a separate source directory for config files.

**Acceptance Criteria (Definition of Done)**
`setup_expt.py` that can do all existing modes as well as a new GEFS (forecast-only) mode.

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
**Description**

Allows GEFS experiment directories to be set up using `setup_expt.py`. This only creates the experiment directory; workflow generation will be added in a follow-up PR.

To facilitate this, a new positional argument is added in the first position to specify which system to set up: `gfs` or `gefs`. If gfs is chosen, the second positional argument is to choose the mode, and allows the same values as before: `cycled` and `forecast-only`. If gefs is chosen, forecast-only is assumed and no second positional argument is required.

To allow both gfs and gefs configure files to exist in workflow concurrently, the `parm/config` directory contains two new directories: gfs and gefs. All of the old config files have been moved into the gfs directory. A few select config files have also been copied to the gefs directory. As yet, they are unmodified (except the changes noted below). These config files will be updated in a future PR so the modifications for GEFS are not hidden in the new file creation. The `yaml/defaults` is also copied over, but the contents were removed since GEFS will not be running its own analyses.

A couple variables have been renamed to be more appropriate for use in both systems: `NMEM_ENKF`, `NMEM_EFCS`, and `CASE_ENKF` are now `NMEM_ENS`, `NMEM_ENS_GFS`, and `CASE_ENS` respectively. Further,  `HOMEfv3gfs` were removed as unused.

Finally, resolution validation was extended to the ensemble resolution as well.

Fixes: #1576

**Type of change**

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**

- [x] Cycled on Orion
- [x] P8 S2SWA on Orion
- [x] Create GEFS experiment dir on Orion
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Note to reviewers: git has decided that for the file copied, the gefs versions are the "moved" ones and the gfs ones are the "new" ones.

Remaining shellcheck complaints are about config files that were copied.

**Review by aerorahul — APPROVED** [review]
looks good to me.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good!

**Review by XianwuXue-NOAA — APPROVED** [review]
Looks good to me. I ran it and created expdir successfully on WCOSS2

**Pull request merged**
