### PR TITLE
Feature/remove theia

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
Removal of Theia from system plus a bug fix for getic.sh.

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
@Hang-Lei-NOAA Please review the incoming changes to remove Theia from the system. I tested this in free-forecast mode and did not encounter any issues.

Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Hi, Kate,

I will test it for 2 cycles.

Thanks,
Hang

**Comment by KateFriedman-NOAA** [comment]
Awesome, thanks Hang!

**Comment by KateFriedman-NOAA** [comment]
@Hang-Lei-NOAA How goes the 2 cycle test? Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Hi, Kate,

I still need one more days. My Hera account had some problems. They fixed
it in Monday and it was closed yesterday.

Thanks,
hang

**Comment by KateFriedman-NOAA** [comment]
Ok thanks for the update!

**Comment by Hang-Lei-NOAA** [comment]
The cycling tests were going fine on Hera. I support merge.

**Comment by KateFriedman-NOAA** [comment]
Thanks for completing the PR @Hang-Lei-NOAA !

**Pull request merged**
