### PR TITLE
Reenable the minimization monitor on Hera

### LINKED ISSUE #2439: Reenable minimization monitor on Hera
### What new functionality do you need?

The Rocky 8 PR (#2421) disabled minmon on Hera as needed Perl libraries are missing on Rocky 8. Once the appropriate perl modules are in place, it should be reenabled.

### What are the requirements for the new functionality?

MinMon works on Hera.

### Acceptance Criteria

- [ ] Update workflow Perl version to one with the necessary libraries
- [ ] Remove section from `config.base` that turns off minmon on Hera

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
This allows the minimization monitor to run on Hera Rocky 8.

A missing perl module was added (List/MoreUtils.pm), but had to be installed under the perl/5.38.0 installation, thus that module needs to be loaded.

Resolves #2439 
Dependent on NOAA-EMC/gsi-monitor#129

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cycled test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Review by EdwardSafford-NOAA — APPROVED** [review]
Looks good to me.  Thanks!

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved.

**Comment by WalterKolczynski-NOAA** [comment]
While it needs to be made for stand-alone purposes, I don't think the GSI monitor update is needed for this PR since workflow handles loading the necessary module.

**Comment by DavidHuber-NOAA** [comment]
I updated the GSI-monitor hash to include the Perl module load and am now marking this ready for review.

**Review by aerorahul — APPROVED** [review]

**Pull request merged**
