### PR TITLE
Add UFSDA ATM var and ens files to hpssarch_gen.sh

### LINKED ISSUE #1628: Update hpssarch_gen.sh to handle differences between GSI and UFS based DA
**Description**
When cycling with UFSDA not all GSI-based DA output files are created.  This causes g-w HPSS archive jobs to fail.   It also means key UFSDA output files are not written to HPSS.  This issue is opened to address both of these problems by adding logic to `ush/hpssarch_gen.sh` to check for the existence of GSI-DA and UFSDA files prior to adding the files to the HPSS archive list.

**Requirements**
`hpssarch_gen.sh` should run without error for both GSI-DA and UFSDA parallels.

**Acceptance Criteria (Definition of Done)**
This issue may be closed when the above requirement is satisfied.

**Dependencies**
None at present

### PR DESCRIPTION
**Pull request by RussTreadon-NOAA**
**Description**
This PR adds UFSDA ATM var and ens files to `hpssarch_gen.sh`.   Logic is also added to check for the existence of GSI-EnKF DA specific output files before adding said files to the archive list.   With this change `hpssgen_arch.sh` works for both GSI and UFS based DA.

Fixes #1628

**Type of change**
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
- [x] Clone and Build tests on Hera
- [x] Cycled test on Hera
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
**Additional Hera cycled tests**
Copy `EXPDIR` and initial conditions from @KateFriedman-NOAA `verfiles` to my space and update to run under my username.   Point my `verfiles` at a `HOMEgfs` containing the updated `hpssarch_gen.sh` from this PR.   Start my `verfiles` from `20220101 18`.   A check of the `20220102 00` gdas and enkfgdas HPSS tarballs shows them to contain the same files as Kate's `verfiles`.   The `20220102 00` gfs cycle is still running.  I will update this PR with results from that comparison when the cycle finishes.    

Tests in the Hera `prufscom`, a UFSDA parallel with ATM var and ens components running confirms 
- gdas, enkfgdas, and gfs archive jobs run to completion without error
- HPSS tarballs contain the intended UFSDA output files

**Review by aerorahul — APPROVED** [review]
Looks good.
I am satisfied with the testing from @RussTreadon-NOAA

**Comment by RussTreadon-NOAA** [comment]
Thank you @aerorahul for the quick reply and approval!

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by RussTreadon-NOAA** [comment]
That was fast, @WalterKolczynski-NOAA.   Thank you!

**Pull request merged**
