### PR TITLE
[DO NOT MERGE] Weekly CI Tests Friday Nov 10, 2023

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Nov 10, 2023

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Link to **gfs_ctrl.nc** on Orion for case **C384_S2SWA** needs work

```
(gfs_workflow) mterry (Orion-login-4) C384_S2SWA_d8b6890c $ cat C384_S2SWA_d8b6890c_gfsstage_ic_201607010000_check.txt | grep exist
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/GEFS-NoahMP-aerosols-p8c_refactored/2016070100/atmos/gfs_ctrl.nc does not exist
      
(gfs_workflow) mterry (Orion-login-4) C384_S2SWA_d8b6890c $ ls /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/GEFS-NoahMP-aerosols-p8c_refactored/2016070100/atmos/gfs_ctrl.nc -l
lrwxrwxrwx 1 wkolczyn global 62 Oct 19 14:27 /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/GEFS-NoahMP-aerosols-p8c_refactored/2016070100/atmos/gfs_ctrl.nc -> GEFS-NoahMP-aerosols-p8c/2016070100/gfs/C384/INPUT/gfs_ctrl.nc
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
Configuration for name logic to  `*.restart.glo_025`  On Hera for **C384_S2SWA** needs work

```
(gfs_workflow) Terry.McGuinness (hfe07) C384_S2SWA_d8b6890c $ grep exist C384_S2SWA_d8b6890c_gfsstage_ic_201607010000_check.txt
      /scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/GEFSwave20210528v2_refactored/2016070100/wave/20160701.000000.restart.glo_025 does not exist
(gfs_workflow) Terry.McGuinness (hfe07) C384_S2SWA_d8b6890c $ ls -l /scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/GEFSwave20210528v2_refactored/2016070100/wave/20160701.000000.restart.*
lrwxrwxrwx 1 role.glopara global 118 Oct 28  2021 /scratch1/NCEPDEV/global/glopara/data/ICSDIR/prototype_ICs/GEFSwave20210528v2_refactored/2016070100/wave/20160701.000000.restart.gwes_30m -> /scratch1/NCEPDEV/climate/role.ufscpara/IC/GEFSwave20210528v2/2016070100/wav/gwes_30m/20160701.000000.restart.gwes_30m
```

**Comment by aerorahul** [comment]
Test gone rogue.  Closing.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@aerorahul @WalterKolczynski-NOAA This case is failing on Orion because we still need to get those config values assigned right in `congfig.base` for the staged wave files.

**Pull request closed without merging**
