### PR TITLE
Sync merge dev_v16 into GFSv16.3.0 package (low res testing updates)

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
**Description**

This PR sync merges recent changes in `dev_v16` into the GFSv16.3.0 package in `release/gfs.v16.3.0`. Incoming changes should not impact on-going high res v16.3.0 parallel testing and mostly revolve around low res testing and support on the R&Ds. See PR #932 for related details on what is in this PR.

Changes include:

1. small hack to run METplus `verif-global.v2.9.5` on the R&Ds
2. move prepobs module load from `jobs/rocoto/prep.sh` to `module_base` files (not used in ops)
3. add missing `COMINtcvital` to `config.base.emc.dyn`
4. resources updates for low resolution on WCOSS2, Hera, and Orion
5. replace `module purge` with `module reset` on Hera/Orion
6. update ecflow workflow generator and move it under `ush/ecflow`

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Cycled tests on WCOSS2, Hera, Orion were performed. See PR #932 for more details.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

Refs: #744 

FYI @lgannoaa @emilyhcliu

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
Removed MPICH setting in `config.resources.nco.static` after discussion with @aerorahul . Have left it in the `config.resources.emc.dyn` one for developers.

**Review by aerorahul — APPROVED** [review]
All the changes here seem to have an impact on R&D platforms.
This PR will allow the same branch to run on R&D machines and WCOSS2 for a variety of resolutions.

**Comment by aerorahul** [comment]
Should take a review from @lgannoaa

**Review by lgannoaa — DISMISSED** [review]
modulefiles/module_base.wcoss2.lua
I see the hardwired location as /lfs/h2/emc/global/save/emc.global/git/prepobs.
This solution does not work when developer need to test prep job using local installed prepobs package during debug. Recommended to remove this hardwire solution. Get base HOME location from config.base.

 
parm/config/config.fv3.emc.dyn
ecflow parallel workflow does not use this setup. Need developer to run a rocoto test job on high resolution to make related change in ecflow.


parm/config/config.resources.emc.dyn
ecflow parallel workflow does not using this setup. Need developer to run a rocoto test job on high resolution to make related change in ecflow.

workflow_generator/__init.py__ → ush/ecflow/__init.py__
workflow_generator/ecflow_setup/__init.py__ → ush/ecflow/ecflow_setup/__init.py__
Please put this file into gitignore list and remove it from commit

**Comment by aerorahul** [comment]
> modulefiles/module_base.wcoss2.lua I see the hardwired location as /lfs/h2/emc/global/save/emc.global/git/prepobs. This solution does not work when developer need to test prep job using local installed prepobs package during debug. Recommended to remove this hardwire solution. Get base HOME location from config.base.

This file is loaded in `load_fv3gfs_modules.sh`
If a developer wishes to debug w/ local install of `prepobs` package, they can comment the line in this file and provide the full path in `config.base`.  This is the same process for a developer to test any package that is not a system or central installed package.

> parm/config/config.fv3.emc.dyn ecflow parallel workflow does not use this setup. Need developer to run a rocoto test job on high resolution to make related change in ecflow.
> 
> parm/config/config.resources.emc.dyn ecflow parallel workflow does not using this setup. Need developer to run a rocoto test job on high resolution to make related change in ecflow.

These two should not impact NRT or retrospective parallels as they use the `nco.static` variant.

> workflow_generator/**init.py** → ush/ecflow/**init.py** workflow_generator/ecflow_setup/**init.py** → ush/ecflow/ecflow_setup/**init.py** Please put this file into gitignore list and remove it from commit

This file is not to be ignored.  This file is executed when the python package is invoked.

**Review by lgannoaa — APPROVED** [review]

**Pull request merged**
