### PR TITLE
Resolve IC filename mismatch and differentiate model component start date variables

### LINKED ISSUE #2865: gdasstage_ic and gdasfcst_seg0 disagree on staged filenames for ocean restarts
### What is wrong?

for a coupled 3dVar cycling experiment with cold starts for 2021032400 `gdasstage_ic` stages oceans restarts with m_prefix = 20210323.180000, but `gdasfcst_seg0` then looks for restarts with m_prefix = 20210324.0000.  Here's the error from `gdasfcst_sego`:

```
/bin/cp -p /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart/20210324.000000.MOM.res.nc /scratch1/NCEPDEV/stmp2/Jeffrey.S.Whitaker/RUNDIRS/C192coupled3dvar_test/gdas.2021032400/gdasfcst.2021032400/fcst.1385029/INPUT/MOM.res.nc
/bin/cp: cannot stat '/scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart/20210324.000000.MOM.res.nc': No such file or directory
```

and the relevant output from `gdasstage_ic`:

```
[[38;21m2024-08-27 15:16:21,927 - INFO     - file_utils  : Created /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart^[[0m
^[[38;21m2024-08-27 15:16:27,068 - INFO     - file_utils  : Copied /scratch2/BMC/gsienkf/whitaker/replayics/C192mx025//gdas.20210323/18/model/ocean/restart/20210323.210000.MOM.res.nc to /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart^[[0m
^[[38;21m2024-08-27 15:16:33,344 - INFO     - file_utils  : Copied /scratch2/BMC/gsienkf/whitaker/replayics/C192mx025//gdas.20210323/18/model/ocean/restart/20210323.210000.MOM.res_1.nc to /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart^[[0m
^[[38;21m2024-08-27 15:16:40,148 - INFO     - file_utils  : Copied /scratch2/BMC/gsienkf/whitaker/replayics/C192mx025//gdas.20210323/18/model/ocean/restart/20210323.210000.MOM.res_2.nc to /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart^[[0m
^[[38;21m2024-08-27 15:16:41,466 - INFO     - file_utils  : Copied /scratch2/BMC/gsienkf/whitaker/replayics/C192mx025//gdas.20210323/18/model/ocean/restart/20210323.210000.MOM.res_3.nc to /scratch2/BMC/gsienkf/whitaker/GWTESTS/COMROOT/C192coupled3dvar_test/gdas.20210323/18//model/ocean/restart^[[0m
```

### What should have happened?

gdasstage_ic stages ocean restarts with the same filenames expected by gdasfcst_seg0 for cold starts.

### What machines are impacted?

Hera

### Steps to reproduce

run a cycled 3DVar coupled atm/ocean experiment.  I ran

```
pslot="C192coupled3dvar_test" HPC_ACCOUNT="gsienkf" RUNTESTS="/scratch2/BMC/gsienkf/whitaker/GWTESTS" ICSDIR_ROOT="/scratch2/BMC/gsienkf/whitaker/replayics/C192mx025/"  ./workflow/create_experiment.py --yaml ci/cases/pr/C192mx025_3DVarAOWCDA.yaml
```

from /scratch2/BMC/gsienkf/whitaker/global-workflow-jswhit, with the patch from issue #2864 applied so that `gdasstage_ic`does not fail.

### Additional information

N/A

### Do you have a proposed solution?

no

### LINKED ISSUE #2890: The staging of the GFSv17 prototype IC's fails
### What is wrong?

The "refactored" staging of the IC's for the C384/025 GFSv17 prototype does not work anymore. 

### What should have happened?

...

### What machines are impacted?

All or N/A

### Steps to reproduce

Run this: [https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/gfsv17/C384mx025_3DVarAOWCDA.yaml](https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/gfsv17/C384mx025_3DVarAOWCDA.yaml)

### Additional information

...

### Do you have a proposed solution?

_No response_

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR resolves errors reported in issues #2865 and #2890. Upon investigation it was discovered that both issues were caused by the same thing = the IAU not being set to "NO" for cold-start. `DOIAU=YES` was set for the experiment but was not being set to "NO" for the cold-started first half-cycle staging job. Within `config.base` is an if-block to sets IAU variables for IAU being off but `DOIAU` was not forced to be "NO" and thus the prior "YES" setting was used to define the filenames in the staging job. I added `export DOIAU="NO"` within that if-block to force it off for cold-start.

Additionally, to manage the start dates for the various model components better, I created specific variables for atmos, ice, mediator, ocean, and wave cycle dates. Updated fcst scripts and the staging yamls to use them.

FYI @guillaumevernieres @apchoiCMD @jswhit 

Resolves #2865
Resolves #2890

# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

- Ran the staging and fcst jobs for the two cases that reported issues
- Ran the staging and fcst jobs for several CI tests on Hera

### CODE REVIEW

**Comment by apchoiCMD** [comment]
Thanks for your PR @KateFriedman-NOAA

**Review by WalterKolczynski-NOAA — DISMISSED** [review]

**Review by DavidHuber-NOAA — DISMISSED** [review]

**Comment by KateFriedman-NOAA** [comment]
Reviewing additional issue reported by @jswhit in #2865.

**Comment by WalterKolczynski-NOAA** [comment]
> Reviewing additional issue reported by @jswhit in #2865.

Are more changes needed, or is this ready to roll?

**Comment by KateFriedman-NOAA** [comment]
> Are more changes needed, or is this ready to roll?

Still trying to resolve the issue.

**Comment by KateFriedman-NOAA** [comment]
Discussed this with @aerorahul and @WalterKolczynski-NOAA yesterday. Will close this and rework the changes based on our conversation.

**Pull request closed without merging**
