### PR TITLE
Update GFS version to v16.3.22

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR updates the version for the "WAFS removal from GFS" release branch to v16.3.22.

Refs #2591

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
FYI @YaliMao-NOAA

**Review by aerorahul — APPROVED** [review]

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA Other than WAFS related script removal from GFS, UPP script needs to be modified and stop generating WAFS UPP products.
Should it be done in global-workflow or in UPP?
Thank you!

**Comment by KateFriedman-NOAA** [comment]
@YaliMao-NOAA In GFSv16 the UPP still owns all of its scripts so everything from the JJOB script level down is in the UPP tag for GFSv16. Therefore, we'll need an updated UPP tag that has removed the WAFS product generation. We'll then need to update the UPP tag in the workflow release branch, cut a new hand-off tag, and let NCO know.

Tagging @HuiyaChuang-NOAA for awareness.

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA Thank you. I will make a PR to UPP based on upp_v8.3.0 which is used by gfs.v16.3.22. You are expecting a new tag upp_v8.3.1 for it.

Tagging @WenMeng-NOAA for awareness

**Comment by KateFriedman-NOAA** [comment]
Sounds good, thanks @YaliMao-NOAA ! Thanks also for tagging Wen!

**Comment by YaliMao-NOAA** [comment]
@KateFriedman-NOAA Sorry I overlooked the fact that global-workflow has already stopped WAFS products from global-workflow by removing 'WAFSF' definition. So for WAFS separation from GFSv16.3, no new UPP tag is needed.
Sorry for the confusion!
@WenMeng-NOAA

**Comment by KateFriedman-NOAA** [comment]
@WenMeng-NOAA No worries, thanks for confirming! Not gonna complain about less work. :)

**Pull request merged**
