### PR TITLE
Update gsd_prep_chem tag to gefs_v12.3.9

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
# Description

This PR serves to update the GSL-prep-chem tag in `sorc/checkout.sh` from gefs_v12.3.8 to gefs_v12.3.9. This new tag in GSL-prep-chem includes a filename change that is needed for an upcoming upgrade to GBBEPX. This script change has been merged into [release/gefs_v12](https://github.com/NOAA-GSL/GSL-prep-chem/tree/release/gefs_v12) in the GSL-prep-chem repository and a new [tag](https://github.com/NOAA-GSL/GSL-prep-chem/releases/tag/gefs_v12.3.9) has been created.

Resolves https://github.com/NOAA-EMC/global-workflow/issues/2361
Refs https://github.com/NOAA-GSL/GSL-prep-chem/issues/12

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
The global-workflow package has been cloned to WCOSS2, and the release/gefs_v12 branch was checked out. Then a feature branch was created specifically to address issue #2361. `sorc/checkout.sh` was modified accordingly and executed to ensure the updated tag from GSL-prep-chem is cloned and checked out properly.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
@EricSinsky-NOAA I assume you need a new tag created after I merge this?

**Comment by EricSinsky-NOAA** [comment]
> @EricSinsky-NOAA I assume you need a new tag created after I merge this?

Yes, can you create a tag named "gefs_v12.3.9"?

**Comment by WalterKolczynski-NOAA** [comment]
New tag created: https://github.com/NOAA-EMC/global-workflow/releases/tag/gefs_v12.3.9

**Comment by EricSinsky-NOAA** [comment]
> New tag created: https://github.com/NOAA-EMC/global-workflow/releases/tag/gefs_v12.3.9

Thank you, @WalterKolczynski-NOAA.

**Pull request merged**
