### PR TITLE
Revert "update GDASApp hash to d34f616"

### PR DESCRIPTION
**Pull request by aerorahul**
Reverts NOAA-EMC/global-workflow#1506

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Do we want to revert it or just fix it?

**Review by RussTreadon-NOAA — APPROVED** [review]
This PR reverts GDASApp to the previous hash.   When/how does g-w pick up the hash ([aaf7caa](https://github.com/NOAA-EMC/GDASApp/commit/aaf7caa2b3e8b2c28b1ae5207166d2b85031e38c)) which @CoryMartin-NOAA cites?

**Comment by CoryMartin-NOAA** [comment]
whichever is easiest @WalterKolczynski-NOAA , either a revert or a 'hotfix' works for me.

**Comment by aerorahul** [comment]
I think @CoryMartin-NOAA will open a PR with the appropriate hash.
I am fine either way.

**Comment by WalterKolczynski-NOAA** [comment]
I'm about the make a PR with the correct hash. Closing this one.

**Pull request closed without merging**
