### PR TITLE
Friday CI Test on develop branch

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
**Description**

Running Friday CI test on develop branch

**How Has This Been Tested?**

- [x] Clone and Build with Build All
- [x] Cycled test on Hera using case [C96_atm3Dvar](https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/C96_atm3DVar.yaml)

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Fri Apr 28 14:49:26 UTC 2023 on hfe11
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Fri Apr 28 14:53:35 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Fri Apr 28 16:07:13 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:17 UTC 2023 for experiment C96_atm3DVar_baseline
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:20 UTC 2023 for experiment C96_atm3DVar

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Fri Apr 28 14:49:26 UTC 2023 on hfe11
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Fri Apr 28 14:53:35 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Fri Apr 28 16:07:13 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:17 UTC 2023 for experiment C96_atm3DVar_baseline
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:20 UTC 2023 for experiment C96_atm3DVar
Experiment C96_atm3DVar completed: *SUCCESS*
Experiment C96_atm3DVar Completed at Fri Apr 28 18:42:09 UTC 2023
with 73 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Fri Apr 28 14:49:26 UTC 2023 on hfe11
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Fri Apr 28 14:53:35 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Fri Apr 28 16:07:13 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:17 UTC 2023 for experiment C96_atm3DVar_baseline
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:20 UTC 2023 for experiment C96_atm3DVar
Experiment C96_atm3DVar completed: *SUCCESS*
Experiment C96_atm3DVar Completed at Fri Apr 28 18:42:09 UTC 2023
with 73 successfully completed jobsExperiment C96_atm3DVar_baseline completed: *SUCCESS*
Experiment C96_atm3DVar_baseline Completed at Fri Apr 28 18:42:13 UTC 2023
with 73 successfully completed jobs

**Comment by TerrenceMcGuinness-NOAA** [comment]
Automated global-workflow Testing Results:
```
Machine: Hera
Start: Fri Apr 28 14:49:26 UTC 2023 on hfe11
---------------------------------------------------
Checkout:                      *SUCCESS*
Checkout: Completed at Fri Apr 28 14:53:35 UTC 2023
Build:                         *SUCCESS*
Build: Completed at Fri Apr 28 16:07:13 UTC 2023
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:17 UTC 2023 for experiment C96_atm3DVar_baseline
Created experiment:            *SUCCESS*
Case setup: Completed at Fri Apr 28 16:07:20 UTC 2023 for experiment C96_atm3DVar
Experiment C96_atm3DVar completed: *SUCCESS*
Experiment C96_atm3DVar Completed at Fri Apr 28 18:42:09 UTC 2023
with 73 successfully completed jobsExperiment C96_atm3DVar_baseline completed: *SUCCESS*
Experiment C96_atm3DVar_baseline Completed at Fri Apr 28 18:42:13 UTC 2023
with 73 successfully completed jobs

**Comment by aerorahul** [comment]
This is great. 
Once we add a few more tests, we should be able to create a weekly stable release branch.

**Pull request closed without merging**
