### PR TITLE
Use deterministic marine resolutions for ensemble

### LINKED ISSUE #1730: OCNRES incorrectly set for efcs when DO_OCN=NO
**Expected behavior**
The efcs jobs should run when submitted.

**Current behavior**
When cold starting a `DO_OCN=NO` parallel in which `CASE=C384` and `CASE_ENS=C192`, the initial efcs01 mem001 forecast aborts because the expected tiled orography files are not present in the run directory.   
```
133: FATAL from PE   133: MPP_OPEN:INPUT/C192_grid.tile1.nc does not exist.
 40: FATAL from PE    40: MPP_OPEN:INPUT/C192_grid.tile1.nc does not exist.
```
See log file `/scratch2/NCEPDEV/stmp1/role.jedipara/comrot/pratmos/logs/2021073106/enkfgdasefcs01.log.0`

**Machines affected**
Failure occurred on Hera but likely affects all machines.

**To Reproduce**
Cold start a `DO_OCN=NO` parallel with a C384 deterministic and C192 ensemble.

**Detailed Description**
`JGDAS_ENKF_FCST` sources `config.base`   Since `CASE=C384`, the following lines of `config.base` set `OCNRES=025`
```
    "C384")
        export OCNRES=025
        export waveGRD='glo_025'
```
While `config.efcs` contains 
```
if [[ ${DO_OCN} == "YES" ]]; then
  case "${CASE_ENS}" in
    "C48") export OCNRES=500;;
    "C96") export OCNRES=500;;
    "C192") export OCNRES=050;;
    "C384") export OCNRES=025;;
    "C768") export OCNRES=025;;
```
`OCNRES` is not reset to `050` because this parallel is running with `DO_OCN=NO`.   Thus, we retain the `config.base` setting of `OCNRES=025`

Later on `JGDAS_ENKF_FCST` resets `CASE` to `CASE_ENS`.   When `forecast_postdet.sh` is executed the following section
```
  OROFIX=${OROFIX:-"${FIX_DIR}/orog/${CASE}.mx${OCNRES}_frac"}
  FIX_SFC=${FIX_SFC:-"${OROFIX}/fix_sfc"}
  for n in $(seq 1 "${ntiles}"); do
    ${NLN} "${OROFIX}/oro_${CASE}.mx${OCNRES}.tile${n}.nc" "${DATA}/INPUT/oro_data.tile${n}.nc"
    ${NLN} "${OROFIX}/${CASE}_grid.tile${n}.nc"     "${DATA}/INPUT/${CASE}_grid.tile${n}.nc"
  done
```
sets `OROFIX` to `C192.mx025_frac`.   This directory does not exist in `FIX_DIR/orog`.   We have `C192` and `C192_mx050` in `fix/orog`.

**Possible Implementation**
As a kludge add the following to `JGDAS_ENKF_FCST`
```
 export CASE=${CASE_ENS}
+case "${CASE_ENS}" in
+    "C48") export OCNRES=500;;
+    "C96") export OCNRES=500;;
+    "C192") export OCNRES=050;;
+    "C384") export OCNRES=025;;
+    "C768") export OCNRES=025;;
+    *) export OCNRES=025;;
+esac
```

**This is NOT the long term solution.**  This is a temporary patch to run my parallel.

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
This PR determines the ensemble resolution for ocean, ice and waves based on the deterministic configuration as there is no dual-resolution capability requested for these model components.

For cycled DA, if the deterministic uses a coupled model, the ensemble will also be a coupled model.  This can be turned off manually via adding `DO_AERO_ENKF`, `DO_OCN_ENKF`, `DO_ICE_ENKF` and `DO_WAVE_ENKF` flags set in `config.base` or `config.efcs`.  This is currently handled manually and will be automated when a requirement arises for this flexibility.

Fixes #1730

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
CI tests will cover the cycled atm-only parts, as well as the s2s forecast-only case and gefs case.
cycled with coupled model does not have a CI test. 

@RussTreadon-NOAA can you please validate if this solution works in the test that exposed this as a bug?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul thanks for this update.  These changes look okay to me although I'm not sure I'm the best reviewer for this.

**Comment by RussTreadon-NOAA** [comment]
Ditto for me.  Should a wave modeler look over these changes?

**Comment by aerorahul** [comment]
Thanks @JessicaMeixner-NOAA @RussTreadon-NOAA 
If possible please identify a suitable reviewer for this PR.  
Issue #1730 was opened by @RussTreadon-NOAA and #1692 by @WalterKolczynski-NOAA and hence were natural choices for reviewers.

**Comment by RussTreadon-NOAA** [comment]
Who works on ocean, ice, and wave related stuff in the modeling group?

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending successful CI completion.

**Comment by WalterKolczynski-NOAA** [comment]
Actually, I don't think this solves #1692 at all. The issue is some of the namelist variables (and other stuff) are set in `config.base` based on the original `DO_*` switches, and these are still not being recomputed here so if you did try to turn a component off for ENKF, the forecast would fail due to a mismatch.

**Comment by JessicaMeixner-NOAA** [comment]
Okay based on @WalterKolczynski-NOAA and @RussTreadon-NOAA comments it looks like I need to do some testing for this PR.  On the model side for now, we've just been running free-forecasts, but it's time to try running the ensemble and try various combinations of turning things off and doing it for this PR is a good time to start that.  FYI being realistic, I'm not sure I'll get to this today.

**Review by RussTreadon-NOAA — COMMENTED** [review]
This PR removes `CASE_ENS` sections which set `OCNRES`.   This is straightforward.  I can't tell, though, from the changes if gefs and gfs executions of the `efcs` step will actually work when run with the ocean model on.    Will `efcs` run with the correct `OCNRES`?   Can this be tested with any of the existing CI tests?

**Comment by aerorahul** [comment]
> This PR removes `CASE_ENS` sections which set `OCNRES`. This is straightforward. I can't tell, though, from the changes if gefs and gfs executions of the `efcs` step will actually work when run with the ocean model on. Will `efcs` run with the correct `OCNRES`? Can this be tested with any of the existing CI tests?

@RussTreadon-NOAA 
The `C48_S2SA_gefs` test will fail if there is a problem in this PR.
The real test would be a `C384C192_S2S_hybatmDA` where there is a dual-resolution atmosphere model, with atmosphere DA and the coupled model.  We do not have a test for that in the workflow, yet!
I think it might be that you tried something along these lines that failed and made you open this issue.

**Comment by aerorahul** [comment]
> Actually, I don't think this solves #1692 at all. The issue is some of the namelist variables (and other stuff) are set in `config.base` based on the original `DO_*` switches, and these are still not being recomputed here so if you did try to turn a component off for ENKF, the forecast would fail due to a mismatch.

@WalterKolczynski-NOAA 
I agree with your assessment in the issue with the need to source/set the "coupling parameters" for the model based on `OCNRES_ENKF` that is set based on `CASE_ENS`.
I think that would/should be a goal, in the event that `OCNRES /= OCNRES_ENKF`; i.e. we have a need for a dual-resolution ocean configuration; one for the deterministic and another for ensemble.  This is not the case for v17 and may be something required for v18 (too far to implement a feature that is a may be).  In the interest of not having an issue open for a very long time, and considering we may refactor configuration (maybe?), we can open a more directed issue in place of #1692 when a requirement such as this presented to us.
Thoughts?

**Comment by WalterKolczynski-NOAA** [comment]
Given things will still break if any of these `DO_*_ENKF` are set to something different than deterministic, and with there not being a need for such a thing in v17, I don't think we should even have these settings around. That will moot #1692, then if the functionality becomes needed later, we can open a new issue to add it back in properly.

**Comment by aerorahul** [comment]
> # Description
> This PR determines the ensemble resolution for ocean, ice and waves based on the deterministic configuration as there is no dual-resolution capability requested for these model components.
> 
> For cycled DA, if the deterministic uses a coupled model, the ensemble will also be a coupled model. This can be turned off manually via adding `DO_AERO_ENKF`, `DO_OCN_ENKF`, `DO_ICE_ENKF` and `DO_WAVE_ENKF` flags set in `config.base` or `config.efcs`. This is currently handled manually and will be automated when a requirement arises for this flexibility.
> 
> Fixes #1730 and possibly #1692
> 
> # Type of change
> * Bug fix (fixes something broken)
> 
> # Change characteristics
> * Is this a breaking change (a change in existing functionality)? NO
> * Does this change require a documentation update? NO
> 
> # How has this been tested?
> CI tests will cover the cycled atm-only parts, as well as the s2s forecast-only case and gefs case. cycled with coupled model does not have a CI test.
> 
> @RussTreadon-NOAA can you please validate if this solution works in the test that exposed this as a bug?
> 
> # Checklist
> * [ ]  Any dependent changes have been merged and published
> * [ ]  My code follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  My changes generate no new warnings
> * [ ]  New and existing tests pass with my changes
> * [ ]  I have made corresponding changes to the documentation if necessary



> Given things will still break if any of these `DO_*_ENKF` are set to something different than deterministic, and with there not being a need for such a thing in v17, I don't think we should even have these settings around. That will moot #1692, then if the functionality becomes needed later, we can open a new issue to add it back in properly.

I think these are still necessary for the case where the ensemble wishes to run with a different set of components than the deterministic. 
This PR does not resolve #1692 in its entirety.
The settings based on `DO_*` in `config.fcst` should be moved to `config.ufs`.  This will allow both `config.fcst` and `config.efcs` to set the correct namelist parameters based on the selected components.  Doing so will resolve #1692.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved as a fix for #1730.

**Comment by DavidHuber-NOAA** [comment]
This fails for the C192/C96 det/ens resolution case.  OCNRES for C192 is `050`, but for C96 it is `500`.  But since the deterministic resolution is used for the ensemble `OCNRES`, dead links are created to `$fix/orog/C96.mx050_frac/C96_grid.tile*.nc`.  This is likely a problem for C384/C192 case (where OCNRES = 025/050, respectively) as well.  Should we reopen #1730 or open a new issue?

**Comment by DavidHuber-NOAA** [comment]
@aerorahul [^^](https://github.com/NOAA-EMC/global-workflow/pull/1894#issuecomment-1768309683)

**Comment by aerorahul** [comment]
C192/C96 cycling with coupled model is not a supported combination as we don't have fix files for C96.mx025 or C192.mx500. 
If they are made available, some work will be required. For now, that resolution is neither here nor there.

**Comment by DavidHuber-NOAA** [comment]
@aerorahul Apologies, I should have specified that this is broken in atmosphere-only mode.  I have not tried using coupled @C192/C96.  The orography resolution is specified by `OCNRES`.  If you would like to see an example, take a look at this log file: /scratch1/NCEPDEV/global/David.Huber/para/comrot/test_spack/logs/2022060118/enkfgdasefcs01.log.  And the accompanying run/INPUT directory: /scratch1/NCEPDEV/stmp2/David.Huber/RUNDIRS/test_spack/efcs.49942/mem001/INPUT.

**Comment by aerorahul** [comment]
Thanks @DavidHuber-NOAA 

Even with atmosphere-only, since we are using fractional grid by default, these fix files are generated based on the knowledge of the underlying ocean resolution (and hence they have the `.mx$OCNRES`) name in their directories. 
If the group that provided these files can provide the C96.mx025 and C192.mx500, we may be able to do C192/C96 atmosphere-only cycling.
It would be good to enable this capability again at some point, but there is no requirement at the moment.
Also, we currently cannot use a dual-resolution ocean (not required).  Enabling a dual-resolution ocean as well as updating configurations to achieve these combinations will require some work in the configuration.

**Comment by DavidHuber-NOAA** [comment]
OK, noted.  Thanks for the explanation @aerorahul.  I see that both 025 and 050 resolution orography data is available for C192, so the C384/C192 test case should work.  So I will stick with with testing C96/C48 and C384/C192 for the time being.  Lastly, I will note that on S4, C192/C96 is the most typical resolution run, so this will cause problems on that system.  FYI @wx20jjung.

**Pull request merged**
