### PR TITLE
Utilize scale-dependent localization for atmospheric analysis

### PR DESCRIPTION
**Pull request by TravisElless-NOAA**
# Description
The plan for GFSv17 is to use a scale-dependent localization for the atmospheric analysis. This PR adds the necessary parameters to allow this feature to be used by default.    

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cycled tests on WCOSS2/Orion/Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by TravisElless-NOAA** [comment]
@CatherineThomas-NOAA please let me know if you would like to see these parameters live in a different location.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Code looks fine. Always nervous about wall clock increases though.

Conditionally approved pending successful completion of CI tests.

**Comment by CatherineThomas-NOAA** [comment]
Noting here that this is implementing work done by @shoyokota from [GSI Issue #459](https://github.com/NOAA-EMC/GSI/issues/459), originally in the context of RRFS.  His code was written generically to allow use in the global system as well.  Thanks for all of your help @shoyokota!

**Review by CatherineThomas-NOAA — APPROVED** [review]

**Comment by CatherineThomas-NOAA** [comment]
@WalterKolczynski-NOAA 
We don't like the increase in wall clock either, but the algorithmic improvement as well as robust forecast skill improvements are too good to pass up.  This feature's use and associated costs have already been approved by management.

**Comment by WalterKolczynski-NOAA** [comment]
@TravisElless-NOAA Please merge in develop, which now has fixes so the CI tests can pass.

**Comment by TravisElless-NOAA** [comment]
Latest version of develop has been merged

**Pull request merged**
