### PR TITLE
Use replace_tmpl Jinja filter instead of namespaces in archiving

### LINKED ISSUE #2763: Remove namespaces from jinja templates where possible
### What new functionality do you need?

By design, Jinja scoping does not retain variables set within `for` loops.  To get around this, namespaces were introduced to allow variables with global scope to allow modifications within a for loop to be retained.  However, this advanced feature is often difficult to understand.  The global workflow uses this most often when constructing ensemble `COM` directories from templates.  Recently, the `replace_tmpl` filter was added to `wxflow` to handle this case and simplify Jinja templating.  The existing templates should be updated to use this filter.

Other namespace use cases should be examined to determine if they can similarly be handled in a more readable form.

### What are the requirements for the new functionality?

The global workflow should have minimal use of Jinja `namespace`s.

### Acceptance Criteria

Rendered templates are identical with/without namespace use.

### Suggest a solution (optional)

Make use of the `replace_tmpl` filter.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
Removes the namespace-based construction of EnKF member COM directories in the enkf archive template.

Resolves #2763 

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cycled test on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Review by aerorahul — DISMISSED** [review]
looks good.

**Review by DavidNew-NOAA — APPROVED** [review]

**Review by WalterKolczynski-NOAA — DISMISSED** [review]
Conditionally approved.

**Comment by DavidHuber-NOAA** [comment]
The archive jobs are failing to submit on the RDHPCS machines because they are attempting to use the `fv3-cpu` slurm account, which I am not a member of.  I will modify the local Jenkins clones so they use `nems` instead and resubmit.

**Comment by DavidHuber-NOAA** [comment]
Jenkins agent crashed on Hera.  Rebooting.

**Comment by DavidHuber-NOAA** [comment]
Cleaning out working directories on Hera and Hercules to allow a clean clone.  CI will be relaunched once complete.

**Comment by DavidHuber-NOAA** [comment]
WCOSS2 failed because I do not have write permissions to the default `ARCDIR` (`/lfs/h2/emc/global/noscrub/$USER/archive/$EXPDIR`) as I am not a member of `global`.  I will run these regression tests manually and report results.

**Comment by DavidHuber-NOAA** [comment]
All WCOSS2 CI tests passed when run manually.  Changing label to `CI-Wcoss2-Passed`.

**Review by aerorahul — APPROVED** [review]

**Pull request merged**
