### PR TITLE
Add atmensanlfv3inc job

### PR DESCRIPTION
**Pull request by DavidNew-NOAA**
This PR creates the atmensanlfv3inc job, the ensemble version of atmanlfv3inc, created in GW PR #2420. Its GDASApp companion PR is #[1104](https://github.com/NOAA-EMC/GDASApp/pull/1104), and its JCB-GDAS companion PR is #[3](https://github.com/NOAA-EMC/jcb-gdas/pull/3).

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES
- Does this change require a documentation update? NO

# How has this been tested?
- Clone build on Orion and Hera
- Cycled test on Orion
- jjob GDASApp CTests on Hera.

# Checklist
- [ ] Any dependent changes have been merged and published
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by RussTreadon-NOAA** [comment]
**Orion test**

Install `DavidNew-NOAA:feature/atmensanlfv3inc`.  Enable `C96C48_ufs_hybatmDA`.  Job enkfgdasatmensanlfv3inc failed because `jobs/rocoto/atmensanlfv3inc.sh` does not exist.   Confirm that `atmensanlfv3inc.sh` is not part of this PR nor is it already in `develop`.

Given this, copy `atmanlfv3inc.sh` to `atmensanlfv3inc.sh` in working copy of  `DavidNew-NOAA:feature/atmensanlfv3inc`.  Update config file to source and j-job to execute.  Rewind and reboot failed enkfgdasatmensanlfv3inc.  Job ran to completion.   The next job, enkfgdasatmensanlfinal, also ran to completion.  

Unfortunately, enkfgdasecen000 failed because the member analysis increment files are not found.  enkfgdasecen000 looks for member increments in `$ROTDIR/enkfgdas.$PDY/$cyc/mem*/analysis/atmos/`.    The atmensanlfinal job copies the increments to `$ROTDIR/enkfgdas.$PDY/$cyc/ensstat/analysis/atmos/`.  Additionally, the copy for each member analysis increment file overwrites the previous file in `ensstat/analysis/atmos/`
```
^[[38;21m2024-05-13 16:57:08,476 - INFO     - atmens_analysis: Copy UFS model readable atm increment file^[[0m
^[[38;5;39m2024-05-13 16:57:08,476 - DEBUG    - atmens_analysis: Copying /work/noaa/stmp/rtreadon/RUNDIRS/prfv3inc/enkfgdasatmensanl_00/anl/mem001/atminc.20240224_000000z.nc4 to /work2/noaa/stmp/rtreadon/COMROOT/prfv3inc/enkfgdas.20240224/00/ensstat/analysis/atmos/enkfgdas.t00z.atminc.nc^[[0m
^[[38;21m2024-05-13 16:57:08,788 - INFO     - file_utils  : Copied /work/noaa/stmp/rtreadon/RUNDIRS/prfv3inc/enkfgdasatmensanl_00/anl/mem001/atminc.20240224_000000z.nc4 to /work2/noaa/stmp/rtreadon/COMROOT/prfv3inc/enkfgdas.20240224/00/ensstat/analysis/atmos/enkfgdas.t00z.atminc.nc^[[0m
^[[38;5;39m2024-05-13 16:57:08,788 - DEBUG    - atmens_analysis: Copying /work/noaa/stmp/rtreadon/RUNDIRS/prfv3inc/enkfgdasatmensanl_00/anl/mem002/atminc.20240224_000000z.nc4 to /\
work2/noaa/stmp/rtreadon/COMROOT/prfv3inc/enkfgdas.20240224/00/ensstat/analysis/atmos/enkfgdas.t00z.atminc.nc^[[0m
^[[38;21m2024-05-13 16:57:09,240 - INFO     - file_utils  : Copied /work/noaa/stmp/rtreadon/RUNDIRS/prfv3inc/enkfgdasatmensanl_00/anl/mem002/atminc.20240224_000000z.nc4 to /work2/noaa/stmp/rtreadon/COMROOT/prfv3inc/enkfgdas.20240224/00/ensstat/analysis/atmos/enkfgdas.t00z.atminc.nc^[[0m
^[[38;21m2024-05-13 16:57:09,240 - INFO     - atmens_analysis:   END: pygfs.task.atmens_analysis.finalize^[[0m
```  
 
@DavidNew-NOAA:  we need to 
- add `atmensanlfv3inc.sh` to `jobs/rocoto` 
- modify python script to copy member increments to member specific directories

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA I accidentally omitted atmensanlfv3inc.sh from the branch/PR, but it's added now. Let me take a second look at the final job, update the python, and re-test.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidNew-NOAA for adding atmensanlfv3inc.sh.  

The following local change to atmens_analysis.py got the member analysis increments to the expected locations and allowed ecen to successfully run to completion.
```
Orion-login-4:/work2/noaa/da/rtreadon/git/global-workflow/fv3inc/ush/python/pygfs/task$ git diff atmens_analysis.py
diff --git a/ush/python/pygfs/task/atmens_analysis.py b/ush/python/pygfs/task/atmens_analysis.py
index cef2d916..9c76b045 100644
--- a/ush/python/pygfs/task/atmens_analysis.py
+++ b/ush/python/pygfs/task/atmens_analysis.py
@@ -248,12 +248,21 @@ class AtmEnsAnalysis(Analysis):
         logger.info("Copy UFS model readable atm increment file")
         cdate = to_fv3time(self.task_config.current_cycle)
         cdate_inc = cdate.replace('.', '_')
+        template_inc = self.task_config.COM_ATMOS_ANALYSIS_TMPL
+        tmpl_inc_dict = {
+            'ROTDIR': self.task_config.ROTDIR,
+            'RUN': self.task_config.RUN,
+            'YMD': to_YMD(self.task_config.current_cycle),
+            'HH': self.task_config.current_cycle.strftime('%H')
+        }
         # loop over ensemble members
         for imem in range(1, self.task_config.NMEM_ENS + 1):
             memchar = f"mem{imem:03d}"

             src = os.path.join(self.task_config.DATA, 'anl', memchar, f"atminc.{cdate_inc}z.nc4")
-            dest = os.path.join(self.task_config.COM_ATMOS_ANALYSIS_ENS, f'{self.task_config.CDUMP}.t{self.task_config.cyc:02d}z.atminc.nc')
+            tmpl_inc_dict['MEMDIR'] = f"mem{imem:03d}"
+            outdir = Template.substitute_structure(template_inc, TemplateConstants.DOLLAR_CURLY_BRACE, tmpl_inc_dict.get)
+            dest = os.path.join(outdir, f'{self.task_config.CDUMP}.t{self.task_config.cyc:02d}z.atminc.nc')
             logger.debug(f"Copying {src} to {dest}")
             inc_copy = {
                 'copy': [[src, dest]]
```
This is just a hack and may not be the best way to achieve the desired end.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Great, that's essentially the same change I just made and that I was testing right now. Let me just double check that ecen passes the way I have the code written, and then I'll commit my changes.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , are the EXPDIR and COMROOT from your test still available?  If so, where may I find them?  My ecen job failed when running `getsigensmeanp_smooth.x`.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA My ecen job actually failed too. I just committed my change to get your feedback, because my change to atmens_analysis.py is essentially equivalent to the "hack" you demonstrated earlier, with the increments going to the right places, but ecen fails. But you said ecen passed with your "hack"?

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , looks like my claim of success was bogus.  I probably looked at an ecen from a different test.  Program `getsigensmeanp_smooth.x` assumes `real(4)` for floating point netcdf input.  ncdump of the new atminc files returns `double` for increment fields.  Does this agree with your understanding of how the oops increment code works?  Does it write output as type `double` (= `real(8)`)?

Your changes to `atmens_analysis.py` are good. They get the right files in the right place.  We're dealing with a new issue now.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Yes, a quick review of the IO modules code in FV3-JEDI indicates that they all create real(8) variables upon defining NetCDF files, and there's no option to change that in the YAML. I suppose the best option here would be to modify getsigensmeanp_smooth.x to read doubles instead of floats?

**Comment by DavidNew-NOAA** [comment]
> @RussTreadon-NOAA Yes, a quick review of the IO modules code in FV3-JEDI indicates that they all create real(8) variables upon defining NetCDF files, and there's no option to change that in the YAML. I suppose the best option here would be to modify getsigensmeanp_smooth.x to read doubles instead of floats?

Or would that break GSI?

**Comment by RussTreadon-NOAA** [comment]
Yes, simply changing `getsigensmeanp_smooth.x` would break GSI based cycling.  GSI-based DA has `real(4)` increment fields.   We need to refactor `getsigensmeanp_smooth.x` to detect the type of real it is reading or pass a flag indicating the type of real it will read.  We won't solve this tonight.  Let's revisit tomorrow.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA .  Upon closer look even if we change `getsigensmeanp_smooth.x` to read `real(8)`, ecen will still fail.  ecen computes the ensemble mean of both atminc and atmf006 files.   A `real(8)` `getsigensmeanp_smooth.x` can process the atminc files but aborts when processing the atmf006 files.  The existing `real(4)` program processes the atmf006 files but fails for the atminc files.  I confirmed this behavior in the JEDI ATM CI by creating a `real(8)` `getsigensmeanp_smooth.x`.

The forecast model writes model fields using `real(4)`.  `gsi.x` and `enkf.x` write 4-byte analyses or increment files.  Disk space is one motivation for doing so.  A file filled with `real(4)` consumes less disk space than a `real(8)` file.  Looking ahead to when we have an 80 member ensemble with 3-hourly IAU we will have 80 x 3 = 240 enkf increment files.  Since we recenter the enkf increments, 240 becomes 240 x 2 = 480 files.  Using `real(8)` will certainly use more disk space than `real(4)`.

While we can get creative and develop a version of `getsigensmeanp_smooth.x`  which can handle `real(4)` and `real(8)`, we may need to do likewise for other codes in the [GSI-utils](https://github.com/NOAA-EMC/GSI-utils) repo, specifically codes in [src/EnKF/gfs/src](https://github.com/NOAA-EMC/GSI-utils/tree/develop/src/EnKF/gfs/src).

Before we go too far down the GSI_utils road it would be useful to examine JEDI software to see if / how we can specify the precision for floating point output via a toggle in a yaml file.

Tagging @CoryMartin-NOAA and @danholdaway for awareness and comment.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Yeah, it's probably a good idea to have some control over write precision in JEDI IO anyway. I'll put together PR for FV3-JEDI.

**Comment by RussTreadon-NOAA** [comment]
Indeed, more codes in GSI_utils will need to be refactored if we stick with `real(8)` enkf increments.  I modified `exgdas_enkf_ecen.sh` to use either a `real(4)` or `real(8)` `getsigensmeanp_smooth.x` as appropriate.  This worked for the atminc and atmf006 files.  Program `recentersigp.x` aborted.  I'll stop experimenting here.

**Comment by RussTreadon-NOAA** [comment]
@DavidNew-NOAA , I found that by adding logic to check if work arrays are allocated before being deallocated, `getsigensmeanp_smooth.x` and `recentersigp.x` sometimes run to completion and job enkfgdasecen000 finishes with `rc=0`.  However, most ecen000 jobs abort.   I think I'm simply play games with memory.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA OK, no worries. I have code written for FV3-JEDI IO subroutines already. PR probably today and hopefully quick review.

**Comment by RussTreadon-NOAA** [comment]
Thank you @DavidNew-NOAA for working on IO modifications.  This will be a useful option.  Both the getsigensmeanp_smooth.x and recentersigp.x codes contain potentially problematic coding:  uninitialized variables, failure to check allocated state, failure to check error return codes, etc.

**Comment by RussTreadon-NOAA** [comment]
With changes in GSI-utils PR [#41](https://github.com/NOAA-EMC/GSI-utils/pull/41) C96C48_ufs_hybatmDA successfully completes all jobs
```
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202402231800        Done    May 13 2024 15:47:59    May 14 2024 16:09:23
202402240000        Done    May 13 2024 15:47:59    May 14 2024 16:52:08
```

**Review by RussTreadon-NOAA — APPROVED** [review]
Install `DavidNew-NOAA:feature/atmensanlfv3inc` at 16c5de41 on Orion.  Enable C96C48_ufs_hybatmDA CI.  All jobs run to completion after making updates to gsi_utils.  

The gsi_utils updates are not related to this PR.  Instead, this PR highlighted unsafe coding in two gsi_utils source codes.  GSI-utils PR [#41](https://github.com/NOAA-EMC/GSI-utils/pull/41) contains the gsi_utils updates used when running C96C48_ufs_hybatmDA CI.

Approve.

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA Awesome, thanks for the testing and update. I put the new gsi_utils hash in this PR, so looks like we're good to go. My PR for FV3-JEDI to specify NetCDF write precision should still be useful, since like you said, double precision will take up a lot of space, but not necessary now for this PR.

**Comment by RussTreadon-NOAA** [comment]
Install a fresh clone of `DavidNew-NOAA:feature/atmensanlfv3inc` at [2114968](https://github.com/DavidNew-NOAA/global-workflow/commit/211496866156f4b59afd8f289102922bb33458d1) on Orion. 

Enable C96C48_ufs_hybatmDA CI.  JEDI-based CI successfully runs to completion.
```
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202402231800        Done    May 15 2024 11:31:22    May 15 2024 11:55:15
202402240000        Done    May 15 2024 11:31:22    May 15 2024 13:50:17
``` 

Run C96C48_hybatmDA CI.  GSI-based CI successfully runs to completion.
```
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202112201800        Done    May 15 2024 13:20:27    May 15 2024 13:40:21
202112210000        Done    May 15 2024 13:20:27    May 15 2024 15:35:16
202112210600        Done    May 15 2024 13:20:27    May 15 2024 15:51:41
```

**Comment by RussTreadon-NOAA** [comment]
Any estimate as to when this PR can be merged into develop?

**Comment by DavidNew-NOAA** [comment]
@RussTreadon-NOAA I think it's ready. We're just waiting for review by rest of GW team

**Comment by WalterKolczynski-NOAA** [comment]
@DavidNew-NOAA Conflicts need to be resolved before we can test it.

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA Thanks, I didn't see the conflict. Not actually sure what it means. Will try to resolve

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA Thanks, I didn't see the conflict. Not actually sure what it means. Will try to resolve

Both your branch and develop have updated the gsi_utils hash. Use whichever version is more recent.

**Comment by WalterKolczynski-NOAA** [comment]
Will run CI after #2584 CI is complete. Waiting because that PR may cause another conflict (this time with the gdas.cd version).

**Comment by DavidNew-NOAA** [comment]
GSI Utils #[43](https://github.com/NOAA-EMC/GSI-utils/pull/43) is now a companion of this PR

**Comment by WalterKolczynski-NOAA** [comment]
Converting to draft until the prerequisite PRs are merged.

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA Sorry, I got my wires crossed. That GSI Utils PR was unrelated and should not have been a companion to this PR. All prerequisite PRs are now merged. Reopening for review.

**Comment by RussTreadon-NOAA** [comment]
Install DavidNew-NOAA:feature/atmensanlfv3inc at 49d95cc5 on Orion.  Run GDASApp ctests.  All 46 ctests _Passed_.  Enable C96C48_ufs_hybatmDA.  Run JEDI ATM CI.  All jobs successfully run to completion
```
(gdasapp) Orion-login-3:/work2/noaa/stmp/rtreadon/EXPDIR/prfv3inc$ rocotostat -d prfv3inc.db -w prfv3inc.xml -c all -s
   CYCLE         STATE           ACTIVATED              DEACTIVATED
202402231800        Done    May 23 2024 12:54:47    May 23 2024 13:15:20
202402240000        Done    May 23 2024 12:54:47    May 23 2024 15:10:15
```
The changes in this PR should be considered for merger into the authoritative g-w `develop`.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved pending successful completion of CI tests.

**Comment by WalterKolczynski-NOAA** [comment]
@DavidNew-NOAA Please merge in develop to get the CI fixes, then I think we are ready for CI testing.

**Comment by DavidNew-NOAA** [comment]
@WalterKolczynski-NOAA done

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA :  automated CI passed on Hercul;es, Orion, & WCOSS2.  The label says CI is running on Hera   Is CI actually running on Hera or is CI stuck?

**Comment by RussTreadon-NOAA** [comment]
**NOTE**:  This PR is required for all WCOSS2 functionality in g-w PR #2620 to be realized.

**Comment by RussTreadon-NOAA** [comment]
Yeah! CI passes on all platforms.  Once this PR is merged, I'll update `RussTreadon-NOAA:feature/wcoss2_ufsda` (PR [#2620](https://github.com/NOAA-EMC/global-workflow/pull/2620)) and finish JEDI ATM CI testing on WCOSS2.

**Pull request merged**
