### PR TITLE
CI Jenkins Project Configuration Self Test [Do not merge]

### PR DESCRIPTION
**Pull request by TerrenceMcGuinness-NOAA**
CI Jenkins Project Configuration Self Test

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA

`git submodule update` on **gdas.cd** fails on Gaea when cloning in Jenkins [error log](https://gist.github.com/emcbot/226bedf5b85c7c6dd93bcd9111947011) with an error not having **git-lsf**

```
Cloning into '/gpfs/f5/epic/proj-shared/global/CI/2848/gfs/sorc/gdas.cd/sorc/vader'...
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
```

On Hera:
```
Terry.McGuinness (hfe10) ~ $ which git-lfs
/usr/bin/git-lfs
Terry.McGuinness (hfe10) ~ $
```

**Comment by AnilKumar-NOAA** [comment]
no git-lfs

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA 
**_yes_** `git-lfs`

**Comment by AnilKumar-NOAA** [comment]
I have load that module - 
module load git-lfs
Anil.Kumar@gaea55:/gpfs/f5/epic/proj-shared/global/CI> which git-lfs
/sw/gaea-c5/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/git-lfs-2.11.0-s6xxak7cm7v4sigmacyiujz5lxq73nec/bin/git-lfs

So, Every time, I have to do module load and that's not correct. So we can add this module in the module setup for gaea file?

**Comment by TerrenceMcGuinness-NOAA** [comment]
Close, update module file [module_gwset.gaea.lua](https://github.com/NOAA-EMC/global-workflow/blob/develop/modulefiles/module_gwsetup.gaea.lua) with that module for `git-lfs` and note that when we [launch](https://github.com/NOAA-EMC/global-workflow/blob/1b18f2f97eec24a8b3f817b7ef1b4caa2be24937/ci/scripts/utils/launch_java_agent.sh#L89) the agent it then gets picked up.

**Review by AnilKumar-NOAA — COMMENTED** [review]
Approved

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA Approved? I think you mean "_acknowledged_"?

**Comment by AnilKumar-NOAA** [comment]
> @AnilKumar-NOAA Approved? I think you mean "_acknowledged_"?

Yes I meant acknowledged!

**Comment by TerrenceMcGuinness-NOAA** [comment]
Try reviewing [this](https://github.com/TerrenceMcGuinness-NOAA/global-workflow/wiki/Configuring-the-Jenkins-Controller's-Node-default-configurations).

**Comment by AnilKumar-NOAA** [comment]
Under build configuration on Jenkin web interface
Mode is selected "by Jenkinsfile" or "by Remote Jenkinsfile Provide Plugins"
I am using Jenkins web interface but not able to find Manage Jenkin tab though

**Pull request closed without merging**
