### PR TITLE
Update UFS for memory bug

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
Updates the UFS version to correct a memory bug.

Closes: #425

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Confirmed identical results to coupled-crow after updating the coupled-crow post version to the same as sprint branch.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
These look like all the changes from PR#426

**Review by KateFriedman-NOAA — APPROVED** [review]
I can't comment on the actual changes but if they reproduce the control I'm good with them. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
> These look like all the changes from PR#426

They are. I just cherry-picked the commit to the sprint branch.

**Pull request merged**
