### PR TITLE
[DO NOT MERGE] Weekly CI Tests Friday Jan 19, 2024

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Jan 19, 2024

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
The `C384_S2SWA` GFS forecast is failing on both Orion and Hera with `MAPL` errors starting in ExtDataGridCompMod.F90:

```
   0:  in radiation_clouds_prop=           8 F           4 F F           2           1
   0:  in radiation_clouds_prop=           8 F           4 F F           2           1
   0:  in radiation_clouds_prop=           8 F           4 F F           2           1
   0:  in radiation_clouds_prop=           8 F           4 F F           2           1
   0:  in radiation_clouds_prop=           8 F           4 F F           2           1
 762: pe=00762 FAIL at line=02588    ExtDataGridCompMod.F90                   <unknown error>
 762: pe=00762 FAIL at line=01323    ExtDataGridCompMod.F90                   <status=-1>
 762: pe=00762 FAIL at line=01901    MAPL_Generic.F90                         <status=-1>
 762: pe=00762 FAIL at line=01243    MAPL_CapGridComp.F90                     <status=-1>
 762: pe=00762 FAIL at line=01206    MAPL_CapGridComp.F90                     <status=-1>
 762: pe=00762 FAIL at line=01166    MAPL_CapGridComp.F90                     <status=-1>
 762: pe=00762 FAIL at line=00834    MAPL_CapGridComp.F90                     <status=-1>
 762: pe=00762 FAIL at line=00974    MAPL_CapGridComp.F90                     <status=-1>
...
```

**Comment by WalterKolczynski-NOAA** [comment]
May be related to the changes last week in #2201, though the low-res tests passed. @bbakernoaa can you take a look?

**Comment by bbakernoaa** [comment]
Yea I'll take a look first thing tomorrow

**Comment by bbakernoaa** [comment]
@WalterKolczynski-NOAA @DavidHuber-NOAA 

Found the issue 

We needed to switch the flag for climatology in the biogenic files.  Do you want me to setup a separate PR or combine it with this one? 

The change is very easy.  The lines that needs changed are here: https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/ufs/gocart/ExtData.other#L57-L60

specifically 

```# # VOCs - OFFLINE MEGAN BIOG
OC_ISOPRENE NA  N Y %y4-%m2-%d2t12:00:00 none none isoprene ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_LIMO     NA  N Y %y4-%m2-%d2t12:00:00 none none limo     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_MTPA     NA  N Y %y4-%m2-%d2t12:00:00 none none mtpa     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_MTPO     NA  N Y %y4-%m2-%d2t12:00:00 none none mtpo     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
```

needs to be changed to Y in the 3rd column. Like so.... 

```# # VOCs - OFFLINE MEGAN BIOG
OC_ISOPRENE NA  Y Y %y4-%m2-%d2t12:00:00 none none isoprene ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_LIMO     NA  Y Y %y4-%m2-%d2t12:00:00 none none limo     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_MTPA     NA  Y Y %y4-%m2-%d2t12:00:00 none none mtpa     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
OC_MTPO     NA  Y Y %y4-%m2-%d2t12:00:00 none none mtpo     ExtData/nexus/MEGAN_OFFLINE_BVOC/v2021-12/MEGAN_OFFLINE_CLIMO_2000_2022_%m2.nc
```

**Comment by WalterKolczynski-NOAA** [comment]
@bbakernoaa Great job. Separate PR please, this "PR" isn't a real PR, it is a kludge for the CI system to run weekly testing.

**Pull request closed without merging**
