### PR TITLE
Handle NSSTBufr file creation/copying in parallels.

### LINKED ISSUE #313: Two issues in the test runs for GFSv16.2
There are a series of cycling runs to check the GSI updates for GFSv16.2.
There are two issues in all of the cycling runs:

dbuoyb and mbuoyb are not used before 2020102200
Before 2020102200 cycle, there are two separate data files, e.g., for 2020090100,

-rw-r--r-- 1 glopara global 1112592 Sep 1 2020 /scratch1/NCEPDEV/global/glopara/dump/gdas.20200901/00/gdas.t00z.mbuoyb.tm00.bufr_d
-rw-r--r-- 1 glopara global 2472584 Sep 1 2020 /scratch1/NCEPDEV/global/glopara/dump/gdas.20200901/00/gdas.t00z.dbuoyb.tm00.bufr_d

which are included into nsstbufr data file, after 2020102200, these two files don't exist anymore since they have been combined into sfcshp data file.

The solution to include dbuoyb and mbuoyb in the cycling run:

add

if [[ "$CDATE" -le "2020102200" ]]; then
export SCRIPTSobsproc_global=$EXPDIR
fi

in config.base

cp /scratch1/NCEPDEV/da/Xu.Li/para_gfs/rocoto_sh/exglobal_makeprepbufr.sh.ecf to $EXPDIR

Only one line change in this exglobal_makeprepbufr.sh.ecf

  DTYPS_nsst='sfcshp tesac bathy trkob'  ==>  DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'
the dmesh(i) needs to be set reasobally, when i > 2, in config.eobs
in config.eobs,

there is a line

export OBSINPUT_INVOBS="dmesh(1)=225.0,dmesh(2)=225.0,"

to set the thinning box size to be 225 km, for dmesh(1) and dmesh(2).

However, there are three data thinning is defined with dmesh(3), which is set to be 100 km in exglobal_atmos_analysis.sh, they are

amsr2_gcom-w1
gmi_gpm
saphir_methat

Currently, only saphir_methat of these three are used in GSI, and gmis_gpm will be used by plan. It is necessary to set dmesh(3) in config.eobs.

### PR DESCRIPTION
**Pull request by aerorahul**
closes #313

### CODE REVIEW

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good and appear to address the issue at hand. Assuming testing goes well I approve. Thanks all!

**Review by XuLi-NOAA — APPROVED** [review]
The changes related to nsstbufr data file handle are OK to me.

**Review by ShelleyMelchior-NOAA — COMMENTED** [review]
These changes look fine to me.  Just to clarify, these changes are unique to the global workflow and will not impact exglobal_makeprepbufr.sh.

**Comment by aerorahul** [comment]
@ShelleyMelchior-NOAA 
You are correct.  These are unique to global-workflow and does not impact the behavior of `exglobal_makeprepbufr.sh`.

Having said that, @XuLi-NOAA asked us to add this logic in global-workflow, specifically `config.prep` to account for the difference in the creation of `nsstbufr` during ops and a rerun experiment:
```
if [[ "$CDATE" -ge "2020102200" ]]; then
  export DTYPS_nsst='sfcshp tesac bathy trkob'
else
  export DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob'
fi
```

This logic will have no impact, since `exglobal_makeprepbufr.sh.ecf` hardwires this:
```
DTYPS_nsst='sfcshp tesac bathy trkob'
```
on Line 558 of [exglobal_makeprepbufr.sh.ecf](https://vlab.noaa.gov/redmine/projects/emc-obsproc/repository/emc_obsproc_global/revisions/master/entry/scripts/exglobal_makeprepbufr.sh.ecf)

So, in order for @XuLi-NOAA to adequately test the issue #313, he will have to make a change in `exglobal_makeprepbufr.sh.ecf`.  That change is outside the scope of this PR.

**Comment by aerorahul** [comment]
@XuLi-NOAA @RussTreadon-NOAA @ShelleyMelchior-NOAA 
We will merge this PR as @XuLi-NOAA has approved.  Unless there are concerns anyone wishes to address regarding the comment in this https://github.com/NOAA-EMC/global-workflow/pull/469#issuecomment-951142550.

**Comment by ShelleyMelchior-NOAA** [comment]
No concerns.

**Comment by XuLi-NOAA** [comment]
I just realized one thing:

We should make sure it works for all the time periods. With the changes, it works after 2020102200. And it works for the time period before 2020102200 but with mbuoyb and dbuoyb existing. How about the earlier rime periods, when mbuoyb and dbuoyb are not available. It seems OK to me as well, for the earlier time period, since export DTYPS_nsst='sfcshp dbuoyb mbuoyb tesac bathy trkob' should be fine if dbuoyb mbuoyb cannot be found, when nsstbufr needs to be generated.  Note: dbuoyb mbuoyb are available only a certain time period (supposed should start from the summer of 2016. However, they are available in NCEP system, real-time dump directories, later, since about autumn of 2018 or 2019?, to 2020102200).

**Comment by aerorahul** [comment]
@XuLi-NOAA 
Can you explain why you closed this and how it relates to the issue #313

**Comment by XuLi-NOAA** [comment]
> @XuLi-NOAA Can you explain why you closed this and how it relates to the issue #313

See the edited comments above (at the beginning, I tried to do it then thought it maybe unnecessary. Any way, I made it complete).

**Comment by aerorahul** [comment]
@XuLi-NOAA 
I am still confused why this PR is closed.
Is this PR no longer necessary to address the issue in #313?
Is this PR incomplete to address the issue in #313? If so, what is missing?

**Comment by XuLi-NOAA** [comment]
> @XuLi-NOAA I am still confused why this PR is closed. Is this PR no longer necessary to address the issue in #313? Is this PR incomplete to address the issue in #313? If so, what is missing?

Did I close the PR? I thought I was trying to terminate my comment. So, if PR was closed accidently by my self. I just reopen it?

**Comment by aerorahul** [comment]
@XuLi-NOAA has tested and confirmed that these changes resolve the issue #313. 
@KateFriedman-NOAA Please do final review and merge.

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good and address the issue. @XuLi-NOAA confirmed it works in testing so I am approving and submitting this now. Thanks all!

**Pull request merged**
