### PR TITLE
Feature/crow merge

### PR DESCRIPTION
**Pull request by jkuang-exploro**
Add CROW configurator into global-workflow develop

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by KateFriedman-NOAA** [comment]
Taking a deep dive into these changes. Checked out feature/crow-merge on Venus, did a sync merge of develop into feature/crow-merge and made a few other adjustments. Committed all that at
ea5f8f6. Added these comments into issue #13.

**Comment by jkuang-exploro** [comment]
@KateFriedman-NOAA Are we still trying to merge this?

**Comment by KateFriedman-NOAA** [comment]
@JianKuang-NOAA Sorry, not at present. Please close this PR, we will try again after v16 hand-off completes this fall. Thanks!

**Comment by jkuang-exploro** [comment]
Will try again after v16 hand-off

**Pull request closed without merging**
