### PR TITLE
Add corrections to the variable names for GEFS

### LINKED ISSUE #2967: GEFS variables available in the forecast output are missing in the products
### What is wrong?

There are a few variables missing in the products for GEFS. In particular, the following variables are missing for atmos_prod:

1. CLMR
2. HCDC
3. LCDC
4. MCDC

### What should have happened?

These variables should be included in the products. It is recommended to include these variables in the GEFS reforecast products on HPSS. 

### What machines are impacted?

All or N/A

### What global-workflow hash are you using?

8f0541cd61755e74e1f3116dedcc3afc8fa9cda1

### Steps to reproduce

1. Run GEFS global-workflow up to atmos_prod

### Additional information

The atmosphere variables specified above are available in the master files, but not the atmos_prod (pgrb) files. This issue is occurring due to incorrect variable names in [parm/product/gefs.0p25.fFFF.paramlist.b.txt](https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/product/gefs.0p25.fFFF.paramlist.b.txt). For example, "CLWMR" should be changed to "CLMR" in the parm file.  

### Do you have a proposed solution?

Modifying `parm/product/gefs.0p25.fFFF.paramlist.b.txt` to include the correct variable names should resolve the issue.

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
# Description

Corrections were made to the GEFS variable names in the parm files so that they can be successfully extracted from the atmos master files in the atmos_prod task.

Resolves #2967 

# Type of change
- [x] Bug fix (fixes something broken)
- [ ] New feature (adds functionality)
- [ ] Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?

This PR was tested on WCOSS2 using a GEFS CI run. 

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] I have made corresponding changes to the system documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by EricSinsky-NOAA** [comment]
The WCOSS2 test was successful. The variables originally missing from pgrb are now being produced in `atmos_prod`.

**Comment by EricSinsky-NOAA** [comment]
@WalterKolczynski-NOAA I don't believe the reasons for the `C96C48_hybatmDA` CI test failure are related to the changes made in this PR.

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA I don't believe the reasons for the `C96C48_hybatmDA` CI test failure are related to the changes made in this PR.

Agreed. Not sure why the model would suddenly be blowing up now.

**Comment by WalterKolczynski-NOAA** [comment]
Hercules failure is unrelated to this PR. It passes on Hera, so I am going to merge.

**Pull request merged**
