### PR TITLE
[DO NOT CLOSE (see  RDHPCS Helpdesk response)] Weekly CI Tests Friday Jan 05, 2024

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Jan 05, 2024

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
Hera failed with an MPI layout issue in gfs analcalc causing aprun's MPI collective operations to fail under slurm when running `calc_anl.x`

```
srun -n 127 --verbose --export=ALL /scratch1/NCEPDEV/stmp2/Terry.McGuinness/RUNDIRS/C384C192_hybatmda_e54438e5/analcalc.300847/calcanl_ensres_06/calc_anl.x submitted
srun: Warning: can't honor --ntasks-per-node set to 40 which doesn't match the requested tasks 127 with the number of requested nodes 4. Ignoring --ntasks-per-node.
```

With the subsequent MPI-I/O system errors:

```
ADIOI_GEN_SetLock:: Cannot send after transport endpoint shutdown ADIOI_GEN_SetLock:offset 67270586, length 524288
Abort(1) on node 53 (rank 53 in comm 0): application called
MPI_Abort(MPI_COMM_WORLD, 1) - process 53
This requires fcntl(2) to be implemented. As of 8/25/2011 it is not.
Generic MPICH Message: File locking failed in ADIOI_GEN_SetLock(fd 15,cmd
F_SETLK64/6,type F_UNLOCK/2,whence 0) with return value FFFFFFFF and errno 6C.
```

@aerorahul Its discrepancy has been sent to the RDHPCS Help desk.
It is currently being processed as ticket number **2024011054000182**.

@DavidHuber-NOAA / @WalterKolczynski-NOAA
A quick turn around from the RDHPCS Help Desk Analyst Wei Yu recomended to use the following MPI Hint flags:
```
export ROMIO_PRINT_HINTS=1
export I_MPI_EXTRA_FILESYSTEM=1
export I_MPI_EXTRA_FILESYSTEM_LIST=lustre
```

**Comment by TerrenceMcGuinness-NOAA** [comment]
The fails on Orion were with accessing staged executables needed by **srun** on` /stmp` at runtime on the compute nodes that were indeed there on the head nodes:
```

mterry (Orion-login-3) ~ $ grep "couldn't chdir to" /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2202/RUNTESTS/COMROT/C384_atm3DVar_e54438e5/logs/2023040200/gfsfcst.log | tail -4
  80: slurmstepd: error: couldn't chdir to `/work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306': No such file or directory: going to /tmp instead
  80: slurmstepd: error: couldn't chdir to `/work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306': No such file or directory: going to /tmp instead
  80: slurmstepd: error: couldn't chdir to `/work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306': No such file or directory: going to /tmp instead
  80: slurmstepd: error: couldn't chdir to `/work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306': No such file or directory: going to /tmp instead
mterry (Orion-login-3) ~ $ 
```
```
mterry (Orion-login-3) ~ $ file /work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306/ufs_model.x
/work/noaa/stmp/mterry/RUNDIRS/C384_atm3DVar_e54438e5/fcst.266306/ufs_model.x: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=ac4e1f1a1d8b6303c3479c0a59513023ab71e11b, not stripped
```

Purged /stmp and will report these discrepancies  to RDHPC Helpdesk as we have seen similar anomalies on Hercules.  We suspect my be related to a known Luster issue  with Rocky 9 and this information  may be helpful to the System Admins.

**Comment by DavidHuber-NOAA** [comment]
The log file for Orion is reporting the following error:

```[Orion-24-70:306707:0:306707]     address.c:1052 Assertion `*addr_version == UCP_OBJECT_VERSION_V2' failed: addr version 8```

I reported this to the Orion admins.  Issue number 2024010854000105.

**Comment by TerrenceMcGuinness-NOAA** [comment]
```
mterry (Orion-login-3) 2016070100 $ tail -3 gfsocnpost_f090-f102.log.0
+ run_reg2grb2.sh[66]: ln -sf /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2202/global-workflow/fix/reg2grb2/mask.0p25x0p25.grb2 ./iceocnpost.g2
+ run_reg2grb2.sh[67]: /work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2202/global-workflow/exec/reg2grb2.x
slurmstepd: error: *** JOB 16197778 ON Orion-01-02 CANCELLED AT 2024-01-08T17:35:21 DUE TO TIME LIMIT ***
mterry (Orion-login-3) 2016070100 $ 
```

Timed out after making link.  Restarted.

**Pull request closed without merging**
