### PR TITLE
add variable tob in diag_table

### LINKED ISSUE #2104: add tob in ocean output
### What new functionality do you need?

@pjpegion informed to Gwen and me that fisheries are working on marine heatwaves, and they need the bottom temperature from the ocean, which is a variable available in MOM6 (tob).

### What are the requirements for the new functionality?

add variable "tob" in diag_table so that this variable will be in ocean output file

### Acceptance Criteria

variable "tob" be in ocean output file. To make it consistency between g-w and rt.sh, I will also add this variable in rt.sh through a mini PR (https://github.com/ufs-community/ufs-weather-model/issues/2019)

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by jiandewang**
# Description
This PR address issue #2104. Variable "tob" is added in diag_table to meet requirement fisheries (per @pjpegion it is required to add variable "tob" in ocean output as fisheries are working on marine heatwaves which needs this variable).
 
Resolves #2104 

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
S2SW test run on wcoss2

# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by jiandewang** [comment]
see cactus /lfs/h2/emc/couple/noscrub/Jiande.Wang/Wei-IC/C768/work-2d/COMROT/test2019120300/gfs.20191203/00/model_data/ocean/history/ocn2019120303.000.2019120300.nc

ncdump -c indicates this variable is in output now:
float tob(time, yh, xh) ;
                tob:_FillValue = -1.e+34f ;
                tob:missing_value = -1.e+34f ;
                tob:units = "degC" ;
                tob:long_name = "Sea Water Potential Temperature at Sea Floor" ;

**Comment by HenryRWinterbottom** [comment]
> # Description
> # Type of change
> 
>     * New feature (adds functionality)
> 
> 
> # Change characteristics
> 
>     * Is this a breaking change (a change in existing functionality)? NO
> 
>     * Does this change require a documentation update? NO
> 
> 
> # How has this been tested?
> 
> S2SW test run on wcoss2
> # Checklist
> 
>     * [ ]  Any dependent changes have been merged and published
> 
>     * [x ] My code follows the style guidelines of this project
> 
>     * [x ] I have performed a self-review of my own code
> 
>     * [ ]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x ] My changes generate no new warnings
> 
>     * [x ] New and existing tests pass with my changes
> 
>     * [ ]  I have made corresponding changes to the documentation if necessary

@jiandewang Please add information to **Description** such that we have a record of what was changed. We can see the file change but we also log the changes within our PRs.

**Comment by jiandewang** [comment]
@HenryWinterbottom-NOAA just added a short description under "type of changes"

**Comment by HenryRWinterbottom** [comment]
@jiandewang Please use this PR as an example: https://github.com/NOAA-EMC/global-workflow/pull/2103

**Review by aerorahul — APPROVED** [review]

**Comment by WalterKolczynski-NOAA** [comment]
@jiandewang That info should be in the "Description" section, which is a separate section from "Type of Change". Please read the instructions for that section (they are there as a comment you'll see when you go to edit).

**Comment by jiandewang** [comment]
how about now ?

**Comment by HenryRWinterbottom** [comment]
> # Description
> 
> This PR address issue #2104. Variable "tob" is added in diag_table to meet requirement fisheries (per @pjpegion it is required to add variable "tob" in ocean output as fisheries are working on marine heatwaves which needs this variable).
> 
> resolve issue #2104
> # Type of change
> 
>     * New feature (adds functionality)
> 
> 
> # Change characteristics
> 
>     * Is this a breaking change (a change in existing functionality)? NO
> 
>     * Does this change require a documentation update? NO
> 
> 
> # How has this been tested?
> 
> S2SW test run on wcoss2
> # Checklist
> 
>     * [ ]  Any dependent changes have been merged and published
> 
>     * [x ] My code follows the style guidelines of this project
> 
>     * [x ] I have performed a self-review of my own code
> 
>     * [ ]  I have commented my code, particularly in hard-to-understand areas
> 
>     * [x ] My changes generate no new warnings
> 
>     * [x ] New and existing tests pass with my changes
> 
>     * [ ]  I have made corresponding changes to the documentation if necessary

Please correct the checklist. The `[x ]` is breaking the template. Please change to `[x]`.

**Comment by jiandewang** [comment]
@HenryWinterbottom-NOAA done

**Comment by HenryRWinterbottom** [comment]
@jiandewang This is still incorrect: `[x ] I have performed a self-review of my own code`.

**Comment by jiandewang** [comment]
> @jiandewang This is still incorrect: `[x ] I have performed a self-review of my own code`.

thanks for the careful checking, just corrected that

**Comment by HenryRWinterbottom** [comment]
@jiandewang Thank you.

@WalterKolczynski-NOAA I believe this is correct now.

**Pull request merged**
