### PR TITLE
Turn on high-frequency output in extended test

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
# Description
Turns on high-frequency (hourly) output in the extended products test to exercise that aspect of the code. This test only runs on WCOSS.

Also adds the hooks to optionally turn on the metplus jobs, but that is deferred as they are not currently working correctly.

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- Extended test on WCOSS

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Looks reasonable.

**Review by KateFriedman-NOAA — APPROVED** [review]
Looks good, thanks @WalterKolczynski-NOAA !

**Comment by TerrenceMcGuinness-NOAA** [comment]
Here Build failed on checkout cloning:

```
fatal: clone of 'https://github.com/NOAA-EMC/GSI.git' into submodule path '/scratch1/NCEPDEV/global/CI/2679/gfs/sorc/gsi_enkf.fd' failed
Failed to clone 'sorc/gsi_enkf.fd'. Retry scheduled
Cloning into '/scratch1/NCEPDEV/global/CI/2679/gfs/sorc/gsi_enkf.fd'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 4431 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/NOAA-EMC/GSI.git' into submodule path '/scratch1/NCEPDEV/global/CI/2[67](https://jenkins.epic.oarcloud.noaa.gov/job/global-workflow/job/EMC-Global-Pipeline/view/change-requests/job/PR-2679/2/pipeline-console/?start-byte=0&selected-node=74#log-67)9/gfs/sorc/gsi_enkf.fd' failed
Failed to clone 'sorc/gsi_enkf.fd' a second time, aborting
```

**Comment by WalterKolczynski-NOAA** [comment]
Will wait a bit and try again

**Comment by DavidHuber-NOAA** [comment]
The `gfsatmos_prod_f099-f105` job failed on Hercules due to the job taking too long.  I suspect a bad node and will reboot the testing.

**Comment by DavidHuber-NOAA** [comment]
Checking manually, all tests passed on Hera, removing the tag.

**Comment by TerrenceMcGuinness-NOAA** [comment]
@DavidHuber-NOAA No **C96_atmaerosnoDA** on Hera is still running.  Put label back to running .`emcbot` will mark if SUCCESS when archive is done in just a sec.

**Comment by DavidHuber-NOAA** [comment]
Great, thanks @TerrenceMcGuinness-NOAA!

**Pull request merged**
