### PR TITLE
enkf_chgres_recenter_nc.fd - Remove hard-coded vertical levels.

### PR DESCRIPTION
**Pull request by GeorgeGayno-NOAA**
The enkf_chgres_recenter_nc program was updated to interpolate to any number of vertical levels.  Previously, the program was hard-wired to output the same vertical levels as the input data.  Supports GEFS-CHEM. 

For details, see issue #102.

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good to me, please merge in coordination with the associated GSI PR: https://github.com/NOAA-EMC/GSI/pull/54

**Comment by KateFriedman-NOAA** [comment]
> Looks good to me, please merge in coordination with the associated GSI PR: [NOAA-EMC/GSI#54](https://github.com/NOAA-EMC/GSI/pull/54)

We have some other PRs in the works so make sure to update this branch if they go in first. Let me know when the GSI PR is ready and I will submit this. Thanks!

**Comment by RussTreadon-NOAA** [comment]
The GSI PR has been approved.  The GSI merge into release/gfsda.v16.0.0 will take place whenever this workflow PR is merged into feature/gfsv16b.

**Comment by KateFriedman-NOAA** [comment]
> The GSI PR has been approved. The GSI merge into release/gfsda.v16.0.0 will take place whenever this workflow PR is merged into feature/gfsv16b.

Okie dokie, approving and submitting!

**Comment by RussTreadon-NOAA** [comment]
GSI [PR#54](https://github.com/NOAA-EMC/GSI/pull/54) has been merged into release/gfsda.v16.0.0.  Done at [df2581c](https://github.com/NOAA-EMC/GSI/commit/df2581cec06ec55fc83175bf2114a051712276b0)

**Pull request merged**
