### PR TITLE
Convert v16.3.8 to satingest update instead of obsproc

### PR DESCRIPTION
**Pull request by ADCollard**
**Description**

This is a temporary fix to allow the `satingest` changes to be implemented on August 29 without causing GSI to crash.   Issue with the CRTM means that GSI will crash unless NOAA-21 radiances are switched off.   

Obsproc version numbers should remain unchanged unless the `obsproc` changes are implemented before or at the same time as the `satingest` changes.

**Type of change**

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

Single cycle test on Hera.  Results are unchanged.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks fine to me.

**Comment by WalterKolczynski-NOAA** [comment]
Please also create a new issue to update `exglobal_atmos_analysis.sh` in develop when you get the chance (all the scripts were moved to global-workflow).

**Comment by ADCollard** [comment]
@WalterKolczynski-NOAA Would you be able to merge this PR and tag with [https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.8](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.8)?  This needs to be part of @ilianagenkova 's `satingest` implementation (scheduled for August 29).

I see this is failing the readthedocs test.   Is this expected behavior (I cannot see how my changes would cause this)

I will not update `exglobal_atmos_analysis.sh` in develop as this should only be a temporary change.

**Comment by WalterKolczynski-NOAA** [comment]
RTD building was added long after the v16 branch, so just ignore it.

I was waiting for @ilianagenkova to approve before merging. If this is all that is needed for the release, I will then tag it. But it should be tested _before_ I tag it.

**Comment by ADCollard** [comment]
@WalterKolczynski-NOAA Thanks!

I just added @RussTreadon-NOAA as @ilianagenkova just got on a plane to Bulgaria!  I spoke with Iliana by phone and she was happy with what I said I had done.

I am running one full cycle test.  I will confirm tomorrow with you that it works.

**Comment by ADCollard** [comment]
@WalterKolczynski-NOAA As you may have seen, I got the go ahead to add a couple of sensor updates to this PR.   So I really want to test it with those changes before you tag.    I am waiting for a new GSI tag to be created right now (need some approvals).

I am going to move ahead with the CDF this afternoon and will assume that [tag/EMC-v16.3.8](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.8) will be available before NCO take a look.

Thanks.

**Review by XuanliLi-NOAA — APPROVED** [review]

**Review by aerorahul — APPROVED** [review]
looks ok to me.

**Review by RussTreadon-NOAA — APPROVED** [review]
Changes are consistent with information presented in this PR and GSI PRs [#611](https://github.com/NOAA-EMC/GSI/pull/611) and [#612](https://github.com/NOAA-EMC/GSI/pull/612).

**Comment by WalterKolczynski-NOAA** [comment]
@ADCollard If more changes need to be made for this release, please open a new PR with the additional changes. Then once the final version is tested we'll tag it.

**Comment by ADCollard** [comment]
@WalterKolczynski-NOAA @aerorahul Can you tag https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.8 as EMC-v16.3.8?  I have promised this to NCO by Monday morning!

Should I start a new issue or repurpose #1356 which concerns an upgrade that was originally going to be 16.3.8, but has since slipped?

**Pull request merged**
