### PR TITLE
Hotfix: Update jcb to avoid git-lfs files

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
# Description
Removes git-lfs files from the `GDASApp` `jcb` submodule, allowing it to be cloned on Hera.

This hotfix points to a non-authoritative branch of the GDASApp (https://github.com/DavidHuber-NOAA/GDASApp/tree/hotfix/update_jcb) and should be updated ASAP back to the authoritative repository.

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Clone and build on Hera.  CI unit tests also pass.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
Thanks for doing this @DavidHuber-NOAA

**Comment by RussTreadon-NOAA** [comment]
GDASApp PR [#1230](https://github.com/NOAA-EMC/GDASApp/pull/1230) updates the `sorc/jcb` hash in GDASApp `develop`.  

Once GDASApp PR [#1230](https://github.com/NOAA-EMC/GDASApp/pull/1230) is approved and merged into GDASApp `develop`, the `sorc/gdas.cd` hash in `DavidHuber-NOAA:hotfix/update_jcb` should be updated to point at the new GDASApp `develop` instead of  https://github.com/DavidHuber-NOAA/GDASApp/tree/hotfix/update_jcb

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA Do you anticipate any changes required to the global-workflow to support the other updates to the GDASApp (hashes https://github.com/NOAA-EMC/GDASApp/commit/c303d99dd991608271ea71e1564cf107167763d7 through https://github.com/NOAA-EMC/GDASApp/commit/c5ead8538f0002dfb0145c34311722db20ab0e93)?

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA , good question.  

@guillaumevernieres merged GDASApp PR [#1230](https://github.com/NOAA-EMC/GDASApp/pull/1230) into GDASApp `develop` at [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50).  Let me install your branch with GDASApp `develop` at [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50) and run g-w JEDI CI.

**Review by aerorahul — APPROVED** [review]
Thanks for the hotfix.

**Comment by RussTreadon-NOAA** [comment]
@DavidHuber-NOAA and @aerorahul , may we reopen this PR since the `jcb` has been updated in GDASApp `develop`?

Installs of `DavidHuber-NOAA:hotfix/update_jcb` with the current [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50) head of GDASApp `develop` are underway on Hercules and Hera.  

As Dave notes [above](https://github.com/NOAA-EMC/global-workflow/pull/2782#issue-2422739084) we should update `sorc/gdas.cd` to an authoritative GDASApp hash ASAP.  This is now possible.  Update `sorc/gdas.cd` to [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50).

**Comment by guillaumevernieres** [comment]
> @DavidHuber-NOAA and @aerorahul , may we reopen this PR since the `jcb` has been updated in GDASApp `develop`?
> 
> Installs of `DavidHuber-NOAA:hotfix/update_jcb` with the current [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50) head of GDASApp `develop` are underway on Hercules and Hera.
> 
> As Dave notes [above](https://github.com/NOAA-EMC/global-workflow/pull/2782#issue-2422739084) we should update `sorc/gdas.cd` to an authoritative GDASApp hash ASAP. This is now possible. Update `sorc/gdas.cd` to [`e9252e1`](https://github.com/NOAA-EMC/GDASApp/commit/e9252e1c49f4f4a1a2ffb61f3b380d37ee103f50).

@RussTreadon-NOAA : 
@DavidHuber-NOAA only updated the jcb # (same #'s for the other repos), which shouldn't require to re-run all the ci. Updating to a more recent gdas.cd # should be consolidated with an other pr.

**Comment by RussTreadon-NOAA** [comment]
Thank you @guillaumevernieres .  Understood.  I was hoping to make the process more agile and get recent GDASApp development into g-w `develop` sooner rather than later given the new management target for a full JEDI transition.  

As you note we have several GDASApp PRs in the g-w queue.  One or more can be updated with recent changes to GDASApp.

**Pull request merged**
