### PR TITLE
Update namelist settings for prototype 7c

### LINKED ISSUE #386: P7: Update input nameless
All namelist values need to be checked and confirmed that the correct options are being used for all components. 
Tracking some of this being done in the google doc [here](https://docs.google.com/document/d/1KxrmA74qqu6jMkjQqREbQfuApSksoSozSLKdlv_oGuE/edit?usp=sharing). 

The namelist that we know need updating for now are: 
* LANDICE should be false 
* Check uGWD settings 
* The following for 
ialb=2
iems=2
lsm=2 
iopt_dveg=4
iopt_crs=2
iopt_rad=3
iopt_alb=1
iopt_stc=3

* Use recommended CA settings from Lisa: These are the settings we recommend for the CA, under the namelist  block &gfs_physics_nml. Note that iseed_ca can be set to the ensemble member number if used in an ensemble forecast. 
  do_ca          = .True.
  ca_sgs         = .True.
  nca            = 1
  scells         = 2600
  tlives         = 1800
  nseed          = 1
  nfracseed      = 0.5
  rcell          = 0.72
  ca_trigger     = .True.
  nspinup        = 1
  iseed_ca       = 12345

There might be more as we continue to check the settings for the various different physics options and all components.

### PR DESCRIPTION
**Pull request by WalterKolczynski-NOAA**
Several namelist settings are updated for prototype 7c.

A large number of the settings are tied to Noah-MP, so those settings
are now set alongside the lsm, but mostly accept overrides.

Another group of settings are related to cellular automata and are
only added to the namelist if a new setting, DO_CA, is set to YES.
The setting defaults to on (YES).

Two other settings, IALB and IEMS, are not confirmed to be tied to
other settings, so the defaults for these are just straightfowardly
changed to the new values.

Closes: #386

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
input.nml: https://gist.github.com/WalterKolczynski-NOAA/ad1ba47aa768a8b2808bbf3b1b6d6ec4

**Comment by WalterKolczynski-NOAA** [comment]
input.nml gist updated

**Comment by WalterKolczynski-NOAA** [comment]
input.nml gist updated again

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Thanks @WalterKolczynski-NOAA

**Pull request merged**
