### PR TITLE
Update global_cycle for fractional grid

### LINKED ISSUE #1775: Update global_cycle for fractional grid
**Description**
Global_cycle within the global-workflow does not currently support fractional grids.  There is an issue ([#549](https://github.com/ufs-community/UFS_UTILS/issues/549)) and draft PR ([#815](https://github.com/ufs-community/UFS_UTILS/pull/815)) within UFS_UTILS to address this gap.  This issue is a placeholder for any needed global-workflow changes to accompany that PR.

**Requirements**
Must be able to run in the deterministic as well as the ensemble portion of cycled mode.

**Acceptance Criteria (Definition of Done)**
Being able to run global_cycle with frac grid on from within the global-workflow in cycled mode (ATM-only, hybrid 4DEnVar) without failure and using the scientifically correct fields in its computations.

### PR DESCRIPTION
**Pull request by CatherineThomas-NOAA**
# Description
The hash for ufs_utils is updated to include the changes for fractional grid support within global_cycle.  This commit also removes the hack to skip global_cycle in cycling mode with v17 physics.

Resolves: #1775
Refs: ufs-community/UFS_UTILS [PR#815](https://github.com/ufs-community/UFS_UTILS/pull/815), [PR#891](https://github.com/ufs-community/UFS_UTILS/pull/891)

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
3.5 cycles on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by CatherineThomas-NOAA** [comment]
@GeorgeGayno-NOAA for awareness

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA 
Can you please merge `develop` in this branch so we can kick off the tests? 
Thanks!

**Comment by CatherineThomas-NOAA** [comment]
@aerorahul - Develop is merged.  Thanks for approving!

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA @jiaruidong2017 
There seems to be an inconsistency in the variable `sheleg` in the `sfc_data.tileX.nc` arising that the model cannot understand.
```
 0: FATAL from PE     0: The checksum in the file:INPUT/sfc_data.tile1.nc and variable:sheleg does not match the checksum calculated from the data. fi
le:9F0FAC4226EB5D9E from data:512B00FA13EBF76C
```

**Comment by jiaruidong2017** [comment]
> @CatherineThomas-NOAA @jiaruidong2017 There seems to be an inconsistency in the variable `sheleg` in the `sfc_data.tileX.nc` arising that the model cannot understand.
> 
> ```
>  0: FATAL from PE     0: The checksum in the file:INPUT/sfc_data.tile1.nc and variable:sheleg does not match the checksum calculated from the data. fi
> le:9F0FAC4226EB5D9E from data:512B00FA13EBF76C
> ```

This is in the half-cycle forecast step, not getting to the snow DA step yet. I think the mismatch may result from using Noah-MP model, but the initial conditions from `INPUT/sfc_data.tile1.nc` are from Noah model. As I remember, one possible solution is to remove the checksum. @GeorgeGayno-NOAA @barlage may provide more help on this.

**Comment by jiaruidong2017** [comment]
CORRECTION to my previous response:

After more investigations, the inconsistency in the `checksum` of the variable `sheleg` resulted from the snow DA analysis which modified these snow related variables including `sheleg`. Currently, the method to avoid these inconsistency is to remove the `checksum` to these modified variables in the `global_cycle`.

**Comment by GeorgeGayno-NOAA** [comment]
global_cycle was recently updated to remove the checksum attribute as it updates the model restart file.

https://github.com/ufs-community/UFS_UTILS/blob/develop/sorc/global_cycle.fd/read_write_data.f90#L182

**Comment by jiaruidong2017** [comment]
Thanks @GeorgeGayno-NOAA. Following your implementation in `global_cycle`, I proposed to remove the checksum attribute to the modified snow related variables during the snow DA analysis in the PR https://github.com/NOAA-PSL/land-apply_jedi_incr/pull/4. I have tested it and it worked. Once @ClaraDraper-NOAA reviews and merges it into develop, we will update the commit hash in GDASApp and make test here.

**Comment by aerorahul** [comment]
@CatherineThomas-NOAA 
Would you be able to merge `develop` in your branch and update the hash of `gdasapp` to latest develop?  We can then kick-off the test again.
Thanks!

**Comment by jiaruidong2017** [comment]
@CatherineThomas-NOAA The https://github.com/NOAA-EMC/GDASApp/pull/899 is merged, and the commit hash is 831b08a3f947e8d743e2afbd6d38ecc4b0dec3b1. Would you want to include the updates of GDASApp in this PR? Thanks.

**Comment by CatherineThomas-NOAA** [comment]
@aerorahul @jiaruidong2017 
My fork has been updated to the latest GDASApp hash and merged with the latest develop.

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
