### PR TITLE
 land surface upgrades for hr4

### LINKED ISSUE #2786: land surface upgrades for HR4
### What new functionality do you need?

opt_diag needs to be set to 2 corresponding to the land surface upgrades for HR4

### What are the requirements for the new functionality?

the default value of opt_diag should be changed to 2 from 1

### Acceptance Criteria

change the default value of opt_diag to 2 in parsing_namelists_FV3.sh and parsing_namelists_FV3_nest.sh

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by HelinWei-NOAA**
# Description

This PR:

- reset the default value of opt_diag to 2 corresponding to the land surface upgrades in ufs-weather-model for hr4 

  Resolves [#2786 ](https://github.com/NOAA-EMC/global-workflow/issues/2786)
 
-->

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved

**Comment by DavidHuber-NOAA** [comment]
> /scratch1/NCEPDEV/global/CI/2787/RUNTESTS/COMROOT/C48_S2SW_54e5d447/logs/2021032312/gfsmetpg2o1.log

This failure is a bug in METplus.  See [this comment](https://github.com/NOAA-EMC/global-workflow/pull/2791#issuecomment-2260424914).  One potential workaround would be to decrease the number of tasks for Grid2Obs to 1.  However, Grid2Obs already takes a long time to run in operations and decreasing the task count from 4 to 1 would significantly increase that runtime.

Since METplus version 9 is no longer supported by the DTC, the likelihood of a bug fix is small.

For the time being, I will manually set the number of METplus tasks to 1 and continue testing.

**Comment by DavidHuber-NOAA** [comment]
I am not the owner of the CI tests on Hera, so I cannot relaunch this job after all.  However, the `gfsmetpg2o1` job is the only failure and I believe that means this is a passed test, so I will set the label as such.

**Review by RuiyuSun — COMMENTED** [review]
fine to me.

**Pull request merged**
