### PR TITLE
Merging develop to feature/efsoi in anticipation of PR from EFSOI development branch

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
**Description**

This PR is to merge current the  g-w develop branch to feature/efsoi in order to minimize differences between EFSOI development fork and branch and feature/efsoi

In support of https://github.com/NOAA-EMC/global-workflow/issues/673

**Type of change**

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Same as develop

- [ ] Cycled test on Orion

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
Since this is just bringing the efsoi branch up-to-date, I'm assuming this is just so you can check it yourself and aren't looking for a review.

**Comment by AndrewEichmann-NOAA** [comment]
@WalterKolczynski-NOAA That's correct - how do I check it in myself? I've only pushed merges to my own fork on the CLI.

**Comment by aerorahul** [comment]
@AndrewEichmann-NOAA I can work with you on resolving this.
I am going to close this PR as it is not really a PR into `develop`.

**Comment by AndrewEichmann-NOAA** [comment]
ok, thanks

**Comment by aerorahul** [comment]
`feature/efsoi` has been rebased on `develop` at fd771cb8.  
Please open a PR with your changes against `feature/efsoi`

**Pull request closed without merging**
