### PR TITLE
Update ufs-weather-model hash

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
This PR simply updates the hash of the ufs-weather-model.
Tagging @NeilBarton-NOAA @bingfu-NOAA @rmontuoro  for awareness

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? No
- Does this change require a documentation update? No

# How has this been tested?
CI testing should suffice.

# Checklist
- [X] Any dependent changes have been merged and published
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [X] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
Looks like there are some settings updates that should go along with the hash update when looking at the compare: https://github.com/ufs-community/ufs-weather-model/compare/GFSv17.HR2...develop 


Editing to add the section where I think we might be missing updates that we'll want. 
Screenshot 2023-09-15 at 2 03 06 PM

**Comment by aerorahul** [comment]
> Looks like there are some settings updates that should go along with the hash update when looking at the compare: [ufs-community/ufs-weather-model@GFSv17.HR2...develop](https://github.com/ufs-community/ufs-weather-model/compare/GFSv17.HR2...develop)
> 
> Editing to add the section where I think we might be missing updates that we'll want. Screenshot 2023-09-15 at 2 03 06 PM

Thank you @JessicaMeixner-NOAA 
Would you recommend I hold off on updating the hash until a more complete update is available?

**Comment by JessicaMeixner-NOAA** [comment]
@aerorahul I think we should.  More details can be seen here : https://github.com/NOAA-EMC/global-workflow/issues/1811 and hopefully @DeniseWorthen can weigh in on this as well.

**Comment by aerorahul** [comment]
> @aerorahul I think we should. More details can be seen here : #1811 and hopefully @DeniseWorthen can weigh in on this as well.

Sounds good.
I will close this PR and let the appropriate teams open a PR with all the relevant changes necessary for consistent model  configurations.

**Pull request closed without merging**
