### PR TITLE
Add downstream wave jobs to GFSv16

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
New jobs:
- gfswavegempak
- gfswaveawipsgridded
- gfswaveawipsbulls

New files:
- jobs/rocoto script for each job
- config for each job
- if-block in config.resources for each job
- modulefile

Changes:
- updates to wave scripts from recent commit
- rename scripts/exgfswave_prdgen_gridded.sh → scripts/exgfs_wave_prdgen_gridded.sh
- add new jobs to setup scripts

Dependencies:
- gfswaveawipsbulls <-- gfswavepostsbs job complete
- gfswavegempak & gfswaveawipsgridded <-- data dependency:
```
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.arctic.9km.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.atlocn.0p16.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.epacif.0p16.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.global.0p16.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.global.0p25.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.gsouth.0p25.f000.grib2</cyclestr></datadep>
<datadep><cyclestr>&ROTDIR;/gfs.@Y@m@d/@H/wave/gridded/gfswave.t@Hz.wcoast.0p16.f000.grib2</cyclestr></datadep>
```

Notes: 
- OPC will now test gempak output from v16 parallel on their system
- Fix coming in near future to handle character change in gempak files (the "C" in ICEC and the
"F" on the first forecast time "F000" are missing inside the gempak files - Roberto)

For users:
- set the following in config.base to get downstream wave jobs in xml:
```
set DO_GEMPAK="YES"
set DO_AWIPS="YES"
set DO_WAVE="YES"
```
- regenerate EXPDIR and xml

### CODE REVIEW

**Review by RussTreadon-NOAA — COMMENTED** [review]
Once tested and confirmed to work ,merge.

**Comment by KateFriedman-NOAA** [comment]
Forgot to include testing info:

- used v16rt2 output as inputs to downstream wave jobs
- symlinked all v16rt2 output in testing comrot
- rocotoboot-ed three jobs
- no full cycle run, just individual jobs in full system setup

**Comment by yangfanglin** [comment]
Is the splitting of wavepost job still not included ?

**Comment by KateFriedman-NOAA** [comment]
> Is the splitting of wavepost job still not included ?

That will be a separate commit. This is just to add the new downstream wave jobs.

**Comment by yangfanglin** [comment]
OK, understand now.  I cannot do a detailed review as I have a few things at hand to complete.  If your test is working and the products have been checked by Roberto then it is fine to merge.

**Pull request merged**
