### PR TITLE
Remove hardwired ImageMagick path for file util/ush/make_tif.sh

### LINKED ISSUE #534: WCOSS2 transition issue - Hardwired DELL path util/ush/make_tif.sh
Line 14-16 contain hardwired dell PATH.

  export PATH=$PATH:/usrx/local/dev/packages/ImageMagick/6.9.9-25/bin:.
  export LIBPATH="$LIBPATH":/usrx/local/dev/packages/ImageMagick/6.9.9-25/lib
  export DELEGATE_PATH=/usrx/local/dev/packages/ImageMagick/6.9.9-25/share/ImageMagick-6

Need to be fixed to create tif product images.

### PR DESCRIPTION
**Pull request by lgannoaa**
**Description**

gfs_atmos_gempak_upapgif used hardwired path for ImageMagick utility as noted in issue #534. It is now removed.
**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

All 31 image files were successfully generated in the test run.

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Changes look good.
I have not tested this changeset.

I think this utility is not used on all platforms, since some platforms might have the imagemagick module missing.

It is only used in operations on WCOSS.
Assuming these variables defined in the imagemagick modulefile, this should be sufficient.

**Comment by KateFriedman-NOAA** [comment]
Has @WeiWei-NCO tested this update on WCOSS2 yet and/or approved the update offline?

**Comment by lgannoaa** [comment]
> Has @WeiWei-NCO tested this update on WCOSS2 yet and/or approved the update offline?
This change will work for NCO. I do not see a need to involve Wei Wei for this testing.

**Comment by KateFriedman-NOAA** [comment]
> This change will work for NCO. I do not see a need to involve Wei Wei for this testing.

This change is going into the branch intended for ops on WCOSS2 for GFSv16.2.0. Therefore, it must be tested and/or approved by NCO/Wei, particularly at this stage now that the GFS has moved into prod space on WCOSS2 and is running in real-time. Wei can test the change in side testing (or prod if he wishes) to confirm it will work as intended before we commit this ahead of cutting final tags. Please contact Wei about this update. If he tests the change (and it works) or he approves the update without testing then I am happy to approve and merge this update into `feature/ops-wcoss2`. Thanks!

**Review by WalterKolczynski-NOAA — APPROVED** [review]
We'll need to add imagemagick to the dev modulefiles later, but this is fine for now.

**Comment by WeiWei-NCO** [comment]
> > This change will work for NCO. I do not see a need to involve Wei Wei for this testing.
> 
> This change is going into the branch intended for ops on WCOSS2 for GFSv16.2.0. Therefore, it must be tested and/or approved by NCO/Wei, particularly at this stage now that the GFS has moved into prod space on WCOSS2 and is running in real-time. Wei can test the change in side testing (or prod if he wishes) to confirm it will work as intended before we commit this ahead of cutting final tags. Please contact Wei about this update. If he tests the change (and it works) or he approves the update without testing then I am happy to approve and merge this update into `feature/ops-wcoss2`. Thanks!

Tested in para/canned environment. Look good. Thanks.

**Comment by KateFriedman-NOAA** [comment]
Thanks @WeiWei-NCO for testing and confirming it works on your end. Thanks for making this change @lgannoaa . Merging this PR into `feature/ops-wcoss2` now.

**Comment by KateFriedman-NOAA** [comment]
Close #534

**Pull request merged**
