### PR TITLE
Add ush/soca to ocean vrfy pythonpath

### PR DESCRIPTION
**Pull request by AndrewEichmann-NOAA**
**Description**

Adds ush/soca to pythonpath in ocean vrfy task jjob in anticipation of python code to be added to said subdirectory

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Tested with GDASApp global-workflow ctests on Hera

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

### CODE REVIEW

**Comment by AndrewEichmann-NOAA** [comment]
FYI @guillaumevernieres

**Review by guillaumevernieres — APPROVED** [review]
Sure! Thanks @AndrewEichmann-NOAA .

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Looks fine for now.

**Review by aerorahul — APPROVED** [review]
Looks good.

**Comment by WalterKolczynski-NOAA** [comment]
Bypassing CI tests since the system does not excercise this job yet.

**Comment by AndrewEichmann-NOAA** [comment]
Thank you!

**Pull request merged**
