### PR TITLE
[DO NOT MERGE] Weekly CI Tests Friday Dec 15, 2023

### PR DESCRIPTION
**Pull request by emcbot**
[DO NOT MERGE] Weekly CI Tests Friday Dec 15, 2023

### CODE REVIEW

**Comment by WalterKolczynski-NOAA** [comment]
This looks like another hardware issue:
```
+ exglobal_forecast.sh[150]: srun -l --export=ALL -n 2120 /work/noaa/stmp/mterry/RUNDIRS/C384_S2SWA_ff301aab/fcst.429043/ufs_model.x
srun: error: slurm_receive_msgs: [[orion-17-28.hpc.msstate.edu]:6818] failed: Zero Bytes were transmitted or received
srun: error: slurm_receive_msgs: [[orion-04-39.hpc.msstate.edu]:6818] failed: Zero Bytes were transmitted or received
srun: error: slurm_receive_msgs: [[orion-11-52.hpc.msstate.edu]:6818] failed: Zero Bytes were transmitted or received
srun: error: slurm_receive_msgs: [[orion-13-08.hpc.msstate.edu]:6818] failed: Zero Bytes were transmitted or received
srun: error: Task launch for StepId=15980453.0 failed on node Orion-17-28: Zero Bytes were transmitted or received
srun: error: Task launch for StepId=15980453.0 failed on node Orion-04-39: Zero Bytes were transmitted or received
srun: error: Task launch for StepId=15980453.0 failed on node Orion-11-52: Zero Bytes were transmitted or received
srun: error: Task launch for StepId=15980453.0 failed on node Orion-13-08: Zero Bytes were transmitted or received
srun: error: Application launch failed: Zero Bytes were transmitted or received
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
   0: slurmstepd: error: *** STEP 15980453.0 ON Orion-01-40 CANCELLED AT 2023-12-15T18:08:24 ***
```

I've made a clean copy of the run directory so we can provide it to MSU if needs be (though maybe we wait for a lower-resolution one, or a different less expense job to fail).

@aerorahul @junwang-noaa Do we have a job card and driver script that we can provide to the helpdesk that will run a given forecast run directory (after supplying the needed resources)?

Having saved the run directory and the log, I'm going to reset the label and try again. (FYI @TerryMcGuinness-NOAA)

**Comment by TerrenceMcGuinness-NOAA** [comment]
`+ exglobal_forecast.sh[150]: srun -l --export=ALL -n 2120 /work/noaa/stmp/mterry/RUNDIRS/C384_S2SWA_ff301aab/fcst.393964/ufs_model.x
`

Both **Hera** and **Orion** fail when running `ufs_model.x` launched by _srun_ in line 150 of `exglobal_forecast.sh`

**Orion**: `/work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2165/RUNTESTS/COMROT/C384_S2SWA_ff301aab/logs/2016070100/gfsfcst.log`
**Hera**: 
`/scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/PR/2165/RUNTESTS/COMROT/C384_atm3DVar_ff301aab/logs/2023040200/gdasfcst.log`

**Comment by aerorahul** [comment]
@TerrenceMcGuinness-NOAA 
Would you please rewind the gdasfcst job on Hera?  I inspected the gfsfcst log from C384_S2SWA and that has succeeded.  I am not sure what the errors originating in `cires_tauamf_data.F90` mean.  We might need to reach out to the model developers if the rerun fails again.
Thanks!

**Comment by TerrenceMcGuinness-NOAA** [comment]
Ok, rewinding **gfsfcst** on Hera for **C384_S2SWA** now.

**Comment by aerorahul** [comment]
> Ok, rewinding **gfsfcst** on Hera for **C384_S2SWA** now.

I was requesting the rewind of `gdasfcst` on the `C384_atm3DVar_ff301aab` experiment on Hera

**Comment by TerrenceMcGuinness-NOAA** [comment]
Oh right I that makes more sense because C384_S2SWA succeeded, ok confirmed we are rewinding only _gdasfcst_ **C384_atm3DVar_ff301aab**

**Comment by TerrenceMcGuinness-NOAA** [comment]
Screen Shot 2023-12-18 at 10 07 18 AM

**Comment by TerrenceMcGuinness-NOAA** [comment]
Its now QUEUED.

_gdasfcst_ in **C384_atm3DVar_ff301aab** on **Hera** ran to completion on the second attempt:


```
Terry.McGuinness (hfe03) C384_atm3DVar_ff301aab $ diff /scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/PR/2165/RUNTESTS/COMROT/C384_atm3DVar_ff301aab/logs/2023040200/gdasfcst.log.0 /scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/PR/2165/RUNTESTS/COMROT/C384_atm3DVar_ff301aab/logs/2023040200/gdasfcst.log | grep "exit code" | grep partition
< Job 53069448 finished for user Terry.McGuinness in partition hera with exit code 137:0
> Job 53069759 finished for user Terry.McGuinness in partition hera with exit code 0:0
```

**Pull request closed without merging**
