### PR TITLE
Gaea c5 added to Jenkinsfile

### PR DESCRIPTION
**Pull request by AnilKumar-NOAA**
# Description
Added Gaea c5 to Jenkinsfile

# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA Add `- gaea` on `skip_ci_on_hosts:` for every case yaml file in the [`$HOMEgfs/ci/cases/pr`](https://github.com/AnilKumar-NOAA/global-workflow/blob/c7a35f2f08dc1bed96a9757642eecd68ddfb3ccd/ci/cases/pr/C48mx500_3DVarAOWCDA.yaml#L20) directory that is not being test on C5 Gaea

**Comment by TerrenceMcGuinness-NOAA** [comment]
@AnilKumar-NOAA Add a `config.gaea` file in `$HOMEgfs/ci/platforms` like the other ones with the allocations account **HPC_ACCOUNT** that will be running the cases you have designated above.

**JENKINS_AGENT_LANUCH_DIR** and **JENKINS_WORK_DIR** will also need to be designated and will become clear when you receive the instructions from Kris Booker about starting the Jenkins Java Agent on Gaea.

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
Left instructions  in the Conversations tab for a few more files that need to be updated and added.
@DavidBurrows-NCO @AnilKumar-NOAA  David has made these changes described above in PR #2577.  You guys need to combined these into one PR.  I will meetup with you to for a short technical brief as we workout which role account these are going to run on.

**Comment by AnilKumar-NOAA** [comment]
> Left instructions in the Conversations tab for a few more files that need to be updated and added. @DavidBurrows-NCO @AnilKumar-NOAA David has made these changes described above in PR #2577. You guys need to combined these into one PR. I will meetup with you to for a short technical brief as we workout which role account these are going to run on.

This PR has everything for ci run. we may discard other PR and focus on this one. Thanks @WalterKolczynski-NOAA @DavidBurrows-NCO

**Review by AnilKumar-NOAA — COMMENTED** [review]
Please check the updated yaml files and config.gaea as requested. Thanks Anil

**Comment by WalterKolczynski-NOAA** [comment]
I made the Gaea labels this morning. Let me know if you need anything else.

**Comment by TerrenceMcGuinness-NOAA** [comment]
PR updates look good.  I will add a PR to this branch too for the needed updates so the **Jenkinsfile** the EPIC team can use the Gaea Node in Jenkins without the EMC tag.  What remains then would be the token for GitHub CLI access to the emcbot account in the epic role account that is running the Java Agent for the Gaea Node.

**Comment by AnilKumar-NOAA** [comment]
@TerrenceMcGuinness-NOAA Thanks Terry! Will check with kris and get token access for github CLI. Thanks

**Review by TerrenceMcGuinness-NOAA — COMMENTED** [review]
These changes in the Jenkins file for generalizing the Node Names (i.e no dependancies on the *-EMC naming scheme) have already been tested and merged into the develop branch.  You may need to simply sync your branch.  Notice they are flagged as conflicts below, those have to be resolved.

**Pull request closed without merging**
