### PR TITLE
Flip the build for GFS and GEFS with waves

### LINKED ISSUE #2461: Flip GFS and GEFS default builds for waves
### What new functionality do you need?

`./build_all.sh` builds the ufs-weather-model with waves configured with a structured grid.  This is a requirement for GFSv17.
To build the ufs-weather-model with with configured with **unstructured grid**, an argument `-w` needs to be passed to `build_all.sh`.

This is often overlooked by developers and results in the model hanging for GFS configurations.

This feature requests flipping the `-w` switch where `-w` would build the ufs-weather-model with a **structured grid**. 

### What are the requirements for the new functionality?

No additional requirements than what is already there.

### Acceptance Criteria

- Updated documentation
- Passing tests for GFS and GEFS

### Suggest a solution (optional)

_No response_

### PR DESCRIPTION
**Pull request by aerorahul**
# Description
This PR:
- builds the unstructured waves as default when invoked with `build_all.sh`.
- updates the CI testing infrastructure to handle this change.
- updates the documentation to reflect this change in behaviour.

To build with structured grid for waves, the flag `-w` needs to be passed to `./build_all.sh`.  Previously, this would trigger the unstructured grid.  Since GFSv17 will move to unstructured grid as default for waves, this makes it easier for a majority of developers.

Resolves #2461 

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? YES

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Conditionally approved

**Comment by WalterKolczynski-NOAA** [comment]
This merge will need a corresponding announcement of the change.

**Comment by TerrenceMcGuinness-NOAA** [comment]
This PR just came on-line and I was doing some late night house cleaning of the Jenkins scrub space and inadvertently killed this job on Orion.  I'm restarting the Orion CI run now.

**Review by JessicaMeixner-NOAA — APPROVED** [review]
Hope this helps with the errors.  Thanks for the update @aerorahul

**Comment by aerorahul** [comment]
> Hope this helps with the errors. Thanks for the update @aerorahul

Thanks for the review.

I am not aware of any errors that this PR fixes.

I am aware that developers are accustomed to building for the GFS with `./build_all.sh` (without `-w`) and that has led to stalled forecast jobs because the forecast executable is built without unstructured grid options and the configuration requires it.

**Comment by JessicaMeixner-NOAA** [comment]
> > Hope this helps with the errors. Thanks for the update @aerorahul
> 
> Thanks for the review.
> 
> I am not aware of any errors that this PR fixes.
> 
> I am aware that developers are accustomed to building for the GFS with `./build_all.sh` (without `-w`) and that has led to stalled forecast jobs because the forecast executable is built without unstructured grid options and the configuration requires it.

@aerorahul that's what I meant by errors.

**Pull request merged**
