### PR TITLE
Feature/gfsv16 wave prdgen

### PR DESCRIPTION
**Pull request by RobertoPadilla-NOAA**

### CODE REVIEW

**Comment by KateFriedman-NOAA** [comment]
I will test these updates in another test I need to run tomorrow and then will submit this PR.

**Review by KateFriedman-NOAA — APPROVED** [review]
Changes look good and work in a test on Mars, thanks!

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @yangfanglin @lgannoaa FYI, I just submitted this PR to pull in updates from Roberto for the downstream wave jobs. I tested the downstream wave jobs on Mars without issue. I will have additional updates to commit this afternoon.

Thanks for working with Roberto on these updates Lin!

**Comment by RussTreadon-NOAA** [comment]
"git pull" executed in Mars v16rt2 $EXPDIR.   The v16rt2 is now at 340f849.

**Comment by KateFriedman-NOAA** [comment]
Thanks Russ!

Kate Friedman (formerly Howard)
NOAA/NWS/NCEP/EMC Engineering and Implementation Branch

**Pull request merged**
