### PR TITLE
Reset to develop

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Humm, looks the same. The history/commit should match with develop.
Do any of these changes make sense @RussTreadon-NOAA and @CoryMartin-NOAA ? This is reseting to the most recent develop.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
never mind, that's not going to work. I'm not sure we can do the equivalent of a forced push as a pr ...

**Comment by RussTreadon-NOAA** [comment]
@guillaumevernieres and @CoryMartin-NOAA 

I did the following on Hera in `/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/gdasapp`
- `git clone --recursive https://github.com/NOAA-EMC/global-workflow.git .`
- `git reset --hard 15eaf35f`   I think 15eaf35f is the commit at which `dev/gdasapp` was created
- clean up submodules with `git submodule update --init --recursive` in some cases.  In other cases remove unnecessary directories

I now have
```
Hera(hfe04):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/gdasapp$ git log |head
commit 15eaf35fb13f361be400be38a5f7ca7b5461ab1d
Author: Eric Sinsky - NOAA <48259628+EricSinsky-NOAA@users.noreply.github.com>
Date:   Wed Jun 12 01:15:37 2024 -0400

    Add ability to process ocean/ice products specific to GEFS (#2561)

    This PR begins to add the capability to produce GEFSv13 ocean and ice
    products in the global-workflow according to stakeholder requirements.
    The following features are added.
```
with the following untracked local modifications
```
Hera(hfe04):/scratch1/NCEPDEV/da/Russ.Treadon/git/global-workflow/gdasapp$ git status
On branch dev/gdasapp
Your branch is behind 'origin/dev/gdasapp' by 19 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        jobs/JGLOBAL_PREP_OBS_AERO
        jobs/rocoto/prepobsaero.sh
        parm/config/gfs/config.prepobsaero
        scripts/exglobal_prep_obs_aero.py
        ush/python/pygfs/task/aero_prepobs.py

nothing added to commit but untracked files present (use "git add" to track)
```

I could try `git push origin dev/gdasapp` to get us back to where we were before PR #2714.   We can try again to update `dev/gdasapp` from this starting point.

Alternatively, we delete the existing `dev/gdasapp` and create a new one as a copy of the current `develop`.

**Comment by guillaumevernieres** [comment]
Can we push directly to dev/gdasapp?

**Comment by RussTreadon-NOAA** [comment]
> Can we push directly to dev/gdasapp?

Don't know.  I can try.

**Comment by aerorahul** [comment]
> > Can we push directly to dev/gdasapp?
> 
> Don't know. I can try.

No.  Need a PR.

**Comment by RussTreadon-NOAA** [comment]
Thanks @aerorahul for the clarification.

**Pull request closed without merging**
