### PR TITLE
Retire cycle-specific FHMAX_GFS variables

### LINKED ISSUE #2218: `FHMAX_GFS_${cyc}` has no relevance in the global-workflow anymore
### What new functionality do you need?

In past GFS implementations, the GFS forecast lengths varied between cycles; e.g. 00z and 06z forecasts would have been different lengths.
A search for `FHMAX_GFS_` results in no hits beyond `config.base` and some places in the workflow generation.
They can be simplified to key on `FHMAX_GFS`
Running different forecast lengths for different cycles is no longer supported in the global-workflow.

### What are the requirements for the new functionality?

Existing functionality and operation should not be impacted.

### Acceptance Criteria

Requirements are met following the suggested changes in functionality.

### Suggest a solution (optional)

Eliminate `FHMAX_GFS_00` etc and consolidate around `FHMAX_GFS`.

### PR DESCRIPTION
**Pull request by KateFriedman-NOAA**
# Description

This PR retires the `FHMAX_GFS_${cyc}` variables that allowed users to specify different gfs forecast lengths for each cycle. This function is no longer supported in global-workflow. The `FHMAX_GFS_*` variables will be removed and will no longer be checked to set the final `FHMAX_GFS` variable. The same forecast length will be set for every cycle.

This PR also includes a small fix to add new post parm files into the `.gitignore` file. This was intended to be included in a different PR but that PR is on hold for further testing so it is being included here to get it into `develop` sooner.

Resolves #2218

# Type of change

Function retirement

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Setup and short low-res atmos-only cycled test on Hera.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
lgtm

**Review by HenryRWinterbottom — APPROVED** [review]
This is a great addition! Thank you @KateFriedman-NOAA. 

Approving pending CI tests.

**Comment by KateFriedman-NOAA** [comment]
Thank you for the reviews and approvals thus far! It was requested to also update `FHMAX_GFS` to have it come from a yaml instead of hardcoding to 120 in `config.base`. I agree and will make that additional change in this PR. Stay tuned...will re-request reviews when done.

Discussed need for CI testing, don't see need. Will not run CI tests for this.

**Comment by HenryRWinterbottom** [comment]
> This is a great addition! Thank you @KateFriedman-NOAA.
> 
> Approving pending CI tests.

@KateFriedman-NOAA My bad. I assumed the CI would catch any possible sneaky bugs that might not like this change. LGTM, otherwise. Thank you for the clarification.

**Review by aerorahul — APPROVED** [review]

**Review by HenryRWinterbottom — APPROVED** [review]
LGTM. Thanks @KateFriedman-NOAA.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
Approved pending successful completion of CI tests

**Comment by TerrenceMcGuinness-NOAA** [comment]
gdas build still failed let me check what happened with the update the rocoto module load

**Comment by TerrenceMcGuinness-NOAA** [comment]
```
mterry (Orion-login-1) C48_S2SW_8e9fa9a7 $ pwd
/work2/noaa/stmp/GFS_CI_ROOT/ORION/PR/2278/RUNTESTS/EXPDIR/C48_S2SW_8e9fa9a7
mterry (Orion-login-1) C48_S2SW_8e9fa9a7 $ grep dependencies -A 3 C48_S2SW_8e9fa9a7_gfsstage_ic_202103231200_check.txt
  dependencies
    AND is not satisfied
      /work/noaa/global/glopara/data/ICSDIR/prototype_ICs/workflow_C48_refactored/2021032312/atmos/gfs_ctrl.nc does not exist
```

**Pull request merged**
